define

##########---------- Entities ----------##########

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

AnnotationTypeDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANNOTATION:IS_ANNOTATION,
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

AnnotationTypeMemberDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANNOTATION:IS_ANNOTATION,
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

AnonymousClassDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANONYMOUS:IS_ANONYMOUS,
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION,
	plays TYPE:IS_TYPE;

ArrayAccessArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

ArrayCreationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

ArrayInitializerArtifact sub JavaSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LIST:IS_LIST,
	plays LITERAL:IS_LITERAL;

ArrayTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays FUNCTION:IS_FUNCTION,
	plays LIST:IS_LIST,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RETURN:IS_RETURN,
	plays TYPE:IS_TYPE;

AssertStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays ASSERT:IS_ASSERT,
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

AssignmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays AND:IS_AND,
	plays ARGUMENT:IS_ARGUMENT,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays DIVIDE:IS_DIVIDE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays MODULO:IS_MODULO,
	plays MULTIPLY:IS_MULTIPLY,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays RIGHT_SHIFT:IS_RIGHT_SHIFT,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNSIGNED:IS_UNSIGNED,
	plays UPDATE:IS_UPDATE,
	plays XOR:IS_XOR;

BlockArtifact sub JavaSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays FINALLY:IS_FINALLY,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays SCOPE:IS_SCOPE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays TRY:IS_TRY,
	plays WHILE:IS_WHILE;

BlockCommentArtifact sub JavaSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT;

BooleanLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

BreakStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays BREAK:IS_BREAK,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

CastExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

CatchClauseArtifact sub JavaSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays TRY:IS_TRY,
	plays UNANNOTATED:IS_UNANNOTATED;

CharacterLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CHARACTER:IS_CHARACTER,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

ClassInstanceCreationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INSTANCE:IS_INSTANCE,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

CompilationUnitArtifact sub JavaSourceArtifact,
	# Semantic
	plays FILE:IS_FILE;

ConditionalExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

ConstructorInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT;

ContinueStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

CreationReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

DimensionArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

DoStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays DO_WHILE:IS_DO_WHILE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

EmptyStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays WHILE:IS_WHILE;

EnhancedForStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

EnumConstantDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays ENUMERATION:IS_ENUMERATION;

EnumDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays ENUMERATION:IS_ENUMERATION,
	plays TYPE:IS_TYPE;

ExpressionMethodReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

ExpressionStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

FieldAccessArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED,
	plays WHILE:IS_WHILE;

FieldDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays VARIABLE:IS_VARIABLE;

ForStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

IfStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

ImportDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays IMPORT:IS_IMPORT;

InfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays AND:IS_AND,
	plays ARGUMENT:IS_ARGUMENT,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays DIVIDE:IS_DIVIDE,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays GREATER_THAN:IS_GREATER_THAN,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays LESS_THAN:IS_LESS_THAN,
	plays LESS_THAN_OR_EQUAL:IS_LESS_THAN_OR_EQUAL,
	plays MODULO:IS_MODULO,
	plays MULTIPLY:IS_MULTIPLY,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays POSITIONAL:IS_POSITIONAL,
	plays RELATIONAL:IS_RELATIONAL,
	plays RIGHT:IS_RIGHT,
	plays RIGHT_SHIFT:IS_RIGHT_SHIFT,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNSIGNED:IS_UNSIGNED,
	plays WHILE:IS_WHILE,
	plays XOR:IS_XOR;

InitializerArtifact sub JavaSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INITIALIZATION:IS_INITIALIZATION;

InstanceofExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays UNANNOTATED:IS_UNANNOTATED,
	plays WHILE:IS_WHILE;

IntersectionTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays TYPE:IS_TYPE;

JavadocArtifact sub JavaSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays DOCUMENTATION:IS_DOCUMENTATION;

LabeledStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

LambdaExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANONYMOUS:IS_ANONYMOUS,
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays DECLARATION:IS_DECLARATION,
	plays ELSE:IS_ELSE,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

LineCommentArtifact sub JavaSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT;

MarkerAnnotationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANNOTATION:IS_ANNOTATION,
	plays INCOMPLETE:IS_INCOMPLETE;

MemberRefArtifact sub JavaSourceArtifact,
	# Semantic
	plays DOCUMENTATION:IS_DOCUMENTATION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays VARIABLE:IS_VARIABLE;

MemberValuePairArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANNOTATION:IS_ANNOTATION,
	plays INCOMPLETE:IS_INCOMPLETE;

MethodDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays PACKAGE:IS_PACKAGE,
	plays SUBTYPE:IS_SUBTYPE,
	plays TYPE:IS_TYPE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

MethodInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UPDATE:IS_UPDATE,
	plays WHILE:IS_WHILE;

MethodRefArtifact sub JavaSourceArtifact,
	# Semantic
	plays DOCUMENTATION:IS_DOCUMENTATION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE;

MethodRefParameterArtifact sub JavaSourceArtifact,
	# Semantic
	plays DOCUMENTATION:IS_DOCUMENTATION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE;

ModifierArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INSTANCE:IS_INSTANCE,
	plays SUBTYPE:IS_SUBTYPE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

NameQualifiedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays NAME:IS_NAME,
	plays QUALIFIED:IS_QUALIFIED,
	plays TYPE:IS_TYPE;

NormalAnnotationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANNOTATION:IS_ANNOTATION,
	plays INCOMPLETE:IS_INCOMPLETE;

NullLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NULL:IS_NULL,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

NumberLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays POSITIONAL:IS_POSITIONAL,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

OperatorArtifact sub JavaSourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays AND:IS_AND,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BOOLEAN:IS_BOOLEAN,
	plays DECREMENT:IS_DECREMENT,
	plays DIVIDE:IS_DIVIDE,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays GREATER_THAN:IS_GREATER_THAN,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays INCREMENT:IS_INCREMENT,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays LESS_THAN:IS_LESS_THAN,
	plays LESS_THAN_OR_EQUAL:IS_LESS_THAN_OR_EQUAL,
	plays MODULO:IS_MODULO,
	plays MULTIPLY:IS_MULTIPLY,
	plays NEGATIVE:IS_NEGATIVE,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays POSITIVE:IS_POSITIVE,
	plays POSTFIX:IS_POSTFIX,
	plays RELATIONAL:IS_RELATIONAL,
	plays RIGHT_SHIFT:IS_RIGHT_SHIFT,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays UNARY:IS_UNARY,
	plays UNSIGNED:IS_UNSIGNED,
	plays XOR:IS_XOR;

PackageDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays PACKAGE:IS_PACKAGE;

ParameterizedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays RETURN:IS_RETURN,
	plays TYPE:IS_TYPE;

ParenthesizedExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

PostfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays DECREMENT:IS_DECREMENT,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCREMENT:IS_INCREMENT,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LEFT:IS_LEFT,
	plays OPERATOR:IS_OPERATOR,
	plays POSITIONAL:IS_POSITIONAL,
	plays POSTFIX:IS_POSTFIX,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE;

PrefixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays DECREMENT:IS_DECREMENT,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays INCREMENT:IS_INCREMENT,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LEFT:IS_LEFT,
	plays NEGATIVE:IS_NEGATIVE,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays POSITIONAL:IS_POSITIONAL,
	plays POSITIVE:IS_POSITIVE,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE,
	plays WHILE:IS_WHILE;

PrimitiveTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays BYTE:IS_BYTE,
	plays CHARACTER:IS_CHARACTER,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays TYPE:IS_TYPE;

QualifiedNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays IF:IS_IF,
	plays IMPORT:IS_IMPORT,
	plays LEFT:IS_LEFT,
	plays PATHNAME:IS_PATHNAME,
	plays POSITIONAL:IS_POSITIONAL,
	plays QUALIFIED:IS_QUALIFIED,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

QualifiedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays QUALIFIED:IS_QUALIFIED,
	plays TYPE:IS_TYPE;

ReturnStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays RETURN:IS_RETURN,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

SimpleNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays NAME:IS_NAME,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

SimpleTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays TYPE:IS_TYPE;

SingleMemberAnnotationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ANNOTATION:IS_ANNOTATION,
	plays INCOMPLETE:IS_INCOMPLETE;

SingleVariableDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGS_LIST:IS_ARGS_LIST,
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays ITERATOR:IS_ITERATOR,
	plays VARIABLE:IS_VARIABLE;

StringLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

SuperConstructorInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays BASE:IS_BASE,
	plays CALL:IS_CALL,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT,
	plays UNANNOTATED:IS_UNANNOTATED;

SuperFieldAccessArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

SuperMethodInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BASE:IS_BASE,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

SuperMethodReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays POSITIONAL:IS_POSITIONAL;

SwitchCaseArtifact sub JavaSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays DEFAULT:IS_DEFAULT,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

SwitchStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

SynchronizedStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

TagElementArtifact sub JavaSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays DOCUMENTATION:IS_DOCUMENTATION,
	plays INCOMPLETE:IS_INCOMPLETE;

TextElementArtifact sub JavaSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays DOCUMENTATION:IS_DOCUMENTATION,
	plays INCOMPLETE:IS_INCOMPLETE;

ThisExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays THIS:IS_THIS;

ThrowStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays THROW:IS_THROW;

TryStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays TRY:IS_TRY,
	plays UNANNOTATED:IS_UNANNOTATED;

TypeDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays PACKAGE:IS_PACKAGE,
	plays SUBTYPE:IS_SUBTYPE,
	plays TYPE:IS_TYPE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

TypeDeclarationStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays STATEMENT:IS_STATEMENT,
	plays TYPE:IS_TYPE;

TypeLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TYPE:IS_TYPE;

TypeMethodReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays POSITIONAL:IS_POSITIONAL;

TypeParameterArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

UnionTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays OR:IS_OR,
	plays TYPE:IS_TYPE;

VariableDeclarationExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays VARIABLE:IS_VARIABLE;

VariableDeclarationFragmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays VARIABLE:IS_VARIABLE;

VariableDeclarationStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays DECLARATION:IS_DECLARATION,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays VARIABLE:IS_VARIABLE;

WhileStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

WildcardTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

AND sub relation,
	relates IS_AND;

ANNOTATION sub relation,
	relates IS_ANNOTATION;

ANONYMOUS sub relation,
	relates IS_ANONYMOUS;

ARGS_LIST sub relation,
	relates IS_ARGS_LIST;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSERT sub relation,
	relates IS_ASSERT;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BASE sub relation,
	relates IS_BASE;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

BYTE sub relation,
	relates IS_BYTE;

CALL sub relation,
	relates IS_CALL;

CALLEE sub relation,
	relates IS_CALLEE;

CASE sub relation,
	relates IS_CASE;

CATCH sub relation,
	relates IS_CATCH;

CHARACTER sub relation,
	relates IS_CHARACTER;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

DECLARATION sub relation,
	relates IS_DECLARATION;

DECREMENT sub relation,
	relates IS_DECREMENT;

DEFAULT sub relation,
	relates IS_DEFAULT;

DIVIDE sub relation,
	relates IS_DIVIDE;

DO_WHILE sub relation,
	relates IS_DO_WHILE;

DOCUMENTATION sub relation,
	relates IS_DOCUMENTATION;

ELSE sub relation,
	relates IS_ELSE;

ENUMERATION sub relation,
	relates IS_ENUMERATION;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FILE sub relation,
	relates IS_FILE;

FINALLY sub relation,
	relates IS_FINALLY;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GREATER_THAN sub relation,
	relates IS_GREATER_THAN;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

INCREMENT sub relation,
	relates IS_INCREMENT;

INITIALIZATION sub relation,
	relates IS_INITIALIZATION;

INSTANCE sub relation,
	relates IS_INSTANCE;

ITERATOR sub relation,
	relates IS_ITERATOR;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN sub relation,
	relates IS_LESS_THAN;

LESS_THAN_OR_EQUAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MODULO sub relation,
	relates IS_MODULO;

MULTIPLY sub relation,
	relates IS_MULTIPLY;

NAME sub relation,
	relates IS_NAME;

NEGATIVE sub relation,
	relates IS_NEGATIVE;

NOT sub relation,
	relates IS_NOT;

NULL sub relation,
	relates IS_NULL;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PACKAGE sub relation,
	relates IS_PACKAGE;

PATHNAME sub relation,
	relates IS_PATHNAME;

POSITIONAL sub relation,
	relates IS_POSITIONAL;

POSITIVE sub relation,
	relates IS_POSITIVE;

POSTFIX sub relation,
	relates IS_POSTFIX;

PRIMITIVE sub relation,
	relates IS_PRIMITIVE;

QUALIFIED sub relation,
	relates IS_QUALIFIED;

RECEIVER sub relation,
	relates IS_RECEIVER;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

RIGHT_SHIFT sub relation,
	relates IS_RIGHT_SHIFT;

SCOPE sub relation,
	relates IS_SCOPE;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

SUBTYPE sub relation,
	relates IS_SUBTYPE;

SWITCH sub relation,
	relates IS_SWITCH;

THEN sub relation,
	relates IS_THEN;

THIS sub relation,
	relates IS_THIS;

THROW sub relation,
	relates IS_THROW;

TRY sub relation,
	relates IS_TRY;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UNSIGNED sub relation,
	relates IS_UNSIGNED;

UPDATE sub relation,
	relates IS_UPDATE;

VARIABLE sub relation,
	relates IS_VARIABLE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WHILE sub relation,
	relates IS_WHILE;

WORLD sub relation,
	relates IS_WORLD;

XOR sub relation,
	relates IS_XOR;
