define

##########---------- Entities ----------##########

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

AnnotationTypeDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_TYPE;

AnnotationTypeMemberDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_TYPE;

AnonymousClassDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANONYMOUS,
	plays IS_DECLARATION,
	plays IS_EXPRESSION,
	plays IS_TYPE;

ArrayAccessArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

ArrayCreationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN;

ArrayInitializerArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_LIST,
	plays IS_LITERAL;

ArrayTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_FUNCTION,
	plays IS_LIST,
	plays IS_PRIMITIVE,
	plays IS_RETURN,
	plays IS_TYPE;

AssertStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ASSERT,
	plays IS_BODY,
	plays IS_CASE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN;

AssignmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DIVIDE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_LEFT_SHIFT,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNSIGNED,
	plays IS_UPDATE,
	plays IS_XOR;

BlockArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_BODY,
	plays IS_CASE,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FINALLY,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_SCOPE,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TRY,
	plays IS_WHILE;

BlockCommentArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_COMMENT;

BooleanLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_WHILE;

BreakStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_BREAK,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN;

CastExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN;

CatchClauseArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CATCH,
	plays IS_TRY,
	plays IS_UNANNOTATED;

CharacterLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CHARACTER,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN;

ClassInstanceCreationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INSTANCE,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_THEN;

CompilationUnitArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_FILE;

ConditionalExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

ConstructorInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CALL,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT;

ContinueStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNANNOTATED;

CreationReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN;

DimensionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_TYPE;

DoStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_DO_WHILE,
	plays IS_STATEMENT,
	plays IS_SWITCH;

EmptyStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_FOR,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_WHILE;

EnhancedForStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_ITERATOR,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN;

EnumConstantDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_ENUMERATION;

EnumDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_ENUMERATION,
	plays IS_TYPE;

ExpressionMethodReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN;

ExpressionStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

FieldAccessArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNANNOTATED,
	plays IS_WHILE;

FieldDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_VARIABLE;

ForStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNANNOTATED;

IfStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

ImportDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_IMPORT;

InfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DIVIDE,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EQUAL,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_GREATER_THAN,
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LEFT_SHIFT,
	plays IS_LESS_THAN,
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_POSITIONAL,
	plays IS_RELATIONAL,
	plays IS_RIGHT,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNSIGNED,
	plays IS_WHILE,
	plays IS_XOR;

InitializerArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_BODY,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION;

InstanceofExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_UNANNOTATED,
	plays IS_WHILE;

IntersectionTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_AND,
	plays IS_TYPE;

JavadocArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_DOCUMENTATION;

LabeledStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_SWITCH;

LambdaExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANONYMOUS,
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DECLARATION,
	plays IS_ELSE,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN;

LineCommentArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_COMMENT;

MarkerAnnotationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_INCOMPLETE;

MemberRefArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DOCUMENTATION,
	plays IS_INCOMPLETE,
	plays IS_VARIABLE;

MemberValuePairArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_INCOMPLETE;

MethodDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_PACKAGE,
	plays IS_SUBTYPE,
	plays IS_TYPE,
	plays IS_VISIBILITY,
	plays IS_WORLD;

MethodInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_WHILE;

MethodRefArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DOCUMENTATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE;

MethodRefParameterArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DOCUMENTATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE;

ModifierArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_INSTANCE,
	plays IS_SUBTYPE,
	plays IS_VISIBILITY,
	plays IS_WORLD;

NameQualifiedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_NAME,
	plays IS_QUALIFIED,
	plays IS_TYPE;

NormalAnnotationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_INCOMPLETE;

NullLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_NULL,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN;

NumberLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_NUMBER,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN;

OperatorArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BOOLEAN,
	plays IS_DECREMENT,
	plays IS_DIVIDE,
	plays IS_EQUAL,
	plays IS_EXPRESSION,
	plays IS_GREATER_THAN,
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_INCREMENT,
	plays IS_LEFT_SHIFT,
	plays IS_LESS_THAN,
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NEGATIVE,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_POSITIVE,
	plays IS_POSTFIX,
	plays IS_RELATIONAL,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_UNARY,
	plays IS_UNSIGNED,
	plays IS_XOR;

PackageDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_PACKAGE;

ParameterizedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_RETURN,
	plays IS_TYPE;

ParenthesizedExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

PostfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DECREMENT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCREMENT,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_OPERATOR,
	plays IS_POSITIONAL,
	plays IS_POSTFIX,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNARY,
	plays IS_UPDATE;

PrefixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DECREMENT,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCREMENT,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_NEGATIVE,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_POSITIONAL,
	plays IS_POSITIVE,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_UNARY,
	plays IS_UPDATE,
	plays IS_WHILE;

PrimitiveTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BOOLEAN,
	plays IS_BYTE,
	plays IS_CHARACTER,
	plays IS_NUMBER,
	plays IS_PRIMITIVE,
	plays IS_TYPE;

QualifiedNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_IMPORT,
	plays IS_LEFT,
	plays IS_PATHNAME,
	plays IS_POSITIONAL,
	plays IS_QUALIFIED,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

QualifiedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_QUALIFIED,
	plays IS_TYPE;

ReturnStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_RETURN,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN;

SimpleNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

SimpleTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_TYPE;

SingleMemberAnnotationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_INCOMPLETE;

SingleVariableDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST,
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_ITERATOR,
	plays IS_VARIABLE;

StringLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_STRING,
	plays IS_SWITCH,
	plays IS_THEN;

SuperConstructorInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BASE,
	plays IS_CALL,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_UNANNOTATED;

SuperFieldAccessArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_UNANNOTATED;

SuperMethodInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_THEN;

SuperMethodReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE,
	plays IS_POSITIONAL;

SwitchCaseArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CASE,
	plays IS_DEFAULT,
	plays IS_STATEMENT,
	plays IS_SWITCH;

SwitchStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_STATEMENT,
	plays IS_SWITCH;

SynchronizedStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN;

TagElementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_DOCUMENTATION,
	plays IS_INCOMPLETE;

TextElementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_DOCUMENTATION,
	plays IS_INCOMPLETE;

ThisExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_THIS;

ThrowStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_THROW;

TryStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TRY,
	plays IS_UNANNOTATED;

TypeDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_PACKAGE,
	plays IS_SUBTYPE,
	plays IS_TYPE,
	plays IS_VISIBILITY,
	plays IS_WORLD;

TypeDeclarationStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_STATEMENT,
	plays IS_TYPE;

TypeLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE;

TypeMethodReferenceArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_POSITIONAL;

TypeParameterArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_TYPE;

UnionTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_OR,
	plays IS_TYPE;

VariableDeclarationExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_INITIALIZATION,
	plays IS_VARIABLE;

VariableDeclarationFragmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_VARIABLE;

VariableDeclarationStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_DECLARATION,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_VARIABLE;

WhileStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CASE,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

WildcardTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_TYPE;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

AND sub relation,
	relates IS_AND;

ANNOTATION sub relation,
	relates IS_ANNOTATION;

ANONYMOUS sub relation,
	relates IS_ANONYMOUS;

ARGS_LIST sub relation,
	relates IS_ARGS_LIST;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSERT sub relation,
	relates IS_ASSERT;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BASE sub relation,
	relates IS_BASE;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

BYTE sub relation,
	relates IS_BYTE;

CALL sub relation,
	relates IS_CALL;

CALLEE sub relation,
	relates IS_CALLEE;

CASE sub relation,
	relates IS_CASE;

CATCH sub relation,
	relates IS_CATCH;

CHARACTER sub relation,
	relates IS_CHARACTER;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

DECLARATION sub relation,
	relates IS_DECLARATION;

DECREMENT sub relation,
	relates IS_DECREMENT;

DEFAULT sub relation,
	relates IS_DEFAULT;

DIVIDE sub relation,
	relates IS_DIVIDE;

DO_WHILE sub relation,
	relates IS_DO_WHILE;

DOCUMENTATION sub relation,
	relates IS_DOCUMENTATION;

ELSE sub relation,
	relates IS_ELSE;

ENUMERATION sub relation,
	relates IS_ENUMERATION;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FILE sub relation,
	relates IS_FILE;

FINALLY sub relation,
	relates IS_FINALLY;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GREATER_THAN sub relation,
	relates IS_GREATER_THAN;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

INCREMENT sub relation,
	relates IS_INCREMENT;

INITIALIZATION sub relation,
	relates IS_INITIALIZATION;

INSTANCE sub relation,
	relates IS_INSTANCE;

ITERATOR sub relation,
	relates IS_ITERATOR;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN sub relation,
	relates IS_LESS_THAN;

LESS_THAN_OR_EQUAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MODULO sub relation,
	relates IS_MODULO;

MULTIPLY sub relation,
	relates IS_MULTIPLY;

NAME sub relation,
	relates IS_NAME;

NEGATIVE sub relation,
	relates IS_NEGATIVE;

NOT sub relation,
	relates IS_NOT;

NULL sub relation,
	relates IS_NULL;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PACKAGE sub relation,
	relates IS_PACKAGE;

PATHNAME sub relation,
	relates IS_PATHNAME;

POSITIONAL sub relation,
	relates IS_POSITIONAL;

POSITIVE sub relation,
	relates IS_POSITIVE;

POSTFIX sub relation,
	relates IS_POSTFIX;

PRIMITIVE sub relation,
	relates IS_PRIMITIVE;

QUALIFIED sub relation,
	relates IS_QUALIFIED;

RECEIVER sub relation,
	relates IS_RECEIVER;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

RIGHT_SHIFT sub relation,
	relates IS_RIGHT_SHIFT;

SCOPE sub relation,
	relates IS_SCOPE;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

SUBTYPE sub relation,
	relates IS_SUBTYPE;

SWITCH sub relation,
	relates IS_SWITCH;

THEN sub relation,
	relates IS_THEN;

THIS sub relation,
	relates IS_THIS;

THROW sub relation,
	relates IS_THROW;

TRY sub relation,
	relates IS_TRY;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UNSIGNED sub relation,
	relates IS_UNSIGNED;

UPDATE sub relation,
	relates IS_UPDATE;

VARIABLE sub relation,
	relates IS_VARIABLE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WHILE sub relation,
	relates IS_WHILE;

WORLD sub relation,
	relates IS_WORLD;

XOR sub relation,
	relates IS_XOR;
