define

##########---------- Entities ----------##########

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

AnyTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

ArrayExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LIST,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

ArrayPatternArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_ITERATOR,
	plays IS_LEFT,
	plays IS_LIST,
	plays IS_MAP,
	plays IS_VALUE;

ArrayTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

ArrowFunctionExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ANONYMOUS,
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DECLARATION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

AssignmentExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DIVIDE,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LEFT_SHIFT,
	plays IS_MAP,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NAME,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_RIGHT,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UNSIGNED,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE,
	plays IS_XOR;

AssignmentPatternArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_ITERATOR,
	plays IS_MAP,
	plays IS_VALUE;

AwaitExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

BigIntLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_UNANNOTATED,
	plays IS_VALUE;

BinaryExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DIVIDE,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EQUAL,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_GREATER_THAN,
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_IDENTICAL,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LEFT_SHIFT,
	plays IS_LESS_THAN,
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_MAP,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NAME,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_RELATIONAL,
	plays IS_RIGHT,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UNSIGNED,
	plays IS_VALUE,
	plays IS_WHILE,
	plays IS_XOR;

BindExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_RIGHT;

BlockStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FINALLY,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_MAP,
	plays IS_SCOPE,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_TRY,
	plays IS_VALUE,
	plays IS_WHILE;

BooleanLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_VALUE,
	plays IS_WHILE;

BooleanLiteralTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BOOLEAN,
	plays IS_DECLARATION,
	plays IS_LITERAL,
	plays IS_TYPE;

BooleanTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BOOLEAN,
	plays IS_DECLARATION,
	plays IS_TYPE;

BreakStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_BREAK,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

CallExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

CatchClauseArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_CATCH,
	plays IS_STATEMENT,
	plays IS_TRY;

ClassBodyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_TYPE;

ClassDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_TYPE;

ClassExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DECLARATION,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_TYPE,
	plays IS_VALUE;

ClassImplementsArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

ClassMethodArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_STATEMENT;

ClassPrivateMethodArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_STATEMENT;

ClassPrivatePropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_VARIABLE;

ClassPropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_VARIABLE;

CommentBlockArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_COMMENT,
	plays IS_NOOP;

CommentLineArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_NOOP;

ConditionalExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE,
	plays IS_WHILE;

ContinueStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_CONTINUE,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

DebuggerStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_NOOP,
	plays IS_STATEMENT,
	plays IS_THEN;

DeclareClassArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

DeclaredPredicateArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareExportAllDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareExportDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareFunctionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareInterfaceArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareModuleArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareModuleExportsArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareOpaqueTypeArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareTypeAliasArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DeclareVariableArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

DecoratorArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_INCOMPLETE;

DirectiveArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE;

DirectiveLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE,
	plays IS_LITERAL;

DoExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_VALUE;

DoWhileStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN;

EmptyStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_NOOP,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

EmptyTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

ExistsTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

ExportAllDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_MODULE,
	plays IS_STATEMENT,
	plays IS_VISIBILITY;

ExportDefaultDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_MODULE,
	plays IS_STATEMENT,
	plays IS_VISIBILITY;

ExportNamedDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_MODULE,
	plays IS_STATEMENT,
	plays IS_VISIBILITY;

ExportSpecifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE;

ExpressionStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

FileArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_FILE;

ForInStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_ITERATOR,
	plays IS_STATEMENT,
	plays IS_THEN;

ForOfStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_FOR,
	plays IS_IF,
	plays IS_ITERATOR,
	plays IS_STATEMENT,
	plays IS_THEN;

ForStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

FunctionDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_WHILE;

FunctionExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_DECLARATION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

FunctionTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

FunctionTypeParamArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

GenericTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_TYPE;

IdentifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_IMPORT,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_ITERATOR,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

IfStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

ImportArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_EXPRESSION,
	plays IS_IMPORT;

ImportDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_IF,
	plays IS_IMPORT,
	plays IS_STATEMENT,
	plays IS_THEN;

ImportDefaultSpecifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DEFAULT,
	plays IS_IMPORT;

ImportNamespaceSpecifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_IMPORT,
	plays IS_NAME;

ImportSpecifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_IMPORT;

InferredPredicateArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

InterfaceDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_UNANNOTATED;

InterfaceExtendsArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_SUBTYPE,
	plays IS_TYPE;

IntersectionTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

JSXAttributeArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE;

JSXClosingElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXClosingFragmentArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

JSXEmptyExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXExpressionContainerArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXFragmentArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_UNANNOTATED,
	plays IS_VALUE;

JSXIdentifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER,
	plays IS_INCOMPLETE;

JSXMemberExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXNamespacedNameArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXOpeningElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_INCOMPLETE;

JSXOpeningFragmentArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXSpreadAttributeArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXSpreadChildArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

JSXTextArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

LabeledStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

LogicalExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_AND,
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

MemberExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_ITERATOR,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_QUALIFIED,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE,
	plays IS_WHILE;

MetaPropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_RIGHT,
	plays IS_VALUE;

MixedTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_TYPE;

NewExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_INSTANCE,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

NullableTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

NullLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NULL,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

NullLiteralTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_NULL,
	plays IS_TYPE;

NumberLiteralTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_LITERAL,
	plays IS_NUMBER,
	plays IS_TYPE;

NumberTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_NUMBER,
	plays IS_TYPE;

NumericLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NUMBER,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

ObjectExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

ObjectMethodArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_MAP;

ObjectPatternArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_ITERATOR,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_VALUE;

ObjectPropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_MAP;

ObjectTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_LITERAL,
	plays IS_TYPE;

ObjectTypeCallPropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

ObjectTypeIndexerArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE;

ObjectTypePropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

ObjectTypeSpreadPropertyArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

OpaqueTypeArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_UNANNOTATED;

OperatorArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BOOLEAN,
	plays IS_DECREMENT,
	plays IS_DIVIDE,
	plays IS_EQUAL,
	plays IS_EXPRESSION,
	plays IS_GREATER_THAN,
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_IDENTICAL,
	plays IS_INCOMPLETE,
	plays IS_INCREMENT,
	plays IS_LEFT_SHIFT,
	plays IS_LESS_THAN,
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NEGATIVE,
	plays IS_NOT,
	plays IS_NULL,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_POSITIVE,
	plays IS_RELATIONAL,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_THROW,
	plays IS_TYPE,
	plays IS_UNARY,
	plays IS_UNSIGNED,
	plays IS_XOR;

PrivateNameArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_IDENTIFIER,
	plays IS_INSTANCE,
	plays IS_KEY,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_QUALIFIED,
	plays IS_VISIBILITY;

ProgramArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_MODULE;

QualifiedTypeIdentifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

RegExpLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_REGEXP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

RestElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST,
	plays IS_ARGUMENT,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE;

ReturnStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_RETURN,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

SequenceExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LIST,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

SpreadElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST,
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_INCOMPLETE,
	plays IS_LIST,
	plays IS_VALUE;

StringLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_IMPORT,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_PATHNAME,
	plays IS_RIGHT,
	plays IS_STRING,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_VALUE;

StringLiteralTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_LITERAL,
	plays IS_STRING,
	plays IS_TYPE;

StringTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_STRING,
	plays IS_TYPE;

SuperArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BASE,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_EXPRESSION,
	plays IS_IDENTIFIER;

SwitchCaseArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_CASE,
	plays IS_SWITCH;

SwitchStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_WHILE;

TaggedTemplateExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_STRING,
	plays IS_THEN,
	plays IS_VALUE;

TemplateElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE,
	plays IS_STRING,
	plays IS_VALUE;

TemplateLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_RIGHT,
	plays IS_STRING,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

ThisExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_THIS,
	plays IS_VALUE;

ThisTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

ThrowStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_THROW;

TryStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_TRY,
	plays IS_WHILE;

TupleTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TUPLE,
	plays IS_TYPE;

TypeAliasArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ALIAS,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

TypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_TYPE;

TypeCastExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ALIAS,
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_DECLARATION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

TypeofTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

TypeParameterArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_TYPE;

TypeParameterDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_TYPE;

TypeParameterInstantiationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

UnaryExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CASE,
	plays IS_CONDITION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NEGATIVE,
	plays IS_NOT,
	plays IS_NULL,
	plays IS_OPERATOR,
	plays IS_POSITIVE,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_THROW,
	plays IS_TYPE,
	plays IS_UNARY,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

UnionTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

UpdateExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DECREMENT,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCREMENT,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_OPERATOR,
	plays IS_POSTFIX,
	plays IS_RIGHT,
	plays IS_SWITCH,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_UNARY,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

VariableDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_DO_WHILE,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_ITERATOR,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_VARIABLE,
	plays IS_WHILE;

VariableDeclaratorArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_VARIABLE;

VarianceArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

VoidTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

WhileStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_IF,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_WHILE;

WithStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_INCOMPLETE,
	plays IS_SCOPE,
	plays IS_STATEMENT;

YieldExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BASE,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_INITIALIZATION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_RETURN,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_TYPE,
	plays IS_VALUE;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

ALIAS sub relation,
	relates IS_ALIAS;

AND sub relation,
	relates IS_AND;

ANNOTATION sub relation,
	relates IS_ANNOTATION;

ANONYMOUS sub relation,
	relates IS_ANONYMOUS;

ARGS_LIST sub relation,
	relates IS_ARGS_LIST;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BASE sub relation,
	relates IS_BASE;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

CALL sub relation,
	relates IS_CALL;

CALLEE sub relation,
	relates IS_CALLEE;

CASE sub relation,
	relates IS_CASE;

CATCH sub relation,
	relates IS_CATCH;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

CONTINUE sub relation,
	relates IS_CONTINUE;

DECLARATION sub relation,
	relates IS_DECLARATION;

DECREMENT sub relation,
	relates IS_DECREMENT;

DEFAULT sub relation,
	relates IS_DEFAULT;

DIVIDE sub relation,
	relates IS_DIVIDE;

DO_WHILE sub relation,
	relates IS_DO_WHILE;

ELSE sub relation,
	relates IS_ELSE;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FILE sub relation,
	relates IS_FILE;

FINALLY sub relation,
	relates IS_FINALLY;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GREATER_THAN sub relation,
	relates IS_GREATER_THAN;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTICAL sub relation,
	relates IS_IDENTICAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

INCREMENT sub relation,
	relates IS_INCREMENT;

INITIALIZATION sub relation,
	relates IS_INITIALIZATION;

INSTANCE sub relation,
	relates IS_INSTANCE;

ITERATOR sub relation,
	relates IS_ITERATOR;

KEY sub relation,
	relates IS_KEY;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN sub relation,
	relates IS_LESS_THAN;

LESS_THAN_OR_EQUAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MAP sub relation,
	relates IS_MAP;

MODULE sub relation,
	relates IS_MODULE;

MODULO sub relation,
	relates IS_MODULO;

MULTIPLY sub relation,
	relates IS_MULTIPLY;

NAME sub relation,
	relates IS_NAME;

NEGATIVE sub relation,
	relates IS_NEGATIVE;

NOOP sub relation,
	relates IS_NOOP;

NOT sub relation,
	relates IS_NOT;

NULL sub relation,
	relates IS_NULL;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PATHNAME sub relation,
	relates IS_PATHNAME;

POSITIVE sub relation,
	relates IS_POSITIVE;

POSTFIX sub relation,
	relates IS_POSTFIX;

QUALIFIED sub relation,
	relates IS_QUALIFIED;

REGEXP sub relation,
	relates IS_REGEXP;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

RIGHT_SHIFT sub relation,
	relates IS_RIGHT_SHIFT;

SCOPE sub relation,
	relates IS_SCOPE;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

SUBTYPE sub relation,
	relates IS_SUBTYPE;

SWITCH sub relation,
	relates IS_SWITCH;

THEN sub relation,
	relates IS_THEN;

THIS sub relation,
	relates IS_THIS;

THROW sub relation,
	relates IS_THROW;

TRY sub relation,
	relates IS_TRY;

TUPLE sub relation,
	relates IS_TUPLE;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UNSIGNED sub relation,
	relates IS_UNSIGNED;

UPDATE sub relation,
	relates IS_UPDATE;

VALUE sub relation,
	relates IS_VALUE;

VARIABLE sub relation,
	relates IS_VARIABLE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WHILE sub relation,
	relates IS_WHILE;

XOR sub relation,
	relates IS_XOR;
