define

##########---------- Attributes ----------##########
booleanValue sub attribute, datatype boolean;
doubleValue sub attribute, datatype double;
name sub attribute, datatype string;
numberValue sub attribute, datatype long;
token sub attribute, datatype string;

#####----- Ruby -----#####
documentationAttribute sub attribute, datatype string;
inlineAttribute sub attribute, datatype string;
selectorAttribute sub attribute, datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	has token,
	plays is_child,
	plays is_parent;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

AliasArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays has_1_role,
	plays has_2_role;

AndArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_left_role,
	plays has_right_role;

AndAsgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_values_role,
	plays has_target_role,
	plays has_value_role;

ArgArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role;

ArgsArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays has_children_role;

ArrayArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_exceptions_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_contents_role;

BackRefArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_left_role,
	plays is_options_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

BeginArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_options_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_text_role,
	plays is_value_role,
	plays is_values_role,
	plays has_body_role,
	plays has_comments_role;

BlockargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role;

BlockArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_args_role,
	plays has_blockdata_role,
	plays has_body_role,
	plays has_comments_role;

BlockPassArtifact sub RubySourceArtifact,
	# Structural
	plays is_children_role,
	plays is_values_role,
	plays has_children_role;

BreakArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays is_right_role,
	plays has_target_role;

CaseArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_body_role,
	plays is_class_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_file_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays is_values_role,
	plays has_casevar_role,
	plays has_comments_role,
	plays has_else_role,
	plays has_when_clauses_role;

CasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_alias_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_children_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_file_role,
	plays is_iterators_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_comments_role,
	plays has_value_role;

CbaseArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role;

ClassArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_right_role,
	plays has_body_role,
	plays has_comments_role,
	plays has_parent_role;

CommentArtifact sub RubySourceArtifact,
	# Attributes
	has documentationAttribute,
	has inlineAttribute,
	# Structural
	plays is_comments_role;

ComplexArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_class_role,
	plays is_contents_role,
	plays is_values_role;

ConstArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role;

CvarArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

CvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_iterators_role,
	plays is_target_role,
	plays is_value_role,
	plays has_value_role;

DefArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_file_role,
	plays is_value_role,
	plays is_values_role,
	plays has_args_role,
	plays has_body_role,
	plays has_comments_role;

DefinedArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

DefsArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays has_args_role,
	plays has_base_role,
	plays has_class_role;

DstrArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

DsymArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

EnsureArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_class_role,
	plays has_body_role,
	plays has_ensure_body_role;

ErangeArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_body_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_iterated_role,
	plays is_value_role,
	plays is_values_role,
	plays has_1_role,
	plays has_2_role;

FalseArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

FloatArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

ForArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_file_role,
	plays has_body_role,
	plays has_comments_role,
	plays has_iterated_role,
	plays has_iterators_role;

GvarArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

GvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role,
	plays has_comments_role;

HashArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_comments_role,
	plays has_contents_role;

IdentifierArtifact sub RubySourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_qnames_role;

IfArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_left_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_body_role,
	plays has_comments_role,
	plays has_condition_role,
	plays has_else_role;

IntArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

IrangeArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_body_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_1_role,
	plays has_2_role;

IvarArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_options_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

IvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_alias_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_iterators_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_value_role;

KwargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role;

KwbeginArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_body_role,
	plays has_comments_role;

KwoptargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role,
	plays has_default_role;

KwrestargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role;

KwsplatArtifact sub RubySourceArtifact,
	# Structural
	plays is_contents_role;

LvarArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

LvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_alias_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_iterated_role,
	plays is_iterators_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_value_role;

MasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays has_targets_role,
	plays has_values_role;

MatchWithLvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

MlhsArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role,
	plays is_iterators_role,
	plays is_targets_role,
	plays has_children_role;

ModuleArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_else_role,
	plays is_file_role,
	plays is_right_role,
	plays has_begin_role,
	plays has_comments_role,
	plays has_file_role;

NextArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays is_right_role,
	plays has_target_role;

NilArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

NilNodeArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_else_role;

NthRefArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

OpAsgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_class_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_comments_role,
	plays has_operator_role,
	plays has_target_role,
	plays has_value_role;

OperatorArtifact sub RubySourceArtifact,
	# Structural
	plays is_operator_role;

OptargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role,
	plays has_default_role;

OrArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_left_role,
	plays has_right_role;

OrAsgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_begin_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_target_role,
	plays has_value_role;

PairArtifact sub RubySourceArtifact,
	# Structural
	plays is_contents_role,
	plays has_1_role,
	plays has_2_role;

PostexeArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays has_body_role;

PreexeArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_file_role,
	plays has_body_role;

RationalArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_body_role,
	plays is_contents_role,
	plays is_value_role,
	plays is_values_role;

RedoArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role;

RegexpArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_options_role,
	plays has_text_role;

RegoptArtifact sub RubySourceArtifact,
	# Structural
	plays is_options_role,
	plays is_text_role,
	plays has_options_role;

ResbodyArtifact sub RubySourceArtifact,
	# Structural
	plays is_handlers_role,
	plays has_alias_role,
	plays has_body_role,
	plays has_exceptions_role;

RescueArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_class_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_value_role,
	plays is_values_role,
	plays has_body_role,
	plays has_else_role,
	plays has_handlers_role;

RestargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays is_children_role;

RetryArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role;

ReturnArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_class_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_right_role,
	plays has_comments_role,
	plays has_target_role;

SclassArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_class_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_value_role,
	plays is_values_role,
	plays has_body_role,
	plays has_comments_role,
	plays has_object_role;

SelfArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_object_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

SendArrayArtifact sub RubySourceArtifact,
	# Attributes
	has selectorAttribute,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_values_role;

SendAssignArtifact sub RubySourceArtifact,
	# Attributes
	has selectorAttribute,
	# Structural
	plays is_base_role,
	plays is_begin_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_comments_role,
	plays has_values_role;

SendCallArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_comments_role,
	plays has_values_role;

SendIdentifierArtifact sub RubySourceArtifact,
	# Attributes
	has selectorAttribute,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_comments_role;

SendOperatorArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_comments_role,
	plays has_values_role;

SendQualifiedArtifact sub RubySourceArtifact,
	# Attributes
	has selectorAttribute,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_iterated_role,
	plays is_left_role,
	plays is_object_role,
	plays is_parent_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_comments_role,
	plays has_qnames_role,
	plays has_values_role;

SendRequireArtifact sub RubySourceArtifact,
	# Attributes
	has selectorAttribute,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_comments_role,
	plays has_values_role;

SendStatementArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_begin_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_base_role,
	plays has_values_role;

ShadowargArtifact sub RubySourceArtifact,
	# Structural
	plays is_args_role,
	plays has_children_role;

SplatArtifact sub RubySourceArtifact,
	# Structural
	plays is_children_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_target_role,
	plays is_values_role;

StrArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_file_role,
	plays is_left_role,
	plays is_options_role,
	plays is_right_role,
	plays is_target_role,
	plays is_text_role,
	plays is_value_role,
	plays is_values_role;

SuperArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

SymArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

SymbolArtifact sub RubySourceArtifact,
	# Structural
	plays is_children_role,
	plays is_options_role;

TrueArtifact sub RubySourceArtifact,
	# Structural
	plays is_1_role,
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_children_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_conditions_role,
	plays is_contents_role,
	plays is_default_role,
	plays is_else_role,
	plays is_left_role,
	plays is_object_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

UndefArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays has_target_role;

UntilArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_body_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays has_body_role,
	plays has_condition_role;

UntilPostArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays has_body_role,
	plays has_condition_role;

WhenArtifact sub RubySourceArtifact,
	# Structural
	plays is_when_clauses_role,
	plays has_body_role,
	plays has_conditions_role;

WhileArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_body_role,
	plays is_class_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_file_role,
	plays is_value_role,
	plays has_body_role,
	plays has_comments_role,
	plays has_condition_role;

WhilePostArtifact sub RubySourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays has_body_role,
	plays has_condition_role;

XstrArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_body_role,
	plays is_children_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_right_role,
	plays is_value_role,
	plays is_values_role,
	plays has_children_role;

YieldArtifact sub RubySourceArtifact,
	# Structural
	plays is_2_role,
	plays is_base_role,
	plays is_body_role,
	plays is_casevar_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role,
	plays has_target_role;

ZsuperArtifact sub RubySourceArtifact,
	# Structural
	plays is_base_role,
	plays is_blockdata_role,
	plays is_body_role,
	plays is_class_role,
	plays is_condition_role,
	plays is_contents_role,
	plays is_else_role,
	plays is_ensure_body_role,
	plays is_left_role,
	plays is_right_role,
	plays is_target_role,
	plays is_value_role,
	plays is_values_role;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Ruby -----#####
1_relation sub parent_child_relation,
	relates is_1_role as is_child, relates has_1_role as is_parent;

2_relation sub parent_child_relation,
	relates is_2_role as is_child, relates has_2_role as is_parent;

alias_relation sub parent_child_relation,
	relates is_alias_role as is_child, relates has_alias_role as is_parent;

args_relation sub parent_child_relation,
	relates is_args_role as is_child, relates has_args_role as is_parent;

base_relation sub parent_child_relation,
	relates is_base_role as is_child, relates has_base_role as is_parent;

begin_relation sub parent_child_relation,
	relates is_begin_role as is_child, relates has_begin_role as is_parent;

blockdata_relation sub parent_child_relation,
	relates is_blockdata_role as is_child, relates has_blockdata_role as is_parent;

body_relation sub parent_child_relation,
	relates is_body_role as is_child, relates has_body_role as is_parent;

casevar_relation sub parent_child_relation,
	relates is_casevar_role as is_child, relates has_casevar_role as is_parent;

children_relation sub parent_child_relation,
	relates is_children_role as is_child, relates has_children_role as is_parent;

class_relation sub parent_child_relation,
	relates is_class_role as is_child, relates has_class_role as is_parent;

comments_relation sub parent_child_relation,
	relates is_comments_role as is_child, relates has_comments_role as is_parent;

condition_relation sub parent_child_relation,
	relates is_condition_role as is_child, relates has_condition_role as is_parent;

conditions_relation sub parent_child_relation,
	relates is_conditions_role as is_child, relates has_conditions_role as is_parent;

contents_relation sub parent_child_relation,
	relates is_contents_role as is_child, relates has_contents_role as is_parent;

default_relation sub parent_child_relation,
	relates is_default_role as is_child, relates has_default_role as is_parent;

else_relation sub parent_child_relation,
	relates is_else_role as is_child, relates has_else_role as is_parent;

ensure_body_relation sub parent_child_relation,
	relates is_ensure_body_role as is_child, relates has_ensure_body_role as is_parent;

exceptions_relation sub parent_child_relation,
	relates is_exceptions_role as is_child, relates has_exceptions_role as is_parent;

file_relation sub parent_child_relation,
	relates is_file_role as is_child, relates has_file_role as is_parent;

handlers_relation sub parent_child_relation,
	relates is_handlers_role as is_child, relates has_handlers_role as is_parent;

iterated_relation sub parent_child_relation,
	relates is_iterated_role as is_child, relates has_iterated_role as is_parent;

iterators_relation sub parent_child_relation,
	relates is_iterators_role as is_child, relates has_iterators_role as is_parent;

left_relation sub parent_child_relation,
	relates is_left_role as is_child, relates has_left_role as is_parent;

object_relation sub parent_child_relation,
	relates is_object_role as is_child, relates has_object_role as is_parent;

operator_relation sub parent_child_relation,
	relates is_operator_role as is_child, relates has_operator_role as is_parent;

options_relation sub parent_child_relation,
	relates is_options_role as is_child, relates has_options_role as is_parent;

parent_relation sub parent_child_relation,
	relates is_parent_role as is_child, relates has_parent_role as is_parent;

qnames_relation sub parent_child_relation,
	relates is_qnames_role as is_child, relates has_qnames_role as is_parent;

right_relation sub parent_child_relation,
	relates is_right_role as is_child, relates has_right_role as is_parent;

target_relation sub parent_child_relation,
	relates is_target_role as is_child, relates has_target_role as is_parent;

targets_relation sub parent_child_relation,
	relates is_targets_role as is_child, relates has_targets_role as is_parent;

text_relation sub parent_child_relation,
	relates is_text_role as is_child, relates has_text_role as is_parent;

value_relation sub parent_child_relation,
	relates is_value_role as is_child, relates has_value_role as is_parent;

values_relation sub parent_child_relation,
	relates is_values_role as is_child, relates has_values_role as is_parent;

when_clauses_relation sub parent_child_relation,
	relates is_when_clauses_role as is_child, relates has_when_clauses_role as is_parent;
