define

##########---------- Attributes ----------##########
booleanValue sub attribute, value boolean;
doubleValue sub attribute, value double;
name sub attribute, value string;
numberValue sub attribute, value long;
stringValue sub attribute, value string;
token sub attribute, value string;

#####----- Ruby -----#####
documentationAttribute sub attribute, value string;
inlineAttribute sub attribute, value string;
selectorAttribute sub attribute, value string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	owns token,
	plays parent_child_relation:is_child,
	plays parent_child_relation:is_parent;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

AliasArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays one_relation:has_one_role,
	plays two_relation:has_two_role;

AndArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays left_relation:has_left_role,
	plays right_relation:has_right_role;

AndAsgnArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays values_relation:is_values_role,
	plays target_relation:has_target_role,
	plays value_relation:has_value_role;

ArgArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role;

ArgsArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:has_children_role;

ArrayArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays exceptions_relation:is_exceptions_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays contents_relation:has_contents_role;

BackRefArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays options_relation:is_options_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

BeginArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays options_relation:is_options_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays text_relation:is_text_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role;

BlockargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role;

BlockArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays args_relation:has_args_role,
	plays blockdata_relation:has_blockdata_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role;

BlockPassArtifact sub RubySourceArtifact,
	# Structural
	plays children_relation:is_children_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

BreakArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays right_relation:is_right_role,
	plays target_relation:has_target_role;

CaseArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays casevar_relation:has_casevar_role,
	plays comments_relation:has_comments_role,
	plays else_relation:has_else_role,
	plays when_clauses_relation:has_when_clauses_role;

CasgnArtifact sub RubySourceArtifact,
	# Structural
	plays alias_relation:is_alias_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays iterators_relation:is_iterators_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays comments_relation:has_comments_role,
	plays value_relation:has_value_role;

CbaseArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role;

ClassArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays right_relation:is_right_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role,
	plays parent_relation:has_parent_role;

CommentArtifact sub RubySourceArtifact,
	# Attributes
	owns documentationAttribute,
	owns inlineAttribute,
	# Structural
	plays comments_relation:is_comments_role;

ComplexArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays contents_relation:is_contents_role,
	plays values_relation:is_values_role;

ConstArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role;

CvarArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

CvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays iterators_relation:is_iterators_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays value_relation:has_value_role;

DefArtifact sub RubySourceArtifact,
	# Attributes
	owns name,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays args_relation:has_args_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role;

DefinedArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

DefsArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays args_relation:has_args_role,
	plays base_relation:has_base_role,
	plays class_relation:has_class_role;

DstrArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

DsymArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

EnsureArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays body_relation:has_body_role,
	plays ensure_body_relation:has_ensure_body_role;

ErangeArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays iterated_relation:is_iterated_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays one_relation:has_one_role,
	plays two_relation:has_two_role;

FalseArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

FloatArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

ForArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role,
	plays iterated_relation:has_iterated_role,
	plays iterators_relation:has_iterators_role;

GvarArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

GvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role,
	plays comments_relation:has_comments_role;

HashArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays comments_relation:has_comments_role,
	plays contents_relation:has_contents_role;

IdentifierArtifact sub RubySourceArtifact,
	# Attributes
	owns name,
	# Structural
	plays qnames_relation:is_qnames_role;

IfArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role,
	plays condition_relation:has_condition_role,
	plays else_relation:has_else_role;

IntArtifact sub RubySourceArtifact,
	# Attributes
	owns doubleValue,
	owns numberValue,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

IrangeArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays one_relation:has_one_role,
	plays two_relation:has_two_role;

IvarArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays options_relation:is_options_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

IvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays alias_relation:is_alias_role,
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays iterators_relation:is_iterators_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays value_relation:has_value_role;

KwargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role;

KwbeginArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role;

KwoptargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role,
	plays default_relation:has_default_role;

KwrestargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role;

KwsplatArtifact sub RubySourceArtifact,
	# Structural
	plays contents_relation:is_contents_role;

LvarArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

LvasgnArtifact sub RubySourceArtifact,
	# Attributes
	owns name,
	# Structural
	plays alias_relation:is_alias_role,
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays iterated_relation:is_iterated_role,
	plays iterators_relation:is_iterators_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays value_relation:has_value_role;

MasgnArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays targets_relation:has_targets_role,
	plays values_relation:has_values_role;

MatchWithLvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

MlhsArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role,
	plays iterators_relation:is_iterators_role,
	plays targets_relation:is_targets_role,
	plays children_relation:has_children_role;

ModuleArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays right_relation:is_right_role,
	plays begin_relation:has_begin_role,
	plays comments_relation:has_comments_role,
	plays file_relation:has_file_role;

NextArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays right_relation:is_right_role,
	plays target_relation:has_target_role;

NilArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

NilNodeArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays else_relation:is_else_role;

NthRefArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

OpAsgnArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays class_relation:is_class_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays comments_relation:has_comments_role,
	plays operator_relation:has_operator_role,
	plays target_relation:has_target_role,
	plays value_relation:has_value_role;

OperatorArtifact sub RubySourceArtifact,
	# Structural
	plays operator_relation:is_operator_role;

OptargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role,
	plays default_relation:has_default_role;

OrArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays left_relation:has_left_role,
	plays right_relation:has_right_role;

OrAsgnArtifact sub RubySourceArtifact,
	# Structural
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays target_relation:has_target_role,
	plays value_relation:has_value_role;

PairArtifact sub RubySourceArtifact,
	# Structural
	plays contents_relation:is_contents_role,
	plays one_relation:has_one_role,
	plays two_relation:has_two_role;

PostexeArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays body_relation:has_body_role;

PreexeArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays file_relation:is_file_role,
	plays body_relation:has_body_role;

RationalArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays contents_relation:is_contents_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

RedoArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role;

RegexpArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays options_relation:has_options_role,
	plays text_relation:has_text_role;

RegoptArtifact sub RubySourceArtifact,
	# Structural
	plays options_relation:is_options_role,
	plays text_relation:is_text_role,
	plays options_relation:has_options_role;

ResbodyArtifact sub RubySourceArtifact,
	# Structural
	plays handlers_relation:is_handlers_role,
	plays alias_relation:has_alias_role,
	plays body_relation:has_body_role,
	plays exceptions_relation:has_exceptions_role;

RescueArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays body_relation:has_body_role,
	plays else_relation:has_else_role,
	plays handlers_relation:has_handlers_role;

RestargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:is_children_role;

RetryArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role;

ReturnArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays right_relation:is_right_role,
	plays comments_relation:has_comments_role,
	plays target_relation:has_target_role;

SclassArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role,
	plays object_relation:has_object_role;

SelfArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

SendArrayArtifact sub RubySourceArtifact,
	# Attributes
	owns selectorAttribute,
	# Structural
	plays base_relation:is_base_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays values_relation:has_values_role;

SendAssignArtifact sub RubySourceArtifact,
	# Attributes
	owns selectorAttribute,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays comments_relation:has_comments_role,
	plays values_relation:has_values_role;

SendCallArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays comments_relation:has_comments_role,
	plays values_relation:has_values_role;

SendIdentifierArtifact sub RubySourceArtifact,
	# Attributes
	owns selectorAttribute,
	# Structural
	plays base_relation:is_base_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays comments_relation:has_comments_role;

SendOperatorArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays comments_relation:has_comments_role,
	plays values_relation:has_values_role;

SendQualifiedArtifact sub RubySourceArtifact,
	# Attributes
	owns selectorAttribute,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays iterated_relation:is_iterated_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays parent_relation:is_parent_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays comments_relation:has_comments_role,
	plays qnames_relation:has_qnames_role,
	plays values_relation:has_values_role;

SendRequireArtifact sub RubySourceArtifact,
	# Attributes
	owns selectorAttribute,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays comments_relation:has_comments_role,
	plays values_relation:has_values_role;

SendStatementArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays begin_relation:is_begin_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays base_relation:has_base_role,
	plays values_relation:has_values_role;

ShadowargArtifact sub RubySourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays children_relation:has_children_role;

SplatArtifact sub RubySourceArtifact,
	# Structural
	plays children_relation:is_children_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays target_relation:is_target_role,
	plays values_relation:is_values_role;

StrArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays file_relation:is_file_role,
	plays left_relation:is_left_role,
	plays one_relation:is_one_role,
	plays options_relation:is_options_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays text_relation:is_text_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

SuperArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

SymArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

SymbolArtifact sub RubySourceArtifact,
	# Structural
	plays children_relation:is_children_role,
	plays options_relation:is_options_role;

TrueArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays children_relation:is_children_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays conditions_relation:is_conditions_role,
	plays contents_relation:is_contents_role,
	plays default_relation:is_default_role,
	plays else_relation:is_else_role,
	plays left_relation:is_left_role,
	plays object_relation:is_object_role,
	plays one_relation:is_one_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

UndefArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays target_relation:has_target_role;

UntilArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays body_relation:has_body_role,
	plays condition_relation:has_condition_role;

UntilPostArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays body_relation:has_body_role,
	plays condition_relation:has_condition_role;

WhenArtifact sub RubySourceArtifact,
	# Structural
	plays when_clauses_relation:is_when_clauses_role,
	plays body_relation:has_body_role,
	plays conditions_relation:has_conditions_role;

WhileArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays file_relation:is_file_role,
	plays value_relation:is_value_role,
	plays body_relation:has_body_role,
	plays comments_relation:has_comments_role,
	plays condition_relation:has_condition_role;

WhilePostArtifact sub RubySourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays body_relation:has_body_role,
	plays condition_relation:has_condition_role;

XstrArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays children_relation:is_children_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays right_relation:is_right_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays children_relation:has_children_role;

YieldArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays body_relation:is_body_role,
	plays casevar_relation:is_casevar_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays two_relation:is_two_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays target_relation:has_target_role;

ZsuperArtifact sub RubySourceArtifact,
	# Structural
	plays base_relation:is_base_role,
	plays blockdata_relation:is_blockdata_role,
	plays body_relation:is_body_role,
	plays class_relation:is_class_role,
	plays condition_relation:is_condition_role,
	plays contents_relation:is_contents_role,
	plays else_relation:is_else_role,
	plays ensure_body_relation:is_ensure_body_role,
	plays left_relation:is_left_role,
	plays right_relation:is_right_role,
	plays target_relation:is_target_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Ruby -----#####
alias_relation sub parent_child_relation,
	relates is_alias_role as is_child, relates has_alias_role as is_parent;

args_relation sub parent_child_relation,
	relates is_args_role as is_child, relates has_args_role as is_parent;

base_relation sub parent_child_relation,
	relates is_base_role as is_child, relates has_base_role as is_parent;

begin_relation sub parent_child_relation,
	relates is_begin_role as is_child, relates has_begin_role as is_parent;

blockdata_relation sub parent_child_relation,
	relates is_blockdata_role as is_child, relates has_blockdata_role as is_parent;

body_relation sub parent_child_relation,
	relates is_body_role as is_child, relates has_body_role as is_parent;

casevar_relation sub parent_child_relation,
	relates is_casevar_role as is_child, relates has_casevar_role as is_parent;

children_relation sub parent_child_relation,
	relates is_children_role as is_child, relates has_children_role as is_parent;

class_relation sub parent_child_relation,
	relates is_class_role as is_child, relates has_class_role as is_parent;

comments_relation sub parent_child_relation,
	relates is_comments_role as is_child, relates has_comments_role as is_parent;

condition_relation sub parent_child_relation,
	relates is_condition_role as is_child, relates has_condition_role as is_parent;

conditions_relation sub parent_child_relation,
	relates is_conditions_role as is_child, relates has_conditions_role as is_parent;

contents_relation sub parent_child_relation,
	relates is_contents_role as is_child, relates has_contents_role as is_parent;

default_relation sub parent_child_relation,
	relates is_default_role as is_child, relates has_default_role as is_parent;

else_relation sub parent_child_relation,
	relates is_else_role as is_child, relates has_else_role as is_parent;

ensure_body_relation sub parent_child_relation,
	relates is_ensure_body_role as is_child, relates has_ensure_body_role as is_parent;

exceptions_relation sub parent_child_relation,
	relates is_exceptions_role as is_child, relates has_exceptions_role as is_parent;

file_relation sub parent_child_relation,
	relates is_file_role as is_child, relates has_file_role as is_parent;

handlers_relation sub parent_child_relation,
	relates is_handlers_role as is_child, relates has_handlers_role as is_parent;

iterated_relation sub parent_child_relation,
	relates is_iterated_role as is_child, relates has_iterated_role as is_parent;

iterators_relation sub parent_child_relation,
	relates is_iterators_role as is_child, relates has_iterators_role as is_parent;

left_relation sub parent_child_relation,
	relates is_left_role as is_child, relates has_left_role as is_parent;

object_relation sub parent_child_relation,
	relates is_object_role as is_child, relates has_object_role as is_parent;

one_relation sub parent_child_relation,
	relates is_one_role as is_child, relates has_one_role as is_parent;

operator_relation sub parent_child_relation,
	relates is_operator_role as is_child, relates has_operator_role as is_parent;

options_relation sub parent_child_relation,
	relates is_options_role as is_child, relates has_options_role as is_parent;

parent_relation sub parent_child_relation,
	relates is_parent_role as is_child, relates has_parent_role as is_parent;

qnames_relation sub parent_child_relation,
	relates is_qnames_role as is_child, relates has_qnames_role as is_parent;

right_relation sub parent_child_relation,
	relates is_right_role as is_child, relates has_right_role as is_parent;

target_relation sub parent_child_relation,
	relates is_target_role as is_child, relates has_target_role as is_parent;

targets_relation sub parent_child_relation,
	relates is_targets_role as is_child, relates has_targets_role as is_parent;

text_relation sub parent_child_relation,
	relates is_text_role as is_child, relates has_text_role as is_parent;

two_relation sub parent_child_relation,
	relates is_two_role as is_child, relates has_two_role as is_parent;

value_relation sub parent_child_relation,
	relates is_value_role as is_child, relates has_value_role as is_parent;

values_relation sub parent_child_relation,
	relates is_values_role as is_child, relates has_values_role as is_parent;

when_clauses_relation sub parent_child_relation,
	relates is_when_clauses_role as is_child, relates has_when_clauses_role as is_parent;
