define

##########---------- Entities ----------##########

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

AliasArtifact sub RubySourceArtifact,
	# Semantic
	plays ALIAS:IS_ALIAS,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

AndArtifact sub RubySourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays OPERATOR:IS_OPERATOR,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

AndAsgnArtifact sub RubySourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays OPERATOR:IS_OPERATOR,
	plays THEN:IS_THEN;

ArgArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME;

ArgsArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE;

ArrayArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LIST:IS_LIST,
	plays LITERAL:IS_LITERAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

BackRefArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays REGEXP:IS_REGEXP,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

BeginArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

BlockargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME;

BlockArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

BlockPassArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays FUNCTION:IS_FUNCTION,
	plays UNANNOTATED:IS_UNANNOTATED;

BreakArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays BREAK:IS_BREAK,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

CaseArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

CasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

CbaseArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays QUALIFIED:IS_QUALIFIED;

ClassArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays TYPE:IS_TYPE;

CommentArtifact sub RubySourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays NOOP:IS_NOOP;

ComplexArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT;

ConstArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

CvarArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays TYPE:IS_TYPE,
	plays VALUE:IS_VALUE,
	plays VISIBILITY:IS_VISIBILITY;

CvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

DefArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays DECLARATION:IS_DECLARATION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

DefinedArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays TUPLE:IS_TUPLE,
	plays UNANNOTATED:IS_UNANNOTATED,
	plays VALUE:IS_VALUE;

DefsArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays DECLARATION:IS_DECLARATION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

DstrArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

DsymArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

EnsureArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays FINALLY:IS_FINALLY;

ErangeArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

FalseArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

FloatArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

ForArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

GvarArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

GvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

HashArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays MAP:IS_MAP,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

IdentifierArtifact sub RubySourceArtifact;

IfArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

IntArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

IrangeArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

IvarArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INSTANCE:IS_INSTANCE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE,
	plays VISIBILITY:IS_VISIBILITY;

IvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

KwargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays MAP:IS_MAP,
	plays NAME:IS_NAME;

KwbeginArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

KwoptargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays NAME:IS_NAME;

KwrestargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE;

KwsplatArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE;

LvarArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

LvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

MasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays THEN:IS_THEN;

MatchWithLvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

MlhsArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT;

ModuleArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays MODULE:IS_MODULE,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

NextArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

NilArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays NULL:IS_NULL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

NilNodeArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays NULL:IS_NULL;

NthRefArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays REGEXP:IS_REGEXP,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

OpAsgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays AND:IS_AND,
	plays ARGUMENT:IS_ARGUMENT,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays DIVIDE:IS_DIVIDE,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays MODULO:IS_MODULO,
	plays MULTIPLY:IS_MULTIPLY,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RIGHT:IS_RIGHT,
	plays RIGHT_SHIFT:IS_RIGHT_SHIFT,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE,
	plays XOR:IS_XOR;

OperatorArtifact sub RubySourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays AND:IS_AND,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays DIVIDE:IS_DIVIDE,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays MODULO:IS_MODULO,
	plays MULTIPLY:IS_MULTIPLY,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RIGHT_SHIFT:IS_RIGHT_SHIFT,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays XOR:IS_XOR;

OptargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DEFAULT:IS_DEFAULT,
	plays EXPRESSION:IS_EXPRESSION,
	plays NAME:IS_NAME;

OrArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

OrAsgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

PairArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays TUPLE:IS_TUPLE;

PostexeArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays EXPRESSION:IS_EXPRESSION,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

PreexeArtifact sub RubySourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

RationalArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT;

RedoArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays THEN:IS_THEN,
	plays UNANNOTATED:IS_UNANNOTATED;

RegexpArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays REGEXP:IS_REGEXP,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

RegoptArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays REGEXP:IS_REGEXP;

ResbodyArtifact sub RubySourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays EXPRESSION:IS_EXPRESSION;

RescueArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TRY:IS_TRY;

RestargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LIST:IS_LIST;

RetryArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

ReturnArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays RETURN:IS_RETURN,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

SclassArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TYPE:IS_TYPE;

SelfArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays THIS:IS_THIS,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

SendArrayArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LIST:IS_LIST,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

SendAssignArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

SendCallArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

SendIdentifierArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

SendOperatorArtifact sub RubySourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays AND:IS_AND,
	plays ARGUMENT:IS_ARGUMENT,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays DIVIDE:IS_DIVIDE,
	plays ELSE:IS_ELSE,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays IDENTICAL:IS_IDENTICAL,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays LESS_THAN_OR_EQUAL:IS_LESS_THAN_OR_EQUAL,
	plays MODULO:IS_MODULO,
	plays MULTIPLY:IS_MULTIPLY,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL,
	plays RIGHT:IS_RIGHT,
	plays RIGHT_SHIFT:IS_RIGHT_SHIFT,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE,
	plays XOR:IS_XOR;

SendQualifiedArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays QUALIFIED:IS_QUALIFIED,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UPDATE:IS_UPDATE,
	plays VALUE:IS_VALUE;

SendRequireArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IMPORT:IS_IMPORT,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays UNANNOTATED:IS_UNANNOTATED,
	plays VALUE:IS_VALUE;

SendStatementArtifact sub RubySourceArtifact,
	# Semantic
	plays ANONYMOUS:IS_ANONYMOUS,
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays CONTINUE:IS_CONTINUE,
	plays DECLARATION:IS_DECLARATION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays INSTANCE:IS_INSTANCE,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays SUBTYPE:IS_SUBTYPE,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

ShadowargArtifact sub RubySourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

SplatArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT;

StrArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

SuperArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BASE:IS_BASE,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

SymArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

SymbolArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER;

TrueArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

UndefArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

UntilArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

UntilPostArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays EXPRESSION:IS_EXPRESSION,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

WhenArtifact sub RubySourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays EXPRESSION:IS_EXPRESSION;

WhileArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

WhilePostArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

XstrArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays BINARY:IS_BINARY,
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING,
	plays THEN:IS_THEN;

YieldArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RETURN:IS_RETURN,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN,
	plays TUPLE:IS_TUPLE,
	plays VALUE:IS_VALUE;

ZsuperArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BASE:IS_BASE,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

ALIAS sub relation,
	relates IS_ALIAS;

AND sub relation,
	relates IS_AND;

ANONYMOUS sub relation,
	relates IS_ANONYMOUS;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BASE sub relation,
	relates IS_BASE;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

CALL sub relation,
	relates IS_CALL;

CASE sub relation,
	relates IS_CASE;

CATCH sub relation,
	relates IS_CATCH;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

CONTINUE sub relation,
	relates IS_CONTINUE;

DECLARATION sub relation,
	relates IS_DECLARATION;

DEFAULT sub relation,
	relates IS_DEFAULT;

DIVIDE sub relation,
	relates IS_DIVIDE;

ELSE sub relation,
	relates IS_ELSE;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FINALLY sub relation,
	relates IS_FINALLY;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTICAL sub relation,
	relates IS_IDENTICAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

INSTANCE sub relation,
	relates IS_INSTANCE;

ITERATOR sub relation,
	relates IS_ITERATOR;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN_OR_EQUAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MAP sub relation,
	relates IS_MAP;

MODULE sub relation,
	relates IS_MODULE;

MODULO sub relation,
	relates IS_MODULO;

MULTIPLY sub relation,
	relates IS_MULTIPLY;

NAME sub relation,
	relates IS_NAME;

NOOP sub relation,
	relates IS_NOOP;

NOT sub relation,
	relates IS_NOT;

NULL sub relation,
	relates IS_NULL;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PRIMITIVE sub relation,
	relates IS_PRIMITIVE;

QUALIFIED sub relation,
	relates IS_QUALIFIED;

REGEXP sub relation,
	relates IS_REGEXP;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

RIGHT_SHIFT sub relation,
	relates IS_RIGHT_SHIFT;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

SUBTYPE sub relation,
	relates IS_SUBTYPE;

SWITCH sub relation,
	relates IS_SWITCH;

THEN sub relation,
	relates IS_THEN;

THIS sub relation,
	relates IS_THIS;

TRY sub relation,
	relates IS_TRY;

TUPLE sub relation,
	relates IS_TUPLE;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UPDATE sub relation,
	relates IS_UPDATE;

VALUE sub relation,
	relates IS_VALUE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WHILE sub relation,
	relates IS_WHILE;

WORLD sub relation,
	relates IS_WORLD;

XOR sub relation,
	relates IS_XOR;
