define

##########---------- Attributes ----------##########
token sub attribute datatype string;

#####----- Ruby -----#####
colAttribute sub attribute datatype string;
documentationAttribute sub attribute datatype string;
inlineAttribute sub attribute datatype string;
lineAttribute sub attribute datatype string;
nameAttribute sub attribute datatype string;
offsetAttribute sub attribute datatype string;
selectorAttribute sub attribute datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity
	has token;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

AliasArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays has_1_relation
	plays has_2_relation
	# Semantic
	plays ALIAS
	plays BODY
	plays EXPRESSION
	plays STATEMENT
	plays THEN;

AndArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_left_relation
	plays has_right_relation
	# Semantic
	plays AND
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays BOOLEAN
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays OPERATOR
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

AndAsgnArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_else_relation
	plays has_target_relation
	plays has_value_relation
	# Semantic
	plays AND
	plays BITWISE
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays OPERATOR
	plays THEN;

ArgArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	# Semantic
	plays ARGUMENT
	plays EXPRESSION
	plays IDENTIFIER
	plays NAME;

ArgsArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays has_children_relation
	# Semantic
	plays ARGUMENT
	plays EXPRESSION
	plays INCOMPLETE;

ArrayArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_exceptions_relation
	plays is_iterated_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_contents_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays LIST
	plays LITERAL
	plays PRIMITIVE
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

BackRefArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_value_relation
	plays is_values_relation
	plays has_children_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays EXPRESSION
	plays INCOMPLETE
	plays REGEXP
	plays RIGHT;

BeginArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_iterated_relation
	plays is_left_relation
	plays is_options_relation
	plays is_right_relation
	plays is_target_relation
	plays is_text_relation
	plays is_value_relation
	plays is_values_relation
	plays has_body_relation
	plays has_comments_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BLOCK
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

BlockargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	# Semantic
	plays UNANNOTATED;

BlockArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_args_relation
	plays has_blockdata_relation
	plays has_body_relation
	plays has_comments_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BLOCK
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

BlockPassArtifact sub RubySourceArtifact
	# Structural
	plays is_children_relation
	plays is_values_relation
	plays has_children_relation
	# Semantic
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays UNANNOTATED;

BreakArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_else_relation
	plays is_right_relation
	plays has_target_relation
	# Semantic
	plays BODY
	plays BREAK
	plays ELSE
	plays EXPRESSION
	plays RIGHT
	plays STATEMENT
	plays THEN;

CaseArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_class_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_left_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	plays has_casevar_relation
	plays has_else_relation
	plays has_when_clauses_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays LEFT
	plays RIGHT
	plays STATEMENT
	plays SWITCH
	plays THEN;

CasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_alias_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_children_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_file_relation
	plays is_iterators_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_comments_relation
	plays has_value_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays IDENTIFIER
	plays ITERATOR
	plays LEFT
	plays RIGHT
	plays THEN;

CbaseArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	# Semantic
	plays EXPRESSION
	plays IDENTIFIER
	plays INCOMPLETE
	plays QUALIFIED;

ClassArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_right_relation
	plays has_body_relation
	plays has_comments_relation
	plays has_parent_relation
	# Semantic
	plays BODY
	plays DECLARATION
	plays ELSE
	plays EXPRESSION
	plays IDENTIFIER
	plays RIGHT
	plays STATEMENT
	plays THEN
	plays TYPE;

CommentArtifact sub RubySourceArtifact
	# Attributes
	has documentationAttribute
	has inlineAttribute
	# Structural
	plays is_comments_relation
	plays has_end_relation
	plays has_start_relation
	# Semantic
	plays COMMENT
	plays NOOP;

ComplexArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	# Semantic
	plays EXPRESSION
	plays INCOMPLETE
	plays LITERAL
	plays NUMBER
	plays PRIMITIVE;

ConstArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_object_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays INCOMPLETE
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

CvarArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_left_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays BINARY
	plays CALL
	plays CONDITION
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays LEFT
	plays RIGHT
	plays TUPLE
	plays TYPE
	plays VALUE
	plays VISIBILITY;

CvasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_ensure_body_relation
	plays is_iterators_relation
	plays is_target_relation
	plays has_value_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays EXPRESSION
	plays FOR
	plays IDENTIFIER
	plays ITERATOR
	plays LEFT
	plays THEN;

DefArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_class_relation
	plays is_else_relation
	plays is_file_relation
	plays is_value_relation
	plays is_values_relation
	plays has_args_relation
	plays has_body_relation
	plays has_comments_relation
	# Semantic
	plays BINARY
	plays BODY
	plays DECLARATION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays RIGHT
	plays STATEMENT
	plays THEN;

DefinedArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_default_relation
	plays is_left_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays BINARY
	plays BODY
	plays CONDITION
	plays EXPRESSION
	plays LEFT
	plays RIGHT
	plays TUPLE
	plays UNANNOTATED
	plays VALUE;

DefsArtifact sub RubySourceArtifact
	# Structural
	plays is_begin_relation
	plays is_body_relation
	plays is_else_relation
	plays is_values_relation
	plays has_args_relation
	plays has_base_relation
	plays has_class_relation
	# Semantic
	plays BODY
	plays DECLARATION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays INCOMPLETE
	plays STATEMENT
	plays THEN;

DstrArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_children_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UNANNOTATED
	plays VALUE;

DsymArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_contents_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_children_relation
	# Semantic
	plays ARGUMENT
	plays BINARY
	plays CALL
	plays EXPRESSION
	plays FUNCTION
	plays INCOMPLETE
	plays LEFT
	plays RIGHT
	plays STRING
	plays TUPLE
	plays VALUE;

EnsureArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_class_relation
	plays has_body_relation
	plays has_ensure_body_relation
	# Semantic
	plays EXPRESSION
	plays FINALLY;

ErangeArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_body_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_value_relation
	plays is_values_relation
	plays has_1_relation
	plays has_2_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays EXPRESSION
	plays FUNCTION
	plays INCOMPLETE
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

FalseArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays BOOLEAN
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays LITERAL
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

FloatArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays LITERAL
	plays NUMBER
	plays PRIMITIVE
	plays RIGHT
	plays TUPLE
	plays VALUE;

ForArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_condition_relation
	plays has_body_relation
	plays has_iterated_relation
	plays has_iterators_relation
	# Semantic
	plays BODY
	plays CONDITION
	plays EXPRESSION
	plays FOR
	plays STATEMENT
	plays THEN;

GvarArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE
	plays VISIBILITY
	plays WORLD;

GvasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_children_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_children_relation
	plays has_comments_relation
	# Semantic
	plays BINARY
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays LEFT
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

HashArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_file_relation
	plays is_iterated_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_comments_relation
	plays has_contents_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays LITERAL
	plays MAP
	plays PRIMITIVE
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

IdentifierArtifact sub RubySourceArtifact
	# Attributes
	has nameAttribute
	# Structural
	plays is_qnames_relation;

IfArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_body_relation
	plays has_comments_relation
	plays has_condition_relation
	plays has_else_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays IF
	plays LEFT
	plays RIGHT
	plays STATEMENT
	plays THEN
	plays TUPLE
	plays VALUE;

IntArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays LITERAL
	plays NUMBER
	plays PRIMITIVE
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

IrangeArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_body_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_iterated_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_1_relation
	plays has_2_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays INCOMPLETE
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

IvarArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays INSTANCE
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE
	plays VISIBILITY;

IvasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_alias_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_iterators_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_value_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays IDENTIFIER
	plays ITERATOR
	plays LEFT
	plays RIGHT
	plays THEN;

KwargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	# Semantic
	plays ARGUMENT
	plays EXPRESSION
	plays MAP
	plays NAME;

KwbeginArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_class_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_left_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	plays has_body_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays BLOCK
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

KwoptargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	plays has_default_relation
	# Semantic
	plays ARGUMENT
	plays EXPRESSION
	plays INCOMPLETE
	plays NAME;

KwrestargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	# Semantic
	plays ARGUMENT
	plays EXPRESSION
	plays IDENTIFIER
	plays INCOMPLETE;

KwsplatArtifact sub RubySourceArtifact
	# Structural
	plays is_contents_relation
	# Semantic
	plays EXPRESSION
	plays INCOMPLETE;

LvarArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_iterated_relation
	plays is_left_relation
	plays is_object_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays IDENTIFIER
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

LvasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_alias_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_iterated_relation
	plays is_iterators_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_value_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays IDENTIFIER
	plays ITERATOR
	plays LEFT
	plays RIGHT
	plays THEN
	plays UPDATE;

MasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays has_targets_relation
	plays has_values_relation
	# Semantic
	plays ASSIGNMENT
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays INCOMPLETE
	plays THEN;

MatchWithLvasgnArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_condition_relation
	plays is_left_relation
	plays is_right_relation
	plays has_children_relation
	# Semantic
	plays BODY
	plays CONDITION
	plays EXPRESSION
	plays LEFT
	plays RIGHT
	plays UNANNOTATED;

MlhsArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	plays is_iterators_relation
	plays is_targets_relation
	plays has_children_relation
	# Semantic
	plays EXPRESSION
	plays FOR
	plays INCOMPLETE
	plays ITERATOR
	plays LEFT;

ModuleArtifact sub RubySourceArtifact
	# Structural
	plays is_begin_relation
	plays is_body_relation
	plays is_else_relation
	plays is_file_relation
	plays has_begin_relation
	plays has_comments_relation
	plays has_file_relation
	# Semantic
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays IDENTIFIER
	plays MODULE
	plays STATEMENT
	plays THEN;

NextArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_else_relation
	plays is_right_relation
	plays has_target_relation
	# Semantic
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

NilArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UNANNOTATED
	plays VALUE;

NilNodeArtifact sub RubySourceArtifact
	# Structural
	plays is_begin_relation
	plays is_body_relation
	plays is_else_relation
	# Semantic
	plays BODY
	plays NULL;

OpAsgnArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_class_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_left_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	plays has_comments_relation
	plays has_operator_relation
	plays has_target_relation
	plays has_value_relation
	# Semantic
	plays ADD
	plays AND
	plays ARGUMENT
	plays ARITHMETIC
	plays ASSIGNMENT
	plays BINARY
	plays BITWISE
	plays BODY
	plays CALL
	plays DIVIDE
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays LEFT_SHIFT
	plays MODULO
	plays MULTIPLY
	plays OPERATOR
	plays OR
	plays RIGHT
	plays RIGHT_SHIFT
	plays SUBSTRACT
	plays THEN
	plays XOR;

OperatorArtifact sub RubySourceArtifact
	# Structural
	plays is_operator_relation
	# Semantic
	plays ADD
	plays AND
	plays ARITHMETIC
	plays BINARY
	plays BITWISE
	plays DIVIDE
	plays EXPRESSION
	plays LEFT_SHIFT
	plays MODULO
	plays MULTIPLY
	plays OPERATOR
	plays OR
	plays RIGHT_SHIFT
	plays SUBSTRACT
	plays XOR;

OptargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	plays has_default_relation
	# Semantic
	plays ARGUMENT
	plays DEFAULT
	plays EXPRESSION
	plays NAME;

OrArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_left_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_left_relation
	plays has_right_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays BOOLEAN
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays OPERATOR
	plays OR
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

OrAsgnArtifact sub RubySourceArtifact
	# Structural
	plays is_begin_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_else_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_target_relation
	plays has_value_relation
	# Semantic
	plays ARGUMENT
	plays BINARY
	plays BITWISE
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays OPERATOR
	plays OR
	plays RIGHT
	plays THEN;

PairArtifact sub RubySourceArtifact
	# Structural
	plays is_contents_relation
	plays has_1_relation
	plays has_2_relation
	# Semantic
	plays EXPRESSION
	plays LITERAL
	plays PRIMITIVE
	plays TUPLE;

PositionArtifact sub RubySourceArtifact
	# Attributes
	has colAttribute
	has lineAttribute
	has offsetAttribute
	# Structural
	plays is_end_relation
	plays is_start_relation;

PreexeArtifact sub RubySourceArtifact
	# Structural
	plays is_file_relation
	plays has_body_relation
	# Semantic
	plays UNANNOTATED;

RationalArtifact sub RubySourceArtifact
	# Structural
	plays is_value_relation
	# Semantic
	plays BINARY
	plays EXPRESSION
	plays INCOMPLETE
	plays LITERAL
	plays NUMBER
	plays PRIMITIVE
	plays RIGHT;

RedoArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	# Semantic
	plays BODY
	plays EXPRESSION
	plays THEN
	plays UNANNOTATED;

RegexpArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	plays has_options_relation
	plays has_text_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays REGEXP
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

RegoptArtifact sub RubySourceArtifact
	# Structural
	plays is_options_relation
	plays is_text_relation
	plays has_options_relation
	# Semantic
	plays EXPRESSION
	plays INCOMPLETE
	plays REGEXP;

ResbodyArtifact sub RubySourceArtifact
	# Structural
	plays is_handlers_relation
	plays has_alias_relation
	plays has_body_relation
	plays has_exceptions_relation
	# Semantic
	plays CATCH
	plays EXPRESSION;

RescueArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_class_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_value_relation
	plays is_values_relation
	plays has_body_relation
	plays has_else_relation
	plays has_handlers_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays RIGHT
	plays THEN
	plays TRY;

RestargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays is_children_relation
	# Semantic
	plays ARGUMENT
	plays EXPRESSION
	plays IDENTIFIER
	plays LIST;

RetryArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_else_relation
	# Semantic
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays INCOMPLETE
	plays STATEMENT
	plays THEN;

ReturnArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays is_class_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_right_relation
	plays has_target_relation
	# Semantic
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays RETURN
	plays RIGHT
	plays STATEMENT
	plays THEN;

SclassArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_class_relation
	plays is_value_relation
	plays has_body_relation
	plays has_object_relation
	# Semantic
	plays BINARY
	plays BODY
	plays DECLARATION
	plays EXPRESSION
	plays INCOMPLETE
	plays RIGHT
	plays THEN
	plays TYPE;

SelfArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_iterated_relation
	plays is_object_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays THIS
	plays TUPLE
	plays UPDATE
	plays VALUE;

SendArrayArtifact sub RubySourceArtifact
	# Attributes
	has selectorAttribute
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_iterated_relation
	plays is_left_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays LIST
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

SendAssignArtifact sub RubySourceArtifact
	# Attributes
	has selectorAttribute
	# Structural
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_comments_relation
	plays has_values_relation
	# Semantic
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays LEFT
	plays RIGHT
	plays THEN;

SendCallArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_iterated_relation
	plays is_left_relation
	plays is_object_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_comments_relation
	plays has_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

SendIdentifierArtifact sub RubySourceArtifact
	# Attributes
	has selectorAttribute
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_iterated_relation
	plays is_left_relation
	plays is_object_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_comments_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays IDENTIFIER
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

SendOperatorArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_values_relation
	# Semantic
	plays ADD
	plays AND
	plays ARGUMENT
	plays ARITHMETIC
	plays ASSIGNMENT
	plays BINARY
	plays BITWISE
	plays BODY
	plays CALL
	plays CONDITION
	plays DIVIDE
	plays ELSE
	plays EQUAL
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays GREATER_THAN_OR_EQUAL
	plays IDENTICAL
	plays INCOMPLETE
	plays LEFT
	plays LEFT_SHIFT
	plays LESS_THAN_OR_EQUAL
	plays MODULO
	plays MULTIPLY
	plays NOT
	plays OPERATOR
	plays OR
	plays RELATIONAL
	plays RIGHT
	plays RIGHT_SHIFT
	plays SUBSTRACT
	plays THEN
	plays TUPLE
	plays UNARY
	plays VALUE
	plays XOR;

SendQualifiedArtifact sub RubySourceArtifact
	# Attributes
	has selectorAttribute
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_iterated_relation
	plays is_left_relation
	plays is_object_relation
	plays is_parent_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_comments_relation
	plays has_qnames_relation
	plays has_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays IDENTIFIER
	plays LEFT
	plays QUALIFIED
	plays RIGHT
	plays THEN
	plays TUPLE
	plays UPDATE
	plays VALUE;

SendRequireArtifact sub RubySourceArtifact
	# Attributes
	has selectorAttribute
	# Structural
	plays is_base_relation
	plays is_begin_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_else_relation
	plays is_file_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_comments_relation
	plays has_values_relation
	# Semantic
	plays BINARY
	plays BODY
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays IMPORT
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

SendStatementArtifact sub RubySourceArtifact
	# Structural
	plays is_2_relation
	plays is_base_relation
	plays is_begin_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_base_relation
	plays has_values_relation
	# Semantic
	plays ANONYMOUS
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays CONTINUE
	plays DECLARATION
	plays ELSE
	plays EXPRESSION
	plays FOR
	plays FUNCTION
	plays INSTANCE
	plays ITERATOR
	plays LEFT
	plays RIGHT
	plays STATEMENT
	plays SUBTYPE
	plays THEN
	plays TUPLE
	plays VALUE
	plays VISIBILITY
	plays WORLD;

ShadowargArtifact sub RubySourceArtifact
	# Structural
	plays is_args_relation
	plays has_children_relation
	# Semantic
	plays UNANNOTATED;

SplatArtifact sub RubySourceArtifact
	# Structural
	plays is_children_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_target_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays CALL
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays INCOMPLETE
	plays LEFT
	plays RIGHT;

StrArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_options_relation
	plays is_right_relation
	plays is_target_relation
	plays is_text_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays LITERAL
	plays PRIMITIVE
	plays RIGHT
	plays STRING
	plays THEN
	plays TUPLE
	plays VALUE;

SuperArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_children_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

SymArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_children_relation
	plays is_class_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays IDENTIFIER
	plays LEFT
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

SymbolArtifact sub RubySourceArtifact
	# Structural
	plays is_children_relation
	plays is_options_relation
	# Semantic
	plays EXPRESSION
	plays IDENTIFIER;

TrueArtifact sub RubySourceArtifact
	# Structural
	plays is_1_relation
	plays is_2_relation
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_children_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_conditions_relation
	plays is_contents_relation
	plays is_default_relation
	plays is_else_relation
	plays is_left_relation
	plays is_object_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays BOOLEAN
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays LITERAL
	plays RIGHT
	plays THEN
	plays TUPLE
	plays VALUE;

UndefArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays has_target_relation
	# Semantic
	plays BODY
	plays EXPRESSION
	plays INCOMPLETE
	plays STATEMENT
	plays THEN;

UntilArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays has_body_relation
	plays has_condition_relation
	# Semantic
	plays BODY
	plays STATEMENT
	plays WHILE;

UntilPostArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays has_body_relation
	plays has_condition_relation
	# Semantic
	plays STATEMENT
	plays WHILE;

WhenArtifact sub RubySourceArtifact
	# Structural
	plays is_when_clauses_relation
	plays has_body_relation
	plays has_conditions_relation
	# Semantic
	plays CASE
	plays EXPRESSION;

WhileArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_else_relation
	plays is_ensure_body_relation
	plays is_file_relation
	plays is_value_relation
	plays has_body_relation
	plays has_comments_relation
	plays has_condition_relation
	# Semantic
	plays BINARY
	plays BODY
	plays ELSE
	plays EXPRESSION
	plays RIGHT
	plays STATEMENT
	plays THEN
	plays WHILE;

WhilePostArtifact sub RubySourceArtifact
	# Structural
	plays is_body_relation
	plays has_body_relation
	plays has_condition_relation
	# Semantic
	plays STATEMENT
	plays WHILE;

XstrArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_else_relation
	plays is_right_relation
	plays is_value_relation
	plays is_values_relation
	plays has_children_relation
	# Semantic
	plays ARGUMENT
	plays BINARY
	plays BODY
	plays CALL
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

YieldArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_body_relation
	plays is_casevar_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	plays has_target_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

ZsuperArtifact sub RubySourceArtifact
	# Structural
	plays is_base_relation
	plays is_blockdata_relation
	plays is_body_relation
	plays is_class_relation
	plays is_condition_relation
	plays is_contents_relation
	plays is_else_relation
	plays is_left_relation
	plays is_right_relation
	plays is_target_relation
	plays is_value_relation
	plays is_values_relation
	# Semantic
	plays ARGUMENT
	plays ASSIGNMENT
	plays BINARY
	plays BODY
	plays CALL
	plays CONDITION
	plays ELSE
	plays EXPRESSION
	plays FUNCTION
	plays LEFT
	plays RIGHT
	plays THEN
	plays UNANNOTATED;

##########---------- Structural Relationships ----------##########

#####----- Ruby -----#####
1_relation sub relationship
	relates is_1_relation, relates has_1_relation;
is_1_relation sub role;
has_1_relation sub role;

2_relation sub relationship
	relates is_2_relation, relates has_2_relation;
is_2_relation sub role;
has_2_relation sub role;

alias_relation sub relationship
	relates is_alias_relation, relates has_alias_relation;
is_alias_relation sub role;
has_alias_relation sub role;

args_relation sub relationship
	relates is_args_relation, relates has_args_relation;
is_args_relation sub role;
has_args_relation sub role;

base_relation sub relationship
	relates is_base_relation, relates has_base_relation;
is_base_relation sub role;
has_base_relation sub role;

begin_relation sub relationship
	relates is_begin_relation, relates has_begin_relation;
is_begin_relation sub role;
has_begin_relation sub role;

blockdata_relation sub relationship
	relates is_blockdata_relation, relates has_blockdata_relation;
is_blockdata_relation sub role;
has_blockdata_relation sub role;

body_relation sub relationship
	relates is_body_relation, relates has_body_relation;
is_body_relation sub role;
has_body_relation sub role;

casevar_relation sub relationship
	relates is_casevar_relation, relates has_casevar_relation;
is_casevar_relation sub role;
has_casevar_relation sub role;

children_relation sub relationship
	relates is_children_relation, relates has_children_relation;
is_children_relation sub role;
has_children_relation sub role;

class_relation sub relationship
	relates is_class_relation, relates has_class_relation;
is_class_relation sub role;
has_class_relation sub role;

comments_relation sub relationship
	relates is_comments_relation, relates has_comments_relation;
is_comments_relation sub role;
has_comments_relation sub role;

condition_relation sub relationship
	relates is_condition_relation, relates has_condition_relation;
is_condition_relation sub role;
has_condition_relation sub role;

conditions_relation sub relationship
	relates is_conditions_relation, relates has_conditions_relation;
is_conditions_relation sub role;
has_conditions_relation sub role;

contents_relation sub relationship
	relates is_contents_relation, relates has_contents_relation;
is_contents_relation sub role;
has_contents_relation sub role;

default_relation sub relationship
	relates is_default_relation, relates has_default_relation;
is_default_relation sub role;
has_default_relation sub role;

else_relation sub relationship
	relates is_else_relation, relates has_else_relation;
is_else_relation sub role;
has_else_relation sub role;

end_relation sub relationship
	relates is_end_relation, relates has_end_relation;
is_end_relation sub role;
has_end_relation sub role;

ensure_body_relation sub relationship
	relates is_ensure_body_relation, relates has_ensure_body_relation;
is_ensure_body_relation sub role;
has_ensure_body_relation sub role;

exceptions_relation sub relationship
	relates is_exceptions_relation, relates has_exceptions_relation;
is_exceptions_relation sub role;
has_exceptions_relation sub role;

file_relation sub relationship
	relates is_file_relation, relates has_file_relation;
is_file_relation sub role;
has_file_relation sub role;

handlers_relation sub relationship
	relates is_handlers_relation, relates has_handlers_relation;
is_handlers_relation sub role;
has_handlers_relation sub role;

iterated_relation sub relationship
	relates is_iterated_relation, relates has_iterated_relation;
is_iterated_relation sub role;
has_iterated_relation sub role;

iterators_relation sub relationship
	relates is_iterators_relation, relates has_iterators_relation;
is_iterators_relation sub role;
has_iterators_relation sub role;

left_relation sub relationship
	relates is_left_relation, relates has_left_relation;
is_left_relation sub role;
has_left_relation sub role;

object_relation sub relationship
	relates is_object_relation, relates has_object_relation;
is_object_relation sub role;
has_object_relation sub role;

operator_relation sub relationship
	relates is_operator_relation, relates has_operator_relation;
is_operator_relation sub role;
has_operator_relation sub role;

options_relation sub relationship
	relates is_options_relation, relates has_options_relation;
is_options_relation sub role;
has_options_relation sub role;

parent_relation sub relationship
	relates is_parent_relation, relates has_parent_relation;
is_parent_relation sub role;
has_parent_relation sub role;

qnames_relation sub relationship
	relates is_qnames_relation, relates has_qnames_relation;
is_qnames_relation sub role;
has_qnames_relation sub role;

right_relation sub relationship
	relates is_right_relation, relates has_right_relation;
is_right_relation sub role;
has_right_relation sub role;

start_relation sub relationship
	relates is_start_relation, relates has_start_relation;
is_start_relation sub role;
has_start_relation sub role;

target_relation sub relationship
	relates is_target_relation, relates has_target_relation;
is_target_relation sub role;
has_target_relation sub role;

targets_relation sub relationship
	relates is_targets_relation, relates has_targets_relation;
is_targets_relation sub role;
has_targets_relation sub role;

text_relation sub relationship
	relates is_text_relation, relates has_text_relation;
is_text_relation sub role;
has_text_relation sub role;

value_relation sub relationship
	relates is_value_relation, relates has_value_relation;
is_value_relation sub role;
has_value_relation sub role;

values_relation sub relationship
	relates is_values_relation, relates has_values_relation;
is_values_relation sub role;
has_values_relation sub role;

when_clauses_relation sub relationship
	relates is_when_clauses_relation, relates has_when_clauses_relation;
is_when_clauses_relation sub role;
has_when_clauses_relation sub role;

##########---------- Semantic Roles ----------##########
IS_ADD sub relationship
	relates ADD;
ADD sub role;

IS_ALIAS sub relationship
	relates ALIAS;
ALIAS sub role;

IS_AND sub relationship
	relates AND;
AND sub role;

IS_ANONYMOUS sub relationship
	relates ANONYMOUS;
ANONYMOUS sub role;

IS_ARGUMENT sub relationship
	relates ARGUMENT;
ARGUMENT sub role;

IS_ARITHMETIC sub relationship
	relates ARITHMETIC;
ARITHMETIC sub role;

IS_ASSIGNMENT sub relationship
	relates ASSIGNMENT;
ASSIGNMENT sub role;

IS_BINARY sub relationship
	relates BINARY;
BINARY sub role;

IS_BITWISE sub relationship
	relates BITWISE;
BITWISE sub role;

IS_BLOCK sub relationship
	relates BLOCK;
BLOCK sub role;

IS_BODY sub relationship
	relates BODY;
BODY sub role;

IS_BOOLEAN sub relationship
	relates BOOLEAN;
BOOLEAN sub role;

IS_BREAK sub relationship
	relates BREAK;
BREAK sub role;

IS_CALL sub relationship
	relates CALL;
CALL sub role;

IS_CASE sub relationship
	relates CASE;
CASE sub role;

IS_CATCH sub relationship
	relates CATCH;
CATCH sub role;

IS_COMMENT sub relationship
	relates COMMENT;
COMMENT sub role;

IS_CONDITION sub relationship
	relates CONDITION;
CONDITION sub role;

IS_CONTINUE sub relationship
	relates CONTINUE;
CONTINUE sub role;

IS_DECLARATION sub relationship
	relates DECLARATION;
DECLARATION sub role;

IS_DEFAULT sub relationship
	relates DEFAULT;
DEFAULT sub role;

IS_DIVIDE sub relationship
	relates DIVIDE;
DIVIDE sub role;

IS_ELSE sub relationship
	relates ELSE;
ELSE sub role;

IS_EQUAL sub relationship
	relates EQUAL;
EQUAL sub role;

IS_EXPRESSION sub relationship
	relates EXPRESSION;
EXPRESSION sub role;

IS_FINALLY sub relationship
	relates FINALLY;
FINALLY sub role;

IS_FOR sub relationship
	relates FOR;
FOR sub role;

IS_FUNCTION sub relationship
	relates FUNCTION;
FUNCTION sub role;

IS_GREATER_THAN_OR_EQUAL sub relationship
	relates GREATER_THAN_OR_EQUAL;
GREATER_THAN_OR_EQUAL sub role;

IS_IDENTICAL sub relationship
	relates IDENTICAL;
IDENTICAL sub role;

IS_IDENTIFIER sub relationship
	relates IDENTIFIER;
IDENTIFIER sub role;

IS_IF sub relationship
	relates IF;
IF sub role;

IS_IMPORT sub relationship
	relates IMPORT;
IMPORT sub role;

IS_INCOMPLETE sub relationship
	relates INCOMPLETE;
INCOMPLETE sub role;

IS_INSTANCE sub relationship
	relates INSTANCE;
INSTANCE sub role;

IS_ITERATOR sub relationship
	relates ITERATOR;
ITERATOR sub role;

IS_LEFT sub relationship
	relates LEFT;
LEFT sub role;

IS_LEFT_SHIFT sub relationship
	relates LEFT_SHIFT;
LEFT_SHIFT sub role;

IS_LESS_THAN_OR_EQUAL sub relationship
	relates LESS_THAN_OR_EQUAL;
LESS_THAN_OR_EQUAL sub role;

IS_LIST sub relationship
	relates LIST;
LIST sub role;

IS_LITERAL sub relationship
	relates LITERAL;
LITERAL sub role;

IS_MAP sub relationship
	relates MAP;
MAP sub role;

IS_MODULE sub relationship
	relates MODULE;
MODULE sub role;

IS_MODULO sub relationship
	relates MODULO;
MODULO sub role;

IS_MULTIPLY sub relationship
	relates MULTIPLY;
MULTIPLY sub role;

IS_NAME sub relationship
	relates NAME;
NAME sub role;

IS_NOOP sub relationship
	relates NOOP;
NOOP sub role;

IS_NOT sub relationship
	relates NOT;
NOT sub role;

IS_NULL sub relationship
	relates NULL;
NULL sub role;

IS_NUMBER sub relationship
	relates NUMBER;
NUMBER sub role;

IS_OPERATOR sub relationship
	relates OPERATOR;
OPERATOR sub role;

IS_OR sub relationship
	relates OR;
OR sub role;

IS_PRIMITIVE sub relationship
	relates PRIMITIVE;
PRIMITIVE sub role;

IS_QUALIFIED sub relationship
	relates QUALIFIED;
QUALIFIED sub role;

IS_REGEXP sub relationship
	relates REGEXP;
REGEXP sub role;

IS_RELATIONAL sub relationship
	relates RELATIONAL;
RELATIONAL sub role;

IS_RETURN sub relationship
	relates RETURN;
RETURN sub role;

IS_RIGHT sub relationship
	relates RIGHT;
RIGHT sub role;

IS_RIGHT_SHIFT sub relationship
	relates RIGHT_SHIFT;
RIGHT_SHIFT sub role;

IS_STATEMENT sub relationship
	relates STATEMENT;
STATEMENT sub role;

IS_STRING sub relationship
	relates STRING;
STRING sub role;

IS_SUBSTRACT sub relationship
	relates SUBSTRACT;
SUBSTRACT sub role;

IS_SUBTYPE sub relationship
	relates SUBTYPE;
SUBTYPE sub role;

IS_SWITCH sub relationship
	relates SWITCH;
SWITCH sub role;

IS_THEN sub relationship
	relates THEN;
THEN sub role;

IS_THIS sub relationship
	relates THIS;
THIS sub role;

IS_TRY sub relationship
	relates TRY;
TRY sub role;

IS_TUPLE sub relationship
	relates TUPLE;
TUPLE sub role;

IS_TYPE sub relationship
	relates TYPE;
TYPE sub role;

IS_UNANNOTATED sub relationship
	relates UNANNOTATED;
UNANNOTATED sub role;

IS_UNARY sub relationship
	relates UNARY;
UNARY sub role;

IS_UPDATE sub relationship
	relates UPDATE;
UPDATE sub role;

IS_VALUE sub relationship
	relates VALUE;
VALUE sub role;

IS_VISIBILITY sub relationship
	relates VISIBILITY;
VISIBILITY sub role;

IS_WHILE sub relationship
	relates WHILE;
WHILE sub role;

IS_WORLD sub relationship
	relates WORLD;
WORLD sub role;

IS_XOR sub relationship
	relates XOR;
XOR sub role;
