define

##########---------- Entities ----------##########

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

AliasArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ALIAS
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_STATEMENT
	plays IS_THEN;

AndArtifact sub RubySourceArtifact
	# Semantic
	plays IS_AND
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_BOOLEAN
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_OPERATOR
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

AndAsgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_AND
	plays IS_BITWISE
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_OPERATOR
	plays IS_THEN;

ArgArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_NAME;

ArgsArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_EXPRESSION
	plays IS_INCOMPLETE;

ArrayArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LIST
	plays IS_LITERAL
	plays IS_PRIMITIVE
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

BackRefArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_REGEXP
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

BeginArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BLOCK
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

BlockargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_UNANNOTATED;

BlockArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BLOCK
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

BlockPassArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_CALL
	plays IS_FUNCTION
	plays IS_UNANNOTATED;

BreakArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_BREAK
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_THEN;

CaseArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_SWITCH
	plays IS_THEN;

CasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_IDENTIFIER
	plays IS_ITERATOR
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN;

CbaseArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_INCOMPLETE
	plays IS_QUALIFIED;

ClassArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_DECLARATION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_THEN
	plays IS_TYPE;

CommentArtifact sub RubySourceArtifact
	# Semantic
	plays IS_COMMENT
	plays IS_NOOP;

ComplexArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_PRIMITIVE
	plays IS_RIGHT;

ConstArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

CvarArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_TYPE
	plays IS_VALUE
	plays IS_VISIBILITY;

CvasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_IDENTIFIER
	plays IS_ITERATOR
	plays IS_LEFT
	plays IS_THEN;

DefArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_BODY
	plays IS_CONDITION
	plays IS_DECLARATION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_THEN;

DefinedArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CONDITION
	plays IS_EXPRESSION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_TUPLE
	plays IS_UNANNOTATED
	plays IS_VALUE;

DefsArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_CONDITION
	plays IS_DECLARATION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_INCOMPLETE
	plays IS_STATEMENT
	plays IS_THEN;

DstrArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UNANNOTATED
	plays IS_VALUE;

DsymArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_STRING
	plays IS_TUPLE
	plays IS_VALUE;

EnsureArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_FINALLY;

ErangeArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

FalseArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_BOOLEAN
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

FloatArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_PRIMITIVE
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

ForArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_STATEMENT
	plays IS_THEN;

GvarArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE
	plays IS_VISIBILITY
	plays IS_WORLD;

GvasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UNANNOTATED;

HashArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_MAP
	plays IS_PRIMITIVE
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

IdentifierArtifact sub RubySourceArtifact;

IfArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IF
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

IntArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_PRIMITIVE
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

IrangeArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

IvarArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_INSTANCE
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE
	plays IS_VISIBILITY;

IvasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_ITERATOR
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN;

KwargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_EXPRESSION
	plays IS_MAP
	plays IS_NAME;

KwbeginArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BLOCK
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

KwoptargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_NAME;

KwrestargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_INCOMPLETE;

KwsplatArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_INCOMPLETE;

LvarArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

LvasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_ITERATOR
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UPDATE;

MasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_THEN;

MatchWithLvasgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_BODY
	plays IS_CONDITION
	plays IS_EXPRESSION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UNANNOTATED;

MlhsArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_INCOMPLETE
	plays IS_ITERATOR
	plays IS_LEFT;

ModuleArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_MODULE
	plays IS_STATEMENT
	plays IS_THEN;

NextArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UNANNOTATED;

NilArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UNANNOTATED
	plays IS_VALUE;

NilNodeArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_NULL;

OpAsgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ADD
	plays IS_AND
	plays IS_ARGUMENT
	plays IS_ARITHMETIC
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BITWISE
	plays IS_BODY
	plays IS_CALL
	plays IS_DIVIDE
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_LEFT_SHIFT
	plays IS_MODULO
	plays IS_MULTIPLY
	plays IS_OPERATOR
	plays IS_OR
	plays IS_RIGHT
	plays IS_RIGHT_SHIFT
	plays IS_SUBSTRACT
	plays IS_THEN
	plays IS_XOR;

OperatorArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ADD
	plays IS_AND
	plays IS_ARITHMETIC
	plays IS_BINARY
	plays IS_BITWISE
	plays IS_DIVIDE
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_LEFT_SHIFT
	plays IS_MODULO
	plays IS_MULTIPLY
	plays IS_OPERATOR
	plays IS_OR
	plays IS_RIGHT_SHIFT
	plays IS_SUBSTRACT
	plays IS_XOR;

OptargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_DEFAULT
	plays IS_EXPRESSION
	plays IS_NAME;

OrArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_BOOLEAN
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_OPERATOR
	plays IS_OR
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

OrAsgnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BITWISE
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_OPERATOR
	plays IS_OR
	plays IS_RIGHT
	plays IS_THEN;

PairArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_LITERAL
	plays IS_PRIMITIVE
	plays IS_TUPLE;

PositionArtifact sub RubySourceArtifact;

PostexeArtifact sub RubySourceArtifact
	# Semantic
	plays IS_UNANNOTATED;

PreexeArtifact sub RubySourceArtifact
	# Semantic
	plays IS_UNANNOTATED;

RationalArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_BINARY
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_PRIMITIVE
	plays IS_RIGHT;

RedoArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_THEN
	plays IS_UNANNOTATED;

RegexpArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_REGEXP
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

RegoptArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_REGEXP;

ResbodyArtifact sub RubySourceArtifact
	# Semantic
	plays IS_CATCH
	plays IS_EXPRESSION;

RescueArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TRY;

RestargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_LIST;

RetryArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_STATEMENT
	plays IS_THEN;

ReturnArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_RETURN
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_THEN;

SclassArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_BODY
	plays IS_DECLARATION
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TYPE;

SelfArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_THIS
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

SendArrayArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LIST
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

SendAssignArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN;

SendCallArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

SendIdentifierArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

SendOperatorArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ADD
	plays IS_AND
	plays IS_ARGUMENT
	plays IS_ARITHMETIC
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BITWISE
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_DIVIDE
	plays IS_ELSE
	plays IS_EQUAL
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_GREATER_THAN_OR_EQUAL
	plays IS_IDENTICAL
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_LEFT_SHIFT
	plays IS_LESS_THAN_OR_EQUAL
	plays IS_MODULO
	plays IS_MULTIPLY
	plays IS_NOT
	plays IS_OPERATOR
	plays IS_OR
	plays IS_RELATIONAL
	plays IS_RIGHT
	plays IS_RIGHT_SHIFT
	plays IS_SUBSTRACT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UNARY
	plays IS_VALUE
	plays IS_XOR;

SendQualifiedArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_QUALIFIED
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UPDATE
	plays IS_VALUE;

SendRequireArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_BODY
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_IMPORT
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UNANNOTATED
	plays IS_VALUE;

SendStatementArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ANONYMOUS
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_CONTINUE
	plays IS_DECLARATION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_INSTANCE
	plays IS_ITERATOR
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_SUBTYPE
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE
	plays IS_VISIBILITY
	plays IS_WORLD;

ShadowargArtifact sub RubySourceArtifact
	# Semantic
	plays IS_UNANNOTATED;

SplatArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_INCOMPLETE
	plays IS_LEFT
	plays IS_RIGHT;

StrArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_PRIMITIVE
	plays IS_RIGHT
	plays IS_STRING
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

SuperArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_UNANNOTATED
	plays IS_VALUE;

SymArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

SymbolArtifact sub RubySourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_IDENTIFIER;

TrueArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_BOOLEAN
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_LITERAL
	plays IS_RIGHT
	plays IS_THEN
	plays IS_TUPLE
	plays IS_VALUE;

UndefArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_EXPRESSION
	plays IS_INCOMPLETE
	plays IS_STATEMENT
	plays IS_THEN;

UntilArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_STATEMENT
	plays IS_THEN
	plays IS_WHILE;

UntilPostArtifact sub RubySourceArtifact
	# Semantic
	plays IS_STATEMENT
	plays IS_WHILE;

WhenArtifact sub RubySourceArtifact
	# Semantic
	plays IS_CASE
	plays IS_EXPRESSION;

WhileArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_BODY
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_RIGHT
	plays IS_STATEMENT
	plays IS_THEN
	plays IS_WHILE;

WhilePostArtifact sub RubySourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_STATEMENT
	plays IS_WHILE;

XstrArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UNANNOTATED;

YieldArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UNANNOTATED;

ZsuperArtifact sub RubySourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_BODY
	plays IS_CALL
	plays IS_CONDITION
	plays IS_ELSE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LEFT
	plays IS_RIGHT
	plays IS_THEN
	plays IS_UNANNOTATED;

##########---------- Semantic Roles ----------##########
ADD sub relationship
	relates IS_ADD;
IS_ADD sub role;

ALIAS sub relationship
	relates IS_ALIAS;
IS_ALIAS sub role;

AND sub relationship
	relates IS_AND;
IS_AND sub role;

ANONYMOUS sub relationship
	relates IS_ANONYMOUS;
IS_ANONYMOUS sub role;

ARGUMENT sub relationship
	relates IS_ARGUMENT;
IS_ARGUMENT sub role;

ARITHMETIC sub relationship
	relates IS_ARITHMETIC;
IS_ARITHMETIC sub role;

ASSIGNMENT sub relationship
	relates IS_ASSIGNMENT;
IS_ASSIGNMENT sub role;

BINARY sub relationship
	relates IS_BINARY;
IS_BINARY sub role;

BITWISE sub relationship
	relates IS_BITWISE;
IS_BITWISE sub role;

BLOCK sub relationship
	relates IS_BLOCK;
IS_BLOCK sub role;

BODY sub relationship
	relates IS_BODY;
IS_BODY sub role;

BOOLEAN sub relationship
	relates IS_BOOLEAN;
IS_BOOLEAN sub role;

BREAK sub relationship
	relates IS_BREAK;
IS_BREAK sub role;

CALL sub relationship
	relates IS_CALL;
IS_CALL sub role;

CASE sub relationship
	relates IS_CASE;
IS_CASE sub role;

CATCH sub relationship
	relates IS_CATCH;
IS_CATCH sub role;

COMMENT sub relationship
	relates IS_COMMENT;
IS_COMMENT sub role;

CONDITION sub relationship
	relates IS_CONDITION;
IS_CONDITION sub role;

CONTINUE sub relationship
	relates IS_CONTINUE;
IS_CONTINUE sub role;

DECLARATION sub relationship
	relates IS_DECLARATION;
IS_DECLARATION sub role;

DEFAULT sub relationship
	relates IS_DEFAULT;
IS_DEFAULT sub role;

DIVIDE sub relationship
	relates IS_DIVIDE;
IS_DIVIDE sub role;

ELSE sub relationship
	relates IS_ELSE;
IS_ELSE sub role;

EQUAL sub relationship
	relates IS_EQUAL;
IS_EQUAL sub role;

EXPRESSION sub relationship
	relates IS_EXPRESSION;
IS_EXPRESSION sub role;

FINALLY sub relationship
	relates IS_FINALLY;
IS_FINALLY sub role;

FOR sub relationship
	relates IS_FOR;
IS_FOR sub role;

FUNCTION sub relationship
	relates IS_FUNCTION;
IS_FUNCTION sub role;

GREATER_THAN_OR_EQUAL sub relationship
	relates IS_GREATER_THAN_OR_EQUAL;
IS_GREATER_THAN_OR_EQUAL sub role;

IDENTICAL sub relationship
	relates IS_IDENTICAL;
IS_IDENTICAL sub role;

IDENTIFIER sub relationship
	relates IS_IDENTIFIER;
IS_IDENTIFIER sub role;

IF sub relationship
	relates IS_IF;
IS_IF sub role;

IMPORT sub relationship
	relates IS_IMPORT;
IS_IMPORT sub role;

INCOMPLETE sub relationship
	relates IS_INCOMPLETE;
IS_INCOMPLETE sub role;

INSTANCE sub relationship
	relates IS_INSTANCE;
IS_INSTANCE sub role;

ITERATOR sub relationship
	relates IS_ITERATOR;
IS_ITERATOR sub role;

LEFT sub relationship
	relates IS_LEFT;
IS_LEFT sub role;

LEFT_SHIFT sub relationship
	relates IS_LEFT_SHIFT;
IS_LEFT_SHIFT sub role;

LESS_THAN_OR_EQUAL sub relationship
	relates IS_LESS_THAN_OR_EQUAL;
IS_LESS_THAN_OR_EQUAL sub role;

LIST sub relationship
	relates IS_LIST;
IS_LIST sub role;

LITERAL sub relationship
	relates IS_LITERAL;
IS_LITERAL sub role;

MAP sub relationship
	relates IS_MAP;
IS_MAP sub role;

MODULE sub relationship
	relates IS_MODULE;
IS_MODULE sub role;

MODULO sub relationship
	relates IS_MODULO;
IS_MODULO sub role;

MULTIPLY sub relationship
	relates IS_MULTIPLY;
IS_MULTIPLY sub role;

NAME sub relationship
	relates IS_NAME;
IS_NAME sub role;

NOOP sub relationship
	relates IS_NOOP;
IS_NOOP sub role;

NOT sub relationship
	relates IS_NOT;
IS_NOT sub role;

NULL sub relationship
	relates IS_NULL;
IS_NULL sub role;

NUMBER sub relationship
	relates IS_NUMBER;
IS_NUMBER sub role;

OPERATOR sub relationship
	relates IS_OPERATOR;
IS_OPERATOR sub role;

OR sub relationship
	relates IS_OR;
IS_OR sub role;

PRIMITIVE sub relationship
	relates IS_PRIMITIVE;
IS_PRIMITIVE sub role;

QUALIFIED sub relationship
	relates IS_QUALIFIED;
IS_QUALIFIED sub role;

REGEXP sub relationship
	relates IS_REGEXP;
IS_REGEXP sub role;

RELATIONAL sub relationship
	relates IS_RELATIONAL;
IS_RELATIONAL sub role;

RETURN sub relationship
	relates IS_RETURN;
IS_RETURN sub role;

RIGHT sub relationship
	relates IS_RIGHT;
IS_RIGHT sub role;

RIGHT_SHIFT sub relationship
	relates IS_RIGHT_SHIFT;
IS_RIGHT_SHIFT sub role;

STATEMENT sub relationship
	relates IS_STATEMENT;
IS_STATEMENT sub role;

STRING sub relationship
	relates IS_STRING;
IS_STRING sub role;

SUBSTRACT sub relationship
	relates IS_SUBSTRACT;
IS_SUBSTRACT sub role;

SUBTYPE sub relationship
	relates IS_SUBTYPE;
IS_SUBTYPE sub role;

SWITCH sub relationship
	relates IS_SWITCH;
IS_SWITCH sub role;

THEN sub relationship
	relates IS_THEN;
IS_THEN sub role;

THIS sub relationship
	relates IS_THIS;
IS_THIS sub role;

TRY sub relationship
	relates IS_TRY;
IS_TRY sub role;

TUPLE sub relationship
	relates IS_TUPLE;
IS_TUPLE sub role;

TYPE sub relationship
	relates IS_TYPE;
IS_TYPE sub role;

UNANNOTATED sub relationship
	relates IS_UNANNOTATED;
IS_UNANNOTATED sub role;

UNARY sub relationship
	relates IS_UNARY;
IS_UNARY sub role;

UPDATE sub relationship
	relates IS_UPDATE;
IS_UPDATE sub role;

VALUE sub relationship
	relates IS_VALUE;
IS_VALUE sub role;

VISIBILITY sub relationship
	relates IS_VISIBILITY;
IS_VISIBILITY sub role;

WHILE sub relationship
	relates IS_WHILE;
IS_WHILE sub role;

WORLD sub relationship
	relates IS_WORLD;
IS_WORLD sub role;

XOR sub relationship
	relates IS_XOR;
IS_XOR sub role;
