define

##########---------- Entities ----------##########

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

ArrayTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALLEE,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_KEY,
	plays IS_LIST,
	plays IS_POSITIONAL,
	plays IS_TYPE;

AssignStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_DECLARATION,
	plays IS_DIVIDE,
	plays IS_FOR,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_LEFT_SHIFT,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NEGATIVE,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_RIGHT_SHIFT,
	plays IS_STATEMENT,
	plays IS_SUBSTRACT,
	plays IS_SWITCH,
	plays IS_UPDATE,
	plays IS_XOR;

BasicLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_CHARACTER,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_IF,
	plays IS_IMPORT,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_NUMBER,
	plays IS_PATHNAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_STRING,
	plays IS_VALUE;

BinaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BOOLEAN,
	plays IS_CONDITION,
	plays IS_DIVIDE,
	plays IS_EQUAL,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_GREATER_THAN,
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LEFT_SHIFT,
	plays IS_LESS_THAN,
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NEGATIVE,
	plays IS_NOT,
	plays IS_OR,
	plays IS_POSITIONAL,
	plays IS_RELATIONAL,
	plays IS_RIGHT,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_VALUE,
	plays IS_XOR;

BlockStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_SCOPE,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_THEN;

BranchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_BREAK,
	plays IS_CONTINUE,
	plays IS_GOTO,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT;

CallExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_VALUE;

CaseClauseArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_CASE,
	plays IS_STATEMENT;

ChanTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALLEE,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_POSITIONAL,
	plays IS_TYPE;

CommClauseArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_CASE,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT;

CommentArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_COMMENT;

CommentGroupArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_LIST;

CompositeLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_EXPRESSION,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_VALUE;

DeclStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_STATEMENT;

DeferStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_STATEMENT;

EllipsisArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_TYPE;

EmptyStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

ExprStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR,
	plays IS_IF,
	plays IS_INITIALIZATION,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_UPDATE;

FieldArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ENTRY,
	plays IS_FUNCTION,
	plays IS_RECEIVER,
	plays IS_RETURN,
	plays IS_UNANNOTATED;

FieldListArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_LIST,
	plays IS_RECEIVER,
	plays IS_RETURN;

FileArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FILE;

ForStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR,
	plays IS_STATEMENT;

FuncDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_UNANNOTATED;

FuncLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_EXPRESSION,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_VALUE;

FuncTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALLEE,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_KEY,
	plays IS_POSITIONAL,
	plays IS_TYPE;

GenDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE,
	plays IS_VARIABLE;

GoStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_STATEMENT;

IdentArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ALIAS,
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_IMPORT,
	plays IS_ITERATOR,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_TYPE,
	plays IS_VALUE,
	plays IS_VARIABLE;

IfStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ELSE,
	plays IS_IF,
	plays IS_STATEMENT;

ImportSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_IMPORT;

IncDecStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECREMENT,
	plays IS_FOR,
	plays IS_IF,
	plays IS_INCREMENT,
	plays IS_INITIALIZATION,
	plays IS_STATEMENT,
	plays IS_SWITCH,
	plays IS_UNARY,
	plays IS_UPDATE;

IndexExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_IF,
	plays IS_ITERATOR,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_VALUE;

InterfaceTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALLEE,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_POSITIONAL,
	plays IS_TYPE;

KeyValueExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_EXPRESSION;

LabeledStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_STATEMENT;

MapTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALLEE,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_KEY,
	plays IS_MAP,
	plays IS_POSITIONAL,
	plays IS_TYPE;

OperatorArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_AND,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BOOLEAN,
	plays IS_DECLARATION,
	plays IS_DECREMENT,
	plays IS_DIVIDE,
	plays IS_EQUAL,
	plays IS_EXPRESSION,
	plays IS_GREATER_THAN,
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_INCOMPLETE,
	plays IS_INCREMENT,
	plays IS_LEFT_SHIFT,
	plays IS_LESS_THAN,
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_MODULO,
	plays IS_MULTIPLY,
	plays IS_NEGATIVE,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_OR,
	plays IS_POSITIVE,
	plays IS_RELATIONAL,
	plays IS_RIGHT_SHIFT,
	plays IS_SUBSTRACT,
	plays IS_TAKE_ADDRESS,
	plays IS_UNARY,
	plays IS_XOR;

ParenExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_TYPE,
	plays IS_VALUE;

PositionArtifact sub GoSourceArtifact;

RangeStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR,
	plays IS_ITERATOR,
	plays IS_STATEMENT;

ReturnStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_RETURN,
	plays IS_STATEMENT;

SelectorExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_ITERATOR,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_TYPE,
	plays IS_VALUE;

SelectStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_SWITCH;

SendStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR,
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_UPDATE;

SliceExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_EXPRESSION,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_VALUE;

StarExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CONDITION,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_ITERATOR,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RECEIVER,
	plays IS_RIGHT,
	plays IS_TYPE,
	plays IS_VALUE;

StructTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALLEE,
	plays IS_ENTRY,
	plays IS_EXPRESSION,
	plays IS_KEY,
	plays IS_POSITIONAL,
	plays IS_TYPE;

SwitchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_STATEMENT,
	plays IS_SWITCH;

TypeAssertExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_VALUE;

TypeSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION;

TypeSwitchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_SWITCH;

UnaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_ARITHMETIC,
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_BOOLEAN,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_NEGATIVE,
	plays IS_POSITIONAL,
	plays IS_POSITIVE,
	plays IS_RIGHT,
	plays IS_TAKE_ADDRESS,
	plays IS_UNARY,
	plays IS_VALUE;

ValueSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

ALIAS sub relation,
	relates IS_ALIAS;

AND sub relation,
	relates IS_AND;

ARGS_LIST sub relation,
	relates IS_ARGS_LIST;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

CALL sub relation,
	relates IS_CALL;

CALLEE sub relation,
	relates IS_CALLEE;

CASE sub relation,
	relates IS_CASE;

CHARACTER sub relation,
	relates IS_CHARACTER;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

CONTINUE sub relation,
	relates IS_CONTINUE;

DECLARATION sub relation,
	relates IS_DECLARATION;

DECREMENT sub relation,
	relates IS_DECREMENT;

DIVIDE sub relation,
	relates IS_DIVIDE;

ELSE sub relation,
	relates IS_ELSE;

ENTRY sub relation,
	relates IS_ENTRY;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FILE sub relation,
	relates IS_FILE;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GOTO sub relation,
	relates IS_GOTO;

GREATER_THAN sub relation,
	relates IS_GREATER_THAN;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

INCREMENT sub relation,
	relates IS_INCREMENT;

INITIALIZATION sub relation,
	relates IS_INITIALIZATION;

ITERATOR sub relation,
	relates IS_ITERATOR;

KEY sub relation,
	relates IS_KEY;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN sub relation,
	relates IS_LESS_THAN;

LESS_THAN_OR_EQUAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MAP sub relation,
	relates IS_MAP;

MODULO sub relation,
	relates IS_MODULO;

MULTIPLY sub relation,
	relates IS_MULTIPLY;

NAME sub relation,
	relates IS_NAME;

NEGATIVE sub relation,
	relates IS_NEGATIVE;

NOT sub relation,
	relates IS_NOT;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PATHNAME sub relation,
	relates IS_PATHNAME;

POSITIONAL sub relation,
	relates IS_POSITIONAL;

POSITIVE sub relation,
	relates IS_POSITIVE;

PRIMITIVE sub relation,
	relates IS_PRIMITIVE;

RECEIVER sub relation,
	relates IS_RECEIVER;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

RIGHT_SHIFT sub relation,
	relates IS_RIGHT_SHIFT;

SCOPE sub relation,
	relates IS_SCOPE;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

SWITCH sub relation,
	relates IS_SWITCH;

TAKE_ADDRESS sub relation,
	relates IS_TAKE_ADDRESS;

THEN sub relation,
	relates IS_THEN;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UPDATE sub relation,
	relates IS_UPDATE;

VALUE sub relation,
	relates IS_VALUE;

VARIABLE sub relation,
	relates IS_VARIABLE;

XOR sub relation,
	relates IS_XOR;
