define

##########---------- Attributes ----------##########
booleanValue sub attribute, datatype boolean;
doubleValue sub attribute, datatype double;
name sub attribute, datatype string;
numberValue sub attribute, datatype long;
token sub attribute, datatype string;

#####----- Go -----#####
colAttribute sub attribute, datatype string;
dirAttribute sub attribute, datatype string;
implicitAttribute sub attribute, datatype string;
incompleteAttribute sub attribute, datatype string;
kindAttribute sub attribute, datatype string;
lineAttribute sub attribute, datatype string;
offsetAttribute sub attribute, datatype string;
slice3Attribute sub attribute, datatype string;
tokAttribute sub attribute, datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	has token,
	plays is_child,
	plays is_parent;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

ArrayTypeArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_elt_role,
	plays is_fun_role,
	plays is_key_role,
	plays is_list_role,
	plays is_type_role,
	plays is_value_role,
	plays is_x_role,
	plays has_elt_role,
	plays has_lbrack_role,
	plays has_len_role;

AssignStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_assign_role,
	plays is_body_role,
	plays is_comm_role,
	plays is_init_role,
	plays is_list_role,
	plays is_post_role,
	plays is_stmt_role,
	plays has_lhs_role,
	plays has_op_role,
	plays has_rhs_role,
	plays has_tok_pos_role;

BasicLitArtifact sub GoSourceArtifact,
	# Attributes
	has doubleValue,
	has kindAttribute,
	has numberValue,
	has stringValue,
	# Structural
	plays is_args_role,
	plays is_cond_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_len_role,
	plays is_lhs_role,
	plays is_list_role,
	plays is_low_role,
	plays is_max_role,
	plays is_path_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_value_pos_role;

BinaryExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_cond_role,
	plays is_elts_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_len_role,
	plays is_list_role,
	plays is_low_role,
	plays is_max_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_op_pos_role,
	plays has_op_role,
	plays has_x_role,
	plays has_y_role;

BlockStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_lbrace_role,
	plays has_list_role,
	plays has_rbrace_role;

BranchStmtArtifact sub GoSourceArtifact,
	# Attributes
	has tokAttribute,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_label_role,
	plays has_tok_pos_role;

CallExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_call_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_len_role,
	plays is_list_role,
	plays is_low_role,
	plays is_max_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_args_role,
	plays has_ellipsis_role,
	plays has_fun_role,
	plays has_lparen_role,
	plays has_rparen_role;

CaseClauseArtifact sub GoSourceArtifact,
	# Structural
	plays is_list_role,
	plays has_body_role,
	plays has_case_role,
	plays has_colon_role,
	plays has_list_role;

ChanTypeArtifact sub GoSourceArtifact,
	# Attributes
	has dirAttribute,
	# Structural
	plays is_args_role,
	plays is_elt_role,
	plays is_fun_role,
	plays is_key_role,
	plays is_list_role,
	plays is_type_role,
	plays is_value_role,
	plays is_x_role,
	plays has_arrow_role,
	plays has_begin_role,
	plays has_value_role;

CommClauseArtifact sub GoSourceArtifact,
	# Structural
	plays is_list_role,
	plays has_body_role,
	plays has_case_role,
	plays has_colon_role,
	plays has_comm_role;

CommentArtifact sub GoSourceArtifact,
	# Structural
	plays is_list_role,
	plays has_slash_role;

CommentGroupArtifact sub GoSourceArtifact,
	# Structural
	plays is_comment_role,
	plays is_comments_role,
	plays is_doc_role,
	plays has_list_role;

CompositeLitArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_elts_role,
	plays is_index_role,
	plays is_key_role,
	plays is_list_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_elts_role,
	plays has_lbrace_role,
	plays has_rbrace_role,
	plays has_type_role;

DeclStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_decl_role;

DeferStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays has_call_role,
	plays has_defer_role;

EllipsisArtifact sub GoSourceArtifact,
	# Structural
	plays is_len_role,
	plays is_type_role,
	plays has_ellipsis_role,
	plays has_elt_role;

EmptyStmtArtifact sub GoSourceArtifact,
	# Attributes
	has implicitAttribute,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_semicolon_role;

ExprStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_assign_role,
	plays is_body_role,
	plays is_comm_role,
	plays is_init_role,
	plays is_list_role,
	plays is_post_role,
	plays is_stmt_role,
	plays has_x_role;

FieldArtifact sub GoSourceArtifact,
	# Structural
	plays is_list_role,
	plays has_comment_role,
	plays has_doc_role,
	plays has_names_role,
	plays has_tag_role,
	plays has_type_role;

FieldListArtifact sub GoSourceArtifact,
	# Structural
	plays is_fields_role,
	plays is_methods_role,
	plays is_params_role,
	plays is_recv_role,
	plays is_results_role,
	plays has_closing_role,
	plays has_list_role,
	plays has_opening_role;

FileArtifact sub GoSourceArtifact,
	# Structural
	plays has_comments_role,
	plays has_decls_role,
	plays has_doc_role,
	plays has_imports_role,
	plays has_name_role,
	plays has_package_role;

ForStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_body_role,
	plays has_cond_role,
	plays has_for_role,
	plays has_init_role,
	plays has_post_role;

FuncDeclArtifact sub GoSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_decls_role,
	plays has_body_role,
	plays has_doc_role,
	plays has_name_role,
	plays has_recv_role,
	plays has_type_role;

FuncLitArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays has_body_role,
	plays has_type_role;

FuncTypeArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_elt_role,
	plays is_fun_role,
	plays is_key_role,
	plays is_list_role,
	plays is_type_role,
	plays is_value_role,
	plays is_x_role,
	plays has_func_role,
	plays has_params_role,
	plays has_results_role;

GenDeclArtifact sub GoSourceArtifact,
	# Attributes
	has tokAttribute,
	has name,
	# Structural
	plays is_decl_role,
	plays is_decls_role,
	plays has_doc_role,
	plays has_lparen_role,
	plays has_rparen_role,
	plays has_specs_role,
	plays has_tok_pos_role;

GoStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_call_role,
	plays has_go_role;

IdentArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elt_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_label_role,
	plays is_len_role,
	plays is_lhs_role,
	plays is_list_role,
	plays is_low_role,
	plays is_max_role,
	plays is_name_role,
	plays is_names_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_sel_role,
	plays is_tag_role,
	plays is_type_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_name_pos_role;

IfStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_else_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_body_role,
	plays has_cond_role,
	plays has_else_role,
	plays has_if_role,
	plays has_init_role;

ImportSpecArtifact sub GoSourceArtifact,
	# Structural
	plays is_imports_role,
	plays is_specs_role,
	plays has_comment_role,
	plays has_doc_role,
	plays has_end_pos_role,
	plays has_name_role,
	plays has_path_role;

IncDecStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_init_role,
	plays is_list_role,
	plays is_post_role,
	plays is_stmt_role,
	plays has_op_role,
	plays has_tok_pos_role,
	plays has_x_role;

IndexExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_lhs_role,
	plays is_list_role,
	plays is_low_role,
	plays is_max_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_index_role,
	plays has_lbrack_role,
	plays has_rbrack_role,
	plays has_x_role;

InterfaceTypeArtifact sub GoSourceArtifact,
	# Attributes
	has incompleteAttribute,
	# Structural
	plays is_args_role,
	plays is_elt_role,
	plays is_fun_role,
	plays is_key_role,
	plays is_list_role,
	plays is_type_role,
	plays is_value_role,
	plays is_x_role,
	plays has_interface_role,
	plays has_methods_role;

KeyValueExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_elts_role,
	plays has_colon_role,
	plays has_key_role,
	plays has_value_role;

LabeledStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_colon_role,
	plays has_label_role,
	plays has_stmt_role;

MapTypeArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_elt_role,
	plays is_fun_role,
	plays is_key_role,
	plays is_list_role,
	plays is_type_role,
	plays is_value_role,
	plays is_x_role,
	plays has_key_role,
	plays has_map_role,
	plays has_value_role;

OperatorArtifact sub GoSourceArtifact,
	# Structural
	plays is_op_role;

ParenExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elt_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_len_role,
	plays is_lhs_role,
	plays is_list_role,
	plays is_low_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_type_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_lparen_role,
	plays has_rparen_role,
	plays has_x_role;

PositionArtifact sub GoSourceArtifact,
	# Attributes
	has colAttribute,
	has lineAttribute,
	has offsetAttribute,
	# Structural
	plays is_arrow_role,
	plays is_assign_role,
	plays is_begin_role,
	plays is_case_role,
	plays is_closing_role,
	plays is_colon_role,
	plays is_defer_role,
	plays is_ellipsis_role,
	plays is_end_pos_role,
	plays is_for_role,
	plays is_func_role,
	plays is_go_role,
	plays is_if_role,
	plays is_interface_role,
	plays is_lbrace_role,
	plays is_lbrack_role,
	plays is_lparen_role,
	plays is_map_role,
	plays is_name_pos_role,
	plays is_op_pos_role,
	plays is_opening_role,
	plays is_package_role,
	plays is_rbrace_role,
	plays is_rbrack_role,
	plays is_return_role,
	plays is_rparen_role,
	plays is_select_role,
	plays is_semicolon_role,
	plays is_slash_role,
	plays is_star_role,
	plays is_struct_role,
	plays is_switch_role,
	plays is_tok_pos_role,
	plays is_value_pos_role;

RangeStmtArtifact sub GoSourceArtifact,
	# Attributes
	has tokAttribute,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_body_role,
	plays has_for_role,
	plays has_key_role,
	plays has_tok_pos_role,
	plays has_value_role,
	plays has_x_role;

ReturnStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_results_role,
	plays has_return_role;

SelectorExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elt_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_len_role,
	plays is_lhs_role,
	plays is_list_role,
	plays is_low_role,
	plays is_max_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_type_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_sel_role,
	plays has_x_role;

SelectStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_body_role,
	plays has_select_role;

SendStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_comm_role,
	plays is_list_role,
	plays is_post_role,
	plays is_stmt_role,
	plays has_arrow_role,
	plays has_chan_role,
	plays has_value_role;

SliceExprArtifact sub GoSourceArtifact,
	# Attributes
	has slice3Attribute,
	# Structural
	plays is_args_role,
	plays is_elts_role,
	plays is_index_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_high_role,
	plays has_lbrack_role,
	plays has_low_role,
	plays has_max_role,
	plays has_rbrack_role,
	plays has_x_role;

StarExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elt_role,
	plays is_elts_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_lhs_role,
	plays is_list_role,
	plays is_low_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_type_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_star_role,
	plays has_x_role;

StructTypeArtifact sub GoSourceArtifact,
	# Attributes
	has incompleteAttribute,
	# Structural
	plays is_args_role,
	plays is_elt_role,
	plays is_fun_role,
	plays is_key_role,
	plays is_list_role,
	plays is_type_role,
	plays is_value_role,
	plays is_x_role,
	plays has_fields_role,
	plays has_struct_role;

SwitchStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_body_role,
	plays has_init_role,
	plays has_switch_role,
	plays has_tag_role;

TypeAssertExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elts_role,
	plays is_fun_role,
	plays is_high_role,
	plays is_index_role,
	plays is_list_role,
	plays is_low_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_lparen_role,
	plays has_rparen_role,
	plays has_type_role,
	plays has_x_role;

TypeSpecArtifact sub GoSourceArtifact,
	# Structural
	plays is_specs_role,
	plays has_assign_role,
	plays has_comment_role,
	plays has_doc_role,
	plays has_name_role,
	plays has_type_role;

TypeSwitchStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_list_role,
	plays is_stmt_role,
	plays has_assign_role,
	plays has_body_role,
	plays has_init_role,
	plays has_switch_role;

UnaryExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_args_role,
	plays is_chan_role,
	plays is_cond_role,
	plays is_elts_role,
	plays is_high_role,
	plays is_index_role,
	plays is_key_role,
	plays is_list_role,
	plays is_low_role,
	plays is_results_role,
	plays is_rhs_role,
	plays is_tag_role,
	plays is_value_role,
	plays is_values_role,
	plays is_x_role,
	plays is_y_role,
	plays has_op_pos_role,
	plays has_op_role,
	plays has_x_role;

ValueSpecArtifact sub GoSourceArtifact,
	# Structural
	plays is_specs_role,
	plays has_comment_role,
	plays has_doc_role,
	plays has_names_role,
	plays has_type_role,
	plays has_values_role;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Go -----#####
args_relation sub parent_child_relation,
	relates is_args_role as is_child, relates has_args_role as is_parent;

arrow_relation sub parent_child_relation,
	relates is_arrow_role as is_child, relates has_arrow_role as is_parent;

assign_relation sub parent_child_relation,
	relates is_assign_role as is_child, relates has_assign_role as is_parent;

begin_relation sub parent_child_relation,
	relates is_begin_role as is_child, relates has_begin_role as is_parent;

body_relation sub parent_child_relation,
	relates is_body_role as is_child, relates has_body_role as is_parent;

call_relation sub parent_child_relation,
	relates is_call_role as is_child, relates has_call_role as is_parent;

case_relation sub parent_child_relation,
	relates is_case_role as is_child, relates has_case_role as is_parent;

chan_relation sub parent_child_relation,
	relates is_chan_role as is_child, relates has_chan_role as is_parent;

closing_relation sub parent_child_relation,
	relates is_closing_role as is_child, relates has_closing_role as is_parent;

colon_relation sub parent_child_relation,
	relates is_colon_role as is_child, relates has_colon_role as is_parent;

comm_relation sub parent_child_relation,
	relates is_comm_role as is_child, relates has_comm_role as is_parent;

comment_relation sub parent_child_relation,
	relates is_comment_role as is_child, relates has_comment_role as is_parent;

comments_relation sub parent_child_relation,
	relates is_comments_role as is_child, relates has_comments_role as is_parent;

cond_relation sub parent_child_relation,
	relates is_cond_role as is_child, relates has_cond_role as is_parent;

decl_relation sub parent_child_relation,
	relates is_decl_role as is_child, relates has_decl_role as is_parent;

decls_relation sub parent_child_relation,
	relates is_decls_role as is_child, relates has_decls_role as is_parent;

defer_relation sub parent_child_relation,
	relates is_defer_role as is_child, relates has_defer_role as is_parent;

doc_relation sub parent_child_relation,
	relates is_doc_role as is_child, relates has_doc_role as is_parent;

ellipsis_relation sub parent_child_relation,
	relates is_ellipsis_role as is_child, relates has_ellipsis_role as is_parent;

else_relation sub parent_child_relation,
	relates is_else_role as is_child, relates has_else_role as is_parent;

elt_relation sub parent_child_relation,
	relates is_elt_role as is_child, relates has_elt_role as is_parent;

elts_relation sub parent_child_relation,
	relates is_elts_role as is_child, relates has_elts_role as is_parent;

end_pos_relation sub parent_child_relation,
	relates is_end_pos_role as is_child, relates has_end_pos_role as is_parent;

fields_relation sub parent_child_relation,
	relates is_fields_role as is_child, relates has_fields_role as is_parent;

for_relation sub parent_child_relation,
	relates is_for_role as is_child, relates has_for_role as is_parent;

fun_relation sub parent_child_relation,
	relates is_fun_role as is_child, relates has_fun_role as is_parent;

func_relation sub parent_child_relation,
	relates is_func_role as is_child, relates has_func_role as is_parent;

go_relation sub parent_child_relation,
	relates is_go_role as is_child, relates has_go_role as is_parent;

high_relation sub parent_child_relation,
	relates is_high_role as is_child, relates has_high_role as is_parent;

if_relation sub parent_child_relation,
	relates is_if_role as is_child, relates has_if_role as is_parent;

imports_relation sub parent_child_relation,
	relates is_imports_role as is_child, relates has_imports_role as is_parent;

index_relation sub parent_child_relation,
	relates is_index_role as is_child, relates has_index_role as is_parent;

init_relation sub parent_child_relation,
	relates is_init_role as is_child, relates has_init_role as is_parent;

interface_relation sub parent_child_relation,
	relates is_interface_role as is_child, relates has_interface_role as is_parent;

key_relation sub parent_child_relation,
	relates is_key_role as is_child, relates has_key_role as is_parent;

label_relation sub parent_child_relation,
	relates is_label_role as is_child, relates has_label_role as is_parent;

lbrace_relation sub parent_child_relation,
	relates is_lbrace_role as is_child, relates has_lbrace_role as is_parent;

lbrack_relation sub parent_child_relation,
	relates is_lbrack_role as is_child, relates has_lbrack_role as is_parent;

len_relation sub parent_child_relation,
	relates is_len_role as is_child, relates has_len_role as is_parent;

lhs_relation sub parent_child_relation,
	relates is_lhs_role as is_child, relates has_lhs_role as is_parent;

list_relation sub parent_child_relation,
	relates is_list_role as is_child, relates has_list_role as is_parent;

low_relation sub parent_child_relation,
	relates is_low_role as is_child, relates has_low_role as is_parent;

lparen_relation sub parent_child_relation,
	relates is_lparen_role as is_child, relates has_lparen_role as is_parent;

map_relation sub parent_child_relation,
	relates is_map_role as is_child, relates has_map_role as is_parent;

max_relation sub parent_child_relation,
	relates is_max_role as is_child, relates has_max_role as is_parent;

methods_relation sub parent_child_relation,
	relates is_methods_role as is_child, relates has_methods_role as is_parent;

name_pos_relation sub parent_child_relation,
	relates is_name_pos_role as is_child, relates has_name_pos_role as is_parent;

name_relation sub parent_child_relation,
	relates is_name_role as is_child, relates has_name_role as is_parent;

names_relation sub parent_child_relation,
	relates is_names_role as is_child, relates has_names_role as is_parent;

op_pos_relation sub parent_child_relation,
	relates is_op_pos_role as is_child, relates has_op_pos_role as is_parent;

op_relation sub parent_child_relation,
	relates is_op_role as is_child, relates has_op_role as is_parent;

opening_relation sub parent_child_relation,
	relates is_opening_role as is_child, relates has_opening_role as is_parent;

package_relation sub parent_child_relation,
	relates is_package_role as is_child, relates has_package_role as is_parent;

params_relation sub parent_child_relation,
	relates is_params_role as is_child, relates has_params_role as is_parent;

path_relation sub parent_child_relation,
	relates is_path_role as is_child, relates has_path_role as is_parent;

post_relation sub parent_child_relation,
	relates is_post_role as is_child, relates has_post_role as is_parent;

rbrace_relation sub parent_child_relation,
	relates is_rbrace_role as is_child, relates has_rbrace_role as is_parent;

rbrack_relation sub parent_child_relation,
	relates is_rbrack_role as is_child, relates has_rbrack_role as is_parent;

recv_relation sub parent_child_relation,
	relates is_recv_role as is_child, relates has_recv_role as is_parent;

results_relation sub parent_child_relation,
	relates is_results_role as is_child, relates has_results_role as is_parent;

return_relation sub parent_child_relation,
	relates is_return_role as is_child, relates has_return_role as is_parent;

rhs_relation sub parent_child_relation,
	relates is_rhs_role as is_child, relates has_rhs_role as is_parent;

rparen_relation sub parent_child_relation,
	relates is_rparen_role as is_child, relates has_rparen_role as is_parent;

sel_relation sub parent_child_relation,
	relates is_sel_role as is_child, relates has_sel_role as is_parent;

select_relation sub parent_child_relation,
	relates is_select_role as is_child, relates has_select_role as is_parent;

semicolon_relation sub parent_child_relation,
	relates is_semicolon_role as is_child, relates has_semicolon_role as is_parent;

slash_relation sub parent_child_relation,
	relates is_slash_role as is_child, relates has_slash_role as is_parent;

specs_relation sub parent_child_relation,
	relates is_specs_role as is_child, relates has_specs_role as is_parent;

star_relation sub parent_child_relation,
	relates is_star_role as is_child, relates has_star_role as is_parent;

stmt_relation sub parent_child_relation,
	relates is_stmt_role as is_child, relates has_stmt_role as is_parent;

struct_relation sub parent_child_relation,
	relates is_struct_role as is_child, relates has_struct_role as is_parent;

switch_relation sub parent_child_relation,
	relates is_switch_role as is_child, relates has_switch_role as is_parent;

tag_relation sub parent_child_relation,
	relates is_tag_role as is_child, relates has_tag_role as is_parent;

tok_pos_relation sub parent_child_relation,
	relates is_tok_pos_role as is_child, relates has_tok_pos_role as is_parent;

type_relation sub parent_child_relation,
	relates is_type_role as is_child, relates has_type_role as is_parent;

value_pos_relation sub parent_child_relation,
	relates is_value_pos_role as is_child, relates has_value_pos_role as is_parent;

value_relation sub parent_child_relation,
	relates is_value_role as is_child, relates has_value_role as is_parent;

values_relation sub parent_child_relation,
	relates is_values_role as is_child, relates has_values_role as is_parent;

x_relation sub parent_child_relation,
	relates is_x_role as is_child, relates has_x_role as is_parent;

y_relation sub parent_child_relation,
	relates is_y_role as is_child, relates has_y_role as is_parent;
