define

##########---------- Attributes ----------##########
booleanValue sub attribute, value boolean;
doubleValue sub attribute, value double;
name sub attribute, value string;
numberValue sub attribute, value long;
stringValue sub attribute, value string;
token sub attribute, value string;

#####----- Go -----#####
colAttribute sub attribute, value string;
dirAttribute sub attribute, value string;
implicitAttribute sub attribute, value string;
incompleteAttribute sub attribute, value string;
kindAttribute sub attribute, value string;
lineAttribute sub attribute, value string;
offsetAttribute sub attribute, value string;
slice3Attribute sub attribute, value string;
tokAttribute sub attribute, value string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	owns token,
	plays parent_child_relation:is_child,
	plays parent_child_relation:is_parent;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

ArrayTypeArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays elt_relation:is_elt_role,
	plays fun_relation:is_fun_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays x_relation:is_x_role,
	plays elt_relation:has_elt_role,
	plays lbrack_relation:has_lbrack_role,
	plays len_relation:has_len_role;

AssignStmtArtifact sub GoSourceArtifact,
	# Attributes
	owns name,
	# Structural
	plays assign_relation:is_assign_role,
	plays body_relation:is_body_role,
	plays comm_relation:is_comm_role,
	plays init_relation:is_init_role,
	plays list_relation:is_list_role,
	plays post_relation:is_post_role,
	plays stmt_relation:is_stmt_role,
	plays lhs_relation:has_lhs_role,
	plays op_relation:has_op_role,
	plays rhs_relation:has_rhs_role,
	plays tok_pos_relation:has_tok_pos_role;

BasicLitArtifact sub GoSourceArtifact,
	# Attributes
	owns doubleValue,
	owns kindAttribute,
	owns numberValue,
	owns stringValue,
	# Structural
	plays args_relation:is_args_role,
	plays cond_relation:is_cond_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays len_relation:is_len_role,
	plays lhs_relation:is_lhs_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays max_relation:is_max_role,
	plays path_relation:is_path_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays value_pos_relation:has_value_pos_role;

BinaryExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays cond_relation:is_cond_role,
	plays elts_relation:is_elts_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays len_relation:is_len_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays max_relation:is_max_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays op_pos_relation:has_op_pos_role,
	plays op_relation:has_op_role,
	plays x_relation:has_x_role,
	plays y_relation:has_y_role;

BlockStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays lbrace_relation:has_lbrace_role,
	plays list_relation:has_list_role,
	plays rbrace_relation:has_rbrace_role;

BranchStmtArtifact sub GoSourceArtifact,
	# Attributes
	owns tokAttribute,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays label_relation:has_label_role,
	plays tok_pos_relation:has_tok_pos_role;

CallExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays call_relation:is_call_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays len_relation:is_len_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays max_relation:is_max_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays args_relation:has_args_role,
	plays ellipsis_relation:has_ellipsis_role,
	plays fun_relation:has_fun_role,
	plays lparen_relation:has_lparen_role,
	plays rparen_relation:has_rparen_role;

CaseClauseArtifact sub GoSourceArtifact,
	# Structural
	plays list_relation:is_list_role,
	plays body_relation:has_body_role,
	plays case_relation:has_case_role,
	plays colon_relation:has_colon_role,
	plays list_relation:has_list_role;

ChanTypeArtifact sub GoSourceArtifact,
	# Attributes
	owns dirAttribute,
	# Structural
	plays args_relation:is_args_role,
	plays elt_relation:is_elt_role,
	plays fun_relation:is_fun_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays x_relation:is_x_role,
	plays arrow_relation:has_arrow_role,
	plays begin_relation:has_begin_role,
	plays value_relation:has_value_role;

CommClauseArtifact sub GoSourceArtifact,
	# Structural
	plays list_relation:is_list_role,
	plays body_relation:has_body_role,
	plays case_relation:has_case_role,
	plays colon_relation:has_colon_role,
	plays comm_relation:has_comm_role;

CommentArtifact sub GoSourceArtifact,
	# Structural
	plays list_relation:is_list_role,
	plays slash_relation:has_slash_role;

CommentGroupArtifact sub GoSourceArtifact,
	# Structural
	plays comment_relation:is_comment_role,
	plays comments_relation:is_comments_role,
	plays doc_relation:is_doc_role,
	plays list_relation:has_list_role;

CompositeLitArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays elts_relation:is_elts_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays elts_relation:has_elts_role,
	plays lbrace_relation:has_lbrace_role,
	plays rbrace_relation:has_rbrace_role,
	plays type_relation:has_type_role;

DeclStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays decl_relation:has_decl_role;

DeferStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays call_relation:has_call_role,
	plays defer_relation:has_defer_role;

EllipsisArtifact sub GoSourceArtifact,
	# Structural
	plays len_relation:is_len_role,
	plays type_relation:is_type_role,
	plays ellipsis_relation:has_ellipsis_role,
	plays elt_relation:has_elt_role;

EmptyStmtArtifact sub GoSourceArtifact,
	# Attributes
	owns implicitAttribute,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays semicolon_relation:has_semicolon_role;

ExprStmtArtifact sub GoSourceArtifact,
	# Structural
	plays assign_relation:is_assign_role,
	plays body_relation:is_body_role,
	plays comm_relation:is_comm_role,
	plays init_relation:is_init_role,
	plays list_relation:is_list_role,
	plays post_relation:is_post_role,
	plays stmt_relation:is_stmt_role,
	plays x_relation:has_x_role;

FieldArtifact sub GoSourceArtifact,
	# Structural
	plays list_relation:is_list_role,
	plays comment_relation:has_comment_role,
	plays doc_relation:has_doc_role,
	plays names_relation:has_names_role,
	plays tag_relation:has_tag_role,
	plays type_relation:has_type_role;

FieldListArtifact sub GoSourceArtifact,
	# Structural
	plays fields_relation:is_fields_role,
	plays methods_relation:is_methods_role,
	plays params_relation:is_params_role,
	plays recv_relation:is_recv_role,
	plays results_relation:is_results_role,
	plays closing_relation:has_closing_role,
	plays list_relation:has_list_role,
	plays opening_relation:has_opening_role;

FileArtifact sub GoSourceArtifact,
	# Structural
	plays comments_relation:has_comments_role,
	plays decls_relation:has_decls_role,
	plays doc_relation:has_doc_role,
	plays imports_relation:has_imports_role,
	plays name_relation:has_name_role,
	plays package_relation:has_package_role;

ForStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays body_relation:has_body_role,
	plays cond_relation:has_cond_role,
	plays for_relation:has_for_role,
	plays init_relation:has_init_role,
	plays post_relation:has_post_role;

FuncDeclArtifact sub GoSourceArtifact,
	# Attributes
	owns name,
	# Structural
	plays decls_relation:is_decls_role,
	plays body_relation:has_body_role,
	plays doc_relation:has_doc_role,
	plays name_relation:has_name_role,
	plays recv_relation:has_recv_role,
	plays type_relation:has_type_role;

FuncLitArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays body_relation:has_body_role,
	plays type_relation:has_type_role;

FuncTypeArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays elt_relation:is_elt_role,
	plays fun_relation:is_fun_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays x_relation:is_x_role,
	plays func_relation:has_func_role,
	plays params_relation:has_params_role,
	plays results_relation:has_results_role;

GenDeclArtifact sub GoSourceArtifact,
	# Attributes
	owns tokAttribute,
	owns name,
	# Structural
	plays decl_relation:is_decl_role,
	plays decls_relation:is_decls_role,
	plays doc_relation:has_doc_role,
	plays lparen_relation:has_lparen_role,
	plays rparen_relation:has_rparen_role,
	plays specs_relation:has_specs_role,
	plays tok_pos_relation:has_tok_pos_role;

GoStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays call_relation:has_call_role,
	plays go_relation:has_go_role;

IdentArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elt_relation:is_elt_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays label_relation:is_label_role,
	plays len_relation:is_len_role,
	plays lhs_relation:is_lhs_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays max_relation:is_max_role,
	plays name_relation:is_name_role,
	plays names_relation:is_names_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays sel_relation:is_sel_role,
	plays tag_relation:is_tag_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays name_pos_relation:has_name_pos_role;

IfStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays else_relation:is_else_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays body_relation:has_body_role,
	plays cond_relation:has_cond_role,
	plays else_relation:has_else_role,
	plays if_relation:has_if_role,
	plays init_relation:has_init_role;

ImportSpecArtifact sub GoSourceArtifact,
	# Structural
	plays imports_relation:is_imports_role,
	plays specs_relation:is_specs_role,
	plays comment_relation:has_comment_role,
	plays doc_relation:has_doc_role,
	plays end_pos_relation:has_end_pos_role,
	plays name_relation:has_name_role,
	plays path_relation:has_path_role;

IncDecStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays init_relation:is_init_role,
	plays list_relation:is_list_role,
	plays post_relation:is_post_role,
	plays stmt_relation:is_stmt_role,
	plays op_relation:has_op_role,
	plays tok_pos_relation:has_tok_pos_role,
	plays x_relation:has_x_role;

IndexExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays lhs_relation:is_lhs_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays max_relation:is_max_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays index_relation:has_index_role,
	plays lbrack_relation:has_lbrack_role,
	plays rbrack_relation:has_rbrack_role,
	plays x_relation:has_x_role;

InterfaceTypeArtifact sub GoSourceArtifact,
	# Attributes
	owns incompleteAttribute,
	# Structural
	plays args_relation:is_args_role,
	plays elt_relation:is_elt_role,
	plays fun_relation:is_fun_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays x_relation:is_x_role,
	plays interface_relation:has_interface_role,
	plays methods_relation:has_methods_role;

KeyValueExprArtifact sub GoSourceArtifact,
	# Structural
	plays elts_relation:is_elts_role,
	plays colon_relation:has_colon_role,
	plays key_relation:has_key_role,
	plays value_relation:has_value_role;

LabeledStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays colon_relation:has_colon_role,
	plays label_relation:has_label_role,
	plays stmt_relation:has_stmt_role;

MapTypeArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays elt_relation:is_elt_role,
	plays fun_relation:is_fun_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays x_relation:is_x_role,
	plays key_relation:has_key_role,
	plays map_relation:has_map_role,
	plays value_relation:has_value_role;

OperatorArtifact sub GoSourceArtifact,
	# Structural
	plays op_relation:is_op_role;

ParenExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elt_relation:is_elt_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays len_relation:is_len_role,
	plays lhs_relation:is_lhs_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays lparen_relation:has_lparen_role,
	plays rparen_relation:has_rparen_role,
	plays x_relation:has_x_role;

PositionArtifact sub GoSourceArtifact,
	# Attributes
	owns colAttribute,
	owns lineAttribute,
	owns offsetAttribute,
	# Structural
	plays arrow_relation:is_arrow_role,
	plays assign_relation:is_assign_role,
	plays begin_relation:is_begin_role,
	plays case_relation:is_case_role,
	plays closing_relation:is_closing_role,
	plays colon_relation:is_colon_role,
	plays defer_relation:is_defer_role,
	plays ellipsis_relation:is_ellipsis_role,
	plays end_pos_relation:is_end_pos_role,
	plays for_relation:is_for_role,
	plays func_relation:is_func_role,
	plays go_relation:is_go_role,
	plays if_relation:is_if_role,
	plays interface_relation:is_interface_role,
	plays lbrace_relation:is_lbrace_role,
	plays lbrack_relation:is_lbrack_role,
	plays lparen_relation:is_lparen_role,
	plays map_relation:is_map_role,
	plays name_pos_relation:is_name_pos_role,
	plays op_pos_relation:is_op_pos_role,
	plays opening_relation:is_opening_role,
	plays package_relation:is_package_role,
	plays rbrace_relation:is_rbrace_role,
	plays rbrack_relation:is_rbrack_role,
	plays return_relation:is_return_role,
	plays rparen_relation:is_rparen_role,
	plays select_relation:is_select_role,
	plays semicolon_relation:is_semicolon_role,
	plays slash_relation:is_slash_role,
	plays star_relation:is_star_role,
	plays struct_relation:is_struct_role,
	plays switch_relation:is_switch_role,
	plays tok_pos_relation:is_tok_pos_role,
	plays value_pos_relation:is_value_pos_role;

RangeStmtArtifact sub GoSourceArtifact,
	# Attributes
	owns tokAttribute,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays body_relation:has_body_role,
	plays for_relation:has_for_role,
	plays key_relation:has_key_role,
	plays tok_pos_relation:has_tok_pos_role,
	plays value_relation:has_value_role,
	plays x_relation:has_x_role;

ReturnStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays results_relation:has_results_role,
	plays return_relation:has_return_role;

SelectorExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elt_relation:is_elt_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays len_relation:is_len_role,
	plays lhs_relation:is_lhs_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays max_relation:is_max_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays sel_relation:has_sel_role,
	plays x_relation:has_x_role;

SelectStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays body_relation:has_body_role,
	plays select_relation:has_select_role;

SendStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays comm_relation:is_comm_role,
	plays list_relation:is_list_role,
	plays post_relation:is_post_role,
	plays stmt_relation:is_stmt_role,
	plays arrow_relation:has_arrow_role,
	plays chan_relation:has_chan_role,
	plays value_relation:has_value_role;

SliceExprArtifact sub GoSourceArtifact,
	# Attributes
	owns slice3Attribute,
	# Structural
	plays args_relation:is_args_role,
	plays elts_relation:is_elts_role,
	plays index_relation:is_index_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays high_relation:has_high_role,
	plays lbrack_relation:has_lbrack_role,
	plays low_relation:has_low_role,
	plays max_relation:has_max_role,
	plays rbrack_relation:has_rbrack_role,
	plays x_relation:has_x_role;

StarExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elt_relation:is_elt_role,
	plays elts_relation:is_elts_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays lhs_relation:is_lhs_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays star_relation:has_star_role,
	plays x_relation:has_x_role;

StructTypeArtifact sub GoSourceArtifact,
	# Attributes
	owns incompleteAttribute,
	# Structural
	plays args_relation:is_args_role,
	plays elt_relation:is_elt_role,
	plays fun_relation:is_fun_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays type_relation:is_type_role,
	plays value_relation:is_value_role,
	plays x_relation:is_x_role,
	plays fields_relation:has_fields_role,
	plays struct_relation:has_struct_role;

SwitchStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays body_relation:has_body_role,
	plays init_relation:has_init_role,
	plays switch_relation:has_switch_role,
	plays tag_relation:has_tag_role;

TypeAssertExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elts_relation:is_elts_role,
	plays fun_relation:is_fun_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays lparen_relation:has_lparen_role,
	plays rparen_relation:has_rparen_role,
	plays type_relation:has_type_role,
	plays x_relation:has_x_role;

TypeSpecArtifact sub GoSourceArtifact,
	# Structural
	plays specs_relation:is_specs_role,
	plays assign_relation:has_assign_role,
	plays comment_relation:has_comment_role,
	plays doc_relation:has_doc_role,
	plays name_relation:has_name_role,
	plays type_relation:has_type_role;

TypeSwitchStmtArtifact sub GoSourceArtifact,
	# Structural
	plays body_relation:is_body_role,
	plays list_relation:is_list_role,
	plays stmt_relation:is_stmt_role,
	plays assign_relation:has_assign_role,
	plays body_relation:has_body_role,
	plays init_relation:has_init_role,
	plays switch_relation:has_switch_role;

UnaryExprArtifact sub GoSourceArtifact,
	# Structural
	plays args_relation:is_args_role,
	plays chan_relation:is_chan_role,
	plays cond_relation:is_cond_role,
	plays elts_relation:is_elts_role,
	plays high_relation:is_high_role,
	plays index_relation:is_index_role,
	plays key_relation:is_key_role,
	plays list_relation:is_list_role,
	plays low_relation:is_low_role,
	plays results_relation:is_results_role,
	plays rhs_relation:is_rhs_role,
	plays tag_relation:is_tag_role,
	plays value_relation:is_value_role,
	plays values_relation:is_values_role,
	plays x_relation:is_x_role,
	plays y_relation:is_y_role,
	plays op_pos_relation:has_op_pos_role,
	plays op_relation:has_op_role,
	plays x_relation:has_x_role;

ValueSpecArtifact sub GoSourceArtifact,
	# Structural
	plays specs_relation:is_specs_role,
	plays comment_relation:has_comment_role,
	plays doc_relation:has_doc_role,
	plays names_relation:has_names_role,
	plays type_relation:has_type_role,
	plays values_relation:has_values_role;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Go -----#####
args_relation sub parent_child_relation,
	relates is_args_role as is_child, relates has_args_role as is_parent;

arrow_relation sub parent_child_relation,
	relates is_arrow_role as is_child, relates has_arrow_role as is_parent;

assign_relation sub parent_child_relation,
	relates is_assign_role as is_child, relates has_assign_role as is_parent;

begin_relation sub parent_child_relation,
	relates is_begin_role as is_child, relates has_begin_role as is_parent;

body_relation sub parent_child_relation,
	relates is_body_role as is_child, relates has_body_role as is_parent;

call_relation sub parent_child_relation,
	relates is_call_role as is_child, relates has_call_role as is_parent;

case_relation sub parent_child_relation,
	relates is_case_role as is_child, relates has_case_role as is_parent;

chan_relation sub parent_child_relation,
	relates is_chan_role as is_child, relates has_chan_role as is_parent;

closing_relation sub parent_child_relation,
	relates is_closing_role as is_child, relates has_closing_role as is_parent;

colon_relation sub parent_child_relation,
	relates is_colon_role as is_child, relates has_colon_role as is_parent;

comm_relation sub parent_child_relation,
	relates is_comm_role as is_child, relates has_comm_role as is_parent;

comment_relation sub parent_child_relation,
	relates is_comment_role as is_child, relates has_comment_role as is_parent;

comments_relation sub parent_child_relation,
	relates is_comments_role as is_child, relates has_comments_role as is_parent;

cond_relation sub parent_child_relation,
	relates is_cond_role as is_child, relates has_cond_role as is_parent;

decl_relation sub parent_child_relation,
	relates is_decl_role as is_child, relates has_decl_role as is_parent;

decls_relation sub parent_child_relation,
	relates is_decls_role as is_child, relates has_decls_role as is_parent;

defer_relation sub parent_child_relation,
	relates is_defer_role as is_child, relates has_defer_role as is_parent;

doc_relation sub parent_child_relation,
	relates is_doc_role as is_child, relates has_doc_role as is_parent;

ellipsis_relation sub parent_child_relation,
	relates is_ellipsis_role as is_child, relates has_ellipsis_role as is_parent;

else_relation sub parent_child_relation,
	relates is_else_role as is_child, relates has_else_role as is_parent;

elt_relation sub parent_child_relation,
	relates is_elt_role as is_child, relates has_elt_role as is_parent;

elts_relation sub parent_child_relation,
	relates is_elts_role as is_child, relates has_elts_role as is_parent;

end_pos_relation sub parent_child_relation,
	relates is_end_pos_role as is_child, relates has_end_pos_role as is_parent;

fields_relation sub parent_child_relation,
	relates is_fields_role as is_child, relates has_fields_role as is_parent;

for_relation sub parent_child_relation,
	relates is_for_role as is_child, relates has_for_role as is_parent;

fun_relation sub parent_child_relation,
	relates is_fun_role as is_child, relates has_fun_role as is_parent;

func_relation sub parent_child_relation,
	relates is_func_role as is_child, relates has_func_role as is_parent;

go_relation sub parent_child_relation,
	relates is_go_role as is_child, relates has_go_role as is_parent;

high_relation sub parent_child_relation,
	relates is_high_role as is_child, relates has_high_role as is_parent;

if_relation sub parent_child_relation,
	relates is_if_role as is_child, relates has_if_role as is_parent;

imports_relation sub parent_child_relation,
	relates is_imports_role as is_child, relates has_imports_role as is_parent;

index_relation sub parent_child_relation,
	relates is_index_role as is_child, relates has_index_role as is_parent;

init_relation sub parent_child_relation,
	relates is_init_role as is_child, relates has_init_role as is_parent;

interface_relation sub parent_child_relation,
	relates is_interface_role as is_child, relates has_interface_role as is_parent;

key_relation sub parent_child_relation,
	relates is_key_role as is_child, relates has_key_role as is_parent;

label_relation sub parent_child_relation,
	relates is_label_role as is_child, relates has_label_role as is_parent;

lbrace_relation sub parent_child_relation,
	relates is_lbrace_role as is_child, relates has_lbrace_role as is_parent;

lbrack_relation sub parent_child_relation,
	relates is_lbrack_role as is_child, relates has_lbrack_role as is_parent;

len_relation sub parent_child_relation,
	relates is_len_role as is_child, relates has_len_role as is_parent;

lhs_relation sub parent_child_relation,
	relates is_lhs_role as is_child, relates has_lhs_role as is_parent;

list_relation sub parent_child_relation,
	relates is_list_role as is_child, relates has_list_role as is_parent;

low_relation sub parent_child_relation,
	relates is_low_role as is_child, relates has_low_role as is_parent;

lparen_relation sub parent_child_relation,
	relates is_lparen_role as is_child, relates has_lparen_role as is_parent;

map_relation sub parent_child_relation,
	relates is_map_role as is_child, relates has_map_role as is_parent;

max_relation sub parent_child_relation,
	relates is_max_role as is_child, relates has_max_role as is_parent;

methods_relation sub parent_child_relation,
	relates is_methods_role as is_child, relates has_methods_role as is_parent;

name_pos_relation sub parent_child_relation,
	relates is_name_pos_role as is_child, relates has_name_pos_role as is_parent;

name_relation sub parent_child_relation,
	relates is_name_role as is_child, relates has_name_role as is_parent;

names_relation sub parent_child_relation,
	relates is_names_role as is_child, relates has_names_role as is_parent;

op_pos_relation sub parent_child_relation,
	relates is_op_pos_role as is_child, relates has_op_pos_role as is_parent;

op_relation sub parent_child_relation,
	relates is_op_role as is_child, relates has_op_role as is_parent;

opening_relation sub parent_child_relation,
	relates is_opening_role as is_child, relates has_opening_role as is_parent;

package_relation sub parent_child_relation,
	relates is_package_role as is_child, relates has_package_role as is_parent;

params_relation sub parent_child_relation,
	relates is_params_role as is_child, relates has_params_role as is_parent;

path_relation sub parent_child_relation,
	relates is_path_role as is_child, relates has_path_role as is_parent;

post_relation sub parent_child_relation,
	relates is_post_role as is_child, relates has_post_role as is_parent;

rbrace_relation sub parent_child_relation,
	relates is_rbrace_role as is_child, relates has_rbrace_role as is_parent;

rbrack_relation sub parent_child_relation,
	relates is_rbrack_role as is_child, relates has_rbrack_role as is_parent;

recv_relation sub parent_child_relation,
	relates is_recv_role as is_child, relates has_recv_role as is_parent;

results_relation sub parent_child_relation,
	relates is_results_role as is_child, relates has_results_role as is_parent;

return_relation sub parent_child_relation,
	relates is_return_role as is_child, relates has_return_role as is_parent;

rhs_relation sub parent_child_relation,
	relates is_rhs_role as is_child, relates has_rhs_role as is_parent;

rparen_relation sub parent_child_relation,
	relates is_rparen_role as is_child, relates has_rparen_role as is_parent;

sel_relation sub parent_child_relation,
	relates is_sel_role as is_child, relates has_sel_role as is_parent;

select_relation sub parent_child_relation,
	relates is_select_role as is_child, relates has_select_role as is_parent;

semicolon_relation sub parent_child_relation,
	relates is_semicolon_role as is_child, relates has_semicolon_role as is_parent;

slash_relation sub parent_child_relation,
	relates is_slash_role as is_child, relates has_slash_role as is_parent;

specs_relation sub parent_child_relation,
	relates is_specs_role as is_child, relates has_specs_role as is_parent;

star_relation sub parent_child_relation,
	relates is_star_role as is_child, relates has_star_role as is_parent;

stmt_relation sub parent_child_relation,
	relates is_stmt_role as is_child, relates has_stmt_role as is_parent;

struct_relation sub parent_child_relation,
	relates is_struct_role as is_child, relates has_struct_role as is_parent;

switch_relation sub parent_child_relation,
	relates is_switch_role as is_child, relates has_switch_role as is_parent;

tag_relation sub parent_child_relation,
	relates is_tag_role as is_child, relates has_tag_role as is_parent;

tok_pos_relation sub parent_child_relation,
	relates is_tok_pos_role as is_child, relates has_tok_pos_role as is_parent;

type_relation sub parent_child_relation,
	relates is_type_role as is_child, relates has_type_role as is_parent;

value_pos_relation sub parent_child_relation,
	relates is_value_pos_role as is_child, relates has_value_pos_role as is_parent;

value_relation sub parent_child_relation,
	relates is_value_role as is_child, relates has_value_role as is_parent;

values_relation sub parent_child_relation,
	relates is_values_role as is_child, relates has_values_role as is_parent;

x_relation sub parent_child_relation,
	relates is_x_role as is_child, relates has_x_role as is_parent;

y_relation sub parent_child_relation,
	relates is_y_role as is_child, relates has_y_role as is_parent;
