define

##########---------- Entities ----------##########

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

ArrayTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_LIST_POSITIONAL_TYPE,
	plays IS_CALLEE_EXPRESSION_LIST_TYPE,
	plays IS_ENTRY_EXPRESSION_LIST_TYPE,
	plays IS_EXPRESSION_KEY_LIST_TYPE,
	plays IS_EXPRESSION_LIST_TYPE;

AssignStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_FOR_INITIALIZATION_OPERATOR_STATEMENT,
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_FOR_OPERATOR_STATEMENT_UPDATE,
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_OPERATOR_STATEMENT,
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_INITIALIZATION_OPERATOR_STATEMENT_SWITCH,
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_OPERATOR_STATEMENT,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_IF_INITIALIZATION_NEGATIVE_OPERATOR_STATEMENT,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_INITIALIZATION_NEGATIVE_OPERATOR_STATEMENT_SWITCH,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_NEGATIVE_OPERATOR_STATEMENT,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_FOR_INITIALIZATION_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_FOR_OPERATOR_STATEMENT_UPDATE,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_FOR_INITIALIZATION_OPERATOR_STATEMENT_SUBSTRACT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_FOR_MULTIPLY_OPERATOR_STATEMENT_UPDATE,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_FOR_OPERATOR_STATEMENT_SUBSTRACT_UPDATE,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_MODULO_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_MULTIPLY_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_OPERATOR_STATEMENT_SUBSTRACT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_MODULO_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_MULTIPLY_OPERATOR_STATEMENT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_OPERATOR_STATEMENT_SUBSTRACT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_FOR_INITIALIZATION_OPERATOR_RIGHT_SHIFT_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_FOR_LEFT_SHIFT_OPERATOR_STATEMENT_UPDATE,
	plays IS_ASSIGNMENT_BINARY_BITWISE_FOR_OPERATOR_RIGHT_SHIFT_STATEMENT_UPDATE,
	plays IS_ASSIGNMENT_BINARY_BITWISE_IF_INITIALIZATION_OPERATOR_RIGHT_SHIFT_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_LEFT_SHIFT_OPERATOR_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_OPERATOR_OR_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_OPERATOR_RIGHT_SHIFT_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_OPERATOR_STATEMENT_XOR,
	plays IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_DECLARATION_FOR_STATEMENT_UPDATE,
	plays IS_ASSIGNMENT_BINARY_DECLARATION_IF_INITIALIZATION_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_DECLARATION_INITIALIZATION_STATEMENT_SWITCH,
	plays IS_ASSIGNMENT_BINARY_DECLARATION_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_FOR_INITIALIZATION_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_FOR_STATEMENT_UPDATE,
	plays IS_ASSIGNMENT_BINARY_IF_INITIALIZATION_STATEMENT,
	plays IS_ASSIGNMENT_BINARY_INITIALIZATION_STATEMENT_SWITCH,
	plays IS_ASSIGNMENT_BINARY_STATEMENT;

BasicLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CHARACTER_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_LITERAL_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_NUMBER_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_STRING,
	plays IS_ASSIGNMENT_BINARY_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING,
	plays IS_BINARY_CHARACTER_EXPRESSION_LEFT_LITERAL_PRIMITIVE,
	plays IS_BINARY_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_RIGHT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING,
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT,
	plays IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING,
	plays IS_CALLEE_EXPRESSION_LITERAL_NUMBER_PRIMITIVE,
	plays IS_CHARACTER_EXPRESSION_KEY_LITERAL_PRIMITIVE,
	plays IS_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE,
	plays IS_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_VALUE,
	plays IS_CONDITION_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING,
	plays IS_EXPRESSION_INCOMPLETE_KEY_LITERAL_PRIMITIVE,
	plays IS_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE,
	plays IS_EXPRESSION_KEY_LITERAL_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_KEY_LITERAL_PRIMITIVE_STRING,
	plays IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_VALUE,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_STRING,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_STRING_VALUE;

BinaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ADD_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_POSITIONAL,
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_RIGHT,
	plays IS_ADD_ARITHMETIC_BINARY_CONDITION_EXPRESSION_IF,
	plays IS_ADD_ARITHMETIC_BINARY_EXPRESSION,
	plays IS_ADD_ARITHMETIC_BINARY_EXPRESSION_KEY,
	plays IS_ADD_ARITHMETIC_BINARY_EXPRESSION_LEFT,
	plays IS_ADD_ARITHMETIC_BINARY_EXPRESSION_RIGHT,
	plays IS_ADD_ARITHMETIC_BINARY_EXPRESSION_VALUE,
	plays IS_AND_ARGUMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_POSITIONAL,
	plays IS_AND_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL,
	plays IS_AND_ARGUMENT_BINARY_BOOLEAN_EXPRESSION_POSITIONAL,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT,
	plays IS_AND_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_RIGHT,
	plays IS_AND_BINARY_BITWISE_EXPRESSION,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_LEFT,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_LEFT_NEGATIVE,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_VALUE,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_RIGHT,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_VALUE,
	plays IS_AND_BINARY_BOOLEAN_CONDITION_EXPRESSION_FOR,
	plays IS_AND_BINARY_BOOLEAN_CONDITION_EXPRESSION_IF,
	plays IS_AND_BINARY_BOOLEAN_EXPRESSION,
	plays IS_AND_BINARY_BOOLEAN_EXPRESSION_LEFT,
	plays IS_AND_BINARY_BOOLEAN_EXPRESSION_RIGHT,
	plays IS_AND_BINARY_BOOLEAN_EXPRESSION_VALUE,
	plays IS_ARGUMENT_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_POSITIONAL,
	plays IS_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_MODULO_POSITIONAL,
	plays IS_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_POSITIONAL,
	plays IS_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_POSITIONAL_SUBSTRACT,
	plays IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_POSITIONAL,
	plays IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_OR_POSITIONAL,
	plays IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL_RIGHT_SHIFT,
	plays IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL_XOR,
	plays IS_ARGUMENT_BINARY_BOOLEAN_EXPRESSION_OR_POSITIONAL,
	plays IS_ARGUMENT_BINARY_EQUAL_EXPRESSION_NOT_POSITIONAL_RELATIONAL,
	plays IS_ARGUMENT_BINARY_EQUAL_EXPRESSION_POSITIONAL_RELATIONAL,
	plays IS_ARGUMENT_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_POSITIONAL_RELATIONAL,
	plays IS_ARGUMENT_BINARY_EXPRESSION_GREATER_THAN_POSITIONAL_RELATIONAL,
	plays IS_ARGUMENT_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_POSITIONAL_RELATIONAL,
	plays IS_ARGUMENT_BINARY_EXPRESSION_LESS_THAN_POSITIONAL_RELATIONAL,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_EXPRESSION_RIGHT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MODULO_RIGHT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MULTIPLY_RIGHT,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_RIGHT_SUBSTRACT,
	plays IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION,
	plays IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_LEFT,
	plays IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_RIGHT,
	plays IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_VALUE,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_KEY_MULTIPLY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_KEY_SUBSTRACT,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_MODULO,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_MULTIPLY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_SUBSTRACT,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MODULO,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MODULO_RIGHT,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MODULO_VALUE,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_RIGHT,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_VALUE,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_RIGHT_SUBSTRACT,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_SUBSTRACT,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_SUBSTRACT_VALUE,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_RIGHT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OR_RIGHT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT_RIGHT_SHIFT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT_XOR,
	plays IS_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_OR_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EQUAL_EXPRESSION_RELATIONAL_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL_RIGHT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_RIGHT,
	plays IS_BINARY_BITWISE_EXPRESSION_KEY_LEFT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_KEY_OR,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_LEFT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_OR,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_RIGHT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_RIGHT,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_VALUE,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_XOR,
	plays IS_BINARY_BITWISE_EXPRESSION_OR,
	plays IS_BINARY_BITWISE_EXPRESSION_OR_RIGHT,
	plays IS_BINARY_BITWISE_EXPRESSION_OR_VALUE,
	plays IS_BINARY_BITWISE_EXPRESSION_RIGHT_RIGHT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_RIGHT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_RIGHT_SHIFT_VALUE,
	plays IS_BINARY_BITWISE_EXPRESSION_XOR,
	plays IS_BINARY_BOOLEAN_CONDITION_EXPRESSION_FOR_OR,
	plays IS_BINARY_BOOLEAN_CONDITION_EXPRESSION_IF_OR,
	plays IS_BINARY_BOOLEAN_EXPRESSION_LEFT_OR,
	plays IS_BINARY_BOOLEAN_EXPRESSION_OR,
	plays IS_BINARY_BOOLEAN_EXPRESSION_OR_VALUE,
	plays IS_BINARY_CONDITION_EQUAL_EXPRESSION_FOR_NOT_RELATIONAL,
	plays IS_BINARY_CONDITION_EQUAL_EXPRESSION_FOR_RELATIONAL,
	plays IS_BINARY_CONDITION_EQUAL_EXPRESSION_IF_NOT_RELATIONAL,
	plays IS_BINARY_CONDITION_EQUAL_EXPRESSION_IF_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_LESS_THAN_OR_EQUAL_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_LESS_THAN_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_GREATER_THAN_IF_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_GREATER_THAN_OR_EQUAL_IF_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_IF_LESS_THAN_OR_EQUAL_RELATIONAL,
	plays IS_BINARY_CONDITION_EXPRESSION_IF_LESS_THAN_RELATIONAL,
	plays IS_BINARY_EQUAL_EXPRESSION_LEFT_NOT_RELATIONAL,
	plays IS_BINARY_EQUAL_EXPRESSION_LEFT_RELATIONAL,
	plays IS_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL,
	plays IS_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_RIGHT,
	plays IS_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_VALUE,
	plays IS_BINARY_EQUAL_EXPRESSION_RELATIONAL,
	plays IS_BINARY_EQUAL_EXPRESSION_RELATIONAL_RIGHT,
	plays IS_BINARY_EQUAL_EXPRESSION_RELATIONAL_VALUE,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_LEFT_RELATIONAL,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_LEFT_RELATIONAL,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_RIGHT,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_VALUE,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_RIGHT,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LESS_THAN_OR_EQUAL_RELATIONAL,
	plays IS_BINARY_EXPRESSION_LEFT_LESS_THAN_RELATIONAL,
	plays IS_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL,
	plays IS_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL_RIGHT,
	plays IS_BINARY_EXPRESSION_LESS_THAN_RELATIONAL,
	plays IS_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_RIGHT,
	plays IS_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_VALUE;

BlockStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_BLOCK_BODY_FOR_SCOPE_STATEMENT,
	plays IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT,
	plays IS_BLOCK_BODY_SCOPE_STATEMENT,
	plays IS_BLOCK_BODY_SCOPE_STATEMENT_SWITCH,
	plays IS_BLOCK_BODY_SCOPE_STATEMENT_THEN,
	plays IS_BLOCK_ELSE_SCOPE_STATEMENT,
	plays IS_BLOCK_SCOPE_STATEMENT;

BranchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_BREAK_STATEMENT,
	plays IS_CONTINUE_STATEMENT,
	plays IS_GOTO_STATEMENT,
	plays IS_INCOMPLETE_STATEMENT;

CallExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_CALL_EXPRESSION_RIGHT,
	plays IS_BINARY_CALL_EXPRESSION_LEFT,
	plays IS_BINARY_CALL_EXPRESSION_RIGHT,
	plays IS_CALL_CALLEE_EXPRESSION,
	plays IS_CALL_CONDITION_EXPRESSION_FOR,
	plays IS_CALL_CONDITION_EXPRESSION_IF,
	plays IS_CALL_EXPRESSION,
	plays IS_CALL_EXPRESSION_KEY,
	plays IS_CALL_EXPRESSION_VALUE;

CaseClauseArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_CASE_STATEMENT;

ChanTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_TYPE,
	plays IS_CALLEE_EXPRESSION_INCOMPLETE_TYPE,
	plays IS_ENTRY_EXPRESSION_INCOMPLETE_TYPE,
	plays IS_EXPRESSION_INCOMPLETE_KEY_TYPE,
	plays IS_EXPRESSION_INCOMPLETE_TYPE;

CommClauseArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_CASE_INCOMPLETE_STATEMENT;

CommentArtifact sub GoSourceArtifact;

CommentGroupArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_COMMENT_LIST;

CompositeLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_LITERAL_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_RIGHT,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL,
	plays IS_BINARY_EXPRESSION_LITERAL_RIGHT,
	plays IS_EXPRESSION_KEY_LITERAL,
	plays IS_EXPRESSION_LITERAL,
	plays IS_EXPRESSION_LITERAL_VALUE;

DeclStmtArtifact sub GoSourceArtifact;

DeferStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_STATEMENT;

EllipsisArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_TYPE;

EmptyStmtArtifact sub GoSourceArtifact;

ExprStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR_INITIALIZATION_STATEMENT,
	plays IS_FOR_STATEMENT_UPDATE,
	plays IS_IF_INITIALIZATION_STATEMENT,
	plays IS_INITIALIZATION_STATEMENT_SWITCH;

FieldArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_RETURN,
	plays IS_FUNCTION_RECEIVER;

FieldListArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST_RETURN,
	plays IS_FUNCTION_LIST,
	plays IS_FUNCTION_LIST_RECEIVER;

FileArtifact sub GoSourceArtifact;

ForStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

FuncDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION;

FuncLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT,
	plays IS_CALLEE_EXPRESSION,
	plays IS_EXPRESSION_VALUE;

FuncTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_FUNCTION_POSITIONAL_TYPE,
	plays IS_CALLEE_EXPRESSION_FUNCTION_TYPE,
	plays IS_ENTRY_EXPRESSION_FUNCTION_TYPE,
	plays IS_EXPRESSION_FUNCTION_KEY_TYPE,
	plays IS_EXPRESSION_FUNCTION_TYPE;

GenDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION_INCOMPLETE,
	plays IS_DECLARATION_TYPE,
	plays IS_DECLARATION_VARIABLE;

GoStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_STATEMENT;

IdentArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ALIAS_EXPRESSION_IDENTIFIER_IMPORT,
	plays IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_RIGHT,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_RIGHT,
	plays IS_CALLEE_EXPRESSION_IDENTIFIER,
	plays IS_CONDITION_EXPRESSION_FOR_IDENTIFIER,
	plays IS_CONDITION_EXPRESSION_IDENTIFIER_IF,
	plays IS_ENTRY_EXPRESSION_IDENTIFIER,
	plays IS_EXPRESSION_FOR_IDENTIFIER_ITERATOR_KEY,
	plays IS_EXPRESSION_FOR_IDENTIFIER_ITERATOR_VALUE,
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME,
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME_RECEIVER,
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_RECEIVER_TYPE,
	plays IS_EXPRESSION_IDENTIFIER,
	plays IS_EXPRESSION_IDENTIFIER_KEY,
	plays IS_EXPRESSION_IDENTIFIER_NAME,
	plays IS_EXPRESSION_IDENTIFIER_NAME_TYPE,
	plays IS_EXPRESSION_IDENTIFIER_NAME_VARIABLE,
	plays IS_EXPRESSION_IDENTIFIER_TYPE,
	plays IS_EXPRESSION_IDENTIFIER_VALUE;

IfStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ELSE_IF_STATEMENT,
	plays IS_IF_STATEMENT;

ImportSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION_IMPORT;

IncDecStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECREMENT_FOR_INITIALIZATION_STATEMENT_UNARY,
	plays IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE,
	plays IS_DECREMENT_IF_INITIALIZATION_STATEMENT_UNARY,
	plays IS_DECREMENT_STATEMENT_UNARY,
	plays IS_FOR_INCREMENT_INITIALIZATION_STATEMENT_UNARY,
	plays IS_FOR_INCREMENT_STATEMENT_UNARY_UPDATE,
	plays IS_IF_INCREMENT_INITIALIZATION_STATEMENT_UNARY,
	plays IS_INCREMENT_INITIALIZATION_STATEMENT_SWITCH_UNARY,
	plays IS_INCREMENT_STATEMENT_UNARY;

IndexExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LEFT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT,
	plays IS_BINARY_EXPRESSION_LEFT,
	plays IS_BINARY_EXPRESSION_RIGHT,
	plays IS_CALLEE_EXPRESSION,
	plays IS_CONDITION_EXPRESSION_FOR,
	plays IS_CONDITION_EXPRESSION_IF,
	plays IS_EXPRESSION_FOR_ITERATOR_KEY,
	plays IS_EXPRESSION_FOR_ITERATOR_VALUE,
	plays IS_EXPRESSION_KEY,
	plays IS_EXPRESSION_VALUE;

InterfaceTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_TYPE,
	plays IS_CALLEE_EXPRESSION_INCOMPLETE_TYPE,
	plays IS_ENTRY_EXPRESSION_INCOMPLETE_TYPE,
	plays IS_EXPRESSION_INCOMPLETE_KEY_TYPE,
	plays IS_EXPRESSION_INCOMPLETE_TYPE;

KeyValueExprArtifact sub GoSourceArtifact;

LabeledStmtArtifact sub GoSourceArtifact;

MapTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_MAP_POSITIONAL_TYPE,
	plays IS_CALLEE_EXPRESSION_MAP_TYPE,
	plays IS_ENTRY_EXPRESSION_MAP_TYPE,
	plays IS_EXPRESSION_KEY_MAP_TYPE,
	plays IS_EXPRESSION_MAP_TYPE;

OperatorArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR,
	plays IS_ADD_ARITHMETIC_BINARY_EXPRESSION_OPERATOR,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_OPERATOR,
	plays IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_OPERATOR,
	plays IS_AND_BINARY_BITWISE_EXPRESSION_OPERATOR,
	plays IS_AND_BINARY_BOOLEAN_EXPRESSION_OPERATOR,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_EXPRESSION_OPERATOR,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MODULO_OPERATOR,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MULTIPLY_OPERATOR,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR_SUBSTRACT,
	plays IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_OPERATOR,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MODULO_OPERATOR,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_OPERATOR,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_OPERATOR_SUBSTRACT,
	plays IS_ARITHMETIC_EXPRESSION_NEGATIVE_OPERATOR_UNARY,
	plays IS_ARITHMETIC_EXPRESSION_OPERATOR_POSITIVE_UNARY,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_OPERATOR,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_OR,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_RIGHT_SHIFT,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_XOR,
	plays IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_OPERATOR,
	plays IS_BINARY_BITWISE_EXPRESSION_OPERATOR_OR,
	plays IS_BINARY_BITWISE_EXPRESSION_OPERATOR_RIGHT_SHIFT,
	plays IS_BINARY_BITWISE_EXPRESSION_OPERATOR_XOR,
	plays IS_BINARY_BOOLEAN_EXPRESSION_OPERATOR_OR,
	plays IS_BINARY_EQUAL_EXPRESSION_NOT_OPERATOR_RELATIONAL,
	plays IS_BINARY_EQUAL_EXPRESSION_OPERATOR_RELATIONAL,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OPERATOR_RELATIONAL,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL,
	plays IS_BINARY_EXPRESSION_LESS_THAN_OPERATOR_RELATIONAL,
	plays IS_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_OPERATOR_RELATIONAL,
	plays IS_BITWISE_EXPRESSION_NEGATIVE_OPERATOR_UNARY,
	plays IS_BOOLEAN_EXPRESSION_NEGATIVE_OPERATOR_UNARY,
	plays IS_DECREMENT_EXPRESSION_OPERATOR_UNARY,
	plays IS_EXPRESSION_INCOMPLETE_OPERATOR_UNARY,
	plays IS_EXPRESSION_INCREMENT_OPERATOR_UNARY,
	plays IS_EXPRESSION_OPERATOR_TAKE_ADDRESS_UNARY;

ParenExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_CALLEE_EXPRESSION_INCOMPLETE,
	plays IS_CONDITION_EXPRESSION_IF_INCOMPLETE,
	plays IS_ENTRY_EXPRESSION_INCOMPLETE,
	plays IS_EXPRESSION_INCOMPLETE,
	plays IS_EXPRESSION_INCOMPLETE_KEY,
	plays IS_EXPRESSION_INCOMPLETE_TYPE,
	plays IS_EXPRESSION_INCOMPLETE_VALUE;

PositionArtifact sub GoSourceArtifact;

RangeStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR_ITERATOR_STATEMENT;

ReturnStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_RETURN_STATEMENT;

SelectorExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_CALLEE_EXPRESSION_INCOMPLETE,
	plays IS_CONDITION_EXPRESSION_FOR_INCOMPLETE,
	plays IS_CONDITION_EXPRESSION_IF_INCOMPLETE,
	plays IS_ENTRY_EXPRESSION_INCOMPLETE,
	plays IS_EXPRESSION_FOR_INCOMPLETE_ITERATOR_KEY,
	plays IS_EXPRESSION_FOR_INCOMPLETE_ITERATOR_VALUE,
	plays IS_EXPRESSION_INCOMPLETE,
	plays IS_EXPRESSION_INCOMPLETE_KEY,
	plays IS_EXPRESSION_INCOMPLETE_TYPE,
	plays IS_EXPRESSION_INCOMPLETE_VALUE;

SelectStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_STATEMENT_SWITCH;

SendStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR_INCOMPLETE_STATEMENT_UPDATE,
	plays IS_INCOMPLETE_STATEMENT;

SliceExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT,
	plays IS_BINARY_EXPRESSION_LEFT,
	plays IS_BINARY_EXPRESSION_RIGHT,
	plays IS_EXPRESSION_VALUE;

StarExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LEFT,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT,
	plays IS_BINARY_EXPRESSION_LEFT,
	plays IS_BINARY_EXPRESSION_RIGHT,
	plays IS_CONDITION_EXPRESSION_IF,
	plays IS_ENTRY_EXPRESSION,
	plays IS_EXPRESSION_FOR_ITERATOR_KEY,
	plays IS_EXPRESSION_FOR_ITERATOR_VALUE,
	plays IS_EXPRESSION_FUNCTION_RECEIVER_TYPE,
	plays IS_EXPRESSION_KEY,
	plays IS_EXPRESSION_TYPE,
	plays IS_EXPRESSION_VALUE;

StructTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_POSITIONAL_TYPE,
	plays IS_CALLEE_EXPRESSION_TYPE,
	plays IS_ENTRY_EXPRESSION_TYPE,
	plays IS_EXPRESSION_KEY_TYPE,
	plays IS_EXPRESSION_TYPE;

SwitchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_STATEMENT_SWITCH;

TypeAssertExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_CALLEE_EXPRESSION_INCOMPLETE,
	plays IS_CONDITION_EXPRESSION_IF_INCOMPLETE,
	plays IS_EXPRESSION_INCOMPLETE,
	plays IS_EXPRESSION_INCOMPLETE_VALUE;

TypeSpecArtifact sub GoSourceArtifact;

TypeSwitchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_STATEMENT_SWITCH;

UnaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_ARITHMETIC_EXPRESSION_NEGATIVE_POSITIONAL_UNARY,
	plays IS_ARGUMENT_ARITHMETIC_EXPRESSION_POSITIONAL_POSITIVE_UNARY,
	plays IS_ARGUMENT_BITWISE_EXPRESSION_NEGATIVE_POSITIONAL_UNARY,
	plays IS_ARGUMENT_BOOLEAN_EXPRESSION_NEGATIVE_POSITIONAL_UNARY,
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_UNARY,
	plays IS_ARGUMENT_EXPRESSION_POSITIONAL_TAKE_ADDRESS_UNARY,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_NEGATIVE_RIGHT_UNARY,
	plays IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_POSITIVE_RIGHT_UNARY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_NEGATIVE_UNARY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_POSITIVE_UNARY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_NEGATIVE_RIGHT_UNARY,
	plays IS_ARITHMETIC_BINARY_EXPRESSION_POSITIVE_RIGHT_UNARY,
	plays IS_ARITHMETIC_EXPRESSION_KEY_NEGATIVE_UNARY,
	plays IS_ARITHMETIC_EXPRESSION_NEGATIVE_UNARY,
	plays IS_ARITHMETIC_EXPRESSION_NEGATIVE_UNARY_VALUE,
	plays IS_ARITHMETIC_EXPRESSION_POSITIVE_UNARY,
	plays IS_ARITHMETIC_EXPRESSION_POSITIVE_UNARY_VALUE,
	plays IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT_UNARY,
	plays IS_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_NEGATIVE_RIGHT_UNARY,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT_UNARY,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT_TAKE_ADDRESS_UNARY,
	plays IS_BINARY_BITWISE_EXPRESSION_LEFT_NEGATIVE_UNARY,
	plays IS_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT_UNARY,
	plays IS_BINARY_BOOLEAN_EXPRESSION_LEFT_NEGATIVE_UNARY,
	plays IS_BINARY_BOOLEAN_EXPRESSION_NEGATIVE_RIGHT_UNARY,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_UNARY,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT_UNARY,
	plays IS_BINARY_EXPRESSION_LEFT_TAKE_ADDRESS_UNARY,
	plays IS_BINARY_EXPRESSION_RIGHT_TAKE_ADDRESS_UNARY,
	plays IS_BITWISE_EXPRESSION_NEGATIVE_UNARY,
	plays IS_BITWISE_EXPRESSION_NEGATIVE_UNARY_VALUE,
	plays IS_BOOLEAN_CONDITION_EXPRESSION_FOR_NEGATIVE_UNARY,
	plays IS_BOOLEAN_CONDITION_EXPRESSION_IF_NEGATIVE_UNARY,
	plays IS_BOOLEAN_EXPRESSION_NEGATIVE_UNARY,
	plays IS_BOOLEAN_EXPRESSION_NEGATIVE_UNARY_VALUE,
	plays IS_CONDITION_EXPRESSION_FOR_INCOMPLETE_UNARY,
	plays IS_CONDITION_EXPRESSION_IF_INCOMPLETE_UNARY,
	plays IS_EXPRESSION_INCOMPLETE_UNARY,
	plays IS_EXPRESSION_INCOMPLETE_UNARY_VALUE,
	plays IS_EXPRESSION_KEY_TAKE_ADDRESS_UNARY,
	plays IS_EXPRESSION_TAKE_ADDRESS_UNARY,
	plays IS_EXPRESSION_TAKE_ADDRESS_UNARY_VALUE;

ValueSpecArtifact sub GoSourceArtifact;

##########---------- Semantic Roles ----------##########
ADD_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_POSITIONAL sub relation,
	relates IS_ADD_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_POSITIONAL;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_RIGHT sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_RIGHT;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_FOR_INITIALIZATION_OPERATOR_STATEMENT sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_FOR_INITIALIZATION_OPERATOR_STATEMENT;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_FOR_OPERATOR_STATEMENT_UPDATE sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_FOR_OPERATOR_STATEMENT_UPDATE;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_OPERATOR_STATEMENT sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_OPERATOR_STATEMENT;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_INITIALIZATION_OPERATOR_STATEMENT_SWITCH sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_INITIALIZATION_OPERATOR_STATEMENT_SWITCH;

ADD_ARITHMETIC_ASSIGNMENT_BINARY_OPERATOR_STATEMENT sub relation,
	relates IS_ADD_ARITHMETIC_ASSIGNMENT_BINARY_OPERATOR_STATEMENT;

ADD_ARITHMETIC_BINARY_CONDITION_EXPRESSION_IF sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_CONDITION_EXPRESSION_IF;

ADD_ARITHMETIC_BINARY_EXPRESSION sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_EXPRESSION;

ADD_ARITHMETIC_BINARY_EXPRESSION_KEY sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_EXPRESSION_KEY;

ADD_ARITHMETIC_BINARY_EXPRESSION_LEFT sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_EXPRESSION_LEFT;

ADD_ARITHMETIC_BINARY_EXPRESSION_OPERATOR sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_EXPRESSION_OPERATOR;

ADD_ARITHMETIC_BINARY_EXPRESSION_RIGHT sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_EXPRESSION_RIGHT;

ADD_ARITHMETIC_BINARY_EXPRESSION_VALUE sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_EXPRESSION_VALUE;

ALIAS_EXPRESSION_IDENTIFIER_IMPORT sub relation,
	relates IS_ALIAS_EXPRESSION_IDENTIFIER_IMPORT;

AND_ARGUMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_POSITIONAL sub relation,
	relates IS_AND_ARGUMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_POSITIONAL;

AND_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL sub relation,
	relates IS_AND_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL;

AND_ARGUMENT_BINARY_BOOLEAN_EXPRESSION_POSITIONAL sub relation,
	relates IS_AND_ARGUMENT_BINARY_BOOLEAN_EXPRESSION_POSITIONAL;

AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_OPERATOR sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_OPERATOR;

AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT;

AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR;

AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT;

AND_ASSIGNMENT_BINARY_BITWISE_IF_INITIALIZATION_NEGATIVE_OPERATOR_STATEMENT sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_IF_INITIALIZATION_NEGATIVE_OPERATOR_STATEMENT;

AND_ASSIGNMENT_BINARY_BITWISE_INITIALIZATION_NEGATIVE_OPERATOR_STATEMENT_SWITCH sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_INITIALIZATION_NEGATIVE_OPERATOR_STATEMENT_SWITCH;

AND_ASSIGNMENT_BINARY_BITWISE_NEGATIVE_OPERATOR_STATEMENT sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_NEGATIVE_OPERATOR_STATEMENT;

AND_ASSIGNMENT_BINARY_BITWISE_OPERATOR_STATEMENT sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BITWISE_OPERATOR_STATEMENT;

AND_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_RIGHT sub relation,
	relates IS_AND_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_RIGHT;

AND_BINARY_BITWISE_EXPRESSION sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION;

AND_BINARY_BITWISE_EXPRESSION_LEFT sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_LEFT;

AND_BINARY_BITWISE_EXPRESSION_LEFT_NEGATIVE sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_LEFT_NEGATIVE;

AND_BINARY_BITWISE_EXPRESSION_NEGATIVE sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE;

AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_OPERATOR sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_OPERATOR;

AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT;

AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_VALUE sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_NEGATIVE_VALUE;

AND_BINARY_BITWISE_EXPRESSION_OPERATOR sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_OPERATOR;

AND_BINARY_BITWISE_EXPRESSION_RIGHT sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_RIGHT;

AND_BINARY_BITWISE_EXPRESSION_VALUE sub relation,
	relates IS_AND_BINARY_BITWISE_EXPRESSION_VALUE;

AND_BINARY_BOOLEAN_CONDITION_EXPRESSION_FOR sub relation,
	relates IS_AND_BINARY_BOOLEAN_CONDITION_EXPRESSION_FOR;

AND_BINARY_BOOLEAN_CONDITION_EXPRESSION_IF sub relation,
	relates IS_AND_BINARY_BOOLEAN_CONDITION_EXPRESSION_IF;

AND_BINARY_BOOLEAN_EXPRESSION sub relation,
	relates IS_AND_BINARY_BOOLEAN_EXPRESSION;

AND_BINARY_BOOLEAN_EXPRESSION_LEFT sub relation,
	relates IS_AND_BINARY_BOOLEAN_EXPRESSION_LEFT;

AND_BINARY_BOOLEAN_EXPRESSION_OPERATOR sub relation,
	relates IS_AND_BINARY_BOOLEAN_EXPRESSION_OPERATOR;

AND_BINARY_BOOLEAN_EXPRESSION_RIGHT sub relation,
	relates IS_AND_BINARY_BOOLEAN_EXPRESSION_RIGHT;

AND_BINARY_BOOLEAN_EXPRESSION_VALUE sub relation,
	relates IS_AND_BINARY_BOOLEAN_EXPRESSION_VALUE;

ARGS_LIST_RETURN sub relation,
	relates IS_ARGS_LIST_RETURN;

ARGUMENT_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_POSITIONAL sub relation,
	relates IS_ARGUMENT_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_POSITIONAL;

ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_MODULO_POSITIONAL sub relation,
	relates IS_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_MODULO_POSITIONAL;

ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_POSITIONAL sub relation,
	relates IS_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_POSITIONAL;

ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_POSITIONAL_SUBSTRACT sub relation,
	relates IS_ARGUMENT_ARITHMETIC_BINARY_EXPRESSION_POSITIONAL_SUBSTRACT;

ARGUMENT_ARITHMETIC_EXPRESSION_NEGATIVE_POSITIONAL_UNARY sub relation,
	relates IS_ARGUMENT_ARITHMETIC_EXPRESSION_NEGATIVE_POSITIONAL_UNARY;

ARGUMENT_ARITHMETIC_EXPRESSION_POSITIONAL_POSITIVE_UNARY sub relation,
	relates IS_ARGUMENT_ARITHMETIC_EXPRESSION_POSITIONAL_POSITIVE_UNARY;

ARGUMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_POSITIONAL;

ARGUMENT_BINARY_BITWISE_EXPRESSION_OR_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_OR_POSITIONAL;

ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL_RIGHT_SHIFT sub relation,
	relates IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL_RIGHT_SHIFT;

ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL_XOR sub relation,
	relates IS_ARGUMENT_BINARY_BITWISE_EXPRESSION_POSITIONAL_XOR;

ARGUMENT_BINARY_BOOLEAN_EXPRESSION_OR_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_BOOLEAN_EXPRESSION_OR_POSITIONAL;

ARGUMENT_BINARY_EQUAL_EXPRESSION_NOT_POSITIONAL_RELATIONAL sub relation,
	relates IS_ARGUMENT_BINARY_EQUAL_EXPRESSION_NOT_POSITIONAL_RELATIONAL;

ARGUMENT_BINARY_EQUAL_EXPRESSION_POSITIONAL_RELATIONAL sub relation,
	relates IS_ARGUMENT_BINARY_EQUAL_EXPRESSION_POSITIONAL_RELATIONAL;

ARGUMENT_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_POSITIONAL_RELATIONAL sub relation,
	relates IS_ARGUMENT_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_POSITIONAL_RELATIONAL;

ARGUMENT_BINARY_EXPRESSION_GREATER_THAN_POSITIONAL_RELATIONAL sub relation,
	relates IS_ARGUMENT_BINARY_EXPRESSION_GREATER_THAN_POSITIONAL_RELATIONAL;

ARGUMENT_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_POSITIONAL_RELATIONAL sub relation,
	relates IS_ARGUMENT_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_POSITIONAL_RELATIONAL;

ARGUMENT_BINARY_EXPRESSION_LESS_THAN_POSITIONAL_RELATIONAL sub relation,
	relates IS_ARGUMENT_BINARY_EXPRESSION_LESS_THAN_POSITIONAL_RELATIONAL;

ARGUMENT_BITWISE_EXPRESSION_NEGATIVE_POSITIONAL_UNARY sub relation,
	relates IS_ARGUMENT_BITWISE_EXPRESSION_NEGATIVE_POSITIONAL_UNARY;

ARGUMENT_BOOLEAN_EXPRESSION_NEGATIVE_POSITIONAL_UNARY sub relation,
	relates IS_ARGUMENT_BOOLEAN_EXPRESSION_NEGATIVE_POSITIONAL_UNARY;

ARGUMENT_CALL_EXPRESSION_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_POSITIONAL;

ARGUMENT_CHARACTER_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CHARACTER_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE;

ARGUMENT_EXPRESSION_FUNCTION_POSITIONAL_TYPE sub relation,
	relates IS_ARGUMENT_EXPRESSION_FUNCTION_POSITIONAL_TYPE;

ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL sub relation,
	relates IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL;

ARGUMENT_EXPRESSION_INCOMPLETE_LITERAL_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE_LITERAL_POSITIONAL_PRIMITIVE;

ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL;

ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_TYPE sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_TYPE;

ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_UNARY sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE_POSITIONAL_UNARY;

ARGUMENT_EXPRESSION_LIST_POSITIONAL_TYPE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LIST_POSITIONAL_TYPE;

ARGUMENT_EXPRESSION_LITERAL_NUMBER_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_NUMBER_POSITIONAL_PRIMITIVE;

ARGUMENT_EXPRESSION_LITERAL_POSITIONAL sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_POSITIONAL;

ARGUMENT_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_STRING sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_STRING;

ARGUMENT_EXPRESSION_MAP_POSITIONAL_TYPE sub relation,
	relates IS_ARGUMENT_EXPRESSION_MAP_POSITIONAL_TYPE;

ARGUMENT_EXPRESSION_POSITIONAL sub relation,
	relates IS_ARGUMENT_EXPRESSION_POSITIONAL;

ARGUMENT_EXPRESSION_POSITIONAL_TAKE_ADDRESS_UNARY sub relation,
	relates IS_ARGUMENT_EXPRESSION_POSITIONAL_TAKE_ADDRESS_UNARY;

ARGUMENT_EXPRESSION_POSITIONAL_TYPE sub relation,
	relates IS_ARGUMENT_EXPRESSION_POSITIONAL_TYPE;

ARGUMENT_RETURN sub relation,
	relates IS_ARGUMENT_RETURN;

ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_EXPRESSION_OPERATOR sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_EXPRESSION_OPERATOR;

ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_EXPRESSION_RIGHT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_EXPRESSION_RIGHT;

ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_FOR_INITIALIZATION_OPERATOR_STATEMENT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_FOR_INITIALIZATION_OPERATOR_STATEMENT;

ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_FOR_OPERATOR_STATEMENT_UPDATE sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_FOR_OPERATOR_STATEMENT_UPDATE;

ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_OPERATOR_STATEMENT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_DIVIDE_OPERATOR_STATEMENT;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MODULO_OPERATOR sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MODULO_OPERATOR;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MODULO_RIGHT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MODULO_RIGHT;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MULTIPLY_OPERATOR sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MULTIPLY_OPERATOR;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MULTIPLY_RIGHT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_MULTIPLY_RIGHT;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_NEGATIVE_RIGHT_UNARY sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_NEGATIVE_RIGHT_UNARY;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR_SUBSTRACT;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_POSITIVE_RIGHT_UNARY sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_POSITIVE_RIGHT_UNARY;

ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_RIGHT_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_EXPRESSION_RIGHT_SUBSTRACT;

ARITHMETIC_ASSIGNMENT_BINARY_FOR_INITIALIZATION_OPERATOR_STATEMENT_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_FOR_INITIALIZATION_OPERATOR_STATEMENT_SUBSTRACT;

ARITHMETIC_ASSIGNMENT_BINARY_FOR_MULTIPLY_OPERATOR_STATEMENT_UPDATE sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_FOR_MULTIPLY_OPERATOR_STATEMENT_UPDATE;

ARITHMETIC_ASSIGNMENT_BINARY_FOR_OPERATOR_STATEMENT_SUBSTRACT_UPDATE sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_FOR_OPERATOR_STATEMENT_SUBSTRACT_UPDATE;

ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_MODULO_OPERATOR_STATEMENT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_MODULO_OPERATOR_STATEMENT;

ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_MULTIPLY_OPERATOR_STATEMENT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_MULTIPLY_OPERATOR_STATEMENT;

ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_OPERATOR_STATEMENT_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_IF_INITIALIZATION_OPERATOR_STATEMENT_SUBSTRACT;

ARITHMETIC_ASSIGNMENT_BINARY_MODULO_OPERATOR_STATEMENT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_MODULO_OPERATOR_STATEMENT;

ARITHMETIC_ASSIGNMENT_BINARY_MULTIPLY_OPERATOR_STATEMENT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_MULTIPLY_OPERATOR_STATEMENT;

ARITHMETIC_ASSIGNMENT_BINARY_OPERATOR_STATEMENT_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_ASSIGNMENT_BINARY_OPERATOR_STATEMENT_SUBSTRACT;

ARITHMETIC_BINARY_DIVIDE_EXPRESSION sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION;

ARITHMETIC_BINARY_DIVIDE_EXPRESSION_LEFT sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_LEFT;

ARITHMETIC_BINARY_DIVIDE_EXPRESSION_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_OPERATOR;

ARITHMETIC_BINARY_DIVIDE_EXPRESSION_RIGHT sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_RIGHT;

ARITHMETIC_BINARY_DIVIDE_EXPRESSION_VALUE sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_EXPRESSION_VALUE;

ARITHMETIC_BINARY_EXPRESSION_KEY_MULTIPLY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_KEY_MULTIPLY;

ARITHMETIC_BINARY_EXPRESSION_KEY_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_KEY_SUBSTRACT;

ARITHMETIC_BINARY_EXPRESSION_LEFT_MODULO sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_MODULO;

ARITHMETIC_BINARY_EXPRESSION_LEFT_MULTIPLY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_MULTIPLY;

ARITHMETIC_BINARY_EXPRESSION_LEFT_NEGATIVE_UNARY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_NEGATIVE_UNARY;

ARITHMETIC_BINARY_EXPRESSION_LEFT_POSITIVE_UNARY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_POSITIVE_UNARY;

ARITHMETIC_BINARY_EXPRESSION_LEFT_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_LEFT_SUBSTRACT;

ARITHMETIC_BINARY_EXPRESSION_MODULO sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MODULO;

ARITHMETIC_BINARY_EXPRESSION_MODULO_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MODULO_OPERATOR;

ARITHMETIC_BINARY_EXPRESSION_MODULO_RIGHT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MODULO_RIGHT;

ARITHMETIC_BINARY_EXPRESSION_MODULO_VALUE sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MODULO_VALUE;

ARITHMETIC_BINARY_EXPRESSION_MULTIPLY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY;

ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_OPERATOR;

ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_RIGHT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_RIGHT;

ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_VALUE sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_MULTIPLY_VALUE;

ARITHMETIC_BINARY_EXPRESSION_NEGATIVE_RIGHT_UNARY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_NEGATIVE_RIGHT_UNARY;

ARITHMETIC_BINARY_EXPRESSION_OPERATOR_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_OPERATOR_SUBSTRACT;

ARITHMETIC_BINARY_EXPRESSION_POSITIVE_RIGHT_UNARY sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_POSITIVE_RIGHT_UNARY;

ARITHMETIC_BINARY_EXPRESSION_RIGHT_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_RIGHT_SUBSTRACT;

ARITHMETIC_BINARY_EXPRESSION_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_SUBSTRACT;

ARITHMETIC_BINARY_EXPRESSION_SUBSTRACT_VALUE sub relation,
	relates IS_ARITHMETIC_BINARY_EXPRESSION_SUBSTRACT_VALUE;

ARITHMETIC_EXPRESSION_KEY_NEGATIVE_UNARY sub relation,
	relates IS_ARITHMETIC_EXPRESSION_KEY_NEGATIVE_UNARY;

ARITHMETIC_EXPRESSION_NEGATIVE_OPERATOR_UNARY sub relation,
	relates IS_ARITHMETIC_EXPRESSION_NEGATIVE_OPERATOR_UNARY;

ARITHMETIC_EXPRESSION_NEGATIVE_UNARY sub relation,
	relates IS_ARITHMETIC_EXPRESSION_NEGATIVE_UNARY;

ARITHMETIC_EXPRESSION_NEGATIVE_UNARY_VALUE sub relation,
	relates IS_ARITHMETIC_EXPRESSION_NEGATIVE_UNARY_VALUE;

ARITHMETIC_EXPRESSION_OPERATOR_POSITIVE_UNARY sub relation,
	relates IS_ARITHMETIC_EXPRESSION_OPERATOR_POSITIVE_UNARY;

ARITHMETIC_EXPRESSION_POSITIVE_UNARY sub relation,
	relates IS_ARITHMETIC_EXPRESSION_POSITIVE_UNARY;

ARITHMETIC_EXPRESSION_POSITIVE_UNARY_VALUE sub relation,
	relates IS_ARITHMETIC_EXPRESSION_POSITIVE_UNARY_VALUE;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_OPERATOR sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_OPERATOR;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_RIGHT;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT_UNARY sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT_UNARY;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_OR sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_OR;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_RIGHT_SHIFT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_RIGHT_SHIFT;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_XOR sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OPERATOR_XOR;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OR_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_OR_RIGHT;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT_RIGHT_SHIFT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT_RIGHT_SHIFT;

ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT_XOR sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_EXPRESSION_RIGHT_XOR;

ASSIGNMENT_BINARY_BITWISE_FOR_INITIALIZATION_OPERATOR_RIGHT_SHIFT_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_FOR_INITIALIZATION_OPERATOR_RIGHT_SHIFT_STATEMENT;

ASSIGNMENT_BINARY_BITWISE_FOR_LEFT_SHIFT_OPERATOR_STATEMENT_UPDATE sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_FOR_LEFT_SHIFT_OPERATOR_STATEMENT_UPDATE;

ASSIGNMENT_BINARY_BITWISE_FOR_OPERATOR_RIGHT_SHIFT_STATEMENT_UPDATE sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_FOR_OPERATOR_RIGHT_SHIFT_STATEMENT_UPDATE;

ASSIGNMENT_BINARY_BITWISE_IF_INITIALIZATION_OPERATOR_RIGHT_SHIFT_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_IF_INITIALIZATION_OPERATOR_RIGHT_SHIFT_STATEMENT;

ASSIGNMENT_BINARY_BITWISE_LEFT_SHIFT_OPERATOR_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_LEFT_SHIFT_OPERATOR_STATEMENT;

ASSIGNMENT_BINARY_BITWISE_OPERATOR_OR_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_OPERATOR_OR_STATEMENT;

ASSIGNMENT_BINARY_BITWISE_OPERATOR_RIGHT_SHIFT_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_OPERATOR_RIGHT_SHIFT_STATEMENT;

ASSIGNMENT_BINARY_BITWISE_OPERATOR_STATEMENT_XOR sub relation,
	relates IS_ASSIGNMENT_BINARY_BITWISE_OPERATOR_STATEMENT_XOR;

ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_NEGATIVE_RIGHT_UNARY sub relation,
	relates IS_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_NEGATIVE_RIGHT_UNARY;

ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_OR_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_BOOLEAN_EXPRESSION_OR_RIGHT;

ASSIGNMENT_BINARY_CALL_EXPRESSION_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_CALL_EXPRESSION_RIGHT;

ASSIGNMENT_BINARY_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR;

ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT;

ASSIGNMENT_BINARY_DECLARATION_FOR_STATEMENT_UPDATE sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_FOR_STATEMENT_UPDATE;

ASSIGNMENT_BINARY_DECLARATION_IF_INITIALIZATION_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_IF_INITIALIZATION_STATEMENT;

ASSIGNMENT_BINARY_DECLARATION_INITIALIZATION_STATEMENT_SWITCH sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_INITIALIZATION_STATEMENT_SWITCH;

ASSIGNMENT_BINARY_DECLARATION_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_STATEMENT;

ASSIGNMENT_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_RIGHT;

ASSIGNMENT_BINARY_EQUAL_EXPRESSION_RELATIONAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EQUAL_EXPRESSION_RELATIONAL_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT;

ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LEFT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LEFT;

ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT_UNARY sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_INCOMPLETE_RIGHT_UNARY;

ASSIGNMENT_BINARY_EXPRESSION_LEFT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LEFT;

ASSIGNMENT_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE;

ASSIGNMENT_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING;

ASSIGNMENT_BINARY_EXPRESSION_LITERAL_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_OPERATOR sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR;

ASSIGNMENT_BINARY_EXPRESSION_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT;

ASSIGNMENT_BINARY_EXPRESSION_RIGHT_TAKE_ADDRESS_UNARY sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_RIGHT_TAKE_ADDRESS_UNARY;

ASSIGNMENT_BINARY_FOR_INITIALIZATION_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_FOR_INITIALIZATION_STATEMENT;

ASSIGNMENT_BINARY_FOR_STATEMENT_UPDATE sub relation,
	relates IS_ASSIGNMENT_BINARY_FOR_STATEMENT_UPDATE;

ASSIGNMENT_BINARY_IF_INITIALIZATION_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_IF_INITIALIZATION_STATEMENT;

ASSIGNMENT_BINARY_INITIALIZATION_STATEMENT_SWITCH sub relation,
	relates IS_ASSIGNMENT_BINARY_INITIALIZATION_STATEMENT_SWITCH;

ASSIGNMENT_BINARY_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_STATEMENT;

BINARY_BITWISE_EXPRESSION_KEY_LEFT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_KEY_LEFT_SHIFT;

BINARY_BITWISE_EXPRESSION_KEY_OR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_KEY_OR;

BINARY_BITWISE_EXPRESSION_LEFT_LEFT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_LEFT_SHIFT;

BINARY_BITWISE_EXPRESSION_LEFT_NEGATIVE_UNARY sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_NEGATIVE_UNARY;

BINARY_BITWISE_EXPRESSION_LEFT_OR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_OR;

BINARY_BITWISE_EXPRESSION_LEFT_RIGHT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_RIGHT_SHIFT;

BINARY_BITWISE_EXPRESSION_LEFT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT;

BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_OPERATOR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_OPERATOR;

BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_RIGHT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_RIGHT;

BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_VALUE sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_SHIFT_VALUE;

BINARY_BITWISE_EXPRESSION_LEFT_XOR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_LEFT_XOR;

BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT_UNARY sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_NEGATIVE_RIGHT_UNARY;

BINARY_BITWISE_EXPRESSION_OPERATOR_OR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_OPERATOR_OR;

BINARY_BITWISE_EXPRESSION_OPERATOR_RIGHT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_OPERATOR_RIGHT_SHIFT;

BINARY_BITWISE_EXPRESSION_OPERATOR_XOR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_OPERATOR_XOR;

BINARY_BITWISE_EXPRESSION_OR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_OR;

BINARY_BITWISE_EXPRESSION_OR_RIGHT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_OR_RIGHT;

BINARY_BITWISE_EXPRESSION_OR_VALUE sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_OR_VALUE;

BINARY_BITWISE_EXPRESSION_RIGHT_RIGHT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_RIGHT_RIGHT_SHIFT;

BINARY_BITWISE_EXPRESSION_RIGHT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_RIGHT_SHIFT;

BINARY_BITWISE_EXPRESSION_RIGHT_SHIFT_VALUE sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_RIGHT_SHIFT_VALUE;

BINARY_BITWISE_EXPRESSION_XOR sub relation,
	relates IS_BINARY_BITWISE_EXPRESSION_XOR;

BINARY_BOOLEAN_CONDITION_EXPRESSION_FOR_OR sub relation,
	relates IS_BINARY_BOOLEAN_CONDITION_EXPRESSION_FOR_OR;

BINARY_BOOLEAN_CONDITION_EXPRESSION_IF_OR sub relation,
	relates IS_BINARY_BOOLEAN_CONDITION_EXPRESSION_IF_OR;

BINARY_BOOLEAN_EXPRESSION_LEFT_NEGATIVE_UNARY sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_LEFT_NEGATIVE_UNARY;

BINARY_BOOLEAN_EXPRESSION_LEFT_OR sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_LEFT_OR;

BINARY_BOOLEAN_EXPRESSION_NEGATIVE_RIGHT_UNARY sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_NEGATIVE_RIGHT_UNARY;

BINARY_BOOLEAN_EXPRESSION_OPERATOR_OR sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_OPERATOR_OR;

BINARY_BOOLEAN_EXPRESSION_OR sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_OR;

BINARY_BOOLEAN_EXPRESSION_OR_VALUE sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_OR_VALUE;

BINARY_CALL_EXPRESSION_LEFT sub relation,
	relates IS_BINARY_CALL_EXPRESSION_LEFT;

BINARY_CALL_EXPRESSION_RIGHT sub relation,
	relates IS_BINARY_CALL_EXPRESSION_RIGHT;

BINARY_CHARACTER_EXPRESSION_LEFT_LITERAL_PRIMITIVE sub relation,
	relates IS_BINARY_CHARACTER_EXPRESSION_LEFT_LITERAL_PRIMITIVE;

BINARY_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

BINARY_CONDITION_EQUAL_EXPRESSION_FOR_NOT_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EQUAL_EXPRESSION_FOR_NOT_RELATIONAL;

BINARY_CONDITION_EQUAL_EXPRESSION_FOR_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EQUAL_EXPRESSION_FOR_RELATIONAL;

BINARY_CONDITION_EQUAL_EXPRESSION_IF_NOT_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EQUAL_EXPRESSION_IF_NOT_RELATIONAL;

BINARY_CONDITION_EQUAL_EXPRESSION_IF_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EQUAL_EXPRESSION_IF_RELATIONAL;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_RELATIONAL;

BINARY_CONDITION_EXPRESSION_FOR_LESS_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_LESS_THAN_OR_EQUAL_RELATIONAL;

BINARY_CONDITION_EXPRESSION_FOR_LESS_THAN_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_LESS_THAN_RELATIONAL;

BINARY_CONDITION_EXPRESSION_GREATER_THAN_IF_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_GREATER_THAN_IF_RELATIONAL;

BINARY_CONDITION_EXPRESSION_GREATER_THAN_OR_EQUAL_IF_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_GREATER_THAN_OR_EQUAL_IF_RELATIONAL;

BINARY_CONDITION_EXPRESSION_IF_LESS_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_IF_LESS_THAN_OR_EQUAL_RELATIONAL;

BINARY_CONDITION_EXPRESSION_IF_LESS_THAN_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_IF_LESS_THAN_RELATIONAL;

BINARY_EQUAL_EXPRESSION_LEFT_NOT_RELATIONAL sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_LEFT_NOT_RELATIONAL;

BINARY_EQUAL_EXPRESSION_LEFT_RELATIONAL sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_LEFT_RELATIONAL;

BINARY_EQUAL_EXPRESSION_NOT_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_NOT_OPERATOR_RELATIONAL;

BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL;

BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_RIGHT sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_RIGHT;

BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_VALUE sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_NOT_RELATIONAL_VALUE;

BINARY_EQUAL_EXPRESSION_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_OPERATOR_RELATIONAL;

BINARY_EQUAL_EXPRESSION_RELATIONAL sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_RELATIONAL;

BINARY_EQUAL_EXPRESSION_RELATIONAL_RIGHT sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_RELATIONAL_RIGHT;

BINARY_EQUAL_EXPRESSION_RELATIONAL_VALUE sub relation,
	relates IS_BINARY_EQUAL_EXPRESSION_RELATIONAL_VALUE;

BINARY_EXPRESSION_GREATER_THAN_LEFT_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_LEFT_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OPERATOR_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_LEFT_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_LEFT_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_RIGHT;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_VALUE sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_RELATIONAL_VALUE;

BINARY_EXPRESSION_GREATER_THAN_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_RIGHT;

BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_VALUE sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_RELATIONAL_VALUE;

BINARY_EXPRESSION_IDENTIFIER_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT;

BINARY_EXPRESSION_IDENTIFIER_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_RIGHT;

BINARY_EXPRESSION_INCOMPLETE_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LEFT;

BINARY_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE;

BINARY_EXPRESSION_INCOMPLETE_LEFT_UNARY sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_UNARY;

BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_INCOMPLETE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT;

BINARY_EXPRESSION_INCOMPLETE_RIGHT_UNARY sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT_UNARY;

BINARY_EXPRESSION_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_LEFT;

BINARY_EXPRESSION_LEFT_LESS_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LESS_THAN_OR_EQUAL_RELATIONAL;

BINARY_EXPRESSION_LEFT_LESS_THAN_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LESS_THAN_RELATIONAL;

BINARY_EXPRESSION_LEFT_LITERAL sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL;

BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE;

BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING;

BINARY_EXPRESSION_LEFT_TAKE_ADDRESS_UNARY sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_TAKE_ADDRESS_UNARY;

BINARY_EXPRESSION_LESS_THAN_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_OPERATOR_RELATIONAL;

BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL;

BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_OR_EQUAL_RELATIONAL_RIGHT;

BINARY_EXPRESSION_LESS_THAN_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_RELATIONAL;

BINARY_EXPRESSION_LESS_THAN_RELATIONAL_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_RIGHT;

BINARY_EXPRESSION_LESS_THAN_RELATIONAL_VALUE sub relation,
	relates IS_BINARY_EXPRESSION_LESS_THAN_RELATIONAL_VALUE;

BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING;

BINARY_EXPRESSION_LITERAL_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_RIGHT;

BINARY_EXPRESSION_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_RIGHT;

BINARY_EXPRESSION_RIGHT_TAKE_ADDRESS_UNARY sub relation,
	relates IS_BINARY_EXPRESSION_RIGHT_TAKE_ADDRESS_UNARY;

BITWISE_EXPRESSION_NEGATIVE_OPERATOR_UNARY sub relation,
	relates IS_BITWISE_EXPRESSION_NEGATIVE_OPERATOR_UNARY;

BITWISE_EXPRESSION_NEGATIVE_UNARY sub relation,
	relates IS_BITWISE_EXPRESSION_NEGATIVE_UNARY;

BITWISE_EXPRESSION_NEGATIVE_UNARY_VALUE sub relation,
	relates IS_BITWISE_EXPRESSION_NEGATIVE_UNARY_VALUE;

BLOCK_BODY_FOR_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_BODY_FOR_SCOPE_STATEMENT;

BLOCK_BODY_FUNCTION_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;

BLOCK_BODY_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_BODY_SCOPE_STATEMENT;

BLOCK_BODY_SCOPE_STATEMENT_SWITCH sub relation,
	relates IS_BLOCK_BODY_SCOPE_STATEMENT_SWITCH;

BLOCK_BODY_SCOPE_STATEMENT_THEN sub relation,
	relates IS_BLOCK_BODY_SCOPE_STATEMENT_THEN;

BLOCK_ELSE_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_ELSE_SCOPE_STATEMENT;

BLOCK_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_SCOPE_STATEMENT;

BOOLEAN_CONDITION_EXPRESSION_FOR_NEGATIVE_UNARY sub relation,
	relates IS_BOOLEAN_CONDITION_EXPRESSION_FOR_NEGATIVE_UNARY;

BOOLEAN_CONDITION_EXPRESSION_IF_NEGATIVE_UNARY sub relation,
	relates IS_BOOLEAN_CONDITION_EXPRESSION_IF_NEGATIVE_UNARY;

BOOLEAN_EXPRESSION_NEGATIVE_OPERATOR_UNARY sub relation,
	relates IS_BOOLEAN_EXPRESSION_NEGATIVE_OPERATOR_UNARY;

BOOLEAN_EXPRESSION_NEGATIVE_UNARY sub relation,
	relates IS_BOOLEAN_EXPRESSION_NEGATIVE_UNARY;

BOOLEAN_EXPRESSION_NEGATIVE_UNARY_VALUE sub relation,
	relates IS_BOOLEAN_EXPRESSION_NEGATIVE_UNARY_VALUE;

BREAK_STATEMENT sub relation,
	relates IS_BREAK_STATEMENT;

CALL_CALLEE_EXPRESSION sub relation,
	relates IS_CALL_CALLEE_EXPRESSION;

CALL_CONDITION_EXPRESSION_FOR sub relation,
	relates IS_CALL_CONDITION_EXPRESSION_FOR;

CALL_CONDITION_EXPRESSION_IF sub relation,
	relates IS_CALL_CONDITION_EXPRESSION_IF;

CALL_EXPRESSION sub relation,
	relates IS_CALL_EXPRESSION;

CALL_EXPRESSION_KEY sub relation,
	relates IS_CALL_EXPRESSION_KEY;

CALL_EXPRESSION_VALUE sub relation,
	relates IS_CALL_EXPRESSION_VALUE;

CALLEE_EXPRESSION sub relation,
	relates IS_CALLEE_EXPRESSION;

CALLEE_EXPRESSION_FUNCTION_TYPE sub relation,
	relates IS_CALLEE_EXPRESSION_FUNCTION_TYPE;

CALLEE_EXPRESSION_IDENTIFIER sub relation,
	relates IS_CALLEE_EXPRESSION_IDENTIFIER;

CALLEE_EXPRESSION_INCOMPLETE sub relation,
	relates IS_CALLEE_EXPRESSION_INCOMPLETE;

CALLEE_EXPRESSION_INCOMPLETE_TYPE sub relation,
	relates IS_CALLEE_EXPRESSION_INCOMPLETE_TYPE;

CALLEE_EXPRESSION_LIST_TYPE sub relation,
	relates IS_CALLEE_EXPRESSION_LIST_TYPE;

CALLEE_EXPRESSION_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_CALLEE_EXPRESSION_LITERAL_NUMBER_PRIMITIVE;

CALLEE_EXPRESSION_MAP_TYPE sub relation,
	relates IS_CALLEE_EXPRESSION_MAP_TYPE;

CALLEE_EXPRESSION_TYPE sub relation,
	relates IS_CALLEE_EXPRESSION_TYPE;

CASE_INCOMPLETE_STATEMENT sub relation,
	relates IS_CASE_INCOMPLETE_STATEMENT;

CASE_STATEMENT sub relation,
	relates IS_CASE_STATEMENT;

CHARACTER_EXPRESSION_KEY_LITERAL_PRIMITIVE sub relation,
	relates IS_CHARACTER_EXPRESSION_KEY_LITERAL_PRIMITIVE;

CHARACTER_EXPRESSION_LITERAL_PRIMITIVE sub relation,
	relates IS_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE;

CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_VALUE sub relation,
	relates IS_CHARACTER_EXPRESSION_LITERAL_PRIMITIVE_VALUE;

COMMENT_LIST sub relation,
	relates IS_COMMENT_LIST;

CONDITION_EXPRESSION_FOR sub relation,
	relates IS_CONDITION_EXPRESSION_FOR;

CONDITION_EXPRESSION_FOR_IDENTIFIER sub relation,
	relates IS_CONDITION_EXPRESSION_FOR_IDENTIFIER;

CONDITION_EXPRESSION_FOR_INCOMPLETE sub relation,
	relates IS_CONDITION_EXPRESSION_FOR_INCOMPLETE;

CONDITION_EXPRESSION_FOR_INCOMPLETE_UNARY sub relation,
	relates IS_CONDITION_EXPRESSION_FOR_INCOMPLETE_UNARY;

CONDITION_EXPRESSION_IDENTIFIER_IF sub relation,
	relates IS_CONDITION_EXPRESSION_IDENTIFIER_IF;

CONDITION_EXPRESSION_IF sub relation,
	relates IS_CONDITION_EXPRESSION_IF;

CONDITION_EXPRESSION_IF_INCOMPLETE sub relation,
	relates IS_CONDITION_EXPRESSION_IF_INCOMPLETE;

CONDITION_EXPRESSION_IF_INCOMPLETE_UNARY sub relation,
	relates IS_CONDITION_EXPRESSION_IF_INCOMPLETE_UNARY;

CONDITION_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_CONDITION_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE;

CONTINUE_STATEMENT sub relation,
	relates IS_CONTINUE_STATEMENT;

DECLARATION_FUNCTION sub relation,
	relates IS_DECLARATION_FUNCTION;

DECLARATION_IMPORT sub relation,
	relates IS_DECLARATION_IMPORT;

DECLARATION_INCOMPLETE sub relation,
	relates IS_DECLARATION_INCOMPLETE;

DECLARATION_TYPE sub relation,
	relates IS_DECLARATION_TYPE;

DECLARATION_VARIABLE sub relation,
	relates IS_DECLARATION_VARIABLE;

DECREMENT_EXPRESSION_OPERATOR_UNARY sub relation,
	relates IS_DECREMENT_EXPRESSION_OPERATOR_UNARY;

DECREMENT_FOR_INITIALIZATION_STATEMENT_UNARY sub relation,
	relates IS_DECREMENT_FOR_INITIALIZATION_STATEMENT_UNARY;

DECREMENT_FOR_STATEMENT_UNARY_UPDATE sub relation,
	relates IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE;

DECREMENT_IF_INITIALIZATION_STATEMENT_UNARY sub relation,
	relates IS_DECREMENT_IF_INITIALIZATION_STATEMENT_UNARY;

DECREMENT_STATEMENT_UNARY sub relation,
	relates IS_DECREMENT_STATEMENT_UNARY;

ELSE_IF_STATEMENT sub relation,
	relates IS_ELSE_IF_STATEMENT;

ENTRY_EXPRESSION sub relation,
	relates IS_ENTRY_EXPRESSION;

ENTRY_EXPRESSION_FUNCTION_TYPE sub relation,
	relates IS_ENTRY_EXPRESSION_FUNCTION_TYPE;

ENTRY_EXPRESSION_IDENTIFIER sub relation,
	relates IS_ENTRY_EXPRESSION_IDENTIFIER;

ENTRY_EXPRESSION_INCOMPLETE sub relation,
	relates IS_ENTRY_EXPRESSION_INCOMPLETE;

ENTRY_EXPRESSION_INCOMPLETE_TYPE sub relation,
	relates IS_ENTRY_EXPRESSION_INCOMPLETE_TYPE;

ENTRY_EXPRESSION_LIST_TYPE sub relation,
	relates IS_ENTRY_EXPRESSION_LIST_TYPE;

ENTRY_EXPRESSION_MAP_TYPE sub relation,
	relates IS_ENTRY_EXPRESSION_MAP_TYPE;

ENTRY_EXPRESSION_TYPE sub relation,
	relates IS_ENTRY_EXPRESSION_TYPE;

EXPRESSION_FOR_IDENTIFIER_ITERATOR_KEY sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_ITERATOR_KEY;

EXPRESSION_FOR_IDENTIFIER_ITERATOR_VALUE sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_ITERATOR_VALUE;

EXPRESSION_FOR_INCOMPLETE_ITERATOR_KEY sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE_ITERATOR_KEY;

EXPRESSION_FOR_INCOMPLETE_ITERATOR_VALUE sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE_ITERATOR_VALUE;

EXPRESSION_FOR_ITERATOR_KEY sub relation,
	relates IS_EXPRESSION_FOR_ITERATOR_KEY;

EXPRESSION_FOR_ITERATOR_VALUE sub relation,
	relates IS_EXPRESSION_FOR_ITERATOR_VALUE;

EXPRESSION_FUNCTION_IDENTIFIER_NAME sub relation,
	relates IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME;

EXPRESSION_FUNCTION_IDENTIFIER_NAME_RECEIVER sub relation,
	relates IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME_RECEIVER;

EXPRESSION_FUNCTION_IDENTIFIER_RECEIVER_TYPE sub relation,
	relates IS_EXPRESSION_FUNCTION_IDENTIFIER_RECEIVER_TYPE;

EXPRESSION_FUNCTION_KEY_TYPE sub relation,
	relates IS_EXPRESSION_FUNCTION_KEY_TYPE;

EXPRESSION_FUNCTION_RECEIVER_TYPE sub relation,
	relates IS_EXPRESSION_FUNCTION_RECEIVER_TYPE;

EXPRESSION_FUNCTION_TYPE sub relation,
	relates IS_EXPRESSION_FUNCTION_TYPE;

EXPRESSION_IDENTIFIER sub relation,
	relates IS_EXPRESSION_IDENTIFIER;

EXPRESSION_IDENTIFIER_KEY sub relation,
	relates IS_EXPRESSION_IDENTIFIER_KEY;

EXPRESSION_IDENTIFIER_NAME sub relation,
	relates IS_EXPRESSION_IDENTIFIER_NAME;

EXPRESSION_IDENTIFIER_NAME_TYPE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_NAME_TYPE;

EXPRESSION_IDENTIFIER_NAME_VARIABLE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_NAME_VARIABLE;

EXPRESSION_IDENTIFIER_TYPE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_TYPE;

EXPRESSION_IDENTIFIER_VALUE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_VALUE;

EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING;

EXPRESSION_INCOMPLETE sub relation,
	relates IS_EXPRESSION_INCOMPLETE;

EXPRESSION_INCOMPLETE_KEY sub relation,
	relates IS_EXPRESSION_INCOMPLETE_KEY;

EXPRESSION_INCOMPLETE_KEY_LITERAL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_KEY_LITERAL_PRIMITIVE;

EXPRESSION_INCOMPLETE_KEY_TYPE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_KEY_TYPE;

EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE;

EXPRESSION_INCOMPLETE_OPERATOR_UNARY sub relation,
	relates IS_EXPRESSION_INCOMPLETE_OPERATOR_UNARY;

EXPRESSION_INCOMPLETE_TYPE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_TYPE;

EXPRESSION_INCOMPLETE_UNARY sub relation,
	relates IS_EXPRESSION_INCOMPLETE_UNARY;

EXPRESSION_INCOMPLETE_UNARY_VALUE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_UNARY_VALUE;

EXPRESSION_INCOMPLETE_VALUE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_VALUE;

EXPRESSION_INCREMENT_OPERATOR_UNARY sub relation,
	relates IS_EXPRESSION_INCREMENT_OPERATOR_UNARY;

EXPRESSION_KEY sub relation,
	relates IS_EXPRESSION_KEY;

EXPRESSION_KEY_LIST_TYPE sub relation,
	relates IS_EXPRESSION_KEY_LIST_TYPE;

EXPRESSION_KEY_LITERAL sub relation,
	relates IS_EXPRESSION_KEY_LITERAL;

EXPRESSION_KEY_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_EXPRESSION_KEY_LITERAL_NUMBER_PRIMITIVE;

EXPRESSION_KEY_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_KEY_LITERAL_PRIMITIVE_STRING;

EXPRESSION_KEY_MAP_TYPE sub relation,
	relates IS_EXPRESSION_KEY_MAP_TYPE;

EXPRESSION_KEY_TAKE_ADDRESS_UNARY sub relation,
	relates IS_EXPRESSION_KEY_TAKE_ADDRESS_UNARY;

EXPRESSION_KEY_TYPE sub relation,
	relates IS_EXPRESSION_KEY_TYPE;

EXPRESSION_LIST_TYPE sub relation,
	relates IS_EXPRESSION_LIST_TYPE;

EXPRESSION_LITERAL sub relation,
	relates IS_EXPRESSION_LITERAL;

EXPRESSION_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE;

EXPRESSION_LITERAL_NUMBER_PRIMITIVE_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_VALUE;

EXPRESSION_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_STRING;

EXPRESSION_LITERAL_PRIMITIVE_STRING_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_STRING_VALUE;

EXPRESSION_LITERAL_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_VALUE;

EXPRESSION_MAP_TYPE sub relation,
	relates IS_EXPRESSION_MAP_TYPE;

EXPRESSION_OPERATOR_TAKE_ADDRESS_UNARY sub relation,
	relates IS_EXPRESSION_OPERATOR_TAKE_ADDRESS_UNARY;

EXPRESSION_TAKE_ADDRESS_UNARY sub relation,
	relates IS_EXPRESSION_TAKE_ADDRESS_UNARY;

EXPRESSION_TAKE_ADDRESS_UNARY_VALUE sub relation,
	relates IS_EXPRESSION_TAKE_ADDRESS_UNARY_VALUE;

EXPRESSION_TYPE sub relation,
	relates IS_EXPRESSION_TYPE;

EXPRESSION_VALUE sub relation,
	relates IS_EXPRESSION_VALUE;

FOR_INCOMPLETE_STATEMENT_UPDATE sub relation,
	relates IS_FOR_INCOMPLETE_STATEMENT_UPDATE;

FOR_INCREMENT_INITIALIZATION_STATEMENT_UNARY sub relation,
	relates IS_FOR_INCREMENT_INITIALIZATION_STATEMENT_UNARY;

FOR_INCREMENT_STATEMENT_UNARY_UPDATE sub relation,
	relates IS_FOR_INCREMENT_STATEMENT_UNARY_UPDATE;

FOR_INITIALIZATION_STATEMENT sub relation,
	relates IS_FOR_INITIALIZATION_STATEMENT;

FOR_ITERATOR_STATEMENT sub relation,
	relates IS_FOR_ITERATOR_STATEMENT;

FOR_STATEMENT sub relation,
	relates IS_FOR_STATEMENT;

FOR_STATEMENT_UPDATE sub relation,
	relates IS_FOR_STATEMENT_UPDATE;

FUNCTION_LIST sub relation,
	relates IS_FUNCTION_LIST;

FUNCTION_LIST_RECEIVER sub relation,
	relates IS_FUNCTION_LIST_RECEIVER;

FUNCTION_RECEIVER sub relation,
	relates IS_FUNCTION_RECEIVER;

GOTO_STATEMENT sub relation,
	relates IS_GOTO_STATEMENT;

IF_INCREMENT_INITIALIZATION_STATEMENT_UNARY sub relation,
	relates IS_IF_INCREMENT_INITIALIZATION_STATEMENT_UNARY;

IF_INITIALIZATION_STATEMENT sub relation,
	relates IS_IF_INITIALIZATION_STATEMENT;

IF_STATEMENT sub relation,
	relates IS_IF_STATEMENT;

INCOMPLETE_STATEMENT sub relation,
	relates IS_INCOMPLETE_STATEMENT;

INCOMPLETE_STATEMENT_SWITCH sub relation,
	relates IS_INCOMPLETE_STATEMENT_SWITCH;

INCREMENT_INITIALIZATION_STATEMENT_SWITCH_UNARY sub relation,
	relates IS_INCREMENT_INITIALIZATION_STATEMENT_SWITCH_UNARY;

INCREMENT_STATEMENT_UNARY sub relation,
	relates IS_INCREMENT_STATEMENT_UNARY;

INITIALIZATION_STATEMENT_SWITCH sub relation,
	relates IS_INITIALIZATION_STATEMENT_SWITCH;

RETURN_STATEMENT sub relation,
	relates IS_RETURN_STATEMENT;

STATEMENT_SWITCH sub relation,
	relates IS_STATEMENT_SWITCH;
