define

##########---------- Entities ----------##########

#####----- Omnilingual -----#####
OmnilingualSourceArtifact sub SourceArtifact;

ExpressionStatementArtifact sub OmnilingualSourceArtifact;

FileArtifact sub OmnilingualSourceArtifact;

ForArtifact sub OmnilingualSourceArtifact;

ForStatementArtifact sub OmnilingualSourceArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

IdentifierArtifact sub OmnilingualSourceArtifact;

ModuleArtifact sub OmnilingualSourceArtifact;

NameArtifact sub OmnilingualSourceArtifact;

OperatorArtifact sub OmnilingualSourceArtifact,
	# Semantic
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoAssignStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT;

GoBasicLitArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT,
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT,
	plays IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING;

GoBinaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL;

GoBlockStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_BLOCK_BODY_FOR_SCOPE_STATEMENT,
	plays IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;

GoCallExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_CALL_EXPRESSION;

GoExprStmtArtifact sub GoSourceArtifact;

GoFieldListArtifact sub GoSourceArtifact;

GoFileArtifact sub FileArtifact;

GoForStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

GoFuncDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION;

GoFuncTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_FUNCTION_TYPE;

GoGenDeclArtifact sub GoSourceArtifact;

GoIdentArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL,
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME,
	plays IS_EXPRESSION_IDENTIFIER;

GoImportSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECLARATION_IMPORT;

GoIncDecStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE;

GoOperatorArtifact sub OperatorArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL,
	plays IS_DECREMENT_EXPRESSION_OPERATOR_UNARY;

GoPositionArtifact sub GoSourceArtifact;

GoSelectorExprArtifact sub GoSourceArtifact,
	# Semantic
	plays IS_CALLEE_EXPRESSION_INCOMPLETE;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaArrayTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_LIST_PRIMITIVE_TYPE;

JavaBlockArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BLOCK_BODY_FOR_SCOPE_STATEMENT,
	plays IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;

JavaCompilationUnitArtifact sub JavaSourceArtifact;

JavaDimensionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_TYPE;

JavaExpressionStatementArtifact sub ExpressionStatementArtifact;

JavaForStatementArtifact sub ForStatementArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

JavaInfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavaMethodDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_VISIBILITY_WORLD;

JavaMethodInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CALL_EXPRESSION;

JavaModifierArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_VISIBILITY_WORLD;

JavaNumberLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT,
	plays IS_EXPRESSION_LITERAL_NUMBER;

JavaOperatorArtifact sub OperatorArtifact,
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavaPostfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;

JavaPrimitiveTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_NUMBER_PRIMITIVE_TYPE,
	plays IS_PRIMITIVE_TYPE;

JavaQualifiedNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER;

JavaSimpleNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL,
	plays IS_ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER,
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME,
	plays IS_EXPRESSION_IDENTIFIER;

JavaSimpleTypeArtifact sub JavaSourceArtifact;

JavaSingleVariableDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_DECLARATION_FUNCTION_VARIABLE;

JavaTypeDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION_TYPE_VISIBILITY_WORLD;

JavaVariableDeclarationExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE;

JavaVariableDeclarationFragmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays IS_DECLARATION_VARIABLE;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptBinaryExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavascriptBlockStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT,
	plays IS_BLOCK_SCOPE_STATEMENT;

JavascriptCallExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_CALL_EXPRESSION;

JavascriptExpressionStatementArtifact sub ExpressionStatementArtifact;

JavascriptFileArtifact sub FileArtifact;

JavascriptForStatementArtifact sub ForStatementArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

JavascriptFunctionDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_STATEMENT;

JavascriptIdentifierArtifact sub IdentifierArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME,
	plays IS_EXPRESSION_IDENTIFIER;

JavascriptMemberExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED;

JavascriptNumericLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT,
	plays IS_EXPRESSION_INITIALIZATION_LITERAL_NUMBER;

JavascriptOperatorArtifact sub OperatorArtifact,
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY,
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavascriptProgramArtifact sub JavascriptSourceArtifact;

JavascriptUpdateExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;

JavascriptVariableDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE;

JavascriptVariableDeclaratorArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays IS_DECLARATION_VARIABLE;

#####----- Php -----#####
PhpSourceArtifact sub SourceArtifact;

PhpExprAssignArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_EXPRESSION_FOR_INITIALIZATION;

PhpExprBinaryOpGreaterOrEqualArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

PhpExprPostDecArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_DECREMENT_EXPRESSION_FOR_POSTFIX_UNARY_UPDATE;

PhpExprVariableArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER_LEFT_VARIABLE,
	plays IS_IDENTIFIER_VARIABLE;

PhpFunctionBodyArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_BODY_DECLARATION_FUNCTION;

PhpFunctionReturnTypeArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_RETURN_TYPE;

PhpModuleArtifact sub ModuleArtifact;

PhpNameArtifact sub NameArtifact,
	# Semantic
	plays IS_EXPRESSION_IDENTIFIER;

PhpScalarLNumberArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_LITERAL_NUMBER_RIGHT;

PhpStmtEchoArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_BODY_CALL_FOR_STATEMENT;

PhpStmtForArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

PhpStmtFunctionArtifact sub PhpSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonCallArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CALL_EXPRESSION_FOR_FUNCTION;

PythonForArtifact sub ForArtifact,
	# Semantic
	plays IS_FOR_ITERATOR_STATEMENT;

PythonForBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_FOR;

PythonForOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_ELSE_FOR;

PythonModuleArtifact sub ModuleArtifact,
	# Semantic
	plays IS_FILE_MODULE;

PythonNameArtifact sub NameArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL,
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER,
	plays IS_EXPRESSION_FOR_IDENTIFIER_UPDATE;

PythonNumArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE;

PythonPrintArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

RubyArgsArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE;

RubyBeginArtifact sub RubySourceArtifact;

RubyDefArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_IDENTIFIER_STATEMENT;

RubyForArtifact sub ForArtifact,
	# Semantic
	plays IS_FOR_STATEMENT;

RubyIdentifierArtifact sub IdentifierArtifact;

RubyIntArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE;

RubyLvarArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_EXPRESSION_IDENTIFIER;

RubyLvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_FOR_IDENTIFIER_ITERATOR_LEFT;

RubyModuleArtifact sub ModuleArtifact,
	# Semantic
	plays IS_IDENTIFIER_MODULE_STATEMENT;

RubySendCallArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_CALL_EXPRESSION_FOR_FUNCTION_UPDATE;

RubySendQualifiedArtifact sub RubySourceArtifact,
	# Semantic
	plays IS_BODY_EXPRESSION_FOR_IDENTIFIER_QUALIFIED;

##########---------- Semantic Roles ----------##########
ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NUMBER_PRIMITIVE;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL;

ARGUMENT_DECLARATION_FUNCTION_VARIABLE sub relation,
	relates IS_ARGUMENT_DECLARATION_FUNCTION_VARIABLE;

ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME sub relation,
	relates IS_ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME;

ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL sub relation,
	relates IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL;

ARGUMENT_EXPRESSION_INCOMPLETE sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE;

ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE sub relation,
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;

ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY sub relation,
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY;

ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY sub relation,
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY;

ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR;

ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT sub relation,
	relates IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT;

ASSIGNMENT_BINARY_EXPRESSION_FOR_IDENTIFIER_ITERATOR_LEFT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_FOR_IDENTIFIER_ITERATOR_LEFT;

ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT;

ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

ASSIGNMENT_EXPRESSION_FOR_INITIALIZATION sub relation,
	relates IS_ASSIGNMENT_EXPRESSION_FOR_INITIALIZATION;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

BINARY_EXPRESSION_IDENTIFIER_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT;

BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT;

BLOCK_BODY_FOR_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_BODY_FOR_SCOPE_STATEMENT;

BLOCK_BODY_FUNCTION_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;

BLOCK_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_SCOPE_STATEMENT;

BODY_CALL_FOR_STATEMENT sub relation,
	relates IS_BODY_CALL_FOR_STATEMENT;

BODY_DECLARATION_FUNCTION sub relation,
	relates IS_BODY_DECLARATION_FUNCTION;

BODY_ELSE_FOR sub relation,
	relates IS_BODY_ELSE_FOR;

BODY_EXPRESSION_FOR_IDENTIFIER_QUALIFIED sub relation,
	relates IS_BODY_EXPRESSION_FOR_IDENTIFIER_QUALIFIED;

BODY_FOR sub relation,
	relates IS_BODY_FOR;

CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER;

CALL_CALLEE_EXPRESSION_IDENTIFIER sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER;

CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED;

CALL_EXPRESSION sub relation,
	relates IS_CALL_EXPRESSION;

CALL_EXPRESSION_FOR_FUNCTION sub relation,
	relates IS_CALL_EXPRESSION_FOR_FUNCTION;

CALL_EXPRESSION_FOR_FUNCTION_UPDATE sub relation,
	relates IS_CALL_EXPRESSION_FOR_FUNCTION_UPDATE;

CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER sub relation,
	relates IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER;

CALLEE_EXPRESSION_INCOMPLETE sub relation,
	relates IS_CALLEE_EXPRESSION_INCOMPLETE;

DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE sub relation,
	relates IS_DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE;

DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE sub relation,
	relates IS_DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE;

DECLARATION_FUNCTION sub relation,
	relates IS_DECLARATION_FUNCTION;

DECLARATION_FUNCTION_IDENTIFIER_STATEMENT sub relation,
	relates IS_DECLARATION_FUNCTION_IDENTIFIER_STATEMENT;

DECLARATION_FUNCTION_RETURN_TYPE sub relation,
	relates IS_DECLARATION_FUNCTION_RETURN_TYPE;

DECLARATION_FUNCTION_STATEMENT sub relation,
	relates IS_DECLARATION_FUNCTION_STATEMENT;

DECLARATION_FUNCTION_VISIBILITY_WORLD sub relation,
	relates IS_DECLARATION_FUNCTION_VISIBILITY_WORLD;

DECLARATION_IMPORT sub relation,
	relates IS_DECLARATION_IMPORT;

DECLARATION_TYPE_VISIBILITY_WORLD sub relation,
	relates IS_DECLARATION_TYPE_VISIBILITY_WORLD;

DECLARATION_VARIABLE sub relation,
	relates IS_DECLARATION_VARIABLE;

DECREMENT_EXPRESSION_FOR_POSTFIX_UNARY_UPDATE sub relation,
	relates IS_DECREMENT_EXPRESSION_FOR_POSTFIX_UNARY_UPDATE;

DECREMENT_EXPRESSION_OPERATOR_UNARY sub relation,
	relates IS_DECREMENT_EXPRESSION_OPERATOR_UNARY;

DECREMENT_FOR_STATEMENT_UNARY_UPDATE sub relation,
	relates IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE;

EXPRESSION_FOR_IDENTIFIER_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_UPDATE;

EXPRESSION_FUNCTION_IDENTIFIER_NAME sub relation,
	relates IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME;

EXPRESSION_FUNCTION_TYPE sub relation,
	relates IS_EXPRESSION_FUNCTION_TYPE;

EXPRESSION_IDENTIFIER sub relation,
	relates IS_EXPRESSION_IDENTIFIER;

EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING;

EXPRESSION_INITIALIZATION_LITERAL_NUMBER sub relation,
	relates IS_EXPRESSION_INITIALIZATION_LITERAL_NUMBER;

EXPRESSION_LITERAL_NUMBER sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER;

EXPRESSION_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE;

EXPRESSION_LITERAL_NUMBER_RIGHT sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER_RIGHT;

FILE_MODULE sub relation,
	relates IS_FILE_MODULE;

FOR_ITERATOR_STATEMENT sub relation,
	relates IS_FOR_ITERATOR_STATEMENT;

FOR_STATEMENT sub relation,
	relates IS_FOR_STATEMENT;

IDENTIFIER_LEFT_VARIABLE sub relation,
	relates IS_IDENTIFIER_LEFT_VARIABLE;

IDENTIFIER_MODULE_STATEMENT sub relation,
	relates IS_IDENTIFIER_MODULE_STATEMENT;

IDENTIFIER_VARIABLE sub relation,
	relates IS_IDENTIFIER_VARIABLE;

INCOMPLETE_TYPE sub relation,
	relates IS_INCOMPLETE_TYPE;

LIST_PRIMITIVE_TYPE sub relation,
	relates IS_LIST_PRIMITIVE_TYPE;

NUMBER_PRIMITIVE_TYPE sub relation,
	relates IS_NUMBER_PRIMITIVE_TYPE;

PRIMITIVE_TYPE sub relation,
	relates IS_PRIMITIVE_TYPE;

VISIBILITY_WORLD sub relation,
	relates IS_VISIBILITY_WORLD;
