define

##########---------- Entities ----------##########

#####----- Omnilingual -----#####
OmnilingualSourceArtifact sub SourceArtifact;

ExpressionStatementArtifact sub OmnilingualSourceArtifact;

FileArtifact sub OmnilingualSourceArtifact;

ForStatementArtifact sub OmnilingualSourceArtifact;

OperatorArtifact sub OmnilingualSourceArtifact;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoAssignStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT;

GoBasicLitArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT
	plays IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING;

GoBinaryExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL;

GoBlockStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_BLOCK_BODY_FOR_SCOPE_STATEMENT
	plays IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;

GoCallExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION;

GoExprStmtArtifact sub GoSourceArtifact;

GoFieldListArtifact sub GoSourceArtifact;

GoFileArtifact sub FileArtifact;

GoForStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_FOR_STATEMENT;

GoFuncDeclArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECLARATION_FUNCTION;

GoFuncTypeArtifact sub GoSourceArtifact
	# Semantic
	plays IS_EXPRESSION_FUNCTION_TYPE;

GoGenDeclArtifact sub GoSourceArtifact;

GoIdentArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME
	plays IS_EXPRESSION_IDENTIFIER;

GoImportSpecArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECLARATION_IMPORT;

GoIncDecStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE;

GoOperatorArtifact sub OperatorArtifact
	# Semantic
	plays IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_DECREMENT_EXPRESSION_OPERATOR_UNARY;

GoPositionArtifact sub GoSourceArtifact;

GoSelectorExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_CALLEE_EXPRESSION_INCOMPLETE;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaArrayTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_LIST_PRIMITIVE_TYPE;

JavaBlockArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BLOCK_BODY_FOR_SCOPE_STATEMENT
	plays IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;

JavaCompilationUnitArtifact sub JavaSourceArtifact;

JavaDimensionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_INCOMPLETE_TYPE;

JavaExpressionStatementArtifact sub ExpressionStatementArtifact;

JavaForStatementArtifact sub ForStatementArtifact
	# Semantic
	plays IS_FOR_STATEMENT;

JavaInfixExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavaMethodDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_FUNCTION_VISIBILITY_WORLD;

JavaMethodInvocationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION;

JavaModifierArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_VISIBILITY_WORLD;

JavaNumberLiteralArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT
	plays IS_EXPRESSION_LITERAL_NUMBER;

JavaOperatorArtifact sub OperatorArtifact
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavaPostfixExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;

JavaPrimitiveTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_NUMBER_PRIMITIVE_TYPE
	plays IS_PRIMITIVE_TYPE;

JavaQualifiedNameArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER;

JavaSimpleNameArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL
	plays IS_ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME
	plays IS_EXPRESSION_IDENTIFIER;

JavaSimpleTypeArtifact sub JavaSourceArtifact;

JavaSingleVariableDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARGUMENT_DECLARATION_FUNCTION_VARIABLE;

JavaTypeDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_TYPE_VISIBILITY_WORLD;

JavaVariableDeclarationExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE;

JavaVariableDeclarationFragmentArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_VARIABLE;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptBinaryExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavascriptBlockStatementArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BLOCK_SCOPE_STATEMENT;

JavascriptCallExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION;

JavascriptExpressionStatementArtifact sub ExpressionStatementArtifact;

JavascriptFileArtifact sub FileArtifact;

JavascriptForStatementArtifact sub ForStatementArtifact
	# Semantic
	plays IS_FOR_STATEMENT;

JavascriptIdentifierArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT
	plays IS_EXPRESSION_IDENTIFIER;

JavascriptMemberExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED;

JavascriptNumericLiteralArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT
	plays IS_EXPRESSION_INITIALIZATION_LITERAL_NUMBER;

JavascriptOperatorArtifact sub OperatorArtifact
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

JavascriptProgramArtifact sub JavascriptSourceArtifact;

JavascriptUpdateExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;

JavascriptVariableDeclarationArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE;

JavascriptVariableDeclaratorArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_DECLARATION_VARIABLE;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonCallArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION_FOR_FUNCTION;

PythonForArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_FOR_ITERATOR_STATEMENT;

PythonForBodyArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_BODY_FOR_THEN;

PythonForOrelseArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_BODY_ELSE_FOR;

PythonModuleArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_FILE_MODULE;

PythonNameArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER
	plays IS_EXPRESSION_FOR_IDENTIFIER_UPDATE;

PythonNumArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE;

PythonPrintArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER;

##########---------- Semantic Roles ----------##########
ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL sub relationship
	relates IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL;
IS_ARGUMENT_EXPRESSION_IDENTIFIER_POSITIONAL sub role;

ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR sub relationship
	relates IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR;
IS_ASSIGNMENT_BINARY_DECLARATION_EXPRESSION_OPERATOR sub role;

ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT sub relationship
	relates IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT;
IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT sub role;

ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT sub relationship
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT;
IS_ASSIGNMENT_BINARY_EXPRESSION_IDENTIFIER_LEFT sub role;

ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relationship
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;
IS_ASSIGNMENT_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub role;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL sub relationship
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL;
IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_EXPRESSION_IDENTIFIER_LEFT sub relationship
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT;
IS_BINARY_EXPRESSION_IDENTIFIER_LEFT sub role;

BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relationship
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;
IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub role;

BLOCK_BODY_FOR_SCOPE_STATEMENT sub relationship
	relates IS_BLOCK_BODY_FOR_SCOPE_STATEMENT;
IS_BLOCK_BODY_FOR_SCOPE_STATEMENT sub role;

BLOCK_BODY_FUNCTION_SCOPE_STATEMENT sub relationship
	relates IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;
IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT sub role;

CALL_EXPRESSION sub relationship
	relates IS_CALL_EXPRESSION;
IS_CALL_EXPRESSION sub role;

CALLEE_EXPRESSION_INCOMPLETE sub relationship
	relates IS_CALLEE_EXPRESSION_INCOMPLETE;
IS_CALLEE_EXPRESSION_INCOMPLETE sub role;

DECLARATION_FUNCTION sub relationship
	relates IS_DECLARATION_FUNCTION;
IS_DECLARATION_FUNCTION sub role;

DECLARATION_IMPORT sub relationship
	relates IS_DECLARATION_IMPORT;
IS_DECLARATION_IMPORT sub role;

DECREMENT_EXPRESSION_OPERATOR_UNARY sub relationship
	relates IS_DECREMENT_EXPRESSION_OPERATOR_UNARY;
IS_DECREMENT_EXPRESSION_OPERATOR_UNARY sub role;

DECREMENT_FOR_STATEMENT_UNARY_UPDATE sub relationship
	relates IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE;
IS_DECREMENT_FOR_STATEMENT_UNARY_UPDATE sub role;

EXPRESSION_FUNCTION_IDENTIFIER_NAME sub relationship
	relates IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME;
IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME sub role;

EXPRESSION_FUNCTION_TYPE sub relationship
	relates IS_EXPRESSION_FUNCTION_TYPE;
IS_EXPRESSION_FUNCTION_TYPE sub role;

EXPRESSION_IDENTIFIER sub relationship
	relates IS_EXPRESSION_IDENTIFIER;
IS_EXPRESSION_IDENTIFIER sub role;

EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING sub relationship
	relates IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING;
IS_EXPRESSION_IMPORT_LITERAL_PATHNAME_PRIMITIVE_STRING sub role;

FOR_STATEMENT sub relationship
	relates IS_FOR_STATEMENT;
IS_FOR_STATEMENT sub role;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL sub relationship
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL;
IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL sub role;

ARGUMENT_DECLARATION_FUNCTION_VARIABLE sub relationship
	relates IS_ARGUMENT_DECLARATION_FUNCTION_VARIABLE;
IS_ARGUMENT_DECLARATION_FUNCTION_VARIABLE sub role;

ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME sub relationship
	relates IS_ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME;
IS_ARGUMENT_EXPRESSION_FUNCTION_IDENTIFIER_NAME sub role;

ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE sub relationship
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;
IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE sub role;

ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY sub relationship
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY;
IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_POSTFIX_UNARY sub role;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_EXPRESSION_IDENTIFIER_LEFT sub relationship
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT;
IS_BINARY_EXPRESSION_IDENTIFIER_LEFT sub role;

BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT sub relationship
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT;
IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT sub role;

BLOCK_BODY_FOR_SCOPE_STATEMENT sub relationship
	relates IS_BLOCK_BODY_FOR_SCOPE_STATEMENT;
IS_BLOCK_BODY_FOR_SCOPE_STATEMENT sub role;

BLOCK_BODY_FUNCTION_SCOPE_STATEMENT sub relationship
	relates IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT;
IS_BLOCK_BODY_FUNCTION_SCOPE_STATEMENT sub role;

CALL_CALLEE_EXPRESSION_IDENTIFIER sub relationship
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER;
IS_CALL_CALLEE_EXPRESSION_IDENTIFIER sub role;

CALL_EXPRESSION sub relationship
	relates IS_CALL_EXPRESSION;
IS_CALL_EXPRESSION sub role;

CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER sub relationship
	relates IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER;
IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER sub role;

DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE sub relationship
	relates IS_DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE;
IS_DECLARATION_EXPRESSION_FOR_INITIALIZATION_VARIABLE sub role;

DECLARATION_FUNCTION_VISIBILITY_WORLD sub relationship
	relates IS_DECLARATION_FUNCTION_VISIBILITY_WORLD;
IS_DECLARATION_FUNCTION_VISIBILITY_WORLD sub role;

DECLARATION_TYPE_VISIBILITY_WORLD sub relationship
	relates IS_DECLARATION_TYPE_VISIBILITY_WORLD;
IS_DECLARATION_TYPE_VISIBILITY_WORLD sub role;

DECLARATION_VARIABLE sub relationship
	relates IS_DECLARATION_VARIABLE;
IS_DECLARATION_VARIABLE sub role;

EXPRESSION_FUNCTION_IDENTIFIER_NAME sub relationship
	relates IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME;
IS_EXPRESSION_FUNCTION_IDENTIFIER_NAME sub role;

EXPRESSION_IDENTIFIER sub relationship
	relates IS_EXPRESSION_IDENTIFIER;
IS_EXPRESSION_IDENTIFIER sub role;

EXPRESSION_LITERAL_NUMBER sub relationship
	relates IS_EXPRESSION_LITERAL_NUMBER;
IS_EXPRESSION_LITERAL_NUMBER sub role;

FOR_STATEMENT sub relationship
	relates IS_FOR_STATEMENT;
IS_FOR_STATEMENT sub role;

INCOMPLETE_TYPE sub relationship
	relates IS_INCOMPLETE_TYPE;
IS_INCOMPLETE_TYPE sub role;

LIST_PRIMITIVE_TYPE sub relationship
	relates IS_LIST_PRIMITIVE_TYPE;
IS_LIST_PRIMITIVE_TYPE sub role;

NUMBER_PRIMITIVE_TYPE sub relationship
	relates IS_NUMBER_PRIMITIVE_TYPE;
IS_NUMBER_PRIMITIVE_TYPE sub role;

PRIMITIVE_TYPE sub relationship
	relates IS_PRIMITIVE_TYPE;
IS_PRIMITIVE_TYPE sub role;

VISIBILITY_WORLD sub relationship
	relates IS_VISIBILITY_WORLD;
IS_VISIBILITY_WORLD sub role;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER sub relationship
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER;
IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER sub role;

ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE sub relationship
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE;
IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE sub role;

ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY sub relationship
	relates IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY;
IS_ARITHMETIC_DECREMENT_EXPRESSION_OPERATOR_UNARY sub role;

BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_EXPRESSION_IDENTIFIER_LEFT sub relationship
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT;
IS_BINARY_EXPRESSION_IDENTIFIER_LEFT sub role;

BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT sub relationship
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT;
IS_BINARY_EXPRESSION_LITERAL_NUMBER_RIGHT sub role;

BLOCK_SCOPE_STATEMENT sub relationship
	relates IS_BLOCK_SCOPE_STATEMENT;
IS_BLOCK_SCOPE_STATEMENT sub role;

CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED sub relationship
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED;
IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED sub role;

CALL_EXPRESSION sub relationship
	relates IS_CALL_EXPRESSION;
IS_CALL_EXPRESSION sub role;

DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE sub relationship
	relates IS_DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE;
IS_DECLARATION_FOR_INITIALIZATION_STATEMENT_VARIABLE sub role;

DECLARATION_VARIABLE sub relationship
	relates IS_DECLARATION_VARIABLE;
IS_DECLARATION_VARIABLE sub role;

EXPRESSION_IDENTIFIER sub relationship
	relates IS_EXPRESSION_IDENTIFIER;
IS_EXPRESSION_IDENTIFIER sub role;

EXPRESSION_INITIALIZATION_LITERAL_NUMBER sub relationship
	relates IS_EXPRESSION_INITIALIZATION_LITERAL_NUMBER;
IS_EXPRESSION_INITIALIZATION_LITERAL_NUMBER sub role;

FOR_STATEMENT sub relationship
	relates IS_FOR_STATEMENT;
IS_FOR_STATEMENT sub role;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE sub relationship
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE;
IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE sub role;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL sub relationship
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL;
IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL sub role;

BODY_ELSE_FOR sub relationship
	relates IS_BODY_ELSE_FOR;
IS_BODY_ELSE_FOR sub role;

BODY_FOR_THEN sub relationship
	relates IS_BODY_FOR_THEN;
IS_BODY_FOR_THEN sub role;

CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER sub relationship
	relates IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER;
IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER sub role;

CALL_CALLEE_EXPRESSION_IDENTIFIER sub relationship
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER;
IS_CALL_CALLEE_EXPRESSION_IDENTIFIER sub role;

CALL_EXPRESSION_FOR_FUNCTION sub relationship
	relates IS_CALL_EXPRESSION_FOR_FUNCTION;
IS_CALL_EXPRESSION_FOR_FUNCTION sub role;

EXPRESSION_FOR_IDENTIFIER_UPDATE sub relationship
	relates IS_EXPRESSION_FOR_IDENTIFIER_UPDATE;
IS_EXPRESSION_FOR_IDENTIFIER_UPDATE sub role;

FILE_MODULE sub relationship
	relates IS_FILE_MODULE;
IS_FILE_MODULE sub role;

FOR_ITERATOR_STATEMENT sub relationship
	relates IS_FOR_ITERATOR_STATEMENT;
IS_FOR_ITERATOR_STATEMENT sub role;
