define

##########---------- Attributes ----------##########
booleanValue sub attribute, datatype boolean;
doubleValue sub attribute, datatype double;
name sub attribute, datatype string;
numberValue sub attribute, datatype long;
token sub attribute, datatype string;

#####----- Omnilingual -----#####
kindAttribute sub attribute, datatype string;

#####----- Go -----#####
goColAttribute sub attribute, datatype string;
goKindAttribute sub kindAttribute, datatype string;
goLineAttribute sub attribute, datatype string;
goOffsetAttribute sub attribute, datatype string;
goTokAttribute sub attribute, datatype string;

#####----- Java -----#####
javaConstructorAttribute sub attribute, datatype string;
javaInterfaceAttribute sub attribute, datatype string;
javaVarargsAttribute sub attribute, datatype string;

#####----- Javascript -----#####
javascriptAsyncAttribute sub attribute, datatype string;
javascriptComputedAttribute sub attribute, datatype string;
javascriptGeneratorAttribute sub attribute, datatype string;
javascriptKindAttribute sub kindAttribute, datatype string;
javascriptPrefixAttribute sub attribute, datatype string;
javascriptSourceTypeAttribute sub attribute, datatype string;

#####----- Php -----#####
phpByRefAttribute sub attribute, datatype string;

#####----- Python -----#####
pythonCtxAttribute sub attribute, datatype string;
pythonNlAttribute sub attribute, datatype string;

#####----- Ruby -----#####
rubySelectorAttribute sub attribute, datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	has token,
	plays is_child,
	plays is_parent;

#####----- Omnilingual -----#####
OmnilingualSourceArtifact sub SourceArtifact;

ExpressionStatementArtifact sub OmnilingualSourceArtifact;

FileArtifact sub OmnilingualSourceArtifact;

ForArtifact sub OmnilingualSourceArtifact;

ForStatementArtifact sub OmnilingualSourceArtifact;

IdentifierArtifact sub OmnilingualSourceArtifact;

ModuleArtifact sub OmnilingualSourceArtifact;

NameArtifact sub OmnilingualSourceArtifact;

OperatorArtifact sub OmnilingualSourceArtifact;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoAssignStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_init_role,
	plays has_go_lhs_role,
	plays has_go_op_role,
	plays has_go_rhs_role,
	plays has_go_tok_pos_role;

GoBasicLitArtifact sub GoSourceArtifact,
	# Attributes
	has doubleValue,
	has goKindAttribute,
	has numberValue,
	# Structural
	plays is_go_path_role,
	plays is_go_rhs_role,
	plays is_go_y_role,
	plays has_go_value_pos_role;

GoBinaryExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_cond_role,
	plays has_go_op_pos_role,
	plays has_go_op_role,
	plays has_go_x_role,
	plays has_go_y_role;

GoBlockStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_body_role,
	plays has_go_lbrace_role,
	plays has_go_list_role,
	plays has_go_rbrace_role;

GoCallExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_x_role,
	plays has_go_args_role,
	plays has_go_ellipsis_role,
	plays has_go_fun_role,
	plays has_go_lparen_role,
	plays has_go_rparen_role;

GoExprStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_list_role,
	plays has_go_x_role;

GoFieldListArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_params_role,
	plays has_go_closing_role,
	plays has_go_opening_role;

GoFileArtifact sub FileArtifact,
	# Structural
	plays has_go_decls_role,
	plays has_go_imports_role,
	plays has_go_name_role,
	plays has_go_package_role;

GoForStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_list_role,
	plays has_go_body_role,
	plays has_go_cond_role,
	plays has_go_for_role,
	plays has_go_init_role,
	plays has_go_post_role;

GoFuncDeclArtifact sub GoSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_go_decls_role,
	plays has_go_body_role,
	plays has_go_name_role,
	plays has_go_type_role;

GoFuncTypeArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_type_role,
	plays has_go_func_role,
	plays has_go_params_role;

GoGenDeclArtifact sub GoSourceArtifact,
	# Attributes
	has goTokAttribute,
	# Structural
	plays is_go_decls_role,
	plays has_go_lparen_role,
	plays has_go_rparen_role,
	plays has_go_specs_role,
	plays has_go_tok_pos_role;

GoIdentArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_args_role,
	plays is_go_lhs_role,
	plays is_go_name_role,
	plays is_go_sel_role,
	plays is_go_x_role,
	plays has_go_name_pos_role;

GoImportSpecArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_imports_role,
	plays is_go_specs_role,
	plays has_go_end_pos_role,
	plays has_go_path_role;

GoIncDecStmtArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_post_role,
	plays has_go_op_role,
	plays has_go_tok_pos_role,
	plays has_go_x_role;

GoOperatorArtifact sub OperatorArtifact,
	# Structural
	plays is_go_op_role;

GoPositionArtifact sub GoSourceArtifact,
	# Attributes
	has goColAttribute,
	has goLineAttribute,
	has goOffsetAttribute,
	# Structural
	plays is_go_closing_role,
	plays is_go_ellipsis_role,
	plays is_go_end_pos_role,
	plays is_go_for_role,
	plays is_go_func_role,
	plays is_go_lbrace_role,
	plays is_go_lparen_role,
	plays is_go_name_pos_role,
	plays is_go_op_pos_role,
	plays is_go_opening_role,
	plays is_go_package_role,
	plays is_go_rbrace_role,
	plays is_go_rparen_role,
	plays is_go_tok_pos_role,
	plays is_go_value_pos_role;

GoSelectorExprArtifact sub GoSourceArtifact,
	# Structural
	plays is_go_fun_role,
	plays has_go_sel_role,
	plays has_go_x_role;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaArrayTypeArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_type_role,
	plays has_java_dimensions_role,
	plays has_java_element_type_role;

JavaBlockArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_body_role,
	plays has_java_statements_role;

JavaCompilationUnitArtifact sub JavaSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays has_java_types_role;

JavaDimensionArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_dimensions_role;

JavaExpressionStatementArtifact sub ExpressionStatementArtifact,
	# Structural
	plays is_java_statements_role,
	plays has_java_expression_role;

JavaForStatementArtifact sub ForStatementArtifact,
	# Structural
	plays is_java_statements_role,
	plays has_java_body_role,
	plays has_java_expression_role,
	plays has_java_initializers_role,
	plays has_java_updaters_role;

JavaInfixExpressionArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_expression_role,
	plays has_java_left_operand_role,
	plays has_java_operator_role,
	plays has_java_right_operand_role;

JavaMethodDeclarationArtifact sub JavaSourceArtifact,
	# Attributes
	has javaConstructorAttribute,
	has name,
	# Structural
	plays is_java_body_declarations_role,
	plays has_java_body_role,
	plays has_java_modifiers_role,
	plays has_java_name_role,
	plays has_java_parameters_role,
	plays has_java_return_type2_role;

JavaMethodInvocationArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_expression_role,
	plays has_java_arguments_role,
	plays has_java_expression_role,
	plays has_java_name_role;

JavaModifierArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_modifiers_role;

JavaNumberLiteralArtifact sub JavaSourceArtifact,
	# Attributes
	has doubleValue,
	has numberValue,
	# Structural
	plays is_java_initializer_role,
	plays is_java_right_operand_role;

JavaOperatorArtifact sub OperatorArtifact,
	# Structural
	plays is_java_operator_role;

JavaPostfixExpressionArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_updaters_role,
	plays has_java_operand_role,
	plays has_java_operator_role;

JavaPrimitiveTypeArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_return_type2_role,
	plays is_java_type_role;

JavaQualifiedNameArtifact sub JavaSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_java_expression_role,
	plays has_java_name_role,
	plays has_java_qualifier_role;

JavaSimpleNameArtifact sub JavaSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_java_arguments_role,
	plays is_java_left_operand_role,
	plays is_java_name_role,
	plays is_java_operand_role,
	plays is_java_qualifier_role;

JavaSimpleTypeArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_element_type_role,
	plays has_java_name_role;

JavaSingleVariableDeclarationArtifact sub JavaSourceArtifact,
	# Attributes
	has javaVarargsAttribute,
	# Structural
	plays is_java_parameters_role,
	plays has_java_name_role,
	plays has_java_type_role;

JavaTypeDeclarationArtifact sub JavaSourceArtifact,
	# Attributes
	has javaInterfaceAttribute,
	has name,
	# Structural
	plays is_java_types_role,
	plays has_java_body_declarations_role,
	plays has_java_modifiers_role,
	plays has_java_name_role;

JavaVariableDeclarationExpressionArtifact sub JavaSourceArtifact,
	# Structural
	plays is_java_initializers_role,
	plays has_java_fragments_role,
	plays has_java_type_role;

JavaVariableDeclarationFragmentArtifact sub JavaSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_java_fragments_role,
	plays has_java_initializer_role,
	plays has_java_name_role;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptBinaryExpressionArtifact sub JavascriptSourceArtifact,
	# Structural
	plays is_javascript_test_role,
	plays has_javascript_left_role,
	plays has_javascript_operator_role,
	plays has_javascript_right_role;

JavascriptBlockStatementArtifact sub JavascriptSourceArtifact,
	# Structural
	plays is_javascript_body_role,
	plays has_javascript_body_role;

JavascriptCallExpressionArtifact sub JavascriptSourceArtifact,
	# Structural
	plays is_javascript_expression_role,
	plays has_javascript_arguments_role,
	plays has_javascript_callee_role;

JavascriptExpressionStatementArtifact sub ExpressionStatementArtifact,
	# Structural
	plays is_javascript_body_role,
	plays has_javascript_expression_role;

JavascriptFileArtifact sub FileArtifact,
	# Structural
	plays has_javascript_program_role;

JavascriptForStatementArtifact sub ForStatementArtifact,
	# Structural
	plays is_javascript_body_role,
	plays has_javascript_body_role,
	plays has_javascript_init_role,
	plays has_javascript_test_role,
	plays has_javascript_update_role;

JavascriptFunctionDeclarationArtifact sub JavascriptSourceArtifact,
	# Attributes
	has javascriptAsyncAttribute,
	has javascriptGeneratorAttribute,
	has name,
	# Structural
	plays is_javascript_body_role,
	plays has_javascript_body_role,
	plays has_javascript_id_role;

JavascriptIdentifierArtifact sub IdentifierArtifact,
	# Structural
	plays is_javascript_argument_role,
	plays is_javascript_arguments_role,
	plays is_javascript_id_role,
	plays is_javascript_left_role,
	plays is_javascript_object_role,
	plays is_javascript_property_role;

JavascriptMemberExpressionArtifact sub JavascriptSourceArtifact,
	# Attributes
	has javascriptComputedAttribute,
	# Structural
	plays is_javascript_callee_role,
	plays has_javascript_object_role,
	plays has_javascript_property_role;

JavascriptNumericLiteralArtifact sub JavascriptSourceArtifact,
	# Attributes
	has numberValue,
	# Structural
	plays is_javascript_init_role,
	plays is_javascript_right_role;

JavascriptOperatorArtifact sub OperatorArtifact,
	# Structural
	plays is_javascript_operator_role;

JavascriptProgramArtifact sub JavascriptSourceArtifact,
	# Attributes
	has javascriptSourceTypeAttribute,
	# Structural
	plays is_javascript_program_role,
	plays has_javascript_body_role;

JavascriptUpdateExpressionArtifact sub JavascriptSourceArtifact,
	# Attributes
	has javascriptPrefixAttribute,
	# Structural
	plays is_javascript_update_role,
	plays has_javascript_argument_role,
	plays has_javascript_operator_role;

JavascriptVariableDeclarationArtifact sub JavascriptSourceArtifact,
	# Attributes
	has javascriptKindAttribute,
	# Structural
	plays is_javascript_init_role,
	plays has_javascript_declarations_role;

JavascriptVariableDeclaratorArtifact sub JavascriptSourceArtifact,
	# Structural
	plays is_javascript_declarations_role,
	plays has_javascript_id_role,
	plays has_javascript_init_role;

#####----- Php -----#####
PhpSourceArtifact sub SourceArtifact;

PhpExprAssignArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_init_role,
	plays has_php_expr_role,
	plays has_php_var_role;

PhpExprBinaryOpGreaterOrEqualArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_cond_role,
	plays has_php_left_role,
	plays has_php_right_role;

PhpExprPostDecArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_loop_role,
	plays has_php_var_role;

PhpExprVariableArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_exprs_role,
	plays is_php_left_role,
	plays is_php_var_role,
	plays has_php_name_role;

PhpFunctionBodyArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_stmts_role,
	plays has_php_body_role;

PhpFunctionReturnTypeArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_return_type_role;

PhpModuleArtifact sub ModuleArtifact,
	# Structural
	plays has_php_children_role;

PhpNameArtifact sub NameArtifact,
	# Structural
	plays is_php_name_role;

PhpScalarLNumberArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_expr_role,
	plays is_php_right_role;

PhpStmtEchoArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_stmts_role,
	plays has_php_exprs_role;

PhpStmtForArtifact sub PhpSourceArtifact,
	# Structural
	plays is_php_body_role,
	plays has_php_cond_role,
	plays has_php_init_role,
	plays has_php_loop_role,
	plays has_php_stmts_role;

PhpStmtFunctionArtifact sub PhpSourceArtifact,
	# Attributes
	has phpByRefAttribute,
	has name,
	# Structural
	plays is_php_children_role,
	plays has_php_name_role,
	plays has_php_return_type_role,
	plays has_php_stmts_role;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonArgumentsArtifact sub PythonSourceArtifact,
	# Structural
	plays is_python_args_role;

PythonCallArtifact sub PythonSourceArtifact,
	# Structural
	plays is_python_iter_role,
	plays has_python_args_role,
	plays has_python_func_role;

PythonForArtifact sub ForArtifact,
	# Structural
	plays is_python_body_stmts_role,
	plays has_python_body_role,
	plays has_python_iter_role,
	plays has_python_orelse_role,
	plays has_python_target_role;

PythonForBodyArtifact sub PythonSourceArtifact,
	# Structural
	plays is_python_body_role,
	plays has_python_body_stmts_role;

PythonForOrelseArtifact sub PythonSourceArtifact,
	# Structural
	plays is_python_orelse_role;

PythonFunctionDefArtifact sub PythonSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_python_body_role,
	plays has_python_args_role,
	plays has_python_body_role,
	plays has_python_decorator_list_role;

PythonFunctionDefBodyArtifact sub PythonSourceArtifact,
	# Structural
	plays is_python_body_role,
	plays has_python_body_stmts_role;

PythonFunctionDefDecoratorsArtifact sub PythonSourceArtifact,
	# Structural
	plays is_python_decorator_list_role;

PythonModuleArtifact sub ModuleArtifact,
	# Structural
	plays has_python_body_role;

PythonNameArtifact sub NameArtifact,
	# Attributes
	has pythonCtxAttribute,
	# Structural
	plays is_python_func_role,
	plays is_python_target_role,
	plays is_python_values_role;

PythonNumArtifact sub PythonSourceArtifact,
	# Attributes
	has numberValue,
	# Structural
	plays is_python_args_role;

PythonPrintArtifact sub PythonSourceArtifact,
	# Attributes
	has pythonNlAttribute,
	# Structural
	plays is_python_body_stmts_role,
	plays has_python_values_role;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

RubyArgsArtifact sub RubySourceArtifact,
	# Structural
	plays is_ruby_args_role;

RubyBeginArtifact sub RubySourceArtifact,
	# Structural
	plays is_ruby_base_role,
	plays has_ruby_body_role;

RubyDefArtifact sub RubySourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_ruby_file_role,
	plays has_ruby_args_role,
	plays has_ruby_body_role;

RubyForArtifact sub ForArtifact,
	# Structural
	plays is_ruby_body_role,
	plays has_ruby_body_role,
	plays has_ruby_iterated_role,
	plays has_ruby_iterators_role;

RubyIdentifierArtifact sub IdentifierArtifact,
	# Attributes
	has name,
	# Structural
	plays is_ruby_qnames_role;

RubyIntArtifact sub RubySourceArtifact,
	# Structural
	plays is_ruby_body_role,
	plays is_ruby_values_role;

RubyLvarArtifact sub RubySourceArtifact,
	# Structural
	plays is_ruby_values_role;

RubyLvasgnArtifact sub RubySourceArtifact,
	# Structural
	plays is_ruby_iterators_role;

RubyModuleArtifact sub ModuleArtifact,
	# Structural
	plays has_ruby_file_role;

RubySendCallArtifact sub RubySourceArtifact,
	# Structural
	plays is_ruby_iterated_role,
	plays has_ruby_base_role,
	plays has_ruby_values_role;

RubySendQualifiedArtifact sub RubySourceArtifact,
	# Attributes
	has rubySelectorAttribute,
	# Structural
	plays is_ruby_body_role,
	plays has_ruby_qnames_role,
	plays has_ruby_values_role;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Omnilingual -----#####
args_relation sub parent_child_relation,
	relates is_args_role as is_child, relates has_args_role as is_parent;

arguments_relation sub parent_child_relation,
	relates is_arguments_role as is_child, relates has_arguments_role as is_parent;

body_relation sub parent_child_relation,
	relates is_body_role as is_child, relates has_body_role as is_parent;

cond_relation sub parent_child_relation,
	relates is_cond_role as is_child, relates has_cond_role as is_parent;

expression_relation sub parent_child_relation,
	relates is_expression_role as is_child, relates has_expression_role as is_parent;

func_relation sub parent_child_relation,
	relates is_func_role as is_child, relates has_func_role as is_parent;

init_relation sub parent_child_relation,
	relates is_init_role as is_child, relates has_init_role as is_parent;

left_relation sub parent_child_relation,
	relates is_left_role as is_child, relates has_left_role as is_parent;

name_relation sub parent_child_relation,
	relates is_name_role as is_child, relates has_name_role as is_parent;

operator_relation sub parent_child_relation,
	relates is_operator_role as is_child, relates has_operator_role as is_parent;

right_relation sub parent_child_relation,
	relates is_right_role as is_child, relates has_right_role as is_parent;

type_relation sub parent_child_relation,
	relates is_type_role as is_child, relates has_type_role as is_parent;

values_relation sub parent_child_relation,
	relates is_values_role as is_child, relates has_values_role as is_parent;

#####----- Go -----#####
go_args_relation sub args_relation,
	relates is_go_args_role as is_args_role, relates has_go_args_role as has_args_role;

go_body_relation sub body_relation,
	relates is_go_body_role as is_body_role, relates has_go_body_role as has_body_role;

go_closing_relation sub parent_child_relation,
	relates is_go_closing_role as is_child, relates has_go_closing_role as is_parent;

go_cond_relation sub cond_relation,
	relates is_go_cond_role as is_cond_role, relates has_go_cond_role as has_cond_role;

go_decls_relation sub parent_child_relation,
	relates is_go_decls_role as is_child, relates has_go_decls_role as is_parent;

go_ellipsis_relation sub parent_child_relation,
	relates is_go_ellipsis_role as is_child, relates has_go_ellipsis_role as is_parent;

go_end_pos_relation sub parent_child_relation,
	relates is_go_end_pos_role as is_child, relates has_go_end_pos_role as is_parent;

go_for_relation sub parent_child_relation,
	relates is_go_for_role as is_child, relates has_go_for_role as is_parent;

go_fun_relation sub parent_child_relation,
	relates is_go_fun_role as is_child, relates has_go_fun_role as is_parent;

go_func_relation sub func_relation,
	relates is_go_func_role as is_func_role, relates has_go_func_role as has_func_role;

go_imports_relation sub parent_child_relation,
	relates is_go_imports_role as is_child, relates has_go_imports_role as is_parent;

go_init_relation sub init_relation,
	relates is_go_init_role as is_init_role, relates has_go_init_role as has_init_role;

go_lbrace_relation sub parent_child_relation,
	relates is_go_lbrace_role as is_child, relates has_go_lbrace_role as is_parent;

go_lhs_relation sub parent_child_relation,
	relates is_go_lhs_role as is_child, relates has_go_lhs_role as is_parent;

go_list_relation sub parent_child_relation,
	relates is_go_list_role as is_child, relates has_go_list_role as is_parent;

go_lparen_relation sub parent_child_relation,
	relates is_go_lparen_role as is_child, relates has_go_lparen_role as is_parent;

go_name_pos_relation sub parent_child_relation,
	relates is_go_name_pos_role as is_child, relates has_go_name_pos_role as is_parent;

go_name_relation sub name_relation,
	relates is_go_name_role as is_name_role, relates has_go_name_role as has_name_role;

go_op_pos_relation sub parent_child_relation,
	relates is_go_op_pos_role as is_child, relates has_go_op_pos_role as is_parent;

go_op_relation sub parent_child_relation,
	relates is_go_op_role as is_child, relates has_go_op_role as is_parent;

go_opening_relation sub parent_child_relation,
	relates is_go_opening_role as is_child, relates has_go_opening_role as is_parent;

go_package_relation sub parent_child_relation,
	relates is_go_package_role as is_child, relates has_go_package_role as is_parent;

go_params_relation sub parent_child_relation,
	relates is_go_params_role as is_child, relates has_go_params_role as is_parent;

go_path_relation sub parent_child_relation,
	relates is_go_path_role as is_child, relates has_go_path_role as is_parent;

go_post_relation sub parent_child_relation,
	relates is_go_post_role as is_child, relates has_go_post_role as is_parent;

go_rbrace_relation sub parent_child_relation,
	relates is_go_rbrace_role as is_child, relates has_go_rbrace_role as is_parent;

go_rhs_relation sub parent_child_relation,
	relates is_go_rhs_role as is_child, relates has_go_rhs_role as is_parent;

go_rparen_relation sub parent_child_relation,
	relates is_go_rparen_role as is_child, relates has_go_rparen_role as is_parent;

go_sel_relation sub parent_child_relation,
	relates is_go_sel_role as is_child, relates has_go_sel_role as is_parent;

go_specs_relation sub parent_child_relation,
	relates is_go_specs_role as is_child, relates has_go_specs_role as is_parent;

go_tok_pos_relation sub parent_child_relation,
	relates is_go_tok_pos_role as is_child, relates has_go_tok_pos_role as is_parent;

go_type_relation sub type_relation,
	relates is_go_type_role as is_type_role, relates has_go_type_role as has_type_role;

go_value_pos_relation sub parent_child_relation,
	relates is_go_value_pos_role as is_child, relates has_go_value_pos_role as is_parent;

go_x_relation sub parent_child_relation,
	relates is_go_x_role as is_child, relates has_go_x_role as is_parent;

go_y_relation sub parent_child_relation,
	relates is_go_y_role as is_child, relates has_go_y_role as is_parent;

#####----- Java -----#####
java_arguments_relation sub arguments_relation,
	relates is_java_arguments_role as is_arguments_role, relates has_java_arguments_role as has_arguments_role;

java_body_declarations_relation sub parent_child_relation,
	relates is_java_body_declarations_role as is_child, relates has_java_body_declarations_role as is_parent;

java_body_relation sub body_relation,
	relates is_java_body_role as is_body_role, relates has_java_body_role as has_body_role;

java_dimensions_relation sub parent_child_relation,
	relates is_java_dimensions_role as is_child, relates has_java_dimensions_role as is_parent;

java_element_type_relation sub parent_child_relation,
	relates is_java_element_type_role as is_child, relates has_java_element_type_role as is_parent;

java_expression_relation sub expression_relation,
	relates is_java_expression_role as is_expression_role, relates has_java_expression_role as has_expression_role;

java_fragments_relation sub parent_child_relation,
	relates is_java_fragments_role as is_child, relates has_java_fragments_role as is_parent;

java_initializer_relation sub parent_child_relation,
	relates is_java_initializer_role as is_child, relates has_java_initializer_role as is_parent;

java_initializers_relation sub parent_child_relation,
	relates is_java_initializers_role as is_child, relates has_java_initializers_role as is_parent;

java_left_operand_relation sub parent_child_relation,
	relates is_java_left_operand_role as is_child, relates has_java_left_operand_role as is_parent;

java_modifiers_relation sub parent_child_relation,
	relates is_java_modifiers_role as is_child, relates has_java_modifiers_role as is_parent;

java_name_relation sub name_relation,
	relates is_java_name_role as is_name_role, relates has_java_name_role as has_name_role;

java_operand_relation sub parent_child_relation,
	relates is_java_operand_role as is_child, relates has_java_operand_role as is_parent;

java_operator_relation sub operator_relation,
	relates is_java_operator_role as is_operator_role, relates has_java_operator_role as has_operator_role;

java_parameters_relation sub parent_child_relation,
	relates is_java_parameters_role as is_child, relates has_java_parameters_role as is_parent;

java_qualifier_relation sub parent_child_relation,
	relates is_java_qualifier_role as is_child, relates has_java_qualifier_role as is_parent;

java_return_type2_relation sub parent_child_relation,
	relates is_java_return_type2_role as is_child, relates has_java_return_type2_role as is_parent;

java_right_operand_relation sub parent_child_relation,
	relates is_java_right_operand_role as is_child, relates has_java_right_operand_role as is_parent;

java_statements_relation sub parent_child_relation,
	relates is_java_statements_role as is_child, relates has_java_statements_role as is_parent;

java_type_relation sub type_relation,
	relates is_java_type_role as is_type_role, relates has_java_type_role as has_type_role;

java_types_relation sub parent_child_relation,
	relates is_java_types_role as is_child, relates has_java_types_role as is_parent;

java_updaters_relation sub parent_child_relation,
	relates is_java_updaters_role as is_child, relates has_java_updaters_role as is_parent;

#####----- Javascript -----#####
javascript_argument_relation sub parent_child_relation,
	relates is_javascript_argument_role as is_child, relates has_javascript_argument_role as is_parent;

javascript_arguments_relation sub arguments_relation,
	relates is_javascript_arguments_role as is_arguments_role, relates has_javascript_arguments_role as has_arguments_role;

javascript_body_relation sub body_relation,
	relates is_javascript_body_role as is_body_role, relates has_javascript_body_role as has_body_role;

javascript_callee_relation sub parent_child_relation,
	relates is_javascript_callee_role as is_child, relates has_javascript_callee_role as is_parent;

javascript_declarations_relation sub parent_child_relation,
	relates is_javascript_declarations_role as is_child, relates has_javascript_declarations_role as is_parent;

javascript_expression_relation sub expression_relation,
	relates is_javascript_expression_role as is_expression_role, relates has_javascript_expression_role as has_expression_role;

javascript_id_relation sub parent_child_relation,
	relates is_javascript_id_role as is_child, relates has_javascript_id_role as is_parent;

javascript_init_relation sub init_relation,
	relates is_javascript_init_role as is_init_role, relates has_javascript_init_role as has_init_role;

javascript_left_relation sub left_relation,
	relates is_javascript_left_role as is_left_role, relates has_javascript_left_role as has_left_role;

javascript_object_relation sub parent_child_relation,
	relates is_javascript_object_role as is_child, relates has_javascript_object_role as is_parent;

javascript_operator_relation sub operator_relation,
	relates is_javascript_operator_role as is_operator_role, relates has_javascript_operator_role as has_operator_role;

javascript_program_relation sub parent_child_relation,
	relates is_javascript_program_role as is_child, relates has_javascript_program_role as is_parent;

javascript_property_relation sub parent_child_relation,
	relates is_javascript_property_role as is_child, relates has_javascript_property_role as is_parent;

javascript_right_relation sub right_relation,
	relates is_javascript_right_role as is_right_role, relates has_javascript_right_role as has_right_role;

javascript_test_relation sub parent_child_relation,
	relates is_javascript_test_role as is_child, relates has_javascript_test_role as is_parent;

javascript_update_relation sub parent_child_relation,
	relates is_javascript_update_role as is_child, relates has_javascript_update_role as is_parent;

#####----- Php -----#####
php_body_relation sub body_relation,
	relates is_php_body_role as is_body_role, relates has_php_body_role as has_body_role;

php_children_relation sub parent_child_relation,
	relates is_php_children_role as is_child, relates has_php_children_role as is_parent;

php_cond_relation sub cond_relation,
	relates is_php_cond_role as is_cond_role, relates has_php_cond_role as has_cond_role;

php_expr_relation sub parent_child_relation,
	relates is_php_expr_role as is_child, relates has_php_expr_role as is_parent;

php_exprs_relation sub parent_child_relation,
	relates is_php_exprs_role as is_child, relates has_php_exprs_role as is_parent;

php_init_relation sub init_relation,
	relates is_php_init_role as is_init_role, relates has_php_init_role as has_init_role;

php_left_relation sub left_relation,
	relates is_php_left_role as is_left_role, relates has_php_left_role as has_left_role;

php_loop_relation sub parent_child_relation,
	relates is_php_loop_role as is_child, relates has_php_loop_role as is_parent;

php_name_relation sub name_relation,
	relates is_php_name_role as is_name_role, relates has_php_name_role as has_name_role;

php_return_type_relation sub parent_child_relation,
	relates is_php_return_type_role as is_child, relates has_php_return_type_role as is_parent;

php_right_relation sub right_relation,
	relates is_php_right_role as is_right_role, relates has_php_right_role as has_right_role;

php_stmts_relation sub parent_child_relation,
	relates is_php_stmts_role as is_child, relates has_php_stmts_role as is_parent;

php_var_relation sub parent_child_relation,
	relates is_php_var_role as is_child, relates has_php_var_role as is_parent;

#####----- Python -----#####
python_args_relation sub args_relation,
	relates is_python_args_role as is_args_role, relates has_python_args_role as has_args_role;

python_body_relation sub body_relation,
	relates is_python_body_role as is_body_role, relates has_python_body_role as has_body_role;

python_body_stmts_relation sub parent_child_relation,
	relates is_python_body_stmts_role as is_child, relates has_python_body_stmts_role as is_parent;

python_decorator_list_relation sub parent_child_relation,
	relates is_python_decorator_list_role as is_child, relates has_python_decorator_list_role as is_parent;

python_func_relation sub func_relation,
	relates is_python_func_role as is_func_role, relates has_python_func_role as has_func_role;

python_iter_relation sub parent_child_relation,
	relates is_python_iter_role as is_child, relates has_python_iter_role as is_parent;

python_orelse_relation sub parent_child_relation,
	relates is_python_orelse_role as is_child, relates has_python_orelse_role as is_parent;

python_target_relation sub parent_child_relation,
	relates is_python_target_role as is_child, relates has_python_target_role as is_parent;

python_values_relation sub values_relation,
	relates is_python_values_role as is_values_role, relates has_python_values_role as has_values_role;

#####----- Ruby -----#####
ruby_args_relation sub args_relation,
	relates is_ruby_args_role as is_args_role, relates has_ruby_args_role as has_args_role;

ruby_base_relation sub parent_child_relation,
	relates is_ruby_base_role as is_child, relates has_ruby_base_role as is_parent;

ruby_body_relation sub body_relation,
	relates is_ruby_body_role as is_body_role, relates has_ruby_body_role as has_body_role;

ruby_file_relation sub parent_child_relation,
	relates is_ruby_file_role as is_child, relates has_ruby_file_role as is_parent;

ruby_iterated_relation sub parent_child_relation,
	relates is_ruby_iterated_role as is_child, relates has_ruby_iterated_role as is_parent;

ruby_iterators_relation sub parent_child_relation,
	relates is_ruby_iterators_role as is_child, relates has_ruby_iterators_role as is_parent;

ruby_qnames_relation sub parent_child_relation,
	relates is_ruby_qnames_role as is_child, relates has_ruby_qnames_role as is_parent;

ruby_values_relation sub values_relation,
	relates is_ruby_values_role as is_values_role, relates has_ruby_values_role as has_values_role;
