define

##########---------- Entities ----------##########

#####----- Omnilingual -----#####
OmnilingualSourceArtifact sub SourceArtifact;

ExpressionStatementArtifact sub OmnilingualSourceArtifact
	# Semantic
	plays IS_STATEMENT;

FileArtifact sub OmnilingualSourceArtifact
	# Semantic
	plays IS_FILE;

ForStatementArtifact sub OmnilingualSourceArtifact
	# Semantic
	plays IS_FOR
	plays IS_STATEMENT;

OperatorArtifact sub OmnilingualSourceArtifact
	# Semantic
	plays IS_ARITHMETIC
	plays IS_BINARY
	plays IS_DECREMENT
	plays IS_EXPRESSION
	plays IS_GREATER_THAN_OR_EQUAL
	plays IS_OPERATOR
	plays IS_RELATIONAL
	plays IS_UNARY;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoAssignStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_DECLARATION
	plays IS_FOR
	plays IS_INITIALIZATION
	plays IS_STATEMENT;

GoBasicLitArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_EXPRESSION
	plays IS_IMPORT
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_PATHNAME
	plays IS_PRIMITIVE
	plays IS_RIGHT
	plays IS_STRING;

GoBinaryExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_CONDITION
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_GREATER_THAN_OR_EQUAL
	plays IS_RELATIONAL;

GoBlockStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_BLOCK
	plays IS_BODY
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_SCOPE
	plays IS_STATEMENT;

GoCallExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_EXPRESSION;

GoExprStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_STATEMENT;

GoFieldListArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ARGS_LIST;

GoFileArtifact sub FileArtifact;

GoForStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_FOR
	plays IS_STATEMENT;

GoFuncDeclArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_FUNCTION;

GoFuncTypeArtifact sub GoSourceArtifact
	# Semantic
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_TYPE;

GoGenDeclArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECLARATION;

GoIdentArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_ASSIGNMENT
	plays IS_BINARY
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_NAME
	plays IS_POSITIONAL;

GoImportSpecArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_IMPORT;

GoIncDecStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECREMENT
	plays IS_FOR
	plays IS_STATEMENT
	plays IS_UNARY
	plays IS_UPDATE;

GoOperatorArtifact sub OperatorArtifact
	# Semantic
	plays IS_ASSIGNMENT
	plays IS_DECLARATION;

GoPositionArtifact sub GoSourceArtifact;

GoSelectorExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_CALLEE
	plays IS_EXPRESSION
	plays IS_INCOMPLETE;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaArrayTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_LIST
	plays IS_PRIMITIVE
	plays IS_TYPE;

JavaBlockArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BLOCK
	plays IS_BODY
	plays IS_FOR
	plays IS_FUNCTION
	plays IS_SCOPE
	plays IS_STATEMENT;

JavaCompilationUnitArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_FILE;

JavaDimensionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_INCOMPLETE
	plays IS_TYPE;

JavaExpressionStatementArtifact sub ExpressionStatementArtifact;

JavaForStatementArtifact sub ForStatementArtifact;

JavaInfixExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_CONDITION
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_GREATER_THAN_OR_EQUAL
	plays IS_OPERATOR
	plays IS_RELATIONAL;

JavaMethodDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_FUNCTION
	plays IS_VISIBILITY
	plays IS_WORLD;

JavaMethodInvocationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_EXPRESSION;

JavaModifierArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_INCOMPLETE
	plays IS_VISIBILITY
	plays IS_WORLD;

JavaNumberLiteralArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_EXPRESSION
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_RIGHT;

JavaOperatorArtifact sub OperatorArtifact
	# Semantic
	plays IS_POSTFIX;

JavaPostfixExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARITHMETIC
	plays IS_DECREMENT
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_OPERATOR
	plays IS_POSTFIX
	plays IS_UNARY
	plays IS_UPDATE;

JavaPrimitiveTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_NUMBER
	plays IS_PRIMITIVE
	plays IS_TYPE;

JavaQualifiedNameArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_QUALIFIED
	plays IS_RECEIVER;

JavaSimpleNameArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_BINARY
	plays IS_CALL
	plays IS_CALLEE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER
	plays IS_LEFT
	plays IS_NAME
	plays IS_POSITIONAL;

JavaSimpleTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_TYPE;

JavaSingleVariableDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_DECLARATION
	plays IS_FUNCTION
	plays IS_VARIABLE;

JavaTypeDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_TYPE
	plays IS_VISIBILITY
	plays IS_WORLD;

JavaVariableDeclarationExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_INITIALIZATION
	plays IS_VARIABLE;

JavaVariableDeclarationFragmentArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_VARIABLE;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptBinaryExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_CONDITION
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_GREATER_THAN_OR_EQUAL
	plays IS_OPERATOR
	plays IS_RELATIONAL;

JavascriptBlockStatementArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BLOCK
	plays IS_SCOPE
	plays IS_STATEMENT;

JavascriptCallExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_EXPRESSION;

JavascriptExpressionStatementArtifact sub ExpressionStatementArtifact;

JavascriptFileArtifact sub FileArtifact;

JavascriptForStatementArtifact sub ForStatementArtifact;

JavascriptIdentifierArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_BINARY
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_LEFT;

JavascriptMemberExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_CALLEE
	plays IS_EXPRESSION
	plays IS_IDENTIFIER
	plays IS_QUALIFIED;

JavascriptNumericLiteralArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BINARY
	plays IS_EXPRESSION
	plays IS_INITIALIZATION
	plays IS_LITERAL
	plays IS_NUMBER
	plays IS_RIGHT;

JavascriptOperatorArtifact sub OperatorArtifact;

JavascriptProgramArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_MODULE;

JavascriptUpdateExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_ARITHMETIC
	plays IS_DECREMENT
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_OPERATOR
	plays IS_POSTFIX
	plays IS_UNARY
	plays IS_UPDATE;

JavascriptVariableDeclarationArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_FOR
	plays IS_INITIALIZATION
	plays IS_STATEMENT
	plays IS_VARIABLE;

JavascriptVariableDeclaratorArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_DECLARATION
	plays IS_VARIABLE;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonCallArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_FUNCTION;

PythonForArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_FOR
	plays IS_ITERATOR
	plays IS_STATEMENT;

PythonForBodyArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_FOR
	plays IS_THEN;

PythonForOrelseArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_BODY
	plays IS_ELSE
	plays IS_FOR;

PythonModuleArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_FILE
	plays IS_MODULE;

PythonNameArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_CALL
	plays IS_CALLEE
	plays IS_EXPRESSION
	plays IS_FOR
	plays IS_IDENTIFIER
	plays IS_POSITIONAL
	plays IS_UPDATE;

PythonNumArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_ARGUMENT
	plays IS_CALL
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_LITERAL
	plays IS_NAME
	plays IS_NUMBER
	plays IS_POSITIONAL
	plays IS_PRIMITIVE;

PythonPrintArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_CALL
	plays IS_CALLEE
	plays IS_EXPRESSION
	plays IS_FUNCTION
	plays IS_IDENTIFIER;

##########---------- Semantic Roles ----------##########
ARGS_LIST sub relationship
	relates IS_ARGS_LIST;
IS_ARGS_LIST sub role;

ARGUMENT sub relationship
	relates IS_ARGUMENT;
IS_ARGUMENT sub role;

ARITHMETIC sub relationship
	relates IS_ARITHMETIC;
IS_ARITHMETIC sub role;

ASSIGNMENT sub relationship
	relates IS_ASSIGNMENT;
IS_ASSIGNMENT sub role;

BINARY sub relationship
	relates IS_BINARY;
IS_BINARY sub role;

BLOCK sub relationship
	relates IS_BLOCK;
IS_BLOCK sub role;

BODY sub relationship
	relates IS_BODY;
IS_BODY sub role;

CALL sub relationship
	relates IS_CALL;
IS_CALL sub role;

CALLEE sub relationship
	relates IS_CALLEE;
IS_CALLEE sub role;

CONDITION sub relationship
	relates IS_CONDITION;
IS_CONDITION sub role;

DECLARATION sub relationship
	relates IS_DECLARATION;
IS_DECLARATION sub role;

DECREMENT sub relationship
	relates IS_DECREMENT;
IS_DECREMENT sub role;

ELSE sub relationship
	relates IS_ELSE;
IS_ELSE sub role;

EXPRESSION sub relationship
	relates IS_EXPRESSION;
IS_EXPRESSION sub role;

FILE sub relationship
	relates IS_FILE;
IS_FILE sub role;

FOR sub relationship
	relates IS_FOR;
IS_FOR sub role;

FUNCTION sub relationship
	relates IS_FUNCTION;
IS_FUNCTION sub role;

GREATER_THAN_OR_EQUAL sub relationship
	relates IS_GREATER_THAN_OR_EQUAL;
IS_GREATER_THAN_OR_EQUAL sub role;

IDENTIFIER sub relationship
	relates IS_IDENTIFIER;
IS_IDENTIFIER sub role;

IMPORT sub relationship
	relates IS_IMPORT;
IS_IMPORT sub role;

INCOMPLETE sub relationship
	relates IS_INCOMPLETE;
IS_INCOMPLETE sub role;

INITIALIZATION sub relationship
	relates IS_INITIALIZATION;
IS_INITIALIZATION sub role;

ITERATOR sub relationship
	relates IS_ITERATOR;
IS_ITERATOR sub role;

LEFT sub relationship
	relates IS_LEFT;
IS_LEFT sub role;

LIST sub relationship
	relates IS_LIST;
IS_LIST sub role;

LITERAL sub relationship
	relates IS_LITERAL;
IS_LITERAL sub role;

MODULE sub relationship
	relates IS_MODULE;
IS_MODULE sub role;

NAME sub relationship
	relates IS_NAME;
IS_NAME sub role;

NUMBER sub relationship
	relates IS_NUMBER;
IS_NUMBER sub role;

OPERATOR sub relationship
	relates IS_OPERATOR;
IS_OPERATOR sub role;

PATHNAME sub relationship
	relates IS_PATHNAME;
IS_PATHNAME sub role;

POSITIONAL sub relationship
	relates IS_POSITIONAL;
IS_POSITIONAL sub role;

POSTFIX sub relationship
	relates IS_POSTFIX;
IS_POSTFIX sub role;

PRIMITIVE sub relationship
	relates IS_PRIMITIVE;
IS_PRIMITIVE sub role;

QUALIFIED sub relationship
	relates IS_QUALIFIED;
IS_QUALIFIED sub role;

RECEIVER sub relationship
	relates IS_RECEIVER;
IS_RECEIVER sub role;

RELATIONAL sub relationship
	relates IS_RELATIONAL;
IS_RELATIONAL sub role;

RIGHT sub relationship
	relates IS_RIGHT;
IS_RIGHT sub role;

SCOPE sub relationship
	relates IS_SCOPE;
IS_SCOPE sub role;

STATEMENT sub relationship
	relates IS_STATEMENT;
IS_STATEMENT sub role;

STRING sub relationship
	relates IS_STRING;
IS_STRING sub role;

THEN sub relationship
	relates IS_THEN;
IS_THEN sub role;

TYPE sub relationship
	relates IS_TYPE;
IS_TYPE sub role;

UNARY sub relationship
	relates IS_UNARY;
IS_UNARY sub role;

UPDATE sub relationship
	relates IS_UPDATE;
IS_UPDATE sub role;

VARIABLE sub relationship
	relates IS_VARIABLE;
IS_VARIABLE sub role;

VISIBILITY sub relationship
	relates IS_VISIBILITY;
IS_VISIBILITY sub role;

WORLD sub relationship
	relates IS_WORLD;
IS_WORLD sub role;
