define

##########---------- Entities ----------##########

#####----- Omnilingual -----#####
OmnilingualSourceArtifact sub SourceArtifact;

ExpressionStatementArtifact sub OmnilingualSourceArtifact;

FileArtifact sub OmnilingualSourceArtifact;

ForStatementArtifact sub OmnilingualSourceArtifact
	# Semantic
	plays IS_FOR_FOR_STATEMENT
	plays IS_FOR_FOR_STATEMENT_STATEMENT
	plays IS_FOR_STATEMENT_STATEMENT;

OperatorArtifact sub OmnilingualSourceArtifact
	# Semantic
	plays IS_ARITHMETIC_BINARY
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY
	plays IS_DECREMENT_EXPRESSION
	plays IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL
	plays IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY
	plays IS_EXPRESSION_GREATER_THAN_OR_EQUAL
	plays IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY
	plays IS_OPERATOR_RELATIONAL
	plays IS_OPERATOR_RELATIONAL_UNARY
	plays IS_RELATIONAL_UNARY;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoAssignStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ASSIGNMENT_BINARY
	plays IS_ASSIGNMENT_BINARY_DECLARATION
	plays IS_ASSIGNMENT_BINARY_DECLARATION_FOR
	plays IS_ASSIGNMENT_BINARY_DECLARATION_FOR_INITIALIZATION
	plays IS_BINARY_DECLARATION
	plays IS_BINARY_DECLARATION_FOR
	plays IS_BINARY_DECLARATION_FOR_INITIALIZATION
	plays IS_BINARY_DECLARATION_FOR_INITIALIZATION_STATEMENT
	plays IS_DECLARATION_FOR
	plays IS_DECLARATION_FOR_INITIALIZATION
	plays IS_DECLARATION_FOR_INITIALIZATION_STATEMENT
	plays IS_FOR_INITIALIZATION
	plays IS_FOR_INITIALIZATION_STATEMENT
	plays IS_INITIALIZATION_STATEMENT;

GoBasicLitArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ASSIGNMENT_BINARY
	plays IS_ASSIGNMENT_BINARY_EXPRESSION
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT_LITERAL
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_BINARY_EXPRESSION
	plays IS_BINARY_EXPRESSION_IMPORT
	plays IS_BINARY_EXPRESSION_IMPORT_LITERAL
	plays IS_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER
	plays IS_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME
	plays IS_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE
	plays IS_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT
	plays IS_BINARY_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_EXPRESSION_IMPORT
	plays IS_EXPRESSION_IMPORT_LITERAL
	plays IS_EXPRESSION_IMPORT_LITERAL_NUMBER
	plays IS_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME
	plays IS_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE
	plays IS_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT
	plays IS_EXPRESSION_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_IMPORT_LITERAL
	plays IS_IMPORT_LITERAL_NUMBER
	plays IS_IMPORT_LITERAL_NUMBER_PATHNAME
	plays IS_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE
	plays IS_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT
	plays IS_IMPORT_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_LITERAL_NUMBER
	plays IS_LITERAL_NUMBER_PATHNAME
	plays IS_LITERAL_NUMBER_PATHNAME_PRIMITIVE
	plays IS_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT
	plays IS_LITERAL_NUMBER_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_NUMBER_PATHNAME
	plays IS_NUMBER_PATHNAME_PRIMITIVE
	plays IS_NUMBER_PATHNAME_PRIMITIVE_RIGHT
	plays IS_NUMBER_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_PATHNAME_PRIMITIVE
	plays IS_PATHNAME_PRIMITIVE_RIGHT
	plays IS_PATHNAME_PRIMITIVE_RIGHT_STRING
	plays IS_PRIMITIVE_RIGHT
	plays IS_PRIMITIVE_RIGHT_STRING
	plays IS_RIGHT_STRING;

GoBinaryExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_BINARY_CONDITION
	plays IS_BINARY_CONDITION_EXPRESSION
	plays IS_BINARY_CONDITION_EXPRESSION_FOR
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_CONDITION_EXPRESSION
	plays IS_CONDITION_EXPRESSION_FOR
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL
	plays IS_FOR_GREATER_THAN_OR_EQUAL
	plays IS_FOR_GREATER_THAN_OR_EQUAL_RELATIONAL
	plays IS_GREATER_THAN_OR_EQUAL_RELATIONAL;

GoBlockStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_BLOCK_BODY
	plays IS_BLOCK_BODY_FOR
	plays IS_BLOCK_BODY_FOR_FUNCTION
	plays IS_BLOCK_BODY_FOR_FUNCTION_SCOPE
	plays IS_BLOCK_BODY_FOR_FUNCTION_SCOPE_STATEMENT
	plays IS_BODY_FOR
	plays IS_BODY_FOR_FUNCTION
	plays IS_BODY_FOR_FUNCTION_SCOPE
	plays IS_BODY_FOR_FUNCTION_SCOPE_STATEMENT
	plays IS_FOR_FUNCTION
	plays IS_FOR_FUNCTION_SCOPE
	plays IS_FOR_FUNCTION_SCOPE_STATEMENT
	plays IS_FUNCTION_SCOPE
	plays IS_FUNCTION_SCOPE_STATEMENT
	plays IS_SCOPE_STATEMENT;

GoCallExprArtifact sub GoSourceArtifact;

GoExprStmtArtifact sub GoSourceArtifact;

GoFieldListArtifact sub GoSourceArtifact;

GoFileArtifact sub FileArtifact;

GoForStmtArtifact sub GoSourceArtifact;

GoFuncDeclArtifact sub GoSourceArtifact;

GoFuncTypeArtifact sub GoSourceArtifact
	# Semantic
	plays IS_EXPRESSION_FUNCTION
	plays IS_FUNCTION_TYPE;

GoGenDeclArtifact sub GoSourceArtifact;

GoIdentArtifact sub GoSourceArtifact
	# Semantic
	plays IS_ARGUMENT_ASSIGNMENT
	plays IS_ARGUMENT_ASSIGNMENT_BINARY
	plays IS_ARGUMENT_ASSIGNMENT_BINARY_EXPRESSION
	plays IS_ARGUMENT_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION
	plays IS_ARGUMENT_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_ARGUMENT_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_ARGUMENT_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_ARGUMENT_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_ASSIGNMENT_BINARY
	plays IS_ASSIGNMENT_BINARY_EXPRESSION
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_BINARY_EXPRESSION
	plays IS_BINARY_EXPRESSION_FUNCTION
	plays IS_BINARY_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_BINARY_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_EXPRESSION_FUNCTION
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_FUNCTION_IDENTIFIER
	plays IS_FUNCTION_IDENTIFIER_LEFT
	plays IS_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_IDENTIFIER_LEFT
	plays IS_IDENTIFIER_LEFT_NAME
	plays IS_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_LEFT_NAME
	plays IS_LEFT_NAME_POSITIONAL
	plays IS_NAME_POSITIONAL;

GoImportSpecArtifact sub GoSourceArtifact;

GoIncDecStmtArtifact sub GoSourceArtifact
	# Semantic
	plays IS_DECREMENT_FOR
	plays IS_DECREMENT_FOR_STATEMENT
	plays IS_DECREMENT_FOR_STATEMENT_UNARY
	plays IS_FOR_STATEMENT
	plays IS_FOR_STATEMENT_UNARY
	plays IS_FOR_STATEMENT_UNARY_UPDATE
	plays IS_STATEMENT_UNARY
	plays IS_STATEMENT_UNARY_UPDATE
	plays IS_UNARY_UPDATE;

GoOperatorArtifact sub OperatorArtifact
	# Semantic
	plays IS_ASSIGNMENT_DECLARATION;

GoPositionArtifact sub GoSourceArtifact;

GoSelectorExprArtifact sub GoSourceArtifact
	# Semantic
	plays IS_CALLEE_EXPRESSION
	plays IS_EXPRESSION_INCOMPLETE;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaArrayTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_LIST_PRIMITIVE
	plays IS_PRIMITIVE_TYPE;

JavaBlockArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BLOCK_BODY
	plays IS_BLOCK_BODY_FOR
	plays IS_BLOCK_BODY_FOR_FUNCTION
	plays IS_BLOCK_BODY_FOR_FUNCTION_SCOPE
	plays IS_BLOCK_BODY_FOR_FUNCTION_SCOPE_STATEMENT
	plays IS_BODY_FOR
	plays IS_BODY_FOR_FUNCTION
	plays IS_BODY_FOR_FUNCTION_SCOPE
	plays IS_BODY_FOR_FUNCTION_SCOPE_STATEMENT
	plays IS_FOR_FUNCTION
	plays IS_FOR_FUNCTION_SCOPE
	plays IS_FOR_FUNCTION_SCOPE_STATEMENT
	plays IS_FUNCTION_SCOPE
	plays IS_FUNCTION_SCOPE_STATEMENT
	plays IS_SCOPE_STATEMENT;

JavaCompilationUnitArtifact sub JavaSourceArtifact;

JavaDimensionArtifact sub JavaSourceArtifact;

JavaExpressionStatementArtifact sub ExpressionStatementArtifact;

JavaForStatementArtifact sub ForStatementArtifact;

JavaInfixExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BINARY_CONDITION
	plays IS_BINARY_CONDITION_EXPRESSION
	plays IS_BINARY_CONDITION_EXPRESSION_FOR
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_CONDITION_EXPRESSION
	plays IS_CONDITION_EXPRESSION_FOR
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_FOR_GREATER_THAN_OR_EQUAL
	plays IS_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_OPERATOR_RELATIONAL;

JavaMethodDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_FUNCTION
	plays IS_DECLARATION_FUNCTION_VISIBILITY
	plays IS_FUNCTION_VISIBILITY
	plays IS_FUNCTION_VISIBILITY_WORLD
	plays IS_VISIBILITY_WORLD;

JavaMethodInvocationArtifact sub JavaSourceArtifact;

JavaModifierArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_INCOMPLETE_VISIBILITY
	plays IS_INCOMPLETE_VISIBILITY_WORLD;

JavaNumberLiteralArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_BINARY_EXPRESSION
	plays IS_BINARY_EXPRESSION_LITERAL
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER
	plays IS_EXPRESSION_LITERAL
	plays IS_EXPRESSION_LITERAL_NUMBER_RIGHT
	plays IS_LITERAL_NUMBER
	plays IS_LITERAL_NUMBER_RIGHT
	plays IS_NUMBER_RIGHT;

JavaOperatorArtifact sub OperatorArtifact;

JavaPostfixExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARITHMETIC_DECREMENT
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_DECREMENT_EXPRESSION
	plays IS_DECREMENT_EXPRESSION_FOR
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_OPERATOR
	plays IS_EXPRESSION_FOR_OPERATOR_POSTFIX
	plays IS_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_FOR_OPERATOR
	plays IS_FOR_OPERATOR_POSTFIX
	plays IS_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_FOR_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_OPERATOR_POSTFIX
	plays IS_OPERATOR_POSTFIX_UNARY
	plays IS_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_POSTFIX_UNARY
	plays IS_POSTFIX_UNARY_UPDATE
	plays IS_UNARY_UPDATE;

JavaPrimitiveTypeArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_NUMBER_PRIMITIVE;

JavaQualifiedNameArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION
	plays IS_CALL_EXPRESSION_IDENTIFIER
	plays IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED
	plays IS_EXPRESSION_IDENTIFIER
	plays IS_EXPRESSION_IDENTIFIER_QUALIFIED
	plays IS_EXPRESSION_IDENTIFIER_QUALIFIED_RECEIVER
	plays IS_IDENTIFIER_QUALIFIED
	plays IS_IDENTIFIER_QUALIFIED_RECEIVER
	plays IS_QUALIFIED_RECEIVER;

JavaSimpleNameArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARGUMENT_BINARY
	plays IS_ARGUMENT_BINARY_CALL
	plays IS_ARGUMENT_BINARY_CALL_CALLEE
	plays IS_ARGUMENT_BINARY_CALL_CALLEE_EXPRESSION
	plays IS_ARGUMENT_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION
	plays IS_ARGUMENT_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_ARGUMENT_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_ARGUMENT_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_ARGUMENT_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_BINARY_CALL
	plays IS_BINARY_CALL_CALLEE
	plays IS_BINARY_CALL_CALLEE_EXPRESSION
	plays IS_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION
	plays IS_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_BINARY_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_CALL_CALLEE
	plays IS_CALL_CALLEE_EXPRESSION
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_CALLEE_EXPRESSION
	plays IS_CALLEE_EXPRESSION_FUNCTION
	plays IS_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_EXPRESSION_FUNCTION
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_LEFT
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_FUNCTION_IDENTIFIER
	plays IS_FUNCTION_IDENTIFIER_LEFT
	plays IS_FUNCTION_IDENTIFIER_LEFT_NAME
	plays IS_FUNCTION_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_IDENTIFIER_LEFT
	plays IS_IDENTIFIER_LEFT_NAME
	plays IS_IDENTIFIER_LEFT_NAME_POSITIONAL
	plays IS_LEFT_NAME
	plays IS_LEFT_NAME_POSITIONAL
	plays IS_NAME_POSITIONAL;

JavaSimpleTypeArtifact sub JavaSourceArtifact;

JavaSingleVariableDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_ARGUMENT_DECLARATION
	plays IS_ARGUMENT_DECLARATION_FUNCTION
	plays IS_DECLARATION_FUNCTION
	plays IS_DECLARATION_FUNCTION_VARIABLE
	plays IS_FUNCTION_VARIABLE;

JavaTypeDeclarationArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_TYPE
	plays IS_DECLARATION_TYPE_VISIBILITY
	plays IS_TYPE_VISIBILITY
	plays IS_TYPE_VISIBILITY_WORLD
	plays IS_VISIBILITY_WORLD;

JavaVariableDeclarationExpressionArtifact sub JavaSourceArtifact
	# Semantic
	plays IS_DECLARATION_EXPRESSION
	plays IS_DECLARATION_EXPRESSION_FOR
	plays IS_DECLARATION_EXPRESSION_FOR_INITIALIZATION
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_INITIALIZATION
	plays IS_EXPRESSION_FOR_INITIALIZATION_VARIABLE
	plays IS_FOR_INITIALIZATION
	plays IS_FOR_INITIALIZATION_VARIABLE
	plays IS_INITIALIZATION_VARIABLE;

JavaVariableDeclarationFragmentArtifact sub JavaSourceArtifact;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptBinaryExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BINARY_CONDITION
	plays IS_BINARY_CONDITION_EXPRESSION
	plays IS_BINARY_CONDITION_EXPRESSION_FOR
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_BINARY_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_CONDITION_EXPRESSION
	plays IS_CONDITION_EXPRESSION_FOR
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_CONDITION_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_EXPRESSION_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_FOR_GREATER_THAN_OR_EQUAL
	plays IS_FOR_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_FOR_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL
	plays IS_OPERATOR_RELATIONAL;

JavascriptBlockStatementArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BLOCK_SCOPE
	plays IS_SCOPE_STATEMENT;

JavascriptCallExpressionArtifact sub JavascriptSourceArtifact;

JavascriptExpressionStatementArtifact sub ExpressionStatementArtifact;

JavascriptFileArtifact sub FileArtifact;

JavascriptForStatementArtifact sub ForStatementArtifact;

JavascriptIdentifierArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_ARGUMENT_BINARY
	plays IS_ARGUMENT_BINARY_CALL
	plays IS_ARGUMENT_BINARY_CALL_EXPRESSION
	plays IS_ARGUMENT_BINARY_CALL_EXPRESSION_IDENTIFIER
	plays IS_ARGUMENT_BINARY_CALL_EXPRESSION_IDENTIFIER_LEFT
	plays IS_BINARY_CALL
	plays IS_BINARY_CALL_EXPRESSION
	plays IS_BINARY_CALL_EXPRESSION_IDENTIFIER
	plays IS_BINARY_CALL_EXPRESSION_IDENTIFIER_LEFT
	plays IS_CALL_EXPRESSION
	plays IS_CALL_EXPRESSION_IDENTIFIER
	plays IS_CALL_EXPRESSION_IDENTIFIER_LEFT
	plays IS_EXPRESSION_IDENTIFIER_LEFT
	plays IS_IDENTIFIER_LEFT;

JavascriptMemberExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_CALL_CALLEE
	plays IS_CALL_CALLEE_EXPRESSION
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER
	plays IS_CALLEE_EXPRESSION
	plays IS_CALLEE_EXPRESSION_IDENTIFIER
	plays IS_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED
	plays IS_EXPRESSION_IDENTIFIER
	plays IS_EXPRESSION_IDENTIFIER_QUALIFIED
	plays IS_IDENTIFIER_QUALIFIED;

JavascriptNumericLiteralArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_BINARY_EXPRESSION
	plays IS_BINARY_EXPRESSION_INITIALIZATION
	plays IS_BINARY_EXPRESSION_INITIALIZATION_LITERAL
	plays IS_BINARY_EXPRESSION_INITIALIZATION_LITERAL_NUMBER
	plays IS_BINARY_EXPRESSION_INITIALIZATION_LITERAL_NUMBER_RIGHT
	plays IS_EXPRESSION_INITIALIZATION
	plays IS_EXPRESSION_INITIALIZATION_LITERAL
	plays IS_EXPRESSION_INITIALIZATION_LITERAL_NUMBER_RIGHT
	plays IS_INITIALIZATION_LITERAL
	plays IS_INITIALIZATION_LITERAL_NUMBER
	plays IS_INITIALIZATION_LITERAL_NUMBER_RIGHT
	plays IS_LITERAL_NUMBER
	plays IS_LITERAL_NUMBER_RIGHT
	plays IS_NUMBER_RIGHT;

JavascriptOperatorArtifact sub OperatorArtifact;

JavascriptProgramArtifact sub JavascriptSourceArtifact;

JavascriptUpdateExpressionArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_ARITHMETIC_DECREMENT
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX
	plays IS_ARITHMETIC_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_DECREMENT_EXPRESSION
	plays IS_DECREMENT_EXPRESSION_FOR
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_DECREMENT_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_OPERATOR
	plays IS_EXPRESSION_FOR_OPERATOR_POSTFIX
	plays IS_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_EXPRESSION_FOR_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_FOR_OPERATOR
	plays IS_FOR_OPERATOR_POSTFIX
	plays IS_FOR_OPERATOR_POSTFIX_UNARY
	plays IS_FOR_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_OPERATOR_POSTFIX
	plays IS_OPERATOR_POSTFIX_UNARY
	plays IS_OPERATOR_POSTFIX_UNARY_UPDATE
	plays IS_POSTFIX_UNARY
	plays IS_POSTFIX_UNARY_UPDATE
	plays IS_UNARY_UPDATE;

JavascriptVariableDeclarationArtifact sub JavascriptSourceArtifact
	# Semantic
	plays IS_DECLARATION_FOR
	plays IS_DECLARATION_FOR_INITIALIZATION
	plays IS_DECLARATION_FOR_INITIALIZATION_STATEMENT
	plays IS_FOR_INITIALIZATION
	plays IS_FOR_INITIALIZATION_STATEMENT
	plays IS_FOR_INITIALIZATION_STATEMENT_VARIABLE
	plays IS_INITIALIZATION_STATEMENT
	plays IS_INITIALIZATION_STATEMENT_VARIABLE
	plays IS_STATEMENT_VARIABLE;

JavascriptVariableDeclaratorArtifact sub JavascriptSourceArtifact;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonCallArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_CALL_EXPRESSION
	plays IS_CALL_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_FUNCTION
	plays IS_FOR_FUNCTION;

PythonForArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_FOR_ITERATOR
	plays IS_ITERATOR_STATEMENT;

PythonForBodyArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_BODY_FOR
	plays IS_FOR_THEN;

PythonForOrelseArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_BODY_ELSE
	plays IS_ELSE_FOR;

PythonModuleArtifact sub PythonSourceArtifact;

PythonNameArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_ARGUMENT_CALL
	plays IS_ARGUMENT_CALL_CALLEE
	plays IS_ARGUMENT_CALL_CALLEE_EXPRESSION
	plays IS_ARGUMENT_CALL_CALLEE_EXPRESSION_FOR
	plays IS_ARGUMENT_CALL_CALLEE_EXPRESSION_FOR_IDENTIFIER
	plays IS_ARGUMENT_CALL_CALLEE_EXPRESSION_FOR_IDENTIFIER_POSITIONAL
	plays IS_ARGUMENT_CALL_CALLEE_EXPRESSION_FOR_IDENTIFIER_POSITIONAL_UPDATE
	plays IS_CALL_CALLEE
	plays IS_CALL_CALLEE_EXPRESSION
	plays IS_CALL_CALLEE_EXPRESSION_FOR
	plays IS_CALL_CALLEE_EXPRESSION_FOR_IDENTIFIER
	plays IS_CALL_CALLEE_EXPRESSION_FOR_IDENTIFIER_POSITIONAL
	plays IS_CALL_CALLEE_EXPRESSION_FOR_IDENTIFIER_POSITIONAL_UPDATE
	plays IS_CALLEE_EXPRESSION
	plays IS_CALLEE_EXPRESSION_FOR
	plays IS_CALLEE_EXPRESSION_FOR_IDENTIFIER
	plays IS_CALLEE_EXPRESSION_FOR_IDENTIFIER_POSITIONAL
	plays IS_CALLEE_EXPRESSION_FOR_IDENTIFIER_POSITIONAL_UPDATE
	plays IS_EXPRESSION_FOR
	plays IS_EXPRESSION_FOR_IDENTIFIER
	plays IS_EXPRESSION_FOR_IDENTIFIER_POSITIONAL
	plays IS_EXPRESSION_FOR_IDENTIFIER_POSITIONAL_UPDATE
	plays IS_FOR_IDENTIFIER
	plays IS_FOR_IDENTIFIER_POSITIONAL
	plays IS_FOR_IDENTIFIER_POSITIONAL_UPDATE
	plays IS_IDENTIFIER_POSITIONAL
	plays IS_IDENTIFIER_POSITIONAL_UPDATE
	plays IS_POSITIONAL_UPDATE;

PythonNumArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_ARGUMENT_CALL
	plays IS_ARGUMENT_CALL_EXPRESSION
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL
	plays IS_CALL_EXPRESSION
	plays IS_CALL_EXPRESSION_FUNCTION
	plays IS_CALL_EXPRESSION_FUNCTION_LITERAL
	plays IS_CALL_EXPRESSION_FUNCTION_LITERAL_NAME
	plays IS_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER
	plays IS_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL
	plays IS_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE
	plays IS_EXPRESSION_FUNCTION
	plays IS_EXPRESSION_FUNCTION_LITERAL
	plays IS_EXPRESSION_FUNCTION_LITERAL_NAME
	plays IS_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER
	plays IS_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL
	plays IS_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE
	plays IS_FUNCTION_LITERAL
	plays IS_FUNCTION_LITERAL_NAME
	plays IS_FUNCTION_LITERAL_NAME_NUMBER
	plays IS_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL
	plays IS_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE
	plays IS_LITERAL_NAME
	plays IS_LITERAL_NAME_NUMBER
	plays IS_LITERAL_NAME_NUMBER_POSITIONAL
	plays IS_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE
	plays IS_NAME_NUMBER
	plays IS_NAME_NUMBER_POSITIONAL
	plays IS_NAME_NUMBER_POSITIONAL_PRIMITIVE
	plays IS_NUMBER_POSITIONAL
	plays IS_NUMBER_POSITIONAL_PRIMITIVE
	plays IS_POSITIONAL_PRIMITIVE;

PythonPrintArtifact sub PythonSourceArtifact
	# Semantic
	plays IS_CALL_CALLEE
	plays IS_CALL_CALLEE_EXPRESSION
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION
	plays IS_CALLEE_EXPRESSION
	plays IS_CALLEE_EXPRESSION_FUNCTION
	plays IS_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_EXPRESSION_FUNCTION
	plays IS_EXPRESSION_FUNCTION_IDENTIFIER
	plays IS_FUNCTION_IDENTIFIER;

##########---------- Semantic Roles ----------##########
ARITHMETIC_BINARY sub relationship
	relates IS_ARITHMETIC_BINARY;
IS_ARITHMETIC_BINARY sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY;
IS_ARITHMETIC_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY;
IS_BINARY_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY;
IS_BINARY_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub role;

DECREMENT_EXPRESSION sub relationship
	relates IS_DECREMENT_EXPRESSION;
IS_DECREMENT_EXPRESSION sub role;

DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub relationship
	relates IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL;
IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL sub role;

DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub relationship
	relates IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR;
IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub role;

DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY;
IS_DECREMENT_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub role;

EXPRESSION_GREATER_THAN_OR_EQUAL sub relationship
	relates IS_EXPRESSION_GREATER_THAN_OR_EQUAL;
IS_EXPRESSION_GREATER_THAN_OR_EQUAL sub role;

EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub relationship
	relates IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR;
IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR sub role;

EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY;
IS_EXPRESSION_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub role;

FOR_FOR_STATEMENT sub relationship
	relates IS_FOR_FOR_STATEMENT;
IS_FOR_FOR_STATEMENT sub role;

FOR_FOR_STATEMENT_STATEMENT sub relationship
	relates IS_FOR_FOR_STATEMENT_STATEMENT;
IS_FOR_FOR_STATEMENT_STATEMENT sub role;

FOR_STATEMENT_STATEMENT sub relationship
	relates IS_FOR_STATEMENT_STATEMENT;
IS_FOR_STATEMENT_STATEMENT sub role;

GREATER_THAN_OR_EQUAL_OPERATOR sub relationship
	relates IS_GREATER_THAN_OR_EQUAL_OPERATOR;
IS_GREATER_THAN_OR_EQUAL_OPERATOR sub role;

GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relationship
	relates IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;
IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub role;

GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY;
IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL_UNARY sub role;

OPERATOR_RELATIONAL sub relationship
	relates IS_OPERATOR_RELATIONAL;
IS_OPERATOR_RELATIONAL sub role;

OPERATOR_RELATIONAL_UNARY sub relationship
	relates IS_OPERATOR_RELATIONAL_UNARY;
IS_OPERATOR_RELATIONAL_UNARY sub role;

RELATIONAL_UNARY sub relationship
	relates IS_RELATIONAL_UNARY;
IS_RELATIONAL_UNARY sub role;
