define

##########---------- Entities ----------##########

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoArrayTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LIST:IS_LIST,
	plays TYPE:IS_TYPE;

GoAssignStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays DECLARATION:IS_DECLARATION,
	plays FOR:IS_FOR,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays STATEMENT:IS_STATEMENT;

GoBasicLitArtifact sub GoSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays IMPORT:IS_IMPORT,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PATHNAME:IS_PATHNAME,
	plays POSITIONAL:IS_POSITIONAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING;

GoBinaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays IF:IS_IF,
	plays LESS_THAN:IS_LESS_THAN,
	plays NOT:IS_NOT,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL;

GoBlockStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays SCOPE:IS_SCOPE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

GoCallExprArtifact sub GoSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION;

GoCaseClauseArtifact sub GoSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays STATEMENT:IS_STATEMENT;

GoCommentArtifact sub GoSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT;

GoCommentGroupArtifact sub GoSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays LIST:IS_LIST;

GoCompositeLitArtifact sub GoSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT;

GoDeclStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT;

GoEllipsisArtifact sub GoSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays TYPE:IS_TYPE;

GoExprStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT;

GoFieldArtifact sub GoSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays FUNCTION:IS_FUNCTION,
	plays RECEIVER:IS_RECEIVER;

GoFieldListArtifact sub GoSourceArtifact,
	# Semantic
	plays ARGS_LIST:IS_ARGS_LIST,
	plays FUNCTION:IS_FUNCTION,
	plays LIST:IS_LIST,
	plays RECEIVER:IS_RECEIVER;

GoFileArtifact sub GoSourceArtifact,
	# Semantic
	plays FILE:IS_FILE;

GoForStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

GoFuncDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

GoFuncTypeArtifact sub GoSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays TYPE:IS_TYPE;

GoGenDeclArtifact sub GoSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE,
	plays VARIABLE:IS_VARIABLE;

GoIdentArtifact sub GoSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays ENTRY:IS_ENTRY,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays IF:IS_IF,
	plays ITERATOR:IS_ITERATOR,
	plays KEY:IS_KEY,
	plays LEFT:IS_LEFT,
	plays NAME:IS_NAME,
	plays POSITIONAL:IS_POSITIONAL,
	plays RECEIVER:IS_RECEIVER,
	plays RIGHT:IS_RIGHT,
	plays TYPE:IS_TYPE,
	plays VALUE:IS_VALUE,
	plays VARIABLE:IS_VARIABLE;

GoIfStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

GoImportSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays IMPORT:IS_IMPORT;

GoIncDecStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays DECREMENT:IS_DECREMENT,
	plays FOR:IS_FOR,
	plays INCREMENT:IS_INCREMENT,
	plays STATEMENT:IS_STATEMENT,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE;

GoOperatorArtifact sub GoSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays DECLARATION:IS_DECLARATION,
	plays DECREMENT:IS_DECREMENT,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays INCREMENT:IS_INCREMENT,
	plays LESS_THAN:IS_LESS_THAN,
	plays NEGATIVE:IS_NEGATIVE,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL,
	plays UNARY:IS_UNARY;

GoPositionArtifact sub GoSourceArtifact;

GoRangeStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT;

GoSelectorExprArtifact sub GoSourceArtifact,
	# Semantic
	plays CALLEE:IS_CALLEE,
	plays EXPRESSION:IS_EXPRESSION,
	plays QUALIFIED:IS_QUALIFIED;

GoStarExprArtifact sub GoSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays RECEIVER:IS_RECEIVER,
	plays TYPE:IS_TYPE;

GoSwitchStmtArtifact sub GoSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

GoTypeSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION;

GoUnaryExprArtifact sub GoSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays NEGATIVE:IS_NEGATIVE,
	plays RIGHT:IS_RIGHT,
	plays UNARY:IS_UNARY;

GoValueSpecArtifact sub GoSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaArrayInitializerArtifact sub JavaSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LIST:IS_LIST,
	plays LITERAL:IS_LITERAL;

JavaArrayTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays LIST:IS_LIST,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays TYPE:IS_TYPE;

JavaAssignmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays OPERATOR:IS_OPERATOR;

JavaBlockArtifact sub JavaSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays FINALLY:IS_FINALLY,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays SCOPE:IS_SCOPE,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays TRY:IS_TRY,
	plays WHILE:IS_WHILE;

JavaBooleanLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT,
	plays WHILE:IS_WHILE;

JavaCatchClauseArtifact sub JavaSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays TRY:IS_TRY;

JavaCompilationUnitArtifact sub JavaSourceArtifact,
	# Semantic
	plays FILE:IS_FILE;

JavaConditionalExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays RIGHT:IS_RIGHT;

JavaDimensionArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

JavaDoStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays DO_WHILE:IS_DO_WHILE,
	plays STATEMENT:IS_STATEMENT;

JavaEnhancedForStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT;

JavaExpressionStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

JavaFieldDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays VARIABLE:IS_VARIABLE;

JavaForStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

JavaIfStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

JavaInfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays IF:IS_IF,
	plays LESS_THAN:IS_LESS_THAN,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL;

JavaMethodDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

JavaMethodInvocationArtifact sub JavaSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION;

JavaModifierArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

JavaNumberLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

JavaOperatorArtifact sub JavaSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays DECREMENT:IS_DECREMENT,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays INCREMENT:IS_INCREMENT,
	plays LESS_THAN:IS_LESS_THAN,
	plays NEGATIVE:IS_NEGATIVE,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays POSTFIX:IS_POSTFIX,
	plays RELATIONAL:IS_RELATIONAL,
	plays UNARY:IS_UNARY;

JavaParameterizedTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

JavaParenthesizedExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE;

JavaPostfixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays DECREMENT:IS_DECREMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INCREMENT:IS_INCREMENT,
	plays OPERATOR:IS_OPERATOR,
	plays POSTFIX:IS_POSTFIX,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE;

JavaPrefixExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays EXPRESSION:IS_EXPRESSION,
	plays NEGATIVE:IS_NEGATIVE,
	plays OPERATOR:IS_OPERATOR,
	plays UNARY:IS_UNARY;

JavaPrimitiveTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays TYPE:IS_TYPE;

JavaQualifiedNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays QUALIFIED:IS_QUALIFIED,
	plays RECEIVER:IS_RECEIVER;

JavaSimpleNameArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays NAME:IS_NAME,
	plays POSITIONAL:IS_POSITIONAL;

JavaSimpleTypeArtifact sub JavaSourceArtifact,
	# Semantic
	plays TYPE:IS_TYPE;

JavaSingleVariableDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGS_LIST:IS_ARGS_LIST,
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays ITERATOR:IS_ITERATOR,
	plays VARIABLE:IS_VARIABLE;

JavaStringLiteralArtifact sub JavaSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays POSITIONAL:IS_POSITIONAL,
	plays STRING:IS_STRING;

JavaSwitchCaseArtifact sub JavaSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

JavaSwitchStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

JavaTryStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

JavaTypeDeclarationArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE,
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

JavaTypeParameterArtifact sub JavaSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

JavaVariableDeclarationExpressionArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays VARIABLE:IS_VARIABLE;

JavaVariableDeclarationFragmentArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays VARIABLE:IS_VARIABLE;

JavaVariableDeclarationStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays STATEMENT:IS_STATEMENT,
	plays VARIABLE:IS_VARIABLE;

JavaWhileStatementArtifact sub JavaSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays WHILE:IS_WHILE;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptAnyTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

JavascriptArrayExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LIST:IS_LIST,
	plays LITERAL:IS_LITERAL;

JavascriptAssignmentExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays OPERATOR:IS_OPERATOR;

JavascriptAssignmentPatternArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE;

JavascriptBinaryExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays IDENTICAL:IS_IDENTICAL,
	plays IF:IS_IF,
	plays LESS_THAN:IS_LESS_THAN,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

JavascriptBlockStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays FINALLY:IS_FINALLY,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays SCOPE:IS_SCOPE,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN,
	plays TRY:IS_TRY,
	plays WHILE:IS_WHILE;

JavascriptBooleanLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT,
	plays WHILE:IS_WHILE;

JavascriptCallExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION;

JavascriptCatchClauseArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

JavascriptCommentLineArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays NOOP:IS_NOOP;

JavascriptConditionalExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays RIGHT:IS_RIGHT;

JavascriptDoWhileStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DO_WHILE:IS_DO_WHILE,
	plays STATEMENT:IS_STATEMENT;

JavascriptEmptyStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays NOOP:IS_NOOP,
	plays STATEMENT:IS_STATEMENT;

JavascriptExpressionStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT;

JavascriptFileArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays FILE:IS_FILE;

JavascriptForInStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT;

JavascriptForStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

JavascriptFunctionDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays STATEMENT:IS_STATEMENT;

JavascriptIdentifierArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays NAME:IS_NAME;

JavascriptIfStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

JavascriptLogicalExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR;

JavascriptMemberExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays QUALIFIED:IS_QUALIFIED;

JavascriptNumberTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER,
	plays TYPE:IS_TYPE;

JavascriptNumericLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays RIGHT:IS_RIGHT,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN;

JavascriptOperatorArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays DECREMENT:IS_DECREMENT,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays IDENTICAL:IS_IDENTICAL,
	plays INCREMENT:IS_INCREMENT,
	plays LESS_THAN:IS_LESS_THAN,
	plays NEGATIVE:IS_NEGATIVE,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL,
	plays UNARY:IS_UNARY;

JavascriptProgramArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays MODULE:IS_MODULE;

JavascriptRestElementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ARGS_LIST:IS_ARGS_LIST,
	plays ARGUMENT:IS_ARGUMENT,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE;

JavascriptStringLiteralArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LITERAL:IS_LITERAL,
	plays STRING:IS_STRING;

JavascriptSwitchCaseArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays SWITCH:IS_SWITCH;

JavascriptSwitchStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

JavascriptTryStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

JavascriptTypeAnnotationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

JavascriptUnaryExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays EXPRESSION:IS_EXPRESSION,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays NEGATIVE:IS_NEGATIVE,
	plays OPERATOR:IS_OPERATOR,
	plays UNARY:IS_UNARY;

JavascriptUpdateExpressionArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays DECREMENT:IS_DECREMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INCREMENT:IS_INCREMENT,
	plays OPERATOR:IS_OPERATOR,
	plays POSTFIX:IS_POSTFIX,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE;

JavascriptVariableDeclarationArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FOR:IS_FOR,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT,
	plays VARIABLE:IS_VARIABLE;

JavascriptVariableDeclaratorArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays VARIABLE:IS_VARIABLE;

JavascriptWhileStatementArtifact sub JavascriptSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays WHILE:IS_WHILE;

#####----- Php -----#####
PhpSourceArtifact sub SourceArtifact;

PhpExprArrayArtifact sub PhpSourceArtifact,
	# Semantic
	plays DEFAULT:IS_DEFAULT,
	plays EXPRESSION:IS_EXPRESSION,
	plays LIST:IS_LIST,
	plays LITERAL:IS_LITERAL;

PhpExprArrayItemArtifact sub PhpSourceArtifact,
	# Semantic
	plays ENTRY:IS_ENTRY,
	plays EXPRESSION:IS_EXPRESSION,
	plays LIST:IS_LIST;

PhpExprAssignArtifact sub PhpSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INITIALIZATION:IS_INITIALIZATION;

PhpExprBinaryOpBooleanAndArtifact sub PhpSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays OPERATOR:IS_OPERATOR;

PhpExprBinaryOpBooleanOrArtifact sub PhpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR;

PhpExprBinaryOpEqualArtifact sub PhpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PhpExprBinaryOpGreaterOrEqualArtifact sub PhpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PhpExprBinaryOpIdenticalArtifact sub PhpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTICAL:IS_IDENTICAL,
	plays IF:IS_IF,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PhpExprBinaryOpNotEqualArtifact sub PhpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PhpExprBinaryOpNotIdenticalArtifact sub PhpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTICAL:IS_IDENTICAL,
	plays IF:IS_IF,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PhpExprConstFetchArtifact sub PhpSourceArtifact,
	# Semantic
	plays CONDITION:IS_CONDITION,
	plays DEFAULT:IS_DEFAULT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT,
	plays RIGHT:IS_RIGHT,
	plays VARIABLE:IS_VARIABLE;

PhpExprPostDecArtifact sub PhpSourceArtifact,
	# Semantic
	plays DECREMENT:IS_DECREMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays POSTFIX:IS_POSTFIX,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE;

PhpExprTernaryArtifact sub PhpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays RIGHT:IS_RIGHT;

PhpExprUnaryMinusArtifact sub PhpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays RIGHT:IS_RIGHT,
	plays UNARY:IS_UNARY;

PhpExprVariableArtifact sub PhpSourceArtifact,
	# Semantic
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT,
	plays VARIABLE:IS_VARIABLE;

PhpFunctionBodyArtifact sub PhpSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

PhpFunctionReturnTypeArtifact sub PhpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays RETURN:IS_RETURN,
	plays TYPE:IS_TYPE;

PhpModuleArtifact sub PhpSourceArtifact,
	# Semantic
	plays MODULE:IS_MODULE;

PhpNameArtifact sub PhpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER;

PhpParamArtifact sub PhpSourceArtifact,
	# Semantic
	plays ARGS_LIST:IS_ARGS_LIST,
	plays ARGUMENT:IS_ARGUMENT,
	plays INCOMPLETE:IS_INCOMPLETE;

PhpScalarDNumberArtifact sub PhpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays RIGHT:IS_RIGHT;

PhpScalarLNumberArtifact sub PhpSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays DEFAULT:IS_DEFAULT,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

PhpScalarStringArtifact sub PhpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING;

PhpStmtCaseArtifact sub PhpSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

PhpStmtEchoArtifact sub PhpSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays CASE:IS_CASE,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

PhpStmtElseArtifact sub PhpSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays STATEMENT:IS_STATEMENT;

PhpStmtElseIfArtifact sub PhpSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

PhpStmtForArtifact sub PhpSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

PhpStmtFunctionArtifact sub PhpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

PhpStmtIfArtifact sub PhpSourceArtifact,
	# Semantic
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

PhpStmtSwitchArtifact sub PhpSourceArtifact,
	# Semantic
	plays SWITCH:IS_SWITCH;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonAddArtifact sub PythonSourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays BINARY:IS_BINARY,
	plays OPERATOR:IS_OPERATOR;

PythonAndArtifact sub PythonSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BOOLEAN:IS_BOOLEAN,
	plays OPERATOR:IS_OPERATOR;

PythonArgArtifact sub PythonSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays NAME:IS_NAME;

PythonArgumentsArtifact sub PythonSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE;

PythonAssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION;

PythonBinOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays RIGHT:IS_RIGHT;

PythonBoolOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays IF:IS_IF,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LITERAL:IS_LITERAL;

PythonCallArtifact sub PythonSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION;

PythonCompareArtifact sub PythonSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF;

PythonCompareComparatorsArtifact sub PythonSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays RIGHT:IS_RIGHT;

PythonCompareOpsArtifact sub PythonSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION;

PythonEqArtifact sub PythonSourceArtifact,
	# Semantic
	plays EQUAL:IS_EQUAL,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PythonExceptHandlerArtifact sub PythonSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays TRY:IS_TRY;

PythonForArtifact sub PythonSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT;

PythonForBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays FOR:IS_FOR,
	plays WHILE:IS_WHILE;

PythonForOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays WHILE:IS_WHILE;

PythonFunctionDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME;

PythonFunctionDefBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

PythonFunctionDefDecoratorsArtifact sub PythonSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays INCOMPLETE:IS_INCOMPLETE;

PythonIfArtifact sub PythonSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF;

PythonIfBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays IF:IS_IF,
	plays THEN:IS_THEN;

PythonIfOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays IF:IS_IF;

PythonKwargArtifact sub PythonSourceArtifact,
	# Semantic
	plays ARGS_LIST:IS_ARGS_LIST,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays MAP:IS_MAP,
	plays NAME:IS_NAME;

PythonModuleArtifact sub PythonSourceArtifact,
	# Semantic
	plays FILE:IS_FILE,
	plays MODULE:IS_MODULE;

PythonNameArtifact sub PythonSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays IF:IS_IF,
	plays LEFT:IS_LEFT,
	plays POSITIONAL:IS_POSITIONAL,
	plays UPDATE:IS_UPDATE,
	plays WHILE:IS_WHILE;

PythonNoopLineArtifact sub PythonSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays NOOP:IS_NOOP;

PythonNoopSameLineArtifact sub PythonSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT,
	plays NOOP:IS_NOOP;

PythonNotEqArtifact sub PythonSourceArtifact,
	# Semantic
	plays EQUAL:IS_EQUAL,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

PythonNumArtifact sub PythonSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays BINARY:IS_BINARY,
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NAME:IS_NAME,
	plays NUMBER:IS_NUMBER,
	plays POSITIONAL:IS_POSITIONAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT;

PythonOrArtifact sub PythonSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR;

PythonPreviousNoopsArtifact sub PythonSourceArtifact,
	# Semantic
	plays NOOP:IS_NOOP;

PythonPrintArtifact sub PythonSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays CALLEE:IS_CALLEE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER;

PythonRemainderNoopsArtifact sub PythonSourceArtifact,
	# Semantic
	plays NOOP:IS_NOOP;

PythonSameLineNoopsArtifact sub PythonSourceArtifact,
	# Semantic
	plays COMMENT:IS_COMMENT;

PythonStrArtifact sub PythonSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays DEFAULT:IS_DEFAULT,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays POSITIONAL:IS_POSITIONAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING;

PythonTryExceptArtifact sub PythonSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

PythonTryFinallyArtifact sub PythonSourceArtifact,
	# Semantic
	plays FINALLY:IS_FINALLY,
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

PythonUnaryOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays EXPRESSION:IS_EXPRESSION,
	plays OPERATOR:IS_OPERATOR,
	plays RIGHT:IS_RIGHT,
	plays UNARY:IS_UNARY;

PythonUSubArtifact sub PythonSourceArtifact,
	# Semantic
	plays BITWISE:IS_BITWISE,
	plays NEGATIVE:IS_NEGATIVE,
	plays OPERATOR:IS_OPERATOR,
	plays UNARY:IS_UNARY;

PythonWhileArtifact sub PythonSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays WHILE:IS_WHILE;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

RubyAndArtifact sub RubySourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays OPERATOR:IS_OPERATOR;

RubyArgArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME;

RubyArgsArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE;

RubyBeginArtifact sub RubySourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK;

RubyBlockargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME;

RubyCaseArtifact sub RubySourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

RubyConstArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LEFT:IS_LEFT;

RubyDefArtifact sub RubySourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays STATEMENT:IS_STATEMENT;

RubyFalseArtifact sub RubySourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL;

RubyFloatArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT;

RubyForArtifact sub RubySourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

RubyIdentifierArtifact sub RubySourceArtifact;

RubyIfArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF,
	plays RIGHT:IS_RIGHT,
	plays STATEMENT:IS_STATEMENT;

RubyIntArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays BINARY:IS_BINARY,
	plays BODY:IS_BODY,
	plays CALL:IS_CALL,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FUNCTION:IS_FUNCTION,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays THEN:IS_THEN;

RubyKwargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays MAP:IS_MAP,
	plays NAME:IS_NAME;

RubyKwoptargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays NAME:IS_NAME;

RubyLvarArtifact sub RubySourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LEFT:IS_LEFT;

RubyLvasgnArtifact sub RubySourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT;

RubyModuleArtifact sub RubySourceArtifact,
	# Semantic
	plays IDENTIFIER:IS_IDENTIFIER,
	plays MODULE:IS_MODULE,
	plays STATEMENT:IS_STATEMENT;

RubyNilNodeArtifact sub RubySourceArtifact,
	# Semantic
	plays NULL:IS_NULL;

RubyOptargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DEFAULT:IS_DEFAULT,
	plays EXPRESSION:IS_EXPRESSION,
	plays NAME:IS_NAME;

RubyOrArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR;

RubyRestargArtifact sub RubySourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays LIST:IS_LIST;

RubySendCallArtifact sub RubySourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays UPDATE:IS_UPDATE;

RubySendOperatorArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTICAL:IS_IDENTICAL,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

RubySendQualifiedArtifact sub RubySourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays QUALIFIED:IS_QUALIFIED,
	plays THEN:IS_THEN;

RubyStrArtifact sub RubySourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING;

RubyTrueArtifact sub RubySourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays RIGHT:IS_RIGHT;

RubyWhenArtifact sub RubySourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays EXPRESSION:IS_EXPRESSION,
	plays SWITCH:IS_SWITCH;

#####----- Csharp -----#####
CsharpSourceArtifact sub SourceArtifact;

CsharpAmpersandAmpersandTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpArgumentArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays FUNCTION:IS_FUNCTION;

CsharpArgumentListArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CALL:IS_CALL,
	plays FUNCTION:IS_FUNCTION,
	plays LIST:IS_LIST;

CsharpArrayInitializerExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INSTANCE:IS_INSTANCE,
	plays LIST:IS_LIST;

CsharpArrayRankSpecifierArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LIST:IS_LIST;

CsharpArrayTypeArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LIST:IS_LIST,
	plays TYPE:IS_TYPE;

CsharpBarBarTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBinaryExpressionEqualsExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBinaryExpressionGreaterThanOrEqualExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBinaryExpressionLessThanExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays LESS_THAN:IS_LESS_THAN,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBinaryExpressionLogicalAndExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBinaryExpressionLogicalOrExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBinaryExpressionNotEqualsExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays NOT:IS_NOT,
	plays RELATIONAL:IS_RELATIONAL;

CsharpBlockArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK;

CsharpBoolKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays DECLARATION:IS_DECLARATION;

CsharpBreakKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BREAK:IS_BREAK;

CsharpBreakStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BREAK:IS_BREAK,
	plays STATEMENT:IS_STATEMENT;

CsharpByteKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpCaseKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays SWITCH:IS_SWITCH;

CsharpCaseSwitchLabelArtifact sub CsharpSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays NAME:IS_NAME,
	plays SWITCH:IS_SWITCH;

CsharpCatchClauseArtifact sub CsharpSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays STATEMENT:IS_STATEMENT;

CsharpCatchDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays CATCH:IS_CATCH;

CsharpCatchKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpClassDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

CsharpClassKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

CsharpCloseBraceTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpCloseBracketTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpCloseParenTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpColonTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpCompilationUnitArtifact sub CsharpSourceArtifact,
	# Semantic
	plays FILE:IS_FILE,
	plays MODULE:IS_MODULE;

CsharpConditionalExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION;

CsharpDecimalKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpDoKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpDoStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DO_WHILE:IS_DO_WHILE,
	plays STATEMENT:IS_STATEMENT;

CsharpDotTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpDoubleKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpElseClauseArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays STATEMENT:IS_STATEMENT;

CsharpElseKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE;

CsharpEndOfFileTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays NOOP:IS_NOOP;

CsharpEnumDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays ENUMERATION:IS_ENUMERATION,
	plays TYPE:IS_TYPE;

CsharpEnumKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpEnumMemberDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays ENUMERATION:IS_ENUMERATION,
	plays TYPE:IS_TYPE,
	plays VALUE:IS_VALUE;

CsharpEqualsEqualsTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EQUAL:IS_EQUAL,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpEqualsTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EQUAL:IS_EQUAL,
	plays OPERATOR:IS_OPERATOR;

CsharpEqualsValueClauseArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays RIGHT:IS_RIGHT;

CsharpExclamationEqualsTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EQUAL:IS_EQUAL,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpExpressionStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays STATEMENT:IS_STATEMENT;

CsharpFieldDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE,
	plays VARIABLE:IS_VARIABLE;

CsharpFinallyClauseArtifact sub CsharpSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

CsharpFinallyKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

CsharpFloatKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpForEachKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpForEachStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

CsharpForKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays FOR:IS_FOR;

CsharpForStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

CsharpGenericNameArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpGreaterThanEqualsTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpGreaterThanTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays GREATER_THAN:IS_GREATER_THAN,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpIdentifierNameArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IDENTIFIER:IS_IDENTIFIER;

CsharpIdentifierTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER;

CsharpIfKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IF:IS_IF;

CsharpIfStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

CsharpInKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpIntKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpInvocationExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays CALL:IS_CALL,
	plays FUNCTION:IS_FUNCTION;

CsharpLessThanTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays LESS_THAN:IS_LESS_THAN,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

CsharpLocalDeclarationStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION;

CsharpLongKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpMethodDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays TYPE:IS_TYPE;

CsharpMinusMinusTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECREMENT:IS_DECREMENT,
	plays OPERATOR:IS_OPERATOR,
	plays UNARY:IS_UNARY;

CsharpMinusTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays OPERATOR:IS_OPERATOR,
	plays SUBSTRACT:IS_SUBSTRACT;

CsharpNoneArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpNumericLiteralExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER;

CsharpNumericLiteralTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays VALUE:IS_VALUE;

CsharpOmittedArraySizeExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LIST:IS_LIST;

CsharpOmittedArraySizeExpressionTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpOpenBraceTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpOpenBracketTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpOpenParenTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpParameterArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

CsharpParameterListArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays LIST:IS_LIST;

CsharpParamsKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpParenthesizedExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION;

CsharpPlusPlusTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays INCREMENT:IS_INCREMENT,
	plays UNARY:IS_UNARY;

CsharpPostfixUnaryExpressionPostDecrementExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays DECREMENT:IS_DECREMENT,
	plays EXPRESSION:IS_EXPRESSION,
	plays POSTFIX:IS_POSTFIX,
	plays UNARY:IS_UNARY;

CsharpPostfixUnaryExpressionPostIncrementExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCREMENT:IS_INCREMENT,
	plays POSTFIX:IS_POSTFIX,
	plays UNARY:IS_UNARY;

CsharpPredefinedTypeArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays TYPE:IS_TYPE;

CsharpPrefixUnaryExpressionUnaryMinusExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays NEGATIVE:IS_NEGATIVE,
	plays UNARY:IS_UNARY;

CsharpPublicKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays VISIBILITY:IS_VISIBILITY,
	plays WORLD:IS_WORLD;

CsharpQualifiedNameArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IDENTIFIER:IS_IDENTIFIER,
	plays QUALIFIED:IS_QUALIFIED;

CsharpQuestionTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays OPERATOR:IS_OPERATOR;

CsharpSByteKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpSemicolonTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpShortKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpSimpleAssignmentExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays EXPRESSION:IS_EXPRESSION;

CsharpSimpleMemberAccessExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays QUALIFIED:IS_QUALIFIED;

CsharpStaticKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpStringKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays STRING:IS_STRING;

CsharpStringLiteralExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays STRING:IS_STRING;

CsharpStringLiteralTokenArtifact sub CsharpSourceArtifact,
	# Semantic
	plays LITERAL:IS_LITERAL,
	plays STRING:IS_STRING;

CsharpStructDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

CsharpStructKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

CsharpSwitchKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays SWITCH:IS_SWITCH;

CsharpSwitchSectionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays SWITCH:IS_SWITCH;

CsharpSwitchStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

CsharpTrueKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays LITERAL:IS_LITERAL;

CsharpTrueLiteralExpressionArtifact sub CsharpSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL;

CsharpTryKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TRY:IS_TRY;

CsharpTryStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

CsharpTypeArgumentListArtifact sub CsharpSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INSTANCE:IS_INSTANCE,
	plays LIST:IS_LIST;

CsharpUIntKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpULongKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpUShortKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays NUMBER:IS_NUMBER;

CsharpUsingDirectiveArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IMPORT:IS_IMPORT,
	plays STATEMENT:IS_STATEMENT;

CsharpUsingKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays IMPORT:IS_IMPORT,
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpVariableDeclarationArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION,
	plays VARIABLE:IS_VARIABLE;

CsharpVariableDeclaratorArtifact sub CsharpSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays RIGHT:IS_RIGHT,
	plays VARIABLE:IS_VARIABLE;

CsharpVoidKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

CsharpWhileKeywordArtifact sub CsharpSourceArtifact,
	# Semantic
	plays WHILE:IS_WHILE;

CsharpWhileStatementArtifact sub CsharpSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays WHILE:IS_WHILE;

#####----- Bash -----#####
BashSourceArtifact sub SourceArtifact;

BashANDANDArtifact sub BashSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays BOOLEAN:IS_BOOLEAN,
	plays OPERATOR:IS_OPERATOR;

BashArithCompundComparisionArtifact sub BashSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

BashArithLTArtifact sub BashSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays OPERATOR:IS_OPERATOR;

BashArithmeticPostIncrArtifact sub BashSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

BashArithmeticSimpleArtifact sub BashSourceArtifact,
	# Semantic
	plays ARITHMETIC:IS_ARITHMETIC,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE;

BashAssignmentWordArtifact sub BashSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays LEFT:IS_LEFT;

BashCasePatternArtifact sub BashSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

BashCasePatternListArtifact sub BashSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays CASE:IS_CASE;

BashCombinedWordArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays RIGHT:IS_RIGHT,
	plays UPDATE:IS_UPDATE;

BashConditionalShellcommandArtifact sub BashSourceArtifact,
	# Semantic
	plays CONDITION:IS_CONDITION,
	plays ELSE:IS_ELSE,
	plays EXPRESSION:IS_EXPRESSION,
	plays IF:IS_IF;

BashElifArtifact sub BashSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

BashElseArtifact sub BashSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays STATEMENT:IS_STATEMENT;

BashEQArtifact sub BashSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays OPERATOR:IS_OPERATOR;

BashFILEArtifact sub BashSourceArtifact,
	# Semantic
	plays FILE:IS_FILE;

BashForShellcommandArtifact sub BashSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

BashFunctionDefElementArtifact sub BashSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

BashGenericBashCommandArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE;

BashGroupElementArtifact sub BashSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY;

BashGTEQArtifact sub BashSourceArtifact,
	# Semantic
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays OPERATOR:IS_OPERATOR,
	plays RELATIONAL:IS_RELATIONAL;

BashHyphenHyphenArtifact sub BashSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

BashIfShellcommandArtifact sub BashSourceArtifact,
	# Semantic
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

BashIntLiteralArtifact sub BashSourceArtifact,
	# Semantic
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays PRIMITIVE:IS_PRIMITIVE;

BashLogicalBlockArtifact sub BashSourceArtifact,
	# Semantic
	plays BLOCK:IS_BLOCK,
	plays BODY:IS_BODY,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays THEN:IS_THEN,
	plays WHILE:IS_WHILE;

BashLPLPArtifact sub BashSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

BashNamedSymbolArtifact sub BashSourceArtifact,
	# Semantic
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME;

BashNumberArtifact sub BashSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

BashORORArtifact sub BashSourceArtifact,
	# Semantic
	plays BOOLEAN:IS_BOOLEAN,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR;

BashPlusPlusArtifact sub BashSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

BashRPRPArtifact sub BashSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

BashSEMICOLONSEMICOLONArtifact sub BashSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE;

BashSimpleCommandArtifact sub BashSourceArtifact,
	# Semantic
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays WHILE:IS_WHILE;

BashSingleBashExpansionArtifact sub BashSourceArtifact,
	# Semantic
	plays UNANNOTATED:IS_UNANNOTATED;

BashStringArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays PRIMITIVE:IS_PRIMITIVE,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING;

BashStringContentArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays LITERAL:IS_LITERAL,
	plays STRING:IS_STRING;

BashThenArtifact sub BashSourceArtifact,
	# Semantic
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT,
	plays THEN:IS_THEN;

BashVarDefElementArtifact sub BashSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays ITERATOR:IS_ITERATOR,
	plays VARIABLE:IS_VARIABLE;

BashVariableArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays VARIABLE:IS_VARIABLE;

BashVarUseElementArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays VARIABLE:IS_VARIABLE;

BashWhileLoopArtifact sub BashSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays WHILE:IS_WHILE;

BashWordArtifact sub BashSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION,
	plays IDENTIFIER:IS_IDENTIFIER;

#####----- Cplusplus -----#####
CplusplusSourceArtifact sub SourceArtifact;

CplusplusASTInclusionStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays IMPORT:IS_IMPORT;

CplusplusCPPASTArrayDeclaratorArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays LIST:IS_LIST;

CplusplusCPPASTArrayModifierArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays LIST:IS_LIST,
	plays TYPE:IS_TYPE;

CplusplusCPPASTBinaryExpressionArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays AND:IS_AND,
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays BINARY:IS_BINARY,
	plays BITWISE:IS_BITWISE,
	plays BOOLEAN:IS_BOOLEAN,
	plays EQUAL:IS_EQUAL,
	plays EXPRESSION:IS_EXPRESSION,
	plays GREATER_THAN_OR_EQUAL:IS_GREATER_THAN_OR_EQUAL,
	plays LEFT:IS_LEFT,
	plays LEFT_SHIFT:IS_LEFT_SHIFT,
	plays LESS_THAN:IS_LESS_THAN,
	plays NOT:IS_NOT,
	plays OPERATOR:IS_OPERATOR,
	plays OR:IS_OR,
	plays RELATIONAL:IS_RELATIONAL;

CplusplusCPPASTCaseStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays CASE:IS_CASE,
	plays SWITCH:IS_SWITCH;

CplusplusCPPASTCatchHandlerArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays CATCH:IS_CATCH,
	plays TRY:IS_TRY;

CplusplusCPPASTCompositeTypeSpecifierArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays TYPE:IS_TYPE;

CplusplusCPPASTCompoundStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays BODY:IS_BODY,
	plays CATCH:IS_CATCH,
	plays DECLARATION:IS_DECLARATION,
	plays DO_WHILE:IS_DO_WHILE,
	plays ELSE:IS_ELSE,
	plays FOR:IS_FOR,
	plays FUNCTION:IS_FUNCTION,
	plays IF:IS_IF,
	plays SWITCH:IS_SWITCH,
	plays THEN:IS_THEN,
	plays TRY:IS_TRY,
	plays WHILE:IS_WHILE;

CplusplusCPPASTConditionalExpressionArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays CONDITION:IS_CONDITION,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays RIGHT:IS_RIGHT;

CplusplusCPPASTDeclarationStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FOR:IS_FOR,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays STATEMENT:IS_STATEMENT;

CplusplusCPPASTDeclaratorArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays NAME:IS_NAME,
	plays VARIABLE:IS_VARIABLE;

CplusplusCPPASTDoStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DO_WHILE:IS_DO_WHILE,
	plays STATEMENT:IS_STATEMENT;

CplusplusCPPASTEqualsInitializerArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ASSIGNMENT:IS_ASSIGNMENT,
	plays DECLARATION:IS_DECLARATION,
	plays EXPRESSION:IS_EXPRESSION,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LIST:IS_LIST,
	plays RIGHT:IS_RIGHT;

CplusplusCPPASTExpressionStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays EXPRESSION:IS_EXPRESSION;

CplusplusCPPASTForStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT;

CplusplusCPPASTFunctionDeclaratorArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

CplusplusCPPASTFunctionDefinitionArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION;

CplusplusCPPASTIdExpressionArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays ITERATOR:IS_ITERATOR,
	plays LEFT:IS_LEFT,
	plays RETURN:IS_RETURN,
	plays RIGHT:IS_RIGHT,
	plays VALUE:IS_VALUE,
	plays VARIABLE:IS_VARIABLE;

CplusplusCPPASTIfStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ELSE:IS_ELSE,
	plays IF:IS_IF,
	plays STATEMENT:IS_STATEMENT;

CplusplusCPPASTInitializerListArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LIST:IS_LIST;

CplusplusCPPASTLiteralExpressionArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays BINARY:IS_BINARY,
	plays BOOLEAN:IS_BOOLEAN,
	plays CONDITION:IS_CONDITION,
	plays DO_WHILE:IS_DO_WHILE,
	plays EXPRESSION:IS_EXPRESSION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays INITIALIZATION:IS_INITIALIZATION,
	plays LEFT:IS_LEFT,
	plays LITERAL:IS_LITERAL,
	plays NUMBER:IS_NUMBER,
	plays RIGHT:IS_RIGHT,
	plays STRING:IS_STRING,
	plays SWITCH:IS_SWITCH,
	plays WHILE:IS_WHILE;

CplusplusCPPASTNameArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays IDENTIFIER:IS_IDENTIFIER,
	plays NAME:IS_NAME,
	plays QUALIFIED:IS_QUALIFIED;

CplusplusCPPASTNamedTypeSpecifierArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays INSTANCE:IS_INSTANCE,
	plays RETURN:IS_RETURN,
	plays TYPE:IS_TYPE;

CplusplusCPPASTProblemDeclarationArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays NOOP:IS_NOOP;

CplusplusCPPASTQualifiedNameArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays QUALIFIED:IS_QUALIFIED;

CplusplusCPPASTRangeBasedForStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays FOR:IS_FOR,
	plays ITERATOR:IS_ITERATOR,
	plays STATEMENT:IS_STATEMENT;

CplusplusCPPASTReturnStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays RETURN:IS_RETURN,
	plays STATEMENT:IS_STATEMENT;

CplusplusCPPASTSimpleDeclarationArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays CATCH:IS_CATCH,
	plays DECLARATION:IS_DECLARATION,
	plays FOR:IS_FOR,
	plays STATEMENT:IS_STATEMENT,
	plays TYPE:IS_TYPE,
	plays VARIABLE:IS_VARIABLE;

CplusplusCPPASTSimpleDeclSpecifierArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays FUNCTION:IS_FUNCTION,
	plays NULL:IS_NULL,
	plays NUMBER:IS_NUMBER,
	plays RETURN:IS_RETURN,
	plays TYPE:IS_TYPE;

CplusplusCPPASTSimpleTypeTemplateParameterArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ARGUMENT:IS_ARGUMENT,
	plays DECLARATION:IS_DECLARATION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

CplusplusCPPASTSwitchStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays SWITCH:IS_SWITCH;

CplusplusCPPASTTemplateDeclarationArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays DECLARATION:IS_DECLARATION,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays TYPE:IS_TYPE;

CplusplusCPPASTTemplateIdArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays INCOMPLETE:IS_INCOMPLETE,
	plays QUALIFIED:IS_QUALIFIED,
	plays TYPE:IS_TYPE;

CplusplusCPPASTTranslationUnitArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays FILE:IS_FILE,
	plays MODULE:IS_MODULE;

CplusplusCPPASTTryBlockStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays TRY:IS_TRY;

CplusplusCPPASTTypeIdArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays TYPE:IS_TYPE;

CplusplusCPPASTUnaryExpressionArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays ADD:IS_ADD,
	plays ARITHMETIC:IS_ARITHMETIC,
	plays EXPRESSION:IS_EXPRESSION,
	plays FOR:IS_FOR,
	plays INCOMPLETE:IS_INCOMPLETE,
	plays SUBSTRACT:IS_SUBSTRACT,
	plays UNARY:IS_UNARY,
	plays UPDATE:IS_UPDATE;

CplusplusCPPASTWhileStatementArtifact sub CplusplusSourceArtifact,
	# Semantic
	plays STATEMENT:IS_STATEMENT,
	plays WHILE:IS_WHILE;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

AND sub relation,
	relates IS_AND;

ARGS_LIST sub relation,
	relates IS_ARGS_LIST;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

CALL sub relation,
	relates IS_CALL;

CALLEE sub relation,
	relates IS_CALLEE;

CASE sub relation,
	relates IS_CASE;

CATCH sub relation,
	relates IS_CATCH;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

DECLARATION sub relation,
	relates IS_DECLARATION;

DECREMENT sub relation,
	relates IS_DECREMENT;

DEFAULT sub relation,
	relates IS_DEFAULT;

DO_WHILE sub relation,
	relates IS_DO_WHILE;

ELSE sub relation,
	relates IS_ELSE;

ENTRY sub relation,
	relates IS_ENTRY;

ENUMERATION sub relation,
	relates IS_ENUMERATION;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FILE sub relation,
	relates IS_FILE;

FINALLY sub relation,
	relates IS_FINALLY;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GREATER_THAN sub relation,
	relates IS_GREATER_THAN;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTICAL sub relation,
	relates IS_IDENTICAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

INCREMENT sub relation,
	relates IS_INCREMENT;

INITIALIZATION sub relation,
	relates IS_INITIALIZATION;

INSTANCE sub relation,
	relates IS_INSTANCE;

ITERATOR sub relation,
	relates IS_ITERATOR;

KEY sub relation,
	relates IS_KEY;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN sub relation,
	relates IS_LESS_THAN;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MAP sub relation,
	relates IS_MAP;

MODULE sub relation,
	relates IS_MODULE;

NAME sub relation,
	relates IS_NAME;

NEGATIVE sub relation,
	relates IS_NEGATIVE;

NOOP sub relation,
	relates IS_NOOP;

NOT sub relation,
	relates IS_NOT;

NULL sub relation,
	relates IS_NULL;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PATHNAME sub relation,
	relates IS_PATHNAME;

POSITIONAL sub relation,
	relates IS_POSITIONAL;

POSTFIX sub relation,
	relates IS_POSTFIX;

PRIMITIVE sub relation,
	relates IS_PRIMITIVE;

QUALIFIED sub relation,
	relates IS_QUALIFIED;

RECEIVER sub relation,
	relates IS_RECEIVER;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

SCOPE sub relation,
	relates IS_SCOPE;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

SWITCH sub relation,
	relates IS_SWITCH;

THEN sub relation,
	relates IS_THEN;

TRY sub relation,
	relates IS_TRY;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UPDATE sub relation,
	relates IS_UPDATE;

VALUE sub relation,
	relates IS_VALUE;

VARIABLE sub relation,
	relates IS_VARIABLE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WHILE sub relation,
	relates IS_WHILE;

WORLD sub relation,
	relates IS_WORLD;
