define

##########---------- Entities ----------##########

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

AddArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ADD_ARITHMETIC_BINARY_OPERATOR,
	plays IS_ADD_ARITHMETIC_OPERATOR;

AliasArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER_IMPORT_PATHNAME;

AliasAsnameArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ALIAS_IDENTIFIER_IMPORT_PATHNAME;

AndArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_AND_BOOLEAN_OPERATOR;

AnnAssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_OPERATOR;

ArgArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_DECLARATION_FUNCTION_NAME;

ArgumentsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_DECLARATION_FUNCTION_INCOMPLETE;

AssertArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSERT_STATEMENT;

AssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_EXPRESSION;

AsyncForArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FOR_INCOMPLETE_ITERATOR_STATEMENT;

AsyncFunctionDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_IDENTIFIER_INCOMPLETE_NAME;

AsyncWithArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK_SCOPE_STATEMENT;

AttributeArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_IDENTIFIER;

AugAssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR;

AwaitArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_STATEMENT,
	plays IS_ARGUMENT_INCOMPLETE_STATEMENT_VALUE,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_STATEMENT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT_STATEMENT,
	plays IS_CONDITION_IF_INCOMPLETE_STATEMENT,
	plays IS_EXPRESSION_FOR_INCOMPLETE_STATEMENT,
	plays IS_EXPRESSION_INCOMPLETE_LEFT_STATEMENT,
	plays IS_FOR_INCOMPLETE_STATEMENT_UPDATE,
	plays IS_INCOMPLETE_LEFT_STATEMENT,
	plays IS_INCOMPLETE_MAP_STATEMENT_VALUE,
	plays IS_INCOMPLETE_RIGHT_STATEMENT,
	plays IS_INCOMPLETE_STATEMENT;

BinOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_BINARY_CALL_EXPRESSION_FUNCTION_NAME_POSITIONAL,
	plays IS_ARGUMENT_BINARY_CALL_EXPRESSION_POSITIONAL,
	plays IS_ARGUMENT_BINARY_DEFAULT_EXPRESSION,
	plays IS_ARGUMENT_BINARY_EXPRESSION_VALUE,
	plays IS_BINARY_BODY_ELSE_EXPRESSION_IF,
	plays IS_BINARY_BODY_EXPRESSION_IF_THEN,
	plays IS_BINARY_CALL_CALLEE_EXPRESSION,
	plays IS_BINARY_CALL_EXPRESSION,
	plays IS_BINARY_CONDITION_EXPRESSION_IF,
	plays IS_BINARY_CONDITION_EXPRESSION_WHILE,
	plays IS_BINARY_EXPRESSION,
	plays IS_BINARY_EXPRESSION_FOR,
	plays IS_BINARY_EXPRESSION_FOR_STATEMENT_UPDATE,
	plays IS_BINARY_EXPRESSION_KEY_MAP,
	plays IS_BINARY_EXPRESSION_LEFT,
	plays IS_BINARY_EXPRESSION_MAP_VALUE,
	plays IS_BINARY_EXPRESSION_RIGHT;

BitAndArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_AND_BINARY_BITWISE_OPERATOR,
	plays IS_AND_BITWISE_OPERATOR;

BitOrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY_BITWISE_OPERATOR_OR,
	plays IS_BITWISE_OPERATOR_OR;

BitXorArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY_BITWISE_OPERATOR_XOR,
	plays IS_BITWISE_OPERATOR_XOR;

BoolLiteralArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_BOOLEAN_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_BOOLEAN_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE,
	plays IS_ARGUMENT_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_VALUE,
	plays IS_BINARY_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_RIGHT,
	plays IS_BODY_BOOLEAN_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE,
	plays IS_BODY_BOOLEAN_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN,
	plays IS_BOOLEAN_CONDITION_EXPRESSION_IF_LITERAL_PRIMITIVE,
	plays IS_BOOLEAN_CONDITION_EXPRESSION_LITERAL_PRIMITIVE_WHILE,
	plays IS_BOOLEAN_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE,
	plays IS_BOOLEAN_EXPRESSION_LEFT_LITERAL_PRIMITIVE,
	plays IS_BOOLEAN_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE,
	plays IS_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE,
	plays IS_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

BoolOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_BOOLEAN_CALL_FUNCTION_INCOMPLETE_LITERAL_NAME_POSITIONAL,
	plays IS_ARGUMENT_BOOLEAN_INCOMPLETE_LITERAL_VALUE,
	plays IS_BINARY_BOOLEAN_EXPRESSION_INCOMPLETE_LEFT_LITERAL,
	plays IS_BINARY_BOOLEAN_EXPRESSION_INCOMPLETE_LITERAL_RIGHT,
	plays IS_BODY_BOOLEAN_ELSE_IF_INCOMPLETE_LITERAL,
	plays IS_BODY_BOOLEAN_IF_INCOMPLETE_LITERAL_THEN,
	plays IS_BOOLEAN_CALL_CALLEE_INCOMPLETE_LITERAL,
	plays IS_BOOLEAN_CONDITION_IF_INCOMPLETE_LITERAL,
	plays IS_BOOLEAN_CONDITION_INCOMPLETE_LITERAL_WHILE,
	plays IS_BOOLEAN_EXPRESSION_FOR_INCOMPLETE_LITERAL,
	plays IS_BOOLEAN_EXPRESSION_INCOMPLETE_LEFT_LITERAL,
	plays IS_BOOLEAN_FOR_INCOMPLETE_LITERAL_STATEMENT_UPDATE,
	plays IS_BOOLEAN_INCOMPLETE_KEY_LITERAL_MAP,
	plays IS_BOOLEAN_INCOMPLETE_LEFT_LITERAL,
	plays IS_BOOLEAN_INCOMPLETE_LITERAL,
	plays IS_BOOLEAN_INCOMPLETE_LITERAL_MAP_VALUE,
	plays IS_BOOLEAN_INCOMPLETE_LITERAL_RIGHT;

BreakArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BREAK_STATEMENT;

BytesArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_BYTE_STRING_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_BYTE_STRING_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE,
	plays IS_ARGUMENT_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_VALUE,
	plays IS_BINARY_BYTE_STRING_EXPRESSION_LEFT_LITERAL_PRIMITIVE,
	plays IS_BINARY_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_RIGHT,
	plays IS_BODY_BYTE_STRING_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE,
	plays IS_BODY_BYTE_STRING_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN,
	plays IS_BYTE_STRING_EXPRESSION_FOR_LITERAL_PRIMITIVE,
	plays IS_BYTE_STRING_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_UPDATE,
	plays IS_BYTE_STRING_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE,
	plays IS_BYTE_STRING_EXPRESSION_LEFT_LITERAL_PRIMITIVE,
	plays IS_BYTE_STRING_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE,
	plays IS_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE,
	plays IS_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

CallArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_DEFAULT_EXPRESSION_FUNCTION,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_NAME_POSITIONAL,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_POSITIONAL,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_VALUE,
	plays IS_BINARY_CALL_EXPRESSION_FUNCTION_LEFT,
	plays IS_BINARY_CALL_EXPRESSION_FUNCTION_RIGHT,
	plays IS_BODY_CALL_ELSE_EXPRESSION_FUNCTION_IF,
	plays IS_BODY_CALL_EXPRESSION_FUNCTION_IF_THEN,
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION,
	plays IS_CALL_CONDITION_EXPRESSION_FUNCTION_IF,
	plays IS_CALL_CONDITION_EXPRESSION_FUNCTION_WHILE,
	plays IS_CALL_EXPRESSION_FOR_FUNCTION,
	plays IS_CALL_EXPRESSION_FOR_FUNCTION_STATEMENT_UPDATE,
	plays IS_CALL_EXPRESSION_FUNCTION,
	plays IS_CALL_EXPRESSION_FUNCTION_KEY_MAP,
	plays IS_CALL_EXPRESSION_FUNCTION_LEFT,
	plays IS_CALL_EXPRESSION_FUNCTION_MAP_VALUE,
	plays IS_CALL_EXPRESSION_FUNCTION_RIGHT;

ClassDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION_IDENTIFIER_STATEMENT_TYPE;

ClassDefBasesArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BASE_DECLARATION_TYPE;

ClassDefBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_DECLARATION_TYPE;

ClassDefDecoratorListArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CALL_DECLARATION_INCOMPLETE_TYPE;

CompareArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_BINARY_CALL_CONDITION_EXPRESSION_FUNCTION_NAME_POSITIONAL,
	plays IS_ARGUMENT_BINARY_CALL_CONDITION_EXPRESSION_POSITIONAL,
	plays IS_ARGUMENT_BINARY_CONDITION_DEFAULT_EXPRESSION,
	plays IS_ARGUMENT_BINARY_CONDITION_EXPRESSION_VALUE,
	plays IS_BINARY_BODY_CONDITION_ELSE_EXPRESSION_IF,
	plays IS_BINARY_BODY_CONDITION_EXPRESSION_IF_THEN,
	plays IS_BINARY_CONDITION_EXPRESSION,
	plays IS_BINARY_CONDITION_EXPRESSION_IF,
	plays IS_BINARY_CONDITION_EXPRESSION_LEFT,
	plays IS_BINARY_CONDITION_EXPRESSION_MAP_VALUE,
	plays IS_BINARY_CONDITION_EXPRESSION_RIGHT,
	plays IS_BINARY_CONDITION_EXPRESSION_WHILE;

CompareComparatorsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_RIGHT;

CompareOpsArtifact sub PythonSourceArtifact;

ComprehensionArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_FOR_INCOMPLETE_ITERATOR;

ContinueArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CONTINUE_STATEMENT;

DeleteArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_STATEMENT;

DictArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_MAP_NAME_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_MAP_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE,
	plays IS_BINARY_EXPRESSION_LITERAL_MAP_PRIMITIVE_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IF_LITERAL_MAP_PRIMITIVE,
	plays IS_BODY_EXPRESSION_IF_LITERAL_MAP_PRIMITIVE_THEN,
	plays IS_EXPRESSION_LEFT_LITERAL_MAP_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_MAP_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_RIGHT,
	plays IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE;

DictCompArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_MAP_NAME_POSITIONAL,
	plays IS_ARGUMENT_EXPRESSION_FOR_MAP_VALUE,
	plays IS_BODY_ELSE_EXPRESSION_FOR_IF_MAP,
	plays IS_BODY_EXPRESSION_FOR_IF_MAP_THEN,
	plays IS_EXPRESSION_FOR_LEFT_MAP,
	plays IS_EXPRESSION_FOR_MAP,
	plays IS_EXPRESSION_FOR_MAP_RIGHT,
	plays IS_EXPRESSION_FOR_MAP_VALUE;

DivArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_DIVIDE_OPERATOR,
	plays IS_ARITHMETIC_DIVIDE_OPERATOR;

EllipsisArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_IDENTIFIER_INCOMPLETE_NAME_POSITIONAL,
	plays IS_ARGUMENT_DEFAULT_IDENTIFIER_INCOMPLETE,
	plays IS_BODY_IDENTIFIER_IF_INCOMPLETE_THEN,
	plays IS_IDENTIFIER_INCOMPLETE,
	plays IS_IDENTIFIER_INCOMPLETE_RIGHT;

EqArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EQUAL_OPERATOR_RELATIONAL;

ExceptHandlerArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CATCH_IDENTIFIER_TRY;

ExecArtifact sub PythonSourceArtifact;

ExprArtifact sub PythonSourceArtifact;

ExtSliceArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_INCOMPLETE;

FloorDivArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_DIVIDE_INCOMPLETE_OPERATOR,
	plays IS_ARITHMETIC_DIVIDE_INCOMPLETE_OPERATOR;

ForArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FOR_ITERATOR_STATEMENT;

ForBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_FOR,
	plays IS_BODY_WHILE;

FormattedValueArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_INCOMPLETE;

ForOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_ELSE_FOR,
	plays IS_BODY_ELSE_WHILE;

FunctionDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_IDENTIFIER_NAME;

FunctionDefBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_DECLARATION_FUNCTION;

FunctionDefDecoratorsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION_FUNCTION_INCOMPLETE;

GeneratorExpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_NAME_POSITIONAL,
	plays IS_ARGUMENT_VALUE,
	plays IS_BODY_ELSE_IF,
	plays IS_BODY_IF_THEN,
	plays IS_EXPRESSION_FOR,
	plays IS_FOR_STATEMENT_UPDATE;

GlobalArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_STATEMENT_VISIBILITY_WORLD;

GtArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_GREATER_THAN_OPERATOR_RELATIONAL;

GtEArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

IfArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_IF;

IfBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_IF_THEN;

IfExpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_IF_NAME_POSITIONAL,
	plays IS_ARGUMENT_EXPRESSION_IF_VALUE,
	plays IS_BINARY_EXPRESSION_IF_LEFT,
	plays IS_BINARY_EXPRESSION_IF_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IF,
	plays IS_BODY_EXPRESSION_IF_THEN,
	plays IS_CALL_CALLEE_EXPRESSION_IF,
	plays IS_CALL_EXPRESSION_IF,
	plays IS_CONDITION_EXPRESSION_IF,
	plays IS_CONDITION_EXPRESSION_IF_WHILE,
	plays IS_EXPRESSION_FOR_IF,
	plays IS_EXPRESSION_FOR_IF_STATEMENT_UPDATE,
	plays IS_EXPRESSION_IF,
	plays IS_EXPRESSION_IF_KEY_MAP,
	plays IS_EXPRESSION_IF_LEFT,
	plays IS_EXPRESSION_IF_MAP_VALUE,
	plays IS_EXPRESSION_IF_RIGHT;

IfOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_ELSE_IF;

ImportArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION_IMPORT_STATEMENT;

ImportFromArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION_IMPORT_STATEMENT;

ImportFromLevelArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IMPORT_INCOMPLETE;

ImportFromModuleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER_IMPORT_PATHNAME;

ImportFromNamesArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER_IMPORT_INCOMPLETE_PATHNAME;

InArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CONTAINS_OPERATOR_RELATIONAL;

IndexArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_INCOMPLETE;

InvertArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BITWISE_NOT_OPERATOR_UNARY;

IsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTICAL_OPERATOR_RELATIONAL;

IsNotArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTICAL_NOT_OPERATOR_RELATIONAL;

JoinedStrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_INCOMPLETE_LITERAL_NAME_POSITIONAL_PRIMITIVE_STRING,
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_STRING_VALUE,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE_STRING,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT_STRING,
	plays IS_BODY_ELSE_EXPRESSION_IF_INCOMPLETE_LITERAL_PRIMITIVE_STRING,
	plays IS_BODY_EXPRESSION_IF_INCOMPLETE_LITERAL_PRIMITIVE_STRING_THEN,
	plays IS_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE_STRING,
	plays IS_EXPRESSION_INCOMPLETE_LITERAL_MAP_PRIMITIVE_STRING_VALUE,
	plays IS_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT_STRING,
	plays IS_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_STRING;

KeywordArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_NAME,
	plays IS_INCOMPLETE_NAME;

KwargArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST_DECLARATION_FUNCTION_MAP_NAME;

KwonlyArgArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_DECLARATION_FUNCTION_INCOMPLETE_NAME;

LambdaArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANONYMOUS_ARGUMENT_CALL_DECLARATION_FUNCTION_NAME_POSITIONAL_VALUE,
	plays IS_ANONYMOUS_ARGUMENT_DECLARATION_DEFAULT_FUNCTION_VALUE,
	plays IS_ANONYMOUS_ARGUMENT_DECLARATION_FUNCTION_VALUE,
	plays IS_ANONYMOUS_BODY_DECLARATION_ELSE_FUNCTION_IF_VALUE,
	plays IS_ANONYMOUS_BODY_DECLARATION_FUNCTION_IF_THEN_VALUE,
	plays IS_ANONYMOUS_CALL_CALLEE_DECLARATION_FUNCTION_VALUE,
	plays IS_ANONYMOUS_DECLARATION_FUNCTION_MAP_VALUE,
	plays IS_ANONYMOUS_DECLARATION_FUNCTION_RIGHT_VALUE,
	plays IS_ANONYMOUS_DECLARATION_FUNCTION_VALUE;

ListArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_LIST_LITERAL_NOOP_PRIMITIVE,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LIST_LITERAL_NAME_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LIST_LITERAL_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_LIST_LITERAL_PRIMITIVE_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LIST_LITERAL_PRIMITIVE,
	plays IS_BINARY_EXPRESSION_LIST_LITERAL_PRIMITIVE_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IF_LIST_LITERAL_PRIMITIVE,
	plays IS_BODY_EXPRESSION_IF_LIST_LITERAL_PRIMITIVE_THEN,
	plays IS_EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE,
	plays IS_EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE_STATEMENT_UPDATE,
	plays IS_EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE_UPDATE,
	plays IS_EXPRESSION_LEFT_LIST_LITERAL_PRIMITIVE,
	plays IS_EXPRESSION_LIST_LITERAL_MAP_PRIMITIVE_VALUE,
	plays IS_EXPRESSION_LIST_LITERAL_PRIMITIVE,
	plays IS_EXPRESSION_LIST_LITERAL_PRIMITIVE_RIGHT;

ListCompArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_LIST_NAME_POSITIONAL,
	plays IS_ARGUMENT_EXPRESSION_FOR_LIST_VALUE,
	plays IS_BINARY_EXPRESSION_FOR_LEFT_LIST,
	plays IS_BINARY_EXPRESSION_FOR_LIST_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_FOR_IF_LIST,
	plays IS_BODY_EXPRESSION_FOR_IF_LIST_THEN,
	plays IS_CONDITION_EXPRESSION_FOR_IF_LIST,
	plays IS_EXPRESSION_FOR_LEFT_LIST,
	plays IS_EXPRESSION_FOR_LIST,
	plays IS_EXPRESSION_FOR_LIST_MAP_VALUE,
	plays IS_EXPRESSION_FOR_LIST_RIGHT,
	plays IS_EXPRESSION_FOR_LIST_STATEMENT_UPDATE;

LShiftArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY_BITWISE_LEFT_SHIFT_OPERATOR,
	plays IS_BITWISE_LEFT_SHIFT_OPERATOR;

LtArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_LESS_THAN_OPERATOR_RELATIONAL;

LtEArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_LESS_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

MatMultArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_INCOMPLETE_MULTIPLY_OPERATOR,
	plays IS_ARITHMETIC_INCOMPLETE_MULTIPLY_OPERATOR;

ModArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_MODULE_OPERATOR,
	plays IS_ARITHMETIC_MODULE_OPERATOR;

ModuleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FILE_MODULE;

MultArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_MULTIPLY_OPERATOR,
	plays IS_ARITHMETIC_MULTIPLY_OPERATOR;

NameArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_IDENTIFIER_NOOP,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_IDENTIFIER_NAME_POSITIONAL,
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_IDENTIFIER,
	plays IS_ARGUMENT_EXPRESSION_IDENTIFIER_VALUE,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IDENTIFIER_IF,
	plays IS_BODY_EXPRESSION_IDENTIFIER_IF_THEN,
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER,
	plays IS_CALL_EXPRESSION_IDENTIFIER,
	plays IS_CONDITION_EXPRESSION_IDENTIFIER_IF,
	plays IS_CONDITION_EXPRESSION_IDENTIFIER_WHILE,
	plays IS_EXPRESSION_FOR_IDENTIFIER,
	plays IS_EXPRESSION_FOR_IDENTIFIER_STATEMENT_UPDATE,
	plays IS_EXPRESSION_FOR_IDENTIFIER_UPDATE,
	plays IS_EXPRESSION_IDENTIFIER,
	plays IS_EXPRESSION_IDENTIFIER_KEY_MAP,
	plays IS_EXPRESSION_IDENTIFIER_LEFT,
	plays IS_EXPRESSION_IDENTIFIER_MAP_VALUE,
	plays IS_EXPRESSION_IDENTIFIER_RIGHT;

NoneLiteralArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_LITERAL_NOOP_NULL_PRIMITIVE,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NULL_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_NULL_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_NULL_PRIMITIVE_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_NULL_PRIMITIVE,
	plays IS_BINARY_EXPRESSION_LITERAL_NULL_PRIMITIVE_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE,
	plays IS_BODY_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE_THEN,
	plays IS_CONDITION_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE,
	plays IS_EXPRESSION_KEY_LITERAL_MAP_NULL_PRIMITIVE,
	plays IS_EXPRESSION_LEFT_LITERAL_NULL_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_MAP_NULL_PRIMITIVE_VALUE,
	plays IS_EXPRESSION_LITERAL_NULL_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_NULL_PRIMITIVE_RIGHT;

NonlocalArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE_MODULE_STATEMENT_VISIBILITY;

NoopLineArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_COMMENT_NOOP;

NoopSameLineArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_COMMENT_NOOP;

NotArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BOOLEAN_NOT_OPERATOR;

NotEqArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EQUAL_NOT_OPERATOR_RELATIONAL;

NotInArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CONTAINS_NOT_OPERATOR_RELATIONAL;

NumArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_LITERAL_NOOP_NUMBER_PRIMITIVE,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_NUMBER_PRIMITIVE,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE,
	plays IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE,
	plays IS_BODY_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE_THEN,
	plays IS_CONDITION_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE,
	plays IS_CONDITION_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_WHILE,
	plays IS_EXPRESSION_KEY_LITERAL_MAP_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_MAP_NUMBER_PRIMITIVE_VALUE,
	plays IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE,
	plays IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

OrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BOOLEAN_OPERATOR_OR;

PassArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_NOOP_STATEMENT;

PowArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_INCOMPLETE_OPERATOR,
	plays IS_ARITHMETIC_INCOMPLETE_OPERATOR;

PreviousNoopsArtifact sub PythonSourceArtifact;

PrintArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER;

QualifiedIdentifierArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_IDENTIFIER_NOOP_QUALIFIED,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_IDENTIFIER_NAME_POSITIONAL_QUALIFIED,
	plays IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL_QUALIFIED,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_IDENTIFIER_QUALIFIED,
	plays IS_ARGUMENT_EXPRESSION_IDENTIFIER_QUALIFIED_VALUE,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_LEFT_QUALIFIED,
	plays IS_BINARY_EXPRESSION_IDENTIFIER_QUALIFIED_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IDENTIFIER_IF_QUALIFIED,
	plays IS_BODY_EXPRESSION_IDENTIFIER_IF_QUALIFIED_THEN,
	plays IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED,
	plays IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED,
	plays IS_CONDITION_EXPRESSION_IDENTIFIER_IF_QUALIFIED,
	plays IS_CONDITION_EXPRESSION_IDENTIFIER_QUALIFIED_WHILE,
	plays IS_EXPRESSION_FOR_IDENTIFIER_QUALIFIED,
	plays IS_EXPRESSION_FOR_IDENTIFIER_QUALIFIED_STATEMENT_UPDATE,
	plays IS_EXPRESSION_FOR_IDENTIFIER_QUALIFIED_UPDATE,
	plays IS_EXPRESSION_IDENTIFIER_KEY_MAP_QUALIFIED,
	plays IS_EXPRESSION_IDENTIFIER_LEFT_QUALIFIED,
	plays IS_EXPRESSION_IDENTIFIER_MAP_QUALIFIED_VALUE,
	plays IS_EXPRESSION_IDENTIFIER_QUALIFIED,
	plays IS_EXPRESSION_IDENTIFIER_QUALIFIED_RIGHT;

RaiseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_STATEMENT_THROW;

RemainderNoopsArtifact sub PythonSourceArtifact;

ReturnArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_RETURN_STATEMENT;

RShiftArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY_BITWISE_OPERATOR_RIGHT_SHIFT,
	plays IS_BITWISE_OPERATOR_RIGHT_SHIFT;

SameLineNoopsArtifact sub PythonSourceArtifact;

SetArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_SET,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_SET,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_SET_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_SET,
	plays IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_SET,
	plays IS_BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_SET,
	plays IS_BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_SET_THEN,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_SET,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_SET_STATEMENT_UPDATE,
	plays IS_EXPRESSION_LEFT_LITERAL_PRIMITIVE_SET,
	plays IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_SET_VALUE,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_SET,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_SET;

SetCompArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_NAME_POSITIONAL_SET,
	plays IS_ARGUMENT_EXPRESSION_FOR_SET_VALUE,
	plays IS_BINARY_EXPRESSION_FOR_LEFT_SET,
	plays IS_BINARY_EXPRESSION_FOR_RIGHT_SET,
	plays IS_BODY_EXPRESSION_FOR_IF_SET_THEN,
	plays IS_EXPRESSION_FOR_LEFT_SET,
	plays IS_EXPRESSION_FOR_MAP_SET_VALUE,
	plays IS_EXPRESSION_FOR_RIGHT_SET,
	plays IS_EXPRESSION_FOR_SET;

SliceArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_INCOMPLETE;

StarredArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_NAME_POSITIONAL;

StrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_LITERAL_NOOP_PRIMITIVE_STRING,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_STRING,
	plays IS_ARGUMENT_CALL_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_STRING,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_STRING,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_STRING_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING,
	plays IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING,
	plays IS_BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING,
	plays IS_BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING_THEN,
	plays IS_CALL_EXPRESSION_LITERAL_PRIMITIVE_STRING,
	plays IS_CONDITION_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_STRING_UPDATE,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_STRING,
	plays IS_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE_STRING,
	plays IS_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING,
	plays IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_STRING_VALUE,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_STRING;

SubArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC_BINARY_OPERATOR_SUBSTRACT,
	plays IS_ARITHMETIC_OPERATOR_SUBSTRACT;

SubscriptArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION_EXPRESSION_INCOMPLETE_NOOP,
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_INCOMPLETE_NAME_POSITIONAL,
	plays IS_ARGUMENT_CALL_EXPRESSION_INCOMPLETE_POSITIONAL,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_INCOMPLETE,
	plays IS_ARGUMENT_EXPRESSION_INCOMPLETE_VALUE,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT,
	plays IS_BODY_ELSE_EXPRESSION_IF_INCOMPLETE,
	plays IS_BODY_EXPRESSION_IF_INCOMPLETE_THEN,
	plays IS_CALL_CALLEE_EXPRESSION_INCOMPLETE,
	plays IS_CALL_EXPRESSION_INCOMPLETE,
	plays IS_CONDITION_EXPRESSION_IF_INCOMPLETE,
	plays IS_CONDITION_EXPRESSION_INCOMPLETE_WHILE,
	plays IS_EXPRESSION_FOR_INCOMPLETE,
	plays IS_EXPRESSION_FOR_INCOMPLETE_STATEMENT_UPDATE,
	plays IS_EXPRESSION_FOR_INCOMPLETE_UPDATE,
	plays IS_EXPRESSION_INCOMPLETE,
	plays IS_EXPRESSION_INCOMPLETE_KEY_MAP,
	plays IS_EXPRESSION_INCOMPLETE_LEFT,
	plays IS_EXPRESSION_INCOMPLETE_MAP_VALUE,
	plays IS_EXPRESSION_INCOMPLETE_RIGHT;

TryArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_STATEMENT_TRY;

TryBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY_TRY;

TryElseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ELSE_TRY;

TryExceptArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CATCH_STATEMENT_TRY;

TryFinalbodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FINALLY_TRY;

TryFinallyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FINALLY_STATEMENT_TRY;

TryHandlersArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CATCH_TRY;

TupleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_TUPLE,
	plays IS_ARGUMENT_CALL_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_TUPLE,
	plays IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_TUPLE,
	plays IS_ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_TUPLE_VALUE,
	plays IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_TUPLE,
	plays IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_TUPLE,
	plays IS_BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_TUPLE,
	plays IS_BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN_TUPLE,
	plays IS_CALL_EXPRESSION_LITERAL_PRIMITIVE_TUPLE,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_TUPLE_UPDATE,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_TUPLE,
	plays IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_TUPLE_UPDATE,
	plays IS_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE_TUPLE,
	plays IS_EXPRESSION_LEFT_LITERAL_PRIMITIVE_TUPLE,
	plays IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_TUPLE_VALUE,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_TUPLE,
	plays IS_EXPRESSION_LITERAL_PRIMITIVE_TUPLE;

UAddArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BITWISE_OPERATOR_POSITIVE_UNARY;

UnaryOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_BOOLEAN_CALL_EXPRESSION_FUNCTION_NAME_OPERATOR_POSITIONAL_UNARY,
	plays IS_ARGUMENT_BOOLEAN_DEFAULT_EXPRESSION_OPERATOR_UNARY,
	plays IS_ARGUMENT_BOOLEAN_EXPRESSION_OPERATOR_UNARY_VALUE,
	plays IS_BINARY_BOOLEAN_EXPRESSION_LEFT_OPERATOR_UNARY,
	plays IS_BINARY_BOOLEAN_EXPRESSION_OPERATOR_RIGHT_UNARY,
	plays IS_BODY_BOOLEAN_ELSE_EXPRESSION_IF_OPERATOR_UNARY,
	plays IS_BODY_BOOLEAN_EXPRESSION_IF_OPERATOR_THEN_UNARY,
	plays IS_BOOLEAN_CONDITION_EXPRESSION_IF_OPERATOR_UNARY,
	plays IS_BOOLEAN_CONDITION_EXPRESSION_OPERATOR_UNARY_WHILE,
	plays IS_BOOLEAN_EXPRESSION_KEY_MAP_OPERATOR_UNARY,
	plays IS_BOOLEAN_EXPRESSION_LEFT_OPERATOR_UNARY,
	plays IS_BOOLEAN_EXPRESSION_MAP_OPERATOR_UNARY_VALUE,
	plays IS_BOOLEAN_EXPRESSION_OPERATOR_RIGHT_UNARY,
	plays IS_BOOLEAN_EXPRESSION_OPERATOR_UNARY;

USubArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BITWISE_NEGATIVE_OPERATOR_UNARY;

VarargArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST_DECLARATION_FUNCTION_LIST_NAME;

WhileArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_STATEMENT_WHILE;

WithArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK_SCOPE_STATEMENT;

WithBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK_BODY_INCOMPLETE_SCOPE;

WithitemArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION_IDENTIFIER_INCOMPLETE;

WithItemsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK_INCOMPLETE_SCOPE;

YieldArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_RETURN_STATEMENT,
	plays IS_INCOMPLETE_LEFT_RETURN_STATEMENT,
	plays IS_INCOMPLETE_RETURN_RIGHT_STATEMENT,
	plays IS_INCOMPLETE_RETURN_STATEMENT;

YieldFromArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_RETURN_STATEMENT,
	plays IS_CONDITION_IF_INCOMPLETE_RETURN_STATEMENT,
	plays IS_FOR_INCOMPLETE_RETURN_STATEMENT_UPDATE,
	plays IS_INCOMPLETE_RETURN_RIGHT_STATEMENT,
	plays IS_INCOMPLETE_RETURN_STATEMENT;

##########---------- Semantic Roles ----------##########
ADD_ARITHMETIC_BINARY_OPERATOR sub relation,
	relates IS_ADD_ARITHMETIC_BINARY_OPERATOR;

ADD_ARITHMETIC_OPERATOR sub relation,
	relates IS_ADD_ARITHMETIC_OPERATOR;

ALIAS_IDENTIFIER_IMPORT_PATHNAME sub relation,
	relates IS_ALIAS_IDENTIFIER_IMPORT_PATHNAME;

AND_BINARY_BITWISE_OPERATOR sub relation,
	relates IS_AND_BINARY_BITWISE_OPERATOR;

AND_BITWISE_OPERATOR sub relation,
	relates IS_AND_BITWISE_OPERATOR;

AND_BOOLEAN_OPERATOR sub relation,
	relates IS_AND_BOOLEAN_OPERATOR;

ANNOTATION_EXPRESSION_IDENTIFIER_NOOP sub relation,
	relates IS_ANNOTATION_EXPRESSION_IDENTIFIER_NOOP;

ANNOTATION_EXPRESSION_IDENTIFIER_NOOP_QUALIFIED sub relation,
	relates IS_ANNOTATION_EXPRESSION_IDENTIFIER_NOOP_QUALIFIED;

ANNOTATION_EXPRESSION_INCOMPLETE_NOOP sub relation,
	relates IS_ANNOTATION_EXPRESSION_INCOMPLETE_NOOP;

ANNOTATION_EXPRESSION_LIST_LITERAL_NOOP_PRIMITIVE sub relation,
	relates IS_ANNOTATION_EXPRESSION_LIST_LITERAL_NOOP_PRIMITIVE;

ANNOTATION_EXPRESSION_LITERAL_NOOP_NULL_PRIMITIVE sub relation,
	relates IS_ANNOTATION_EXPRESSION_LITERAL_NOOP_NULL_PRIMITIVE;

ANNOTATION_EXPRESSION_LITERAL_NOOP_NUMBER_PRIMITIVE sub relation,
	relates IS_ANNOTATION_EXPRESSION_LITERAL_NOOP_NUMBER_PRIMITIVE;

ANNOTATION_EXPRESSION_LITERAL_NOOP_PRIMITIVE_STRING sub relation,
	relates IS_ANNOTATION_EXPRESSION_LITERAL_NOOP_PRIMITIVE_STRING;

ANONYMOUS_ARGUMENT_CALL_DECLARATION_FUNCTION_NAME_POSITIONAL_VALUE sub relation,
	relates IS_ANONYMOUS_ARGUMENT_CALL_DECLARATION_FUNCTION_NAME_POSITIONAL_VALUE;

ANONYMOUS_ARGUMENT_DECLARATION_DEFAULT_FUNCTION_VALUE sub relation,
	relates IS_ANONYMOUS_ARGUMENT_DECLARATION_DEFAULT_FUNCTION_VALUE;

ANONYMOUS_ARGUMENT_DECLARATION_FUNCTION_VALUE sub relation,
	relates IS_ANONYMOUS_ARGUMENT_DECLARATION_FUNCTION_VALUE;

ANONYMOUS_BODY_DECLARATION_ELSE_FUNCTION_IF_VALUE sub relation,
	relates IS_ANONYMOUS_BODY_DECLARATION_ELSE_FUNCTION_IF_VALUE;

ANONYMOUS_BODY_DECLARATION_FUNCTION_IF_THEN_VALUE sub relation,
	relates IS_ANONYMOUS_BODY_DECLARATION_FUNCTION_IF_THEN_VALUE;

ANONYMOUS_CALL_CALLEE_DECLARATION_FUNCTION_VALUE sub relation,
	relates IS_ANONYMOUS_CALL_CALLEE_DECLARATION_FUNCTION_VALUE;

ANONYMOUS_DECLARATION_FUNCTION_MAP_VALUE sub relation,
	relates IS_ANONYMOUS_DECLARATION_FUNCTION_MAP_VALUE;

ANONYMOUS_DECLARATION_FUNCTION_RIGHT_VALUE sub relation,
	relates IS_ANONYMOUS_DECLARATION_FUNCTION_RIGHT_VALUE;

ANONYMOUS_DECLARATION_FUNCTION_VALUE sub relation,
	relates IS_ANONYMOUS_DECLARATION_FUNCTION_VALUE;

ARGS_LIST_DECLARATION_FUNCTION_LIST_NAME sub relation,
	relates IS_ARGS_LIST_DECLARATION_FUNCTION_LIST_NAME;

ARGS_LIST_DECLARATION_FUNCTION_MAP_NAME sub relation,
	relates IS_ARGS_LIST_DECLARATION_FUNCTION_MAP_NAME;

ARGUMENT_BINARY_CALL_CONDITION_EXPRESSION_FUNCTION_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_CALL_CONDITION_EXPRESSION_FUNCTION_NAME_POSITIONAL;

ARGUMENT_BINARY_CALL_CONDITION_EXPRESSION_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_CALL_CONDITION_EXPRESSION_POSITIONAL;

ARGUMENT_BINARY_CALL_EXPRESSION_FUNCTION_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_CALL_EXPRESSION_FUNCTION_NAME_POSITIONAL;

ARGUMENT_BINARY_CALL_EXPRESSION_POSITIONAL sub relation,
	relates IS_ARGUMENT_BINARY_CALL_EXPRESSION_POSITIONAL;

ARGUMENT_BINARY_CONDITION_DEFAULT_EXPRESSION sub relation,
	relates IS_ARGUMENT_BINARY_CONDITION_DEFAULT_EXPRESSION;

ARGUMENT_BINARY_CONDITION_EXPRESSION_VALUE sub relation,
	relates IS_ARGUMENT_BINARY_CONDITION_EXPRESSION_VALUE;

ARGUMENT_BINARY_DEFAULT_EXPRESSION sub relation,
	relates IS_ARGUMENT_BINARY_DEFAULT_EXPRESSION;

ARGUMENT_BINARY_EXPRESSION_VALUE sub relation,
	relates IS_ARGUMENT_BINARY_EXPRESSION_VALUE;

ARGUMENT_BOOLEAN_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_BOOLEAN_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE;

ARGUMENT_BOOLEAN_CALL_EXPRESSION_FUNCTION_NAME_OPERATOR_POSITIONAL_UNARY sub relation,
	relates IS_ARGUMENT_BOOLEAN_CALL_EXPRESSION_FUNCTION_NAME_OPERATOR_POSITIONAL_UNARY;

ARGUMENT_BOOLEAN_CALL_FUNCTION_INCOMPLETE_LITERAL_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_BOOLEAN_CALL_FUNCTION_INCOMPLETE_LITERAL_NAME_POSITIONAL;

ARGUMENT_BOOLEAN_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_BOOLEAN_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE;

ARGUMENT_BOOLEAN_DEFAULT_EXPRESSION_OPERATOR_UNARY sub relation,
	relates IS_ARGUMENT_BOOLEAN_DEFAULT_EXPRESSION_OPERATOR_UNARY;

ARGUMENT_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_VALUE sub relation,
	relates IS_ARGUMENT_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_VALUE;

ARGUMENT_BOOLEAN_EXPRESSION_OPERATOR_UNARY_VALUE sub relation,
	relates IS_ARGUMENT_BOOLEAN_EXPRESSION_OPERATOR_UNARY_VALUE;

ARGUMENT_BOOLEAN_INCOMPLETE_LITERAL_VALUE sub relation,
	relates IS_ARGUMENT_BOOLEAN_INCOMPLETE_LITERAL_VALUE;

ARGUMENT_BYTE_STRING_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_BYTE_STRING_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE;

ARGUMENT_BYTE_STRING_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_BYTE_STRING_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE;

ARGUMENT_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_VALUE sub relation,
	relates IS_ARGUMENT_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_VALUE;

ARGUMENT_CALL_DEFAULT_EXPRESSION_FUNCTION sub relation,
	relates IS_ARGUMENT_CALL_DEFAULT_EXPRESSION_FUNCTION;

ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_LIST_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_LIST_NAME_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_MAP_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_MAP_NAME_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_NAME_POSITIONAL_SET sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FOR_FUNCTION_NAME_POSITIONAL_SET;

ARGUMENT_CALL_EXPRESSION_FUNCTION_IDENTIFIER_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_IDENTIFIER_NAME_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FUNCTION_IDENTIFIER_NAME_POSITIONAL_QUALIFIED sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_IDENTIFIER_NAME_POSITIONAL_QUALIFIED;

ARGUMENT_CALL_EXPRESSION_FUNCTION_IF_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_IF_NAME_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FUNCTION_INCOMPLETE_LITERAL_NAME_POSITIONAL_PRIMITIVE_STRING sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_INCOMPLETE_LITERAL_NAME_POSITIONAL_PRIMITIVE_STRING;

ARGUMENT_CALL_EXPRESSION_FUNCTION_INCOMPLETE_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_INCOMPLETE_NAME_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LIST_LITERAL_NAME_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LIST_LITERAL_NAME_POSITIONAL_PRIMITIVE;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_MAP_NAME_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_MAP_NAME_POSITIONAL_PRIMITIVE;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NULL_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NULL_POSITIONAL_PRIMITIVE;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_NUMBER_POSITIONAL_PRIMITIVE;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_SET sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_SET;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_STRING sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_STRING;

ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_TUPLE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_LITERAL_NAME_POSITIONAL_PRIMITIVE_TUPLE;

ARGUMENT_CALL_EXPRESSION_FUNCTION_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_NAME_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FUNCTION_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_FUNCTION_VALUE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_FUNCTION_VALUE;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL_QUALIFIED sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_IDENTIFIER_POSITIONAL_QUALIFIED;

ARGUMENT_CALL_EXPRESSION_INCOMPLETE_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_INCOMPLETE_POSITIONAL;

ARGUMENT_CALL_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_STRING sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_STRING;

ARGUMENT_CALL_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_TUPLE sub relation,
	relates IS_ARGUMENT_CALL_EXPRESSION_LITERAL_POSITIONAL_PRIMITIVE_TUPLE;

ARGUMENT_CALL_FUNCTION_IDENTIFIER_INCOMPLETE_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_FUNCTION_IDENTIFIER_INCOMPLETE_NAME_POSITIONAL;

ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_RETURN_STATEMENT sub relation,
	relates IS_ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_RETURN_STATEMENT;

ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_STATEMENT sub relation,
	relates IS_ARGUMENT_CALL_FUNCTION_INCOMPLETE_NAME_POSITIONAL_STATEMENT;

ARGUMENT_CALL_FUNCTION_NAME sub relation,
	relates IS_ARGUMENT_CALL_FUNCTION_NAME;

ARGUMENT_CALL_FUNCTION_NAME_POSITIONAL sub relation,
	relates IS_ARGUMENT_CALL_FUNCTION_NAME_POSITIONAL;

ARGUMENT_DECLARATION_FUNCTION_INCOMPLETE sub relation,
	relates IS_ARGUMENT_DECLARATION_FUNCTION_INCOMPLETE;

ARGUMENT_DECLARATION_FUNCTION_INCOMPLETE_NAME sub relation,
	relates IS_ARGUMENT_DECLARATION_FUNCTION_INCOMPLETE_NAME;

ARGUMENT_DECLARATION_FUNCTION_NAME sub relation,
	relates IS_ARGUMENT_DECLARATION_FUNCTION_NAME;

ARGUMENT_DEFAULT_EXPRESSION_IDENTIFIER sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_IDENTIFIER;

ARGUMENT_DEFAULT_EXPRESSION_IDENTIFIER_QUALIFIED sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_IDENTIFIER_QUALIFIED;

ARGUMENT_DEFAULT_EXPRESSION_INCOMPLETE sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_INCOMPLETE;

ARGUMENT_DEFAULT_EXPRESSION_LIST_LITERAL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LIST_LITERAL_PRIMITIVE;

ARGUMENT_DEFAULT_EXPRESSION_LITERAL_MAP_PRIMITIVE sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_MAP_PRIMITIVE;

ARGUMENT_DEFAULT_EXPRESSION_LITERAL_NULL_PRIMITIVE sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_NULL_PRIMITIVE;

ARGUMENT_DEFAULT_EXPRESSION_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_NUMBER_PRIMITIVE;

ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_SET sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_SET;

ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_STRING;

ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_ARGUMENT_DEFAULT_EXPRESSION_LITERAL_PRIMITIVE_TUPLE;

ARGUMENT_DEFAULT_IDENTIFIER_INCOMPLETE sub relation,
	relates IS_ARGUMENT_DEFAULT_IDENTIFIER_INCOMPLETE;

ARGUMENT_EXPRESSION_FOR_LIST_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_FOR_LIST_VALUE;

ARGUMENT_EXPRESSION_FOR_MAP_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_FOR_MAP_VALUE;

ARGUMENT_EXPRESSION_FOR_SET_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_FOR_SET_VALUE;

ARGUMENT_EXPRESSION_IDENTIFIER_QUALIFIED_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_IDENTIFIER_QUALIFIED_VALUE;

ARGUMENT_EXPRESSION_IDENTIFIER_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_IDENTIFIER_VALUE;

ARGUMENT_EXPRESSION_IF_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_IF_VALUE;

ARGUMENT_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_STRING_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_STRING_VALUE;

ARGUMENT_EXPRESSION_INCOMPLETE_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_INCOMPLETE_VALUE;

ARGUMENT_EXPRESSION_LIST_LITERAL_PRIMITIVE_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LIST_LITERAL_PRIMITIVE_VALUE;

ARGUMENT_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE;

ARGUMENT_EXPRESSION_LITERAL_NULL_PRIMITIVE_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_NULL_PRIMITIVE_VALUE;

ARGUMENT_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_VALUE;

ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_SET_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_SET_VALUE;

ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_STRING_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_STRING_VALUE;

ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_TUPLE_VALUE sub relation,
	relates IS_ARGUMENT_EXPRESSION_LITERAL_PRIMITIVE_TUPLE_VALUE;

ARGUMENT_INCOMPLETE_STATEMENT_VALUE sub relation,
	relates IS_ARGUMENT_INCOMPLETE_STATEMENT_VALUE;

ARGUMENT_VALUE sub relation,
	relates IS_ARGUMENT_VALUE;

ARITHMETIC_BINARY_DIVIDE_INCOMPLETE_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_INCOMPLETE_OPERATOR;

ARITHMETIC_BINARY_DIVIDE_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_DIVIDE_OPERATOR;

ARITHMETIC_BINARY_INCOMPLETE_MULTIPLY_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_INCOMPLETE_MULTIPLY_OPERATOR;

ARITHMETIC_BINARY_INCOMPLETE_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_INCOMPLETE_OPERATOR;

ARITHMETIC_BINARY_MODULE_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_MODULE_OPERATOR;

ARITHMETIC_BINARY_MULTIPLY_OPERATOR sub relation,
	relates IS_ARITHMETIC_BINARY_MULTIPLY_OPERATOR;

ARITHMETIC_BINARY_OPERATOR_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_BINARY_OPERATOR_SUBSTRACT;

ARITHMETIC_DIVIDE_INCOMPLETE_OPERATOR sub relation,
	relates IS_ARITHMETIC_DIVIDE_INCOMPLETE_OPERATOR;

ARITHMETIC_DIVIDE_OPERATOR sub relation,
	relates IS_ARITHMETIC_DIVIDE_OPERATOR;

ARITHMETIC_INCOMPLETE_MULTIPLY_OPERATOR sub relation,
	relates IS_ARITHMETIC_INCOMPLETE_MULTIPLY_OPERATOR;

ARITHMETIC_INCOMPLETE_OPERATOR sub relation,
	relates IS_ARITHMETIC_INCOMPLETE_OPERATOR;

ARITHMETIC_MODULE_OPERATOR sub relation,
	relates IS_ARITHMETIC_MODULE_OPERATOR;

ARITHMETIC_MULTIPLY_OPERATOR sub relation,
	relates IS_ARITHMETIC_MULTIPLY_OPERATOR;

ARITHMETIC_OPERATOR_SUBSTRACT sub relation,
	relates IS_ARITHMETIC_OPERATOR_SUBSTRACT;

ASSERT_STATEMENT sub relation,
	relates IS_ASSERT_STATEMENT;

ASSIGNMENT_BINARY_EXPRESSION sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION;

ASSIGNMENT_BINARY_EXPRESSION_OPERATOR sub relation,
	relates IS_ASSIGNMENT_BINARY_EXPRESSION_OPERATOR;

ASSIGNMENT_BINARY_OPERATOR sub relation,
	relates IS_ASSIGNMENT_BINARY_OPERATOR;

BASE_DECLARATION_TYPE sub relation,
	relates IS_BASE_DECLARATION_TYPE;

BINARY_BITWISE_LEFT_SHIFT_OPERATOR sub relation,
	relates IS_BINARY_BITWISE_LEFT_SHIFT_OPERATOR;

BINARY_BITWISE_OPERATOR_OR sub relation,
	relates IS_BINARY_BITWISE_OPERATOR_OR;

BINARY_BITWISE_OPERATOR_RIGHT_SHIFT sub relation,
	relates IS_BINARY_BITWISE_OPERATOR_RIGHT_SHIFT;

BINARY_BITWISE_OPERATOR_XOR sub relation,
	relates IS_BINARY_BITWISE_OPERATOR_XOR;

BINARY_BODY_CONDITION_ELSE_EXPRESSION_IF sub relation,
	relates IS_BINARY_BODY_CONDITION_ELSE_EXPRESSION_IF;

BINARY_BODY_CONDITION_EXPRESSION_IF_THEN sub relation,
	relates IS_BINARY_BODY_CONDITION_EXPRESSION_IF_THEN;

BINARY_BODY_ELSE_EXPRESSION_IF sub relation,
	relates IS_BINARY_BODY_ELSE_EXPRESSION_IF;

BINARY_BODY_EXPRESSION_IF_THEN sub relation,
	relates IS_BINARY_BODY_EXPRESSION_IF_THEN;

BINARY_BOOLEAN_EXPRESSION_INCOMPLETE_LEFT_LITERAL sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_INCOMPLETE_LEFT_LITERAL;

BINARY_BOOLEAN_EXPRESSION_INCOMPLETE_LITERAL_RIGHT sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_INCOMPLETE_LITERAL_RIGHT;

BINARY_BOOLEAN_EXPRESSION_LEFT_OPERATOR_UNARY sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_LEFT_OPERATOR_UNARY;

BINARY_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

BINARY_BOOLEAN_EXPRESSION_OPERATOR_RIGHT_UNARY sub relation,
	relates IS_BINARY_BOOLEAN_EXPRESSION_OPERATOR_RIGHT_UNARY;

BINARY_BYTE_STRING_EXPRESSION_LEFT_LITERAL_PRIMITIVE sub relation,
	relates IS_BINARY_BYTE_STRING_EXPRESSION_LEFT_LITERAL_PRIMITIVE;

BINARY_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

BINARY_CALL_CALLEE_EXPRESSION sub relation,
	relates IS_BINARY_CALL_CALLEE_EXPRESSION;

BINARY_CALL_EXPRESSION sub relation,
	relates IS_BINARY_CALL_EXPRESSION;

BINARY_CALL_EXPRESSION_FUNCTION_LEFT sub relation,
	relates IS_BINARY_CALL_EXPRESSION_FUNCTION_LEFT;

BINARY_CALL_EXPRESSION_FUNCTION_RIGHT sub relation,
	relates IS_BINARY_CALL_EXPRESSION_FUNCTION_RIGHT;

BINARY_CONDITION_EXPRESSION sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION;

BINARY_CONDITION_EXPRESSION_IF sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_IF;

BINARY_CONDITION_EXPRESSION_LEFT sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_LEFT;

BINARY_CONDITION_EXPRESSION_MAP_VALUE sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_MAP_VALUE;

BINARY_CONDITION_EXPRESSION_RIGHT sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_RIGHT;

BINARY_CONDITION_EXPRESSION_WHILE sub relation,
	relates IS_BINARY_CONDITION_EXPRESSION_WHILE;

BINARY_EXPRESSION sub relation,
	relates IS_BINARY_EXPRESSION;

BINARY_EXPRESSION_FOR sub relation,
	relates IS_BINARY_EXPRESSION_FOR;

BINARY_EXPRESSION_FOR_LEFT_LIST sub relation,
	relates IS_BINARY_EXPRESSION_FOR_LEFT_LIST;

BINARY_EXPRESSION_FOR_LEFT_SET sub relation,
	relates IS_BINARY_EXPRESSION_FOR_LEFT_SET;

BINARY_EXPRESSION_FOR_LIST_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_FOR_LIST_RIGHT;

BINARY_EXPRESSION_FOR_RIGHT_SET sub relation,
	relates IS_BINARY_EXPRESSION_FOR_RIGHT_SET;

BINARY_EXPRESSION_FOR_STATEMENT_UPDATE sub relation,
	relates IS_BINARY_EXPRESSION_FOR_STATEMENT_UPDATE;

BINARY_EXPRESSION_IDENTIFIER_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT;

BINARY_EXPRESSION_IDENTIFIER_LEFT_QUALIFIED sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_LEFT_QUALIFIED;

BINARY_EXPRESSION_IDENTIFIER_QUALIFIED_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_QUALIFIED_RIGHT;

BINARY_EXPRESSION_IDENTIFIER_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_IDENTIFIER_RIGHT;

BINARY_EXPRESSION_IF_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_IF_LEFT;

BINARY_EXPRESSION_IF_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_IF_RIGHT;

BINARY_EXPRESSION_INCOMPLETE_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LEFT;

BINARY_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE_STRING;

BINARY_EXPRESSION_INCOMPLETE_LEFT_STATEMENT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LEFT_STATEMENT;

BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT_STRING sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT_STRING;

BINARY_EXPRESSION_INCOMPLETE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT;

BINARY_EXPRESSION_INCOMPLETE_RIGHT_STATEMENT sub relation,
	relates IS_BINARY_EXPRESSION_INCOMPLETE_RIGHT_STATEMENT;

BINARY_EXPRESSION_KEY_MAP sub relation,
	relates IS_BINARY_EXPRESSION_KEY_MAP;

BINARY_EXPRESSION_LEFT sub relation,
	relates IS_BINARY_EXPRESSION_LEFT;

BINARY_EXPRESSION_LEFT_LIST_LITERAL_PRIMITIVE sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LIST_LITERAL_PRIMITIVE;

BINARY_EXPRESSION_LEFT_LITERAL_NULL_PRIMITIVE sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_NULL_PRIMITIVE;

BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE;

BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_SET sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_SET;

BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING;

BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_BINARY_EXPRESSION_LEFT_LITERAL_PRIMITIVE_TUPLE;

BINARY_EXPRESSION_LIST_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LIST_LITERAL_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_LITERAL_MAP_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_MAP_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_LITERAL_NULL_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_NULL_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_SET sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_SET;

BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING;

BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_TUPLE sub relation,
	relates IS_BINARY_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_TUPLE;

BINARY_EXPRESSION_MAP_VALUE sub relation,
	relates IS_BINARY_EXPRESSION_MAP_VALUE;

BINARY_EXPRESSION_RIGHT sub relation,
	relates IS_BINARY_EXPRESSION_RIGHT;

BITWISE_LEFT_SHIFT_OPERATOR sub relation,
	relates IS_BITWISE_LEFT_SHIFT_OPERATOR;

BITWISE_NEGATIVE_OPERATOR_UNARY sub relation,
	relates IS_BITWISE_NEGATIVE_OPERATOR_UNARY;

BITWISE_NOT_OPERATOR_UNARY sub relation,
	relates IS_BITWISE_NOT_OPERATOR_UNARY;

BITWISE_OPERATOR_OR sub relation,
	relates IS_BITWISE_OPERATOR_OR;

BITWISE_OPERATOR_POSITIVE_UNARY sub relation,
	relates IS_BITWISE_OPERATOR_POSITIVE_UNARY;

BITWISE_OPERATOR_RIGHT_SHIFT sub relation,
	relates IS_BITWISE_OPERATOR_RIGHT_SHIFT;

BITWISE_OPERATOR_XOR sub relation,
	relates IS_BITWISE_OPERATOR_XOR;

BLOCK_BODY_INCOMPLETE_SCOPE sub relation,
	relates IS_BLOCK_BODY_INCOMPLETE_SCOPE;

BLOCK_INCOMPLETE_SCOPE sub relation,
	relates IS_BLOCK_INCOMPLETE_SCOPE;

BLOCK_SCOPE_STATEMENT sub relation,
	relates IS_BLOCK_SCOPE_STATEMENT;

BODY_BOOLEAN_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE sub relation,
	relates IS_BODY_BOOLEAN_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE;

BODY_BOOLEAN_ELSE_EXPRESSION_IF_OPERATOR_UNARY sub relation,
	relates IS_BODY_BOOLEAN_ELSE_EXPRESSION_IF_OPERATOR_UNARY;

BODY_BOOLEAN_ELSE_IF_INCOMPLETE_LITERAL sub relation,
	relates IS_BODY_BOOLEAN_ELSE_IF_INCOMPLETE_LITERAL;

BODY_BOOLEAN_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN sub relation,
	relates IS_BODY_BOOLEAN_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN;

BODY_BOOLEAN_EXPRESSION_IF_OPERATOR_THEN_UNARY sub relation,
	relates IS_BODY_BOOLEAN_EXPRESSION_IF_OPERATOR_THEN_UNARY;

BODY_BOOLEAN_IF_INCOMPLETE_LITERAL_THEN sub relation,
	relates IS_BODY_BOOLEAN_IF_INCOMPLETE_LITERAL_THEN;

BODY_BYTE_STRING_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE sub relation,
	relates IS_BODY_BYTE_STRING_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE;

BODY_BYTE_STRING_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN sub relation,
	relates IS_BODY_BYTE_STRING_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN;

BODY_CALL_ELSE_EXPRESSION_FUNCTION_IF sub relation,
	relates IS_BODY_CALL_ELSE_EXPRESSION_FUNCTION_IF;

BODY_CALL_EXPRESSION_FUNCTION_IF_THEN sub relation,
	relates IS_BODY_CALL_EXPRESSION_FUNCTION_IF_THEN;

BODY_DECLARATION_FUNCTION sub relation,
	relates IS_BODY_DECLARATION_FUNCTION;

BODY_DECLARATION_TYPE sub relation,
	relates IS_BODY_DECLARATION_TYPE;

BODY_ELSE_EXPRESSION_FOR_IF_LIST sub relation,
	relates IS_BODY_ELSE_EXPRESSION_FOR_IF_LIST;

BODY_ELSE_EXPRESSION_FOR_IF_MAP sub relation,
	relates IS_BODY_ELSE_EXPRESSION_FOR_IF_MAP;

BODY_ELSE_EXPRESSION_IDENTIFIER_IF sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IDENTIFIER_IF;

BODY_ELSE_EXPRESSION_IDENTIFIER_IF_QUALIFIED sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IDENTIFIER_IF_QUALIFIED;

BODY_ELSE_EXPRESSION_IF sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF;

BODY_ELSE_EXPRESSION_IF_INCOMPLETE sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_INCOMPLETE;

BODY_ELSE_EXPRESSION_IF_INCOMPLETE_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_INCOMPLETE_LITERAL_PRIMITIVE_STRING;

BODY_ELSE_EXPRESSION_IF_LIST_LITERAL_PRIMITIVE sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LIST_LITERAL_PRIMITIVE;

BODY_ELSE_EXPRESSION_IF_LITERAL_MAP_PRIMITIVE sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LITERAL_MAP_PRIMITIVE;

BODY_ELSE_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE;

BODY_ELSE_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE;

BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_SET sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_SET;

BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING;

BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_BODY_ELSE_EXPRESSION_IF_LITERAL_PRIMITIVE_TUPLE;

BODY_ELSE_FOR sub relation,
	relates IS_BODY_ELSE_FOR;

BODY_ELSE_IF sub relation,
	relates IS_BODY_ELSE_IF;

BODY_ELSE_WHILE sub relation,
	relates IS_BODY_ELSE_WHILE;

BODY_EXPRESSION_FOR_IF_LIST_THEN sub relation,
	relates IS_BODY_EXPRESSION_FOR_IF_LIST_THEN;

BODY_EXPRESSION_FOR_IF_MAP_THEN sub relation,
	relates IS_BODY_EXPRESSION_FOR_IF_MAP_THEN;

BODY_EXPRESSION_FOR_IF_SET_THEN sub relation,
	relates IS_BODY_EXPRESSION_FOR_IF_SET_THEN;

BODY_EXPRESSION_IDENTIFIER_IF_QUALIFIED_THEN sub relation,
	relates IS_BODY_EXPRESSION_IDENTIFIER_IF_QUALIFIED_THEN;

BODY_EXPRESSION_IDENTIFIER_IF_THEN sub relation,
	relates IS_BODY_EXPRESSION_IDENTIFIER_IF_THEN;

BODY_EXPRESSION_IF_INCOMPLETE_LITERAL_PRIMITIVE_STRING_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_INCOMPLETE_LITERAL_PRIMITIVE_STRING_THEN;

BODY_EXPRESSION_IF_INCOMPLETE_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_INCOMPLETE_THEN;

BODY_EXPRESSION_IF_LIST_LITERAL_PRIMITIVE_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_LIST_LITERAL_PRIMITIVE_THEN;

BODY_EXPRESSION_IF_LITERAL_MAP_PRIMITIVE_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_LITERAL_MAP_PRIMITIVE_THEN;

BODY_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE_THEN;

BODY_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE_THEN;

BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_SET_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_SET_THEN;

BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING_THEN;

BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN_TUPLE sub relation,
	relates IS_BODY_EXPRESSION_IF_LITERAL_PRIMITIVE_THEN_TUPLE;

BODY_EXPRESSION_IF_THEN sub relation,
	relates IS_BODY_EXPRESSION_IF_THEN;

BODY_FOR sub relation,
	relates IS_BODY_FOR;

BODY_IDENTIFIER_IF_INCOMPLETE_THEN sub relation,
	relates IS_BODY_IDENTIFIER_IF_INCOMPLETE_THEN;

BODY_IF_THEN sub relation,
	relates IS_BODY_IF_THEN;

BODY_TRY sub relation,
	relates IS_BODY_TRY;

BODY_WHILE sub relation,
	relates IS_BODY_WHILE;

BOOLEAN_CALL_CALLEE_INCOMPLETE_LITERAL sub relation,
	relates IS_BOOLEAN_CALL_CALLEE_INCOMPLETE_LITERAL;

BOOLEAN_CONDITION_EXPRESSION_IF_LITERAL_PRIMITIVE sub relation,
	relates IS_BOOLEAN_CONDITION_EXPRESSION_IF_LITERAL_PRIMITIVE;

BOOLEAN_CONDITION_EXPRESSION_IF_OPERATOR_UNARY sub relation,
	relates IS_BOOLEAN_CONDITION_EXPRESSION_IF_OPERATOR_UNARY;

BOOLEAN_CONDITION_EXPRESSION_LITERAL_PRIMITIVE_WHILE sub relation,
	relates IS_BOOLEAN_CONDITION_EXPRESSION_LITERAL_PRIMITIVE_WHILE;

BOOLEAN_CONDITION_EXPRESSION_OPERATOR_UNARY_WHILE sub relation,
	relates IS_BOOLEAN_CONDITION_EXPRESSION_OPERATOR_UNARY_WHILE;

BOOLEAN_CONDITION_IF_INCOMPLETE_LITERAL sub relation,
	relates IS_BOOLEAN_CONDITION_IF_INCOMPLETE_LITERAL;

BOOLEAN_CONDITION_INCOMPLETE_LITERAL_WHILE sub relation,
	relates IS_BOOLEAN_CONDITION_INCOMPLETE_LITERAL_WHILE;

BOOLEAN_EXPRESSION_FOR_INCOMPLETE_LITERAL sub relation,
	relates IS_BOOLEAN_EXPRESSION_FOR_INCOMPLETE_LITERAL;

BOOLEAN_EXPRESSION_INCOMPLETE_LEFT_LITERAL sub relation,
	relates IS_BOOLEAN_EXPRESSION_INCOMPLETE_LEFT_LITERAL;

BOOLEAN_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE sub relation,
	relates IS_BOOLEAN_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE;

BOOLEAN_EXPRESSION_KEY_MAP_OPERATOR_UNARY sub relation,
	relates IS_BOOLEAN_EXPRESSION_KEY_MAP_OPERATOR_UNARY;

BOOLEAN_EXPRESSION_LEFT_LITERAL_PRIMITIVE sub relation,
	relates IS_BOOLEAN_EXPRESSION_LEFT_LITERAL_PRIMITIVE;

BOOLEAN_EXPRESSION_LEFT_OPERATOR_UNARY sub relation,
	relates IS_BOOLEAN_EXPRESSION_LEFT_OPERATOR_UNARY;

BOOLEAN_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE sub relation,
	relates IS_BOOLEAN_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE;

BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE sub relation,
	relates IS_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE;

BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BOOLEAN_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

BOOLEAN_EXPRESSION_MAP_OPERATOR_UNARY_VALUE sub relation,
	relates IS_BOOLEAN_EXPRESSION_MAP_OPERATOR_UNARY_VALUE;

BOOLEAN_EXPRESSION_OPERATOR_RIGHT_UNARY sub relation,
	relates IS_BOOLEAN_EXPRESSION_OPERATOR_RIGHT_UNARY;

BOOLEAN_EXPRESSION_OPERATOR_UNARY sub relation,
	relates IS_BOOLEAN_EXPRESSION_OPERATOR_UNARY;

BOOLEAN_FOR_INCOMPLETE_LITERAL_STATEMENT_UPDATE sub relation,
	relates IS_BOOLEAN_FOR_INCOMPLETE_LITERAL_STATEMENT_UPDATE;

BOOLEAN_INCOMPLETE_KEY_LITERAL_MAP sub relation,
	relates IS_BOOLEAN_INCOMPLETE_KEY_LITERAL_MAP;

BOOLEAN_INCOMPLETE_LEFT_LITERAL sub relation,
	relates IS_BOOLEAN_INCOMPLETE_LEFT_LITERAL;

BOOLEAN_INCOMPLETE_LITERAL sub relation,
	relates IS_BOOLEAN_INCOMPLETE_LITERAL;

BOOLEAN_INCOMPLETE_LITERAL_MAP_VALUE sub relation,
	relates IS_BOOLEAN_INCOMPLETE_LITERAL_MAP_VALUE;

BOOLEAN_INCOMPLETE_LITERAL_RIGHT sub relation,
	relates IS_BOOLEAN_INCOMPLETE_LITERAL_RIGHT;

BOOLEAN_NOT_OPERATOR sub relation,
	relates IS_BOOLEAN_NOT_OPERATOR;

BOOLEAN_OPERATOR_OR sub relation,
	relates IS_BOOLEAN_OPERATOR_OR;

BREAK_STATEMENT sub relation,
	relates IS_BREAK_STATEMENT;

BYTE_STRING_EXPRESSION_FOR_LITERAL_PRIMITIVE sub relation,
	relates IS_BYTE_STRING_EXPRESSION_FOR_LITERAL_PRIMITIVE;

BYTE_STRING_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_UPDATE sub relation,
	relates IS_BYTE_STRING_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_UPDATE;

BYTE_STRING_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE sub relation,
	relates IS_BYTE_STRING_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE;

BYTE_STRING_EXPRESSION_LEFT_LITERAL_PRIMITIVE sub relation,
	relates IS_BYTE_STRING_EXPRESSION_LEFT_LITERAL_PRIMITIVE;

BYTE_STRING_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE sub relation,
	relates IS_BYTE_STRING_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE;

BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE sub relation,
	relates IS_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE;

BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_BYTE_STRING_EXPRESSION_LITERAL_PRIMITIVE_RIGHT;

CALL_CALLEE_EXPRESSION_FUNCTION sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_FUNCTION;

CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_FUNCTION_IDENTIFIER;

CALL_CALLEE_EXPRESSION_IDENTIFIER sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER;

CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_IDENTIFIER_QUALIFIED;

CALL_CALLEE_EXPRESSION_IF sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_IF;

CALL_CALLEE_EXPRESSION_INCOMPLETE sub relation,
	relates IS_CALL_CALLEE_EXPRESSION_INCOMPLETE;

CALL_CONDITION_EXPRESSION_FUNCTION_IF sub relation,
	relates IS_CALL_CONDITION_EXPRESSION_FUNCTION_IF;

CALL_CONDITION_EXPRESSION_FUNCTION_WHILE sub relation,
	relates IS_CALL_CONDITION_EXPRESSION_FUNCTION_WHILE;

CALL_DECLARATION_INCOMPLETE_TYPE sub relation,
	relates IS_CALL_DECLARATION_INCOMPLETE_TYPE;

CALL_EXPRESSION_FOR_FUNCTION sub relation,
	relates IS_CALL_EXPRESSION_FOR_FUNCTION;

CALL_EXPRESSION_FOR_FUNCTION_STATEMENT_UPDATE sub relation,
	relates IS_CALL_EXPRESSION_FOR_FUNCTION_STATEMENT_UPDATE;

CALL_EXPRESSION_FUNCTION sub relation,
	relates IS_CALL_EXPRESSION_FUNCTION;

CALL_EXPRESSION_FUNCTION_KEY_MAP sub relation,
	relates IS_CALL_EXPRESSION_FUNCTION_KEY_MAP;

CALL_EXPRESSION_FUNCTION_LEFT sub relation,
	relates IS_CALL_EXPRESSION_FUNCTION_LEFT;

CALL_EXPRESSION_FUNCTION_MAP_VALUE sub relation,
	relates IS_CALL_EXPRESSION_FUNCTION_MAP_VALUE;

CALL_EXPRESSION_FUNCTION_RIGHT sub relation,
	relates IS_CALL_EXPRESSION_FUNCTION_RIGHT;

CALL_EXPRESSION_IDENTIFIER sub relation,
	relates IS_CALL_EXPRESSION_IDENTIFIER;

CALL_EXPRESSION_IDENTIFIER_QUALIFIED sub relation,
	relates IS_CALL_EXPRESSION_IDENTIFIER_QUALIFIED;

CALL_EXPRESSION_IF sub relation,
	relates IS_CALL_EXPRESSION_IF;

CALL_EXPRESSION_INCOMPLETE sub relation,
	relates IS_CALL_EXPRESSION_INCOMPLETE;

CALL_EXPRESSION_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_CALL_EXPRESSION_LITERAL_PRIMITIVE_STRING;

CALL_EXPRESSION_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_CALL_EXPRESSION_LITERAL_PRIMITIVE_TUPLE;

CATCH_IDENTIFIER_TRY sub relation,
	relates IS_CATCH_IDENTIFIER_TRY;

CATCH_STATEMENT_TRY sub relation,
	relates IS_CATCH_STATEMENT_TRY;

CATCH_TRY sub relation,
	relates IS_CATCH_TRY;

COMMENT_NOOP sub relation,
	relates IS_COMMENT_NOOP;

CONDITION_EXPRESSION_FOR_IF_LIST sub relation,
	relates IS_CONDITION_EXPRESSION_FOR_IF_LIST;

CONDITION_EXPRESSION_IDENTIFIER_IF sub relation,
	relates IS_CONDITION_EXPRESSION_IDENTIFIER_IF;

CONDITION_EXPRESSION_IDENTIFIER_IF_QUALIFIED sub relation,
	relates IS_CONDITION_EXPRESSION_IDENTIFIER_IF_QUALIFIED;

CONDITION_EXPRESSION_IDENTIFIER_QUALIFIED_WHILE sub relation,
	relates IS_CONDITION_EXPRESSION_IDENTIFIER_QUALIFIED_WHILE;

CONDITION_EXPRESSION_IDENTIFIER_WHILE sub relation,
	relates IS_CONDITION_EXPRESSION_IDENTIFIER_WHILE;

CONDITION_EXPRESSION_IF sub relation,
	relates IS_CONDITION_EXPRESSION_IF;

CONDITION_EXPRESSION_IF_INCOMPLETE sub relation,
	relates IS_CONDITION_EXPRESSION_IF_INCOMPLETE;

CONDITION_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE sub relation,
	relates IS_CONDITION_EXPRESSION_IF_LITERAL_NULL_PRIMITIVE;

CONDITION_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_CONDITION_EXPRESSION_IF_LITERAL_NUMBER_PRIMITIVE;

CONDITION_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_CONDITION_EXPRESSION_IF_LITERAL_PRIMITIVE_STRING;

CONDITION_EXPRESSION_IF_WHILE sub relation,
	relates IS_CONDITION_EXPRESSION_IF_WHILE;

CONDITION_EXPRESSION_INCOMPLETE_WHILE sub relation,
	relates IS_CONDITION_EXPRESSION_INCOMPLETE_WHILE;

CONDITION_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_WHILE sub relation,
	relates IS_CONDITION_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_WHILE;

CONDITION_IF_INCOMPLETE_RETURN_STATEMENT sub relation,
	relates IS_CONDITION_IF_INCOMPLETE_RETURN_STATEMENT;

CONDITION_IF_INCOMPLETE_STATEMENT sub relation,
	relates IS_CONDITION_IF_INCOMPLETE_STATEMENT;

CONTAINS_NOT_OPERATOR_RELATIONAL sub relation,
	relates IS_CONTAINS_NOT_OPERATOR_RELATIONAL;

CONTAINS_OPERATOR_RELATIONAL sub relation,
	relates IS_CONTAINS_OPERATOR_RELATIONAL;

CONTINUE_STATEMENT sub relation,
	relates IS_CONTINUE_STATEMENT;

DECLARATION_FUNCTION_IDENTIFIER_INCOMPLETE_NAME sub relation,
	relates IS_DECLARATION_FUNCTION_IDENTIFIER_INCOMPLETE_NAME;

DECLARATION_FUNCTION_IDENTIFIER_NAME sub relation,
	relates IS_DECLARATION_FUNCTION_IDENTIFIER_NAME;

DECLARATION_FUNCTION_INCOMPLETE sub relation,
	relates IS_DECLARATION_FUNCTION_INCOMPLETE;

DECLARATION_IDENTIFIER_STATEMENT_TYPE sub relation,
	relates IS_DECLARATION_IDENTIFIER_STATEMENT_TYPE;

DECLARATION_IMPORT_STATEMENT sub relation,
	relates IS_DECLARATION_IMPORT_STATEMENT;

ELSE_TRY sub relation,
	relates IS_ELSE_TRY;

EQUAL_NOT_OPERATOR_RELATIONAL sub relation,
	relates IS_EQUAL_NOT_OPERATOR_RELATIONAL;

EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_EQUAL_OPERATOR_RELATIONAL;

EXPRESSION_FOR sub relation,
	relates IS_EXPRESSION_FOR;

EXPRESSION_FOR_IDENTIFIER sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER;

EXPRESSION_FOR_IDENTIFIER_QUALIFIED sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_QUALIFIED;

EXPRESSION_FOR_IDENTIFIER_QUALIFIED_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_QUALIFIED_STATEMENT_UPDATE;

EXPRESSION_FOR_IDENTIFIER_QUALIFIED_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_QUALIFIED_UPDATE;

EXPRESSION_FOR_IDENTIFIER_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_STATEMENT_UPDATE;

EXPRESSION_FOR_IDENTIFIER_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_IDENTIFIER_UPDATE;

EXPRESSION_FOR_IF sub relation,
	relates IS_EXPRESSION_FOR_IF;

EXPRESSION_FOR_IF_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_IF_STATEMENT_UPDATE;

EXPRESSION_FOR_INCOMPLETE sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE;

EXPRESSION_FOR_INCOMPLETE_ITERATOR sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE_ITERATOR;

EXPRESSION_FOR_INCOMPLETE_STATEMENT sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE_STATEMENT;

EXPRESSION_FOR_INCOMPLETE_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE_STATEMENT_UPDATE;

EXPRESSION_FOR_INCOMPLETE_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_INCOMPLETE_UPDATE;

EXPRESSION_FOR_LEFT_LIST sub relation,
	relates IS_EXPRESSION_FOR_LEFT_LIST;

EXPRESSION_FOR_LEFT_MAP sub relation,
	relates IS_EXPRESSION_FOR_LEFT_MAP;

EXPRESSION_FOR_LEFT_SET sub relation,
	relates IS_EXPRESSION_FOR_LEFT_SET;

EXPRESSION_FOR_LIST sub relation,
	relates IS_EXPRESSION_FOR_LIST;

EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE;

EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE_STATEMENT_UPDATE;

EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LIST_LITERAL_PRIMITIVE_UPDATE;

EXPRESSION_FOR_LIST_MAP_VALUE sub relation,
	relates IS_EXPRESSION_FOR_LIST_MAP_VALUE;

EXPRESSION_FOR_LIST_RIGHT sub relation,
	relates IS_EXPRESSION_FOR_LIST_RIGHT;

EXPRESSION_FOR_LIST_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LIST_STATEMENT_UPDATE;

EXPRESSION_FOR_LITERAL_PRIMITIVE_SET sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_SET;

EXPRESSION_FOR_LITERAL_PRIMITIVE_SET_STATEMENT_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_SET_STATEMENT_UPDATE;

EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_STRING_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_STRING_UPDATE;

EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_TUPLE_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_STATEMENT_TUPLE_UPDATE;

EXPRESSION_FOR_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_STRING;

EXPRESSION_FOR_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_TUPLE;

EXPRESSION_FOR_LITERAL_PRIMITIVE_TUPLE_UPDATE sub relation,
	relates IS_EXPRESSION_FOR_LITERAL_PRIMITIVE_TUPLE_UPDATE;

EXPRESSION_FOR_MAP sub relation,
	relates IS_EXPRESSION_FOR_MAP;

EXPRESSION_FOR_MAP_RIGHT sub relation,
	relates IS_EXPRESSION_FOR_MAP_RIGHT;

EXPRESSION_FOR_MAP_SET_VALUE sub relation,
	relates IS_EXPRESSION_FOR_MAP_SET_VALUE;

EXPRESSION_FOR_MAP_VALUE sub relation,
	relates IS_EXPRESSION_FOR_MAP_VALUE;

EXPRESSION_FOR_RIGHT_SET sub relation,
	relates IS_EXPRESSION_FOR_RIGHT_SET;

EXPRESSION_FOR_SET sub relation,
	relates IS_EXPRESSION_FOR_SET;

EXPRESSION_IDENTIFIER sub relation,
	relates IS_EXPRESSION_IDENTIFIER;

EXPRESSION_IDENTIFIER_INCOMPLETE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_INCOMPLETE;

EXPRESSION_IDENTIFIER_KEY_MAP sub relation,
	relates IS_EXPRESSION_IDENTIFIER_KEY_MAP;

EXPRESSION_IDENTIFIER_KEY_MAP_QUALIFIED sub relation,
	relates IS_EXPRESSION_IDENTIFIER_KEY_MAP_QUALIFIED;

EXPRESSION_IDENTIFIER_LEFT sub relation,
	relates IS_EXPRESSION_IDENTIFIER_LEFT;

EXPRESSION_IDENTIFIER_LEFT_QUALIFIED sub relation,
	relates IS_EXPRESSION_IDENTIFIER_LEFT_QUALIFIED;

EXPRESSION_IDENTIFIER_MAP_QUALIFIED_VALUE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_MAP_QUALIFIED_VALUE;

EXPRESSION_IDENTIFIER_MAP_VALUE sub relation,
	relates IS_EXPRESSION_IDENTIFIER_MAP_VALUE;

EXPRESSION_IDENTIFIER_QUALIFIED sub relation,
	relates IS_EXPRESSION_IDENTIFIER_QUALIFIED;

EXPRESSION_IDENTIFIER_QUALIFIED_RIGHT sub relation,
	relates IS_EXPRESSION_IDENTIFIER_QUALIFIED_RIGHT;

EXPRESSION_IDENTIFIER_RIGHT sub relation,
	relates IS_EXPRESSION_IDENTIFIER_RIGHT;

EXPRESSION_IF sub relation,
	relates IS_EXPRESSION_IF;

EXPRESSION_IF_KEY_MAP sub relation,
	relates IS_EXPRESSION_IF_KEY_MAP;

EXPRESSION_IF_LEFT sub relation,
	relates IS_EXPRESSION_IF_LEFT;

EXPRESSION_IF_MAP_VALUE sub relation,
	relates IS_EXPRESSION_IF_MAP_VALUE;

EXPRESSION_IF_RIGHT sub relation,
	relates IS_EXPRESSION_IF_RIGHT;

EXPRESSION_INCOMPLETE sub relation,
	relates IS_EXPRESSION_INCOMPLETE;

EXPRESSION_INCOMPLETE_KEY_MAP sub relation,
	relates IS_EXPRESSION_INCOMPLETE_KEY_MAP;

EXPRESSION_INCOMPLETE_LEFT sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LEFT;

EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LEFT_LITERAL_PRIMITIVE_STRING;

EXPRESSION_INCOMPLETE_LEFT_STATEMENT sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LEFT_STATEMENT;

EXPRESSION_INCOMPLETE_LITERAL_MAP_PRIMITIVE_STRING_VALUE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LITERAL_MAP_PRIMITIVE_STRING_VALUE;

EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT_STRING sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_RIGHT_STRING;

EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_INCOMPLETE_LITERAL_PRIMITIVE_STRING;

EXPRESSION_INCOMPLETE_MAP_VALUE sub relation,
	relates IS_EXPRESSION_INCOMPLETE_MAP_VALUE;

EXPRESSION_INCOMPLETE_RIGHT sub relation,
	relates IS_EXPRESSION_INCOMPLETE_RIGHT;

EXPRESSION_KEY_LITERAL_MAP_NULL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_KEY_LITERAL_MAP_NULL_PRIMITIVE;

EXPRESSION_KEY_LITERAL_MAP_NUMBER_PRIMITIVE sub relation,
	relates IS_EXPRESSION_KEY_LITERAL_MAP_NUMBER_PRIMITIVE;

EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE_STRING;

EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE_TUPLE sub relation,
	relates IS_EXPRESSION_KEY_LITERAL_MAP_PRIMITIVE_TUPLE;

EXPRESSION_LEFT_LIST_LITERAL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LEFT_LIST_LITERAL_PRIMITIVE;

EXPRESSION_LEFT_LITERAL_MAP_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LEFT_LITERAL_MAP_PRIMITIVE;

EXPRESSION_LEFT_LITERAL_NULL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LEFT_LITERAL_NULL_PRIMITIVE;

EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LEFT_LITERAL_NUMBER_PRIMITIVE;

EXPRESSION_LEFT_LITERAL_PRIMITIVE_SET sub relation,
	relates IS_EXPRESSION_LEFT_LITERAL_PRIMITIVE_SET;

EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_LEFT_LITERAL_PRIMITIVE_STRING;

EXPRESSION_LEFT_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_EXPRESSION_LEFT_LITERAL_PRIMITIVE_TUPLE;

EXPRESSION_LIST_LITERAL_MAP_PRIMITIVE_VALUE sub relation,
	relates IS_EXPRESSION_LIST_LITERAL_MAP_PRIMITIVE_VALUE;

EXPRESSION_LIST_LITERAL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LIST_LITERAL_PRIMITIVE;

EXPRESSION_LIST_LITERAL_PRIMITIVE_RIGHT sub relation,
	relates IS_EXPRESSION_LIST_LITERAL_PRIMITIVE_RIGHT;

EXPRESSION_LITERAL_MAP_NULL_PRIMITIVE_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_NULL_PRIMITIVE_VALUE;

EXPRESSION_LITERAL_MAP_NUMBER_PRIMITIVE_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_NUMBER_PRIMITIVE_VALUE;

EXPRESSION_LITERAL_MAP_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_PRIMITIVE;

EXPRESSION_LITERAL_MAP_PRIMITIVE_RIGHT sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_RIGHT;

EXPRESSION_LITERAL_MAP_PRIMITIVE_SET_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_SET_VALUE;

EXPRESSION_LITERAL_MAP_PRIMITIVE_STRING_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_STRING_VALUE;

EXPRESSION_LITERAL_MAP_PRIMITIVE_TUPLE_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_TUPLE_VALUE;

EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE sub relation,
	relates IS_EXPRESSION_LITERAL_MAP_PRIMITIVE_VALUE;

EXPRESSION_LITERAL_NULL_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LITERAL_NULL_PRIMITIVE;

EXPRESSION_LITERAL_NULL_PRIMITIVE_RIGHT sub relation,
	relates IS_EXPRESSION_LITERAL_NULL_PRIMITIVE_RIGHT;

EXPRESSION_LITERAL_NUMBER_PRIMITIVE sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE;

EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT sub relation,
	relates IS_EXPRESSION_LITERAL_NUMBER_PRIMITIVE_RIGHT;

EXPRESSION_LITERAL_PRIMITIVE_RIGHT_SET sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_SET;

EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_STRING;

EXPRESSION_LITERAL_PRIMITIVE_RIGHT_TUPLE sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_RIGHT_TUPLE;

EXPRESSION_LITERAL_PRIMITIVE_SET sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_SET;

EXPRESSION_LITERAL_PRIMITIVE_STRING sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_STRING;

EXPRESSION_LITERAL_PRIMITIVE_TUPLE sub relation,
	relates IS_EXPRESSION_LITERAL_PRIMITIVE_TUPLE;

EXPRESSION_RIGHT sub relation,
	relates IS_EXPRESSION_RIGHT;

FILE_MODULE sub relation,
	relates IS_FILE_MODULE;

FINALLY_STATEMENT_TRY sub relation,
	relates IS_FINALLY_STATEMENT_TRY;

FINALLY_TRY sub relation,
	relates IS_FINALLY_TRY;

FOR_INCOMPLETE_ITERATOR_STATEMENT sub relation,
	relates IS_FOR_INCOMPLETE_ITERATOR_STATEMENT;

FOR_INCOMPLETE_RETURN_STATEMENT_UPDATE sub relation,
	relates IS_FOR_INCOMPLETE_RETURN_STATEMENT_UPDATE;

FOR_INCOMPLETE_STATEMENT_UPDATE sub relation,
	relates IS_FOR_INCOMPLETE_STATEMENT_UPDATE;

FOR_ITERATOR_STATEMENT sub relation,
	relates IS_FOR_ITERATOR_STATEMENT;

FOR_STATEMENT_UPDATE sub relation,
	relates IS_FOR_STATEMENT_UPDATE;

GREATER_THAN_OPERATOR_RELATIONAL sub relation,
	relates IS_GREATER_THAN_OPERATOR_RELATIONAL;

GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

IDENTICAL_NOT_OPERATOR_RELATIONAL sub relation,
	relates IS_IDENTICAL_NOT_OPERATOR_RELATIONAL;

IDENTICAL_OPERATOR_RELATIONAL sub relation,
	relates IS_IDENTICAL_OPERATOR_RELATIONAL;

IDENTIFIER_IMPORT_INCOMPLETE_PATHNAME sub relation,
	relates IS_IDENTIFIER_IMPORT_INCOMPLETE_PATHNAME;

IDENTIFIER_IMPORT_PATHNAME sub relation,
	relates IS_IDENTIFIER_IMPORT_PATHNAME;

IDENTIFIER_INCOMPLETE sub relation,
	relates IS_IDENTIFIER_INCOMPLETE;

IDENTIFIER_INCOMPLETE_RIGHT sub relation,
	relates IS_IDENTIFIER_INCOMPLETE_RIGHT;

IMPORT_INCOMPLETE sub relation,
	relates IS_IMPORT_INCOMPLETE;

INCOMPLETE_LEFT_RETURN_STATEMENT sub relation,
	relates IS_INCOMPLETE_LEFT_RETURN_STATEMENT;

INCOMPLETE_LEFT_STATEMENT sub relation,
	relates IS_INCOMPLETE_LEFT_STATEMENT;

INCOMPLETE_MAP_STATEMENT_VALUE sub relation,
	relates IS_INCOMPLETE_MAP_STATEMENT_VALUE;

INCOMPLETE_MODULE_STATEMENT_VISIBILITY sub relation,
	relates IS_INCOMPLETE_MODULE_STATEMENT_VISIBILITY;

INCOMPLETE_NAME sub relation,
	relates IS_INCOMPLETE_NAME;

INCOMPLETE_RETURN_RIGHT_STATEMENT sub relation,
	relates IS_INCOMPLETE_RETURN_RIGHT_STATEMENT;

INCOMPLETE_RETURN_STATEMENT sub relation,
	relates IS_INCOMPLETE_RETURN_STATEMENT;

INCOMPLETE_RIGHT_STATEMENT sub relation,
	relates IS_INCOMPLETE_RIGHT_STATEMENT;

INCOMPLETE_STATEMENT sub relation,
	relates IS_INCOMPLETE_STATEMENT;

INCOMPLETE_STATEMENT_VISIBILITY_WORLD sub relation,
	relates IS_INCOMPLETE_STATEMENT_VISIBILITY_WORLD;

LESS_THAN_OPERATOR_RELATIONAL sub relation,
	relates IS_LESS_THAN_OPERATOR_RELATIONAL;

LESS_THAN_OR_EQUAL_OPERATOR_RELATIONAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL_OPERATOR_RELATIONAL;

NOOP_STATEMENT sub relation,
	relates IS_NOOP_STATEMENT;

RETURN_STATEMENT sub relation,
	relates IS_RETURN_STATEMENT;

STATEMENT_THROW sub relation,
	relates IS_STATEMENT_THROW;

STATEMENT_TRY sub relation,
	relates IS_STATEMENT_TRY;

STATEMENT_WHILE sub relation,
	relates IS_STATEMENT_WHILE;
