define

##########---------- Attributes ----------##########
token sub attribute datatype string;
uuid sub attribute datatype string;

#####----- Python -----#####
valueAttribute sub attribute datatype string;
numLevelAttribute sub attribute datatype string;
simpleAttribute sub attribute datatype string;
nlAttribute sub attribute datatype string;
encodingAttribute sub attribute datatype string;
isAsyncAttribute sub attribute datatype string;
conversionAttribute sub attribute datatype string;
literalValueAttribute sub attribute datatype string;
ctxAttribute sub attribute datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity
	has token
	has uuid;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

GtArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays OPERATOR
	plays GREATER_THAN;

WithArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_items_relation
	plays has_context_expr_relation
	plays has_optional_vars_relation
	# Semantic
	plays STATEMENT
	plays SCOPE
	plays BLOCK
	plays UNANNOTATED;

AsyncWithArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_items_relation
	# Semantic
	plays STATEMENT
	plays SCOPE
	plays BLOCK;

ImportFromArtifact sub PythonSourceArtifact
	# Attributes
	has numLevelAttribute
	# Structural
	plays has_level_relation
	plays has_module_relation
	plays has_names_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays IMPORT
	plays DECLARATION;

GtEArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays GREATER_THAN_OR_EQUAL
	plays OPERATOR;

NoopSameLineArtifact sub PythonSourceArtifact
	# Semantic
	plays NOOP
	plays COMMENT;

RaiseArtifact sub PythonSourceArtifact
	# Structural
	plays has_exc_relation
	plays has_type_relation
	plays has_cause_relation
	plays has_inst_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	plays has_tback_relation
	# Semantic
	plays STATEMENT
	plays THROW;

AliasArtifact sub PythonSourceArtifact
	# Structural
	plays has_asname_relation
	# Semantic
	plays IMPORT
	plays PATHNAME
	plays IDENTIFIER;

InvertArtifact sub PythonSourceArtifact
	# Semantic
	plays NOT
	plays OPERATOR
	plays BITWISE
	plays UNARY;

FunctionDefArtifact sub PythonSourceArtifact
	# Structural
	plays has_args_relation
	plays has_body_relation
	plays has_decorator_list_relation
	plays has_returns_relation
	plays has_noops_sameline_relation
	# Semantic
	plays DECLARATION
	plays IDENTIFIER
	plays FUNCTION
	plays NAME;

WhileArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_orelse_relation
	plays has_test_relation
	# Semantic
	plays STATEMENT
	plays WHILE;

IndexArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	# Semantic
	plays INCOMPLETE
	plays EXPRESSION;

AwaitArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	# Semantic
	plays STATEMENT
	plays INCOMPLETE
	plays RIGHT
	plays EXPRESSION
	plays LEFT
	plays CONDITION
	plays IF
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays FOR
	plays BINARY
	plays UPDATE
	plays VALUE
	plays MAP;

DeleteArtifact sub PythonSourceArtifact
	# Structural
	plays has_targets_relation
	# Semantic
	plays STATEMENT
	plays INCOMPLETE;

ListCompArtifact sub PythonSourceArtifact
	# Structural
	plays has_generators_relation
	plays has_elt_relation
	# Semantic
	plays FOR
	plays LIST
	plays EXPRESSION
	plays RIGHT
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays VALUE
	plays LEFT
	plays BINARY
	plays MAP
	plays IF
	plays BODY
	plays THEN
	plays STATEMENT
	plays UPDATE
	plays CONDITION
	plays ELSE;

USubArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays BITWISE
	plays NEGATIVE
	plays UNARY;

RShiftArtifact sub PythonSourceArtifact
	# Semantic
	plays RIGHT_SHIFT
	plays OPERATOR
	plays BITWISE
	plays BINARY;

TryHandlersArtifact sub PythonSourceArtifact
	# Structural
	plays has_handlers_relation
	# Semantic
	plays CATCH
	plays TRY;

GlobalArtifact sub PythonSourceArtifact
	# Structural
	plays has_names_relation
	# Semantic
	plays STATEMENT
	plays VISIBILITY
	plays INCOMPLETE
	plays WORLD;

SetCompArtifact sub PythonSourceArtifact
	# Structural
	plays has_generators_relation
	plays has_elt_relation
	# Semantic
	plays SET
	plays FOR
	plays EXPRESSION
	plays RIGHT
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays LEFT
	plays VALUE
	plays BINARY
	plays MAP
	plays THEN
	plays IF
	plays BODY;

BoolLiteralArtifact sub PythonSourceArtifact
	# Attributes
	has valueAttribute
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays LITERAL
	plays BOOLEAN
	plays PRIMITIVE
	plays EXPRESSION
	plays ARGUMENT
	plays VALUE
	plays RIGHT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays DEFAULT
	plays MAP
	plays CONDITION
	plays WHILE
	plays IF
	plays BODY
	plays THEN
	plays ELSE
	plays KEY
	plays LEFT
	plays BINARY;

EqArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays OPERATOR
	plays EQUAL;

VarargArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_annotation_relation
	plays has_noops_sameline_relation
	# Semantic
	plays DECLARATION
	plays ARGS_LIST
	plays FUNCTION
	plays LIST
	plays NAME;

ModArtifact sub PythonSourceArtifact
	# Semantic
	plays MODULE
	plays OPERATOR
	plays ARITHMETIC
	plays BINARY;

ExceptHandlerArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_type_relation
	plays has_noops_sameline_relation
	# Semantic
	plays CATCH
	plays TRY
	plays IDENTIFIER;

TryFinallyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_finalbody_relation
	# Semantic
	plays STATEMENT
	plays TRY
	plays FINALLY;

FormattedValueArtifact sub PythonSourceArtifact
	# Attributes
	has conversionAttribute
	# Structural
	plays has_value_relation
	plays has_format_spec_relation
	# Semantic
	plays INCOMPLETE
	plays EXPRESSION;

ClassDefBodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_stmts_relation
	# Semantic
	plays DECLARATION
	plays TYPE
	plays BODY;

TryFinalbodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_final_stmts_relation
	# Semantic
	plays TRY
	plays FINALLY;

NameArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays IDENTIFIER
	plays EXPRESSION
	plays CALL
	plays LEFT
	plays ARGUMENT
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays CALLEE
	plays RIGHT
	plays VALUE
	plays BINARY
	plays FOR
	plays UPDATE
	plays MAP
	plays IF
	plays CONDITION
	plays STATEMENT
	plays KEY
	plays DEFAULT
	plays BODY
	plays NOOP
	plays ANNOTATION
	plays ELSE
	plays THEN
	plays WHILE;

BinOpArtifact sub PythonSourceArtifact
	# Structural
	plays has_left_relation
	plays has_op_relation
	plays has_right_relation
	# Semantic
	plays BINARY
	plays EXPRESSION
	plays ARGUMENT
	plays CALL
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays RIGHT
	plays LEFT
	plays VALUE
	plays MAP
	plays IF
	plays BODY
	plays CONDITION
	plays THEN
	plays FOR
	plays KEY
	plays ELSE
	plays DEFAULT
	plays STATEMENT
	plays UPDATE
	plays CALLEE
	plays WHILE
	plays NOOP
	plays ANNOTATION;

KeywordArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	# Semantic
	plays NAME
	plays CALL
	plays ARGUMENT
	plays FUNCTION
	plays INCOMPLETE;

ReturnArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays RETURN;

LambdaArtifact sub PythonSourceArtifact
	# Structural
	plays has_args_relation
	plays has_body_relation
	# Semantic
	plays ANONYMOUS
	plays VALUE
	plays FUNCTION
	plays DECLARATION
	plays ARGUMENT
	plays CALL
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays MAP
	plays DEFAULT
	plays IF
	plays BODY
	plays ELSE
	plays CALLEE
	plays THEN
	plays CONDITION;

AugAssignArtifact sub PythonSourceArtifact
	# Structural
	plays has_op_relation
	plays has_target_relation
	plays has_value_relation
	# Semantic
	plays OPERATOR
	plays BINARY
	plays ASSIGNMENT
	plays EXPRESSION;

TryArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_finalbody_relation
	plays has_handlers_relation
	plays has_orelse_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays TRY;

NonlocalArtifact sub PythonSourceArtifact
	# Structural
	plays has_names_relation
	# Semantic
	plays STATEMENT
	plays VISIBILITY
	plays MODULE
	plays INCOMPLETE;

NoneLiteralArtifact sub PythonSourceArtifact
	# Attributes
	has literalValueAttribute
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays NULL
	plays LITERAL
	plays PRIMITIVE
	plays EXPRESSION
	plays ARGUMENT
	plays DEFAULT
	plays RIGHT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays VALUE
	plays MAP
	plays IF
	plays BODY
	plays ELSE
	plays KEY
	plays THEN
	plays LEFT
	plays BINARY
	plays NOOP
	plays ANNOTATION
	plays CONDITION;

OrArtifact sub PythonSourceArtifact
	# Semantic
	plays OR
	plays OPERATOR
	plays BOOLEAN;

ExprArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	# Semantic
	plays EXPRESSION;

KwargArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	plays has_annotation_relation
	# Semantic
	plays DECLARATION
	plays ARGS_LIST
	plays FUNCTION
	plays MAP
	plays NAME;

TupleArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_elts_relation
	plays has_noops_previous_relation
	# Semantic
	plays LITERAL
	plays TUPLE
	plays PRIMITIVE
	plays EXPRESSION
	plays VALUE
	plays MAP
	plays LEFT
	plays RIGHT
	plays ARGUMENT
	plays CALL
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays BINARY
	plays FOR
	plays UPDATE
	plays KEY
	plays DEFAULT
	plays STATEMENT
	plays IF
	plays BODY
	plays THEN
	plays ELSE;

NoopLineArtifact sub PythonSourceArtifact
	# Semantic
	plays NOOP
	plays COMMENT;

IfExpArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_orelse_relation
	plays has_test_relation
	# Semantic
	plays IF
	plays EXPRESSION
	plays RIGHT
	plays ARGUMENT
	plays VALUE
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays MAP
	plays BINARY
	plays LEFT
	plays ELSE
	plays BODY
	plays CALLEE
	plays FOR
	plays CONDITION
	plays STATEMENT
	plays WHILE
	plays UPDATE;

IsNotArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays NOT
	plays OPERATOR
	plays IDENTICAL;

AssignArtifact sub PythonSourceArtifact
	# Structural
	plays has_targets_relation
	plays has_value_relation
	# Semantic
	plays BINARY
	plays ASSIGNMENT
	plays EXPRESSION;

CompareComparatorsArtifact sub PythonSourceArtifact
	# Structural
	plays has_comparators_relation
	# Semantic
	plays RIGHT
	plays EXPRESSION;

SliceArtifact sub PythonSourceArtifact
	# Structural
	plays has_upper_relation
	plays has_lower_relation
	plays has_step_relation
	# Semantic
	plays INCOMPLETE
	plays EXPRESSION;

AsyncForArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_iter_relation
	plays has_orelse_relation
	plays has_target_relation
	# Semantic
	plays STATEMENT
	plays FOR
	plays INCOMPLETE
	plays ITERATOR;

ImportFromLevelArtifact sub PythonSourceArtifact
	# Semantic
	plays IMPORT
	plays INCOMPLETE;

StarredArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_value_relation
	# Semantic
	plays CALL
	plays ARGUMENT
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays UNANNOTATED;

RemainderNoopsArtifact sub PythonSourceArtifact
	# Structural
	plays has_lines_relation
	# Semantic
	plays NOOP;

AndArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays AND
	plays BOOLEAN;

ImportFromNamesArtifact sub PythonSourceArtifact
	# Structural
	plays has_name_list_relation
	# Semantic
	plays IMPORT
	plays PATHNAME
	plays INCOMPLETE
	plays IDENTIFIER;

DivArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays ARITHMETIC
	plays DIVIDE
	plays BINARY;

WithitemArtifact sub PythonSourceArtifact
	# Structural
	plays has_context_expr_relation
	plays has_optional_vars_relation
	# Semantic
	plays INCOMPLETE
	plays IDENTIFIER
	plays EXPRESSION;

QualifiedIdentifierArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_identifiers_relation
	# Semantic
	plays QUALIFIED
	plays IDENTIFIER
	plays EXPRESSION
	plays CALL
	plays CALLEE
	plays ARGUMENT
	plays LEFT
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays VALUE
	plays RIGHT
	plays IF
	plays MAP
	plays CONDITION
	plays BINARY
	plays FOR
	plays KEY
	plays UPDATE
	plays STATEMENT
	plays BODY
	plays THEN
	plays DEFAULT
	plays ELSE
	plays WHILE
	plays NOOP
	plays ANNOTATION;

AddArtifact sub PythonSourceArtifact
	# Semantic
	plays ADD
	plays OPERATOR
	plays ARITHMETIC
	plays BINARY;

SameLineNoopsArtifact sub PythonSourceArtifact
	# Structural
	plays has_noop_lines_relation
	# Semantic
	plays COMMENT;

SubscriptArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_slice_relation
	plays has_value_relation
	# Semantic
	plays INCOMPLETE
	plays EXPRESSION
	plays LEFT
	plays ARGUMENT
	plays RIGHT
	plays CALL
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays VALUE
	plays BINARY
	plays MAP
	plays FOR
	plays IF
	plays CONDITION
	plays UPDATE
	plays STATEMENT
	plays CALLEE
	plays BODY
	plays THEN
	plays NOOP
	plays ANNOTATION
	plays ELSE
	plays KEY
	plays DEFAULT
	plays WHILE;

AnnAssignArtifact sub PythonSourceArtifact
	# Attributes
	has simpleAttribute
	# Structural
	plays has_annotation_relation
	plays has_target_relation
	plays has_value_relation
	# Semantic
	plays OPERATOR
	plays BINARY
	plays ASSIGNMENT;

MatMultArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays ARITHMETIC
	plays INCOMPLETE
	plays MULTIPLY
	plays BINARY;

UnaryOpArtifact sub PythonSourceArtifact
	# Structural
	plays has_op_relation
	plays has_operand_relation
	# Semantic
	plays BOOLEAN
	plays OPERATOR
	plays UNARY
	plays EXPRESSION
	plays CONDITION
	plays IF
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays VALUE
	plays BINARY
	plays LEFT
	plays MAP
	plays DEFAULT
	plays WHILE
	plays BODY
	plays ELSE
	plays KEY
	plays THEN;

ClassDefArtifact sub PythonSourceArtifact
	# Structural
	plays has_bases_relation
	plays has_body_relation
	plays has_decorator_list_relation
	plays has_keywords_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays DECLARATION
	plays IDENTIFIER
	plays TYPE;

IsArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays OPERATOR
	plays IDENTICAL;

PrintArtifact sub PythonSourceArtifact
	# Attributes
	has nlAttribute
	# Structural
	plays has_values_relation
	plays has_dest_relation
	plays has_noops_previous_relation
	# Semantic
	plays CALL
	plays CALLEE
	plays IDENTIFIER
	plays FUNCTION
	plays EXPRESSION;

FloorDivArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays ARITHMETIC
	plays INCOMPLETE
	plays DIVIDE
	plays BINARY;

ModuleArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_noops_remainder_relation
	# Semantic
	plays MODULE
	plays FILE;

WithBodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_stmts_relation
	# Semantic
	plays SCOPE
	plays BLOCK
	plays INCOMPLETE
	plays BODY;

ComprehensionArtifact sub PythonSourceArtifact
	# Attributes
	has isAsyncAttribute
	# Structural
	plays has_iter_relation
	plays has_target_relation
	plays has_ifs_relation
	# Semantic
	plays FOR
	plays INCOMPLETE
	plays EXPRESSION
	plays ITERATOR;

IfBodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_stmts_relation
	# Semantic
	plays THEN
	plays IF
	plays BODY;

StrArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays LITERAL
	plays STRING
	plays PRIMITIVE
	plays EXPRESSION
	plays MAP
	plays KEY
	plays VALUE
	plays ARGUMENT
	plays CALL
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays RIGHT
	plays LEFT
	plays BINARY
	plays DEFAULT
	plays IF
	plays BODY
	plays ELSE
	plays THEN
	plays FOR
	plays NOOP
	plays ANNOTATION
	plays STATEMENT
	plays UPDATE
	plays CONDITION
	plays CALLEE;

NotArtifact sub PythonSourceArtifact
	# Semantic
	plays NOT
	plays OPERATOR
	plays BOOLEAN;

NotEqArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays NOT
	plays OPERATOR
	plays EQUAL;

ExecArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_globals_relation
	# Semantic
	plays UNANNOTATED;

TryBodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_stmts_relation
	# Semantic
	plays TRY
	plays BODY;

ImportArtifact sub PythonSourceArtifact
	# Structural
	plays has_names_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays IMPORT
	plays DECLARATION;

SetArtifact sub PythonSourceArtifact
	# Structural
	plays has_elts_relation
	# Semantic
	plays SET
	plays LITERAL
	plays PRIMITIVE
	plays EXPRESSION
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays VALUE
	plays MAP
	plays BINARY
	plays LEFT
	plays DEFAULT
	plays FOR
	plays STATEMENT
	plays UPDATE
	plays THEN
	plays IF
	plays BODY;

BytesArtifact sub PythonSourceArtifact
	# Attributes
	has encodingAttribute
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays LITERAL
	plays BYTE_STRING
	plays PRIMITIVE
	plays EXPRESSION
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays BINARY
	plays LEFT
	plays VALUE
	plays MAP
	plays KEY
	plays DEFAULT
	plays IF
	plays BODY
	plays ELSE
	plays THEN
	plays FOR
	plays STATEMENT
	plays UPDATE;

PowArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays ARITHMETIC
	plays INCOMPLETE
	plays BINARY;

ListArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_elts_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays LITERAL
	plays PRIMITIVE
	plays LIST
	plays EXPRESSION
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays VALUE
	plays MAP
	plays BINARY
	plays LEFT
	plays FOR
	plays IF
	plays BODY
	plays UPDATE
	plays STATEMENT
	plays THEN
	plays ELSE
	plays DEFAULT;

SubArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays SUBSTRACT
	plays ARITHMETIC
	plays BINARY;

YieldFromArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	# Semantic
	plays STATEMENT
	plays RETURN
	plays INCOMPLETE
	plays RIGHT
	plays CALL
	plays LEFT
	plays ARGUMENT
	plays FUNCTION
	plays EXPRESSION
	plays POSITIONAL
	plays NAME;

PassArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays NOOP;

NotInArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays NOT
	plays OPERATOR
	plays CONTAINS;

AliasAsnameArtifact sub PythonSourceArtifact
	# Semantic
	plays IMPORT
	plays PATHNAME
	plays ALIAS
	plays IDENTIFIER;

LShiftArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays BITWISE
	plays LEFT_SHIFT
	plays BINARY;

WithItemsArtifact sub PythonSourceArtifact
	# Structural
	plays has_items_relation
	# Semantic
	plays SCOPE
	plays BLOCK
	plays INCOMPLETE;

NumArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_sameline_relation
	plays has_noops_previous_relation
	# Semantic
	plays NUMBER
	plays LITERAL
	plays PRIMITIVE
	plays EXPRESSION
	plays ARGUMENT
	plays CALL
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays VALUE
	plays RIGHT
	plays MAP
	plays BINARY
	plays KEY
	plays LEFT
	plays DEFAULT
	plays IF
	plays BODY
	plays ELSE
	plays THEN
	plays CONDITION
	plays WHILE
	plays NOOP
	plays ANNOTATION
	plays STATEMENT
	plays UPDATE
	plays FOR;

CompareArtifact sub PythonSourceArtifact
	# Structural
	plays has_comparators_relation
	plays has_left_relation
	plays has_ops_relation
	# Semantic
	plays BINARY
	plays CONDITION
	plays EXPRESSION
	plays IF
	plays ARGUMENT
	plays CALL
	plays POSITIONAL
	plays FUNCTION
	plays NAME
	plays WHILE
	plays RIGHT
	plays VALUE
	plays LEFT
	plays MAP
	plays BODY
	plays THEN
	plays ELSE;

YieldArtifact sub PythonSourceArtifact
	# Structural
	plays has_value_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays RETURN
	plays INCOMPLETE
	plays RIGHT
	plays CALL
	plays ARGUMENT
	plays FUNCTION
	plays POSITIONAL
	plays NAME;

BitOrArtifact sub PythonSourceArtifact
	# Semantic
	plays OR
	plays OPERATOR
	plays BITWISE
	plays BINARY;

ImportFromModuleArtifact sub PythonSourceArtifact
	# Semantic
	plays IMPORT
	plays PATHNAME
	plays IDENTIFIER;

ArgumentsArtifact sub PythonSourceArtifact
	# Structural
	plays has_args_relation
	# Semantic
	plays DECLARATION
	plays ARGUMENT
	plays INCOMPLETE
	plays FUNCTION;

DictCompArtifact sub PythonSourceArtifact
	# Structural
	plays has_generators_relation
	plays has_key_relation
	plays has_value_relation
	# Semantic
	plays FOR
	plays MAP
	plays EXPRESSION
	plays RIGHT
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays VALUE
	plays THEN
	plays IF
	plays BODY;

PreviousNoopsArtifact sub PythonSourceArtifact
	# Structural
	plays has_lines_relation
	# Semantic
	plays NOOP;

ClassDefBasesArtifact sub PythonSourceArtifact
	# Structural
	plays has_bases_relation
	# Semantic
	plays DECLARATION
	plays TYPE
	plays BASE;

GeneratorExpArtifact sub PythonSourceArtifact
	# Structural
	plays has_generators_relation
	plays has_elt_relation
	# Semantic
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays UNANNOTATED
	plays FOR
	plays EXPRESSION
	plays STATEMENT
	plays UPDATE
	plays IF
	plays BODY
	plays THEN
	plays LEFT
	plays VALUE
	plays ELSE;

LtEArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays OPERATOR
	plays LESS_THAN_OR_EQUAL;

ForBodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_stmts_relation
	# Semantic
	plays THEN
	plays BODY
	plays FOR
	plays WHILE;

TryExceptArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_handlers_relation
	plays has_orelse_relation
	# Semantic
	plays STATEMENT
	plays CATCH
	plays TRY;

TryElseArtifact sub PythonSourceArtifact
	# Semantic
	plays ELSE
	plays TRY;

ArgArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_noops_previous_relation
	plays has_default_relation
	plays has_annotation_relation
	plays has_noops_sameline_relation
	# Semantic
	plays DECLARATION
	plays ARGUMENT
	plays FUNCTION
	plays NAME;

InArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays OPERATOR
	plays CONTAINS;

JoinedStrArtifact sub PythonSourceArtifact
	# Structural
	plays has_values_relation
	# Semantic
	plays LITERAL
	plays INCOMPLETE
	plays STRING
	plays PRIMITIVE
	plays EXPRESSION
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays RIGHT
	plays LEFT
	plays VALUE
	plays MAP
	plays BINARY
	plays IF
	plays BODY
	plays ELSE
	plays THEN;

ForOrelseArtifact sub PythonSourceArtifact
	# Structural
	plays has_else_stmts_relation
	# Semantic
	plays ELSE
	plays BODY
	plays FOR
	plays WHILE;

DictArtifact sub PythonSourceArtifact
	# Structural
	plays has_keys_relation
	plays has_values_relation
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays LITERAL
	plays PRIMITIVE
	plays EXPRESSION
	plays MAP
	plays VALUE
	plays ARGUMENT
	plays RIGHT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays BINARY
	plays DEFAULT
	plays IF
	plays BODY
	plays THEN
	plays ELSE
	plays LEFT;

BoolOpArtifact sub PythonSourceArtifact
	# Structural
	plays has_values_relation
	plays has_op_relation
	# Semantic
	plays LITERAL
	plays INCOMPLETE
	plays BOOLEAN
	plays CONDITION
	plays IF
	plays RIGHT
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays VALUE
	plays WHILE
	plays MAP
	plays EXPRESSION
	plays BINARY
	plays FOR
	plays LEFT
	plays STATEMENT
	plays UPDATE
	plays BODY
	plays ELSE
	plays CALLEE
	plays THEN
	plays KEY;

MultArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays ARITHMETIC
	plays MULTIPLY
	plays BINARY;

IfOrelseArtifact sub PythonSourceArtifact
	# Structural
	plays has_else_stmts_relation
	# Semantic
	plays ELSE
	plays IF
	plays BODY;

FunctionDefBodyArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_stmts_relation
	# Semantic
	plays DECLARATION
	plays FUNCTION
	plays BODY;

BitXorArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays BITWISE
	plays XOR
	plays BINARY;

FunctionDefDecoratorsArtifact sub PythonSourceArtifact
	# Structural
	plays has_decorators_relation
	# Semantic
	plays DECLARATION
	plays INCOMPLETE
	plays FUNCTION;

KwonlyArgArtifact sub PythonSourceArtifact
	# Structural
	plays has_default_relation
	plays has_annotation_relation
	plays has_noops_previous_relation
	# Semantic
	plays DECLARATION
	plays ARGUMENT
	plays INCOMPLETE
	plays FUNCTION
	plays NAME;

ClassDefDecoratorListArtifact sub PythonSourceArtifact
	# Structural
	plays has_decorators_relation
	# Semantic
	plays DECLARATION
	plays CALL
	plays INCOMPLETE
	plays TYPE;

AssertArtifact sub PythonSourceArtifact
	# Structural
	plays has_test_relation
	plays has_msg_relation
	# Semantic
	plays STATEMENT
	plays ASSERT;

ExtSliceArtifact sub PythonSourceArtifact
	# Structural
	plays has_dims_relation
	# Semantic
	plays INCOMPLETE
	plays EXPRESSION;

CompareOpsArtifact sub PythonSourceArtifact
	# Structural
	plays has_ops_relation
	# Semantic
	plays EXPRESSION;

UAddArtifact sub PythonSourceArtifact
	# Semantic
	plays POSITIVE
	plays OPERATOR
	plays BITWISE
	plays UNARY;

CallArtifact sub PythonSourceArtifact
	# Structural
	plays has_args_relation
	plays has_func_relation
	plays has_keywords_relation
	plays has_starargs_relation
	plays has_kwargs_relation
	# Semantic
	plays CALL
	plays FUNCTION
	plays EXPRESSION
	plays RIGHT
	plays ARGUMENT
	plays POSITIONAL
	plays NAME
	plays VALUE
	plays LEFT
	plays BINARY
	plays IF
	plays FOR
	plays MAP
	plays CONDITION
	plays STATEMENT
	plays UPDATE
	plays KEY
	plays CALLEE
	plays BODY
	plays THEN
	plays ELSE
	plays WHILE
	plays DEFAULT
	plays NOOP
	plays ANNOTATION;

ForArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_iter_relation
	plays has_orelse_relation
	plays has_target_relation
	# Semantic
	plays STATEMENT
	plays FOR
	plays ITERATOR;

ContinueArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays CONTINUE
	plays STATEMENT;

LtArtifact sub PythonSourceArtifact
	# Semantic
	plays RELATIONAL
	plays OPERATOR
	plays LESS_THAN;

BreakArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays STATEMENT
	plays BREAK;

EllipsisArtifact sub PythonSourceArtifact
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays INCOMPLETE
	plays IDENTIFIER
	plays RIGHT
	plays ARGUMENT
	plays CALL
	plays FUNCTION
	plays POSITIONAL
	plays NAME
	plays THEN
	plays IF
	plays BODY
	plays DEFAULT;

IfArtifact sub PythonSourceArtifact
	# Structural
	plays has_body_relation
	plays has_orelse_relation
	plays has_test_relation
	plays has_noops_sameline_relation
	# Semantic
	plays IF
	plays EXPRESSION;

BitAndArtifact sub PythonSourceArtifact
	# Semantic
	plays OPERATOR
	plays BITWISE
	plays AND
	plays BINARY;

AsyncFunctionDefArtifact sub PythonSourceArtifact
	# Structural
	plays has_args_relation
	plays has_body_relation
	plays has_decorator_list_relation
	plays has_returns_relation
	# Semantic
	plays DECLARATION
	plays INCOMPLETE
	plays IDENTIFIER
	plays FUNCTION
	plays NAME;

AttributeArtifact sub PythonSourceArtifact
	# Attributes
	has ctxAttribute
	# Structural
	plays has_noops_previous_relation
	plays has_noops_sameline_relation
	# Semantic
	plays IDENTIFIER
	plays EXPRESSION;

##########---------- Structural Relationships ----------##########

#####----- Python -----#####
final_stmts_relation sub relationship
	relates is_final_stmts_relation, relates has_final_stmts_relation;
is_final_stmts_relation sub role;
has_final_stmts_relation sub role;

keywords_relation sub relationship
	relates is_keywords_relation, relates has_keywords_relation;
is_keywords_relation sub role;
has_keywords_relation sub role;

lines_relation sub relationship
	relates is_lines_relation, relates has_lines_relation;
is_lines_relation sub role;
has_lines_relation sub role;

identifiers_relation sub relationship
	relates is_identifiers_relation, relates has_identifiers_relation;
is_identifiers_relation sub role;
has_identifiers_relation sub role;

upper_relation sub relationship
	relates is_upper_relation, relates has_upper_relation;
is_upper_relation sub role;
has_upper_relation sub role;

finalbody_relation sub relationship
	relates is_finalbody_relation, relates has_finalbody_relation;
is_finalbody_relation sub role;
has_finalbody_relation sub role;

format_spec_relation sub relationship
	relates is_format_spec_relation, relates has_format_spec_relation;
is_format_spec_relation sub role;
has_format_spec_relation sub role;

module_relation sub relationship
	relates is_module_relation, relates has_module_relation;
is_module_relation sub role;
has_module_relation sub role;

keys_relation sub relationship
	relates is_keys_relation, relates has_keys_relation;
is_keys_relation sub role;
has_keys_relation sub role;

handlers_relation sub relationship
	relates is_handlers_relation, relates has_handlers_relation;
is_handlers_relation sub role;
has_handlers_relation sub role;

items_relation sub relationship
	relates is_items_relation, relates has_items_relation;
is_items_relation sub role;
has_items_relation sub role;

iter_relation sub relationship
	relates is_iter_relation, relates has_iter_relation;
is_iter_relation sub role;
has_iter_relation sub role;

level_relation sub relationship
	relates is_level_relation, relates has_level_relation;
is_level_relation sub role;
has_level_relation sub role;

returns_relation sub relationship
	relates is_returns_relation, relates has_returns_relation;
is_returns_relation sub role;
has_returns_relation sub role;

args_relation sub relationship
	relates is_args_relation, relates has_args_relation;
is_args_relation sub role;
has_args_relation sub role;

elts_relation sub relationship
	relates is_elts_relation, relates has_elts_relation;
is_elts_relation sub role;
has_elts_relation sub role;

op_relation sub relationship
	relates is_op_relation, relates has_op_relation;
is_op_relation sub role;
has_op_relation sub role;

ifs_relation sub relationship
	relates is_ifs_relation, relates has_ifs_relation;
is_ifs_relation sub role;
has_ifs_relation sub role;

slice_relation sub relationship
	relates is_slice_relation, relates has_slice_relation;
is_slice_relation sub role;
has_slice_relation sub role;

noops_sameline_relation sub relationship
	relates is_noops_sameline_relation, relates has_noops_sameline_relation;
is_noops_sameline_relation sub role;
has_noops_sameline_relation sub role;

value_relation sub relationship
	relates is_value_relation, relates has_value_relation;
is_value_relation sub role;
has_value_relation sub role;

cause_relation sub relationship
	relates is_cause_relation, relates has_cause_relation;
is_cause_relation sub role;
has_cause_relation sub role;

inst_relation sub relationship
	relates is_inst_relation, relates has_inst_relation;
is_inst_relation sub role;
has_inst_relation sub role;

operand_relation sub relationship
	relates is_operand_relation, relates has_operand_relation;
is_operand_relation sub role;
has_operand_relation sub role;

tback_relation sub relationship
	relates is_tback_relation, relates has_tback_relation;
is_tback_relation sub role;
has_tback_relation sub role;

noops_previous_relation sub relationship
	relates is_noops_previous_relation, relates has_noops_previous_relation;
is_noops_previous_relation sub role;
has_noops_previous_relation sub role;

step_relation sub relationship
	relates is_step_relation, relates has_step_relation;
is_step_relation sub role;
has_step_relation sub role;

left_relation sub relationship
	relates is_left_relation, relates has_left_relation;
is_left_relation sub role;
has_left_relation sub role;

noop_lines_relation sub relationship
	relates is_noop_lines_relation, relates has_noop_lines_relation;
is_noop_lines_relation sub role;
has_noop_lines_relation sub role;

asname_relation sub relationship
	relates is_asname_relation, relates has_asname_relation;
is_asname_relation sub role;
has_asname_relation sub role;

decorator_list_relation sub relationship
	relates is_decorator_list_relation, relates has_decorator_list_relation;
is_decorator_list_relation sub role;
has_decorator_list_relation sub role;

names_relation sub relationship
	relates is_names_relation, relates has_names_relation;
is_names_relation sub role;
has_names_relation sub role;

exc_relation sub relationship
	relates is_exc_relation, relates has_exc_relation;
is_exc_relation sub role;
has_exc_relation sub role;

lower_relation sub relationship
	relates is_lower_relation, relates has_lower_relation;
is_lower_relation sub role;
has_lower_relation sub role;

dest_relation sub relationship
	relates is_dest_relation, relates has_dest_relation;
is_dest_relation sub role;
has_dest_relation sub role;

elt_relation sub relationship
	relates is_elt_relation, relates has_elt_relation;
is_elt_relation sub role;
has_elt_relation sub role;

func_relation sub relationship
	relates is_func_relation, relates has_func_relation;
is_func_relation sub role;
has_func_relation sub role;

body_stmts_relation sub relationship
	relates is_body_stmts_relation, relates has_body_stmts_relation;
is_body_stmts_relation sub role;
has_body_stmts_relation sub role;

generators_relation sub relationship
	relates is_generators_relation, relates has_generators_relation;
is_generators_relation sub role;
has_generators_relation sub role;

orelse_relation sub relationship
	relates is_orelse_relation, relates has_orelse_relation;
is_orelse_relation sub role;
has_orelse_relation sub role;

type_relation sub relationship
	relates is_type_relation, relates has_type_relation;
is_type_relation sub role;
has_type_relation sub role;

default_relation sub relationship
	relates is_default_relation, relates has_default_relation;
is_default_relation sub role;
has_default_relation sub role;

dims_relation sub relationship
	relates is_dims_relation, relates has_dims_relation;
is_dims_relation sub role;
has_dims_relation sub role;

annotation_relation sub relationship
	relates is_annotation_relation, relates has_annotation_relation;
is_annotation_relation sub role;
has_annotation_relation sub role;

bases_relation sub relationship
	relates is_bases_relation, relates has_bases_relation;
is_bases_relation sub role;
has_bases_relation sub role;

right_relation sub relationship
	relates is_right_relation, relates has_right_relation;
is_right_relation sub role;
has_right_relation sub role;

values_relation sub relationship
	relates is_values_relation, relates has_values_relation;
is_values_relation sub role;
has_values_relation sub role;

name_list_relation sub relationship
	relates is_name_list_relation, relates has_name_list_relation;
is_name_list_relation sub role;
has_name_list_relation sub role;

key_relation sub relationship
	relates is_key_relation, relates has_key_relation;
is_key_relation sub role;
has_key_relation sub role;

targets_relation sub relationship
	relates is_targets_relation, relates has_targets_relation;
is_targets_relation sub role;
has_targets_relation sub role;

starargs_relation sub relationship
	relates is_starargs_relation, relates has_starargs_relation;
is_starargs_relation sub role;
has_starargs_relation sub role;

body_relation sub relationship
	relates is_body_relation, relates has_body_relation;
is_body_relation sub role;
has_body_relation sub role;

else_stmts_relation sub relationship
	relates is_else_stmts_relation, relates has_else_stmts_relation;
is_else_stmts_relation sub role;
has_else_stmts_relation sub role;

optional_vars_relation sub relationship
	relates is_optional_vars_relation, relates has_optional_vars_relation;
is_optional_vars_relation sub role;
has_optional_vars_relation sub role;

ops_relation sub relationship
	relates is_ops_relation, relates has_ops_relation;
is_ops_relation sub role;
has_ops_relation sub role;

decorators_relation sub relationship
	relates is_decorators_relation, relates has_decorators_relation;
is_decorators_relation sub role;
has_decorators_relation sub role;

globals_relation sub relationship
	relates is_globals_relation, relates has_globals_relation;
is_globals_relation sub role;
has_globals_relation sub role;

context_expr_relation sub relationship
	relates is_context_expr_relation, relates has_context_expr_relation;
is_context_expr_relation sub role;
has_context_expr_relation sub role;

noops_remainder_relation sub relationship
	relates is_noops_remainder_relation, relates has_noops_remainder_relation;
is_noops_remainder_relation sub role;
has_noops_remainder_relation sub role;

msg_relation sub relationship
	relates is_msg_relation, relates has_msg_relation;
is_msg_relation sub role;
has_msg_relation sub role;

target_relation sub relationship
	relates is_target_relation, relates has_target_relation;
is_target_relation sub role;
has_target_relation sub role;

test_relation sub relationship
	relates is_test_relation, relates has_test_relation;
is_test_relation sub role;
has_test_relation sub role;

kwargs_relation sub relationship
	relates is_kwargs_relation, relates has_kwargs_relation;
is_kwargs_relation sub role;
has_kwargs_relation sub role;

comparators_relation sub relationship
	relates is_comparators_relation, relates has_comparators_relation;
is_comparators_relation sub role;
has_comparators_relation sub role;

##########---------- Semantic Roles ----------##########
IS_GREATER_THAN_OR_EQUAL sub relationship
	relates GREATER_THAN_OR_EQUAL;
GREATER_THAN_OR_EQUAL sub role;

IS_LEFT_SHIFT sub relationship
	relates LEFT_SHIFT;
LEFT_SHIFT sub role;

IS_LEFT sub relationship
	relates LEFT;
LEFT sub role;

IS_POSITIONAL sub relationship
	relates POSITIONAL;
POSITIONAL sub role;

IS_XOR sub relationship
	relates XOR;
XOR sub role;

IS_SET sub relationship
	relates SET;
SET sub role;

IS_DIVIDE sub relationship
	relates DIVIDE;
DIVIDE sub role;

IS_CONTINUE sub relationship
	relates CONTINUE;
CONTINUE sub role;

IS_OPERATOR sub relationship
	relates OPERATOR;
OPERATOR sub role;

IS_PATHNAME sub relationship
	relates PATHNAME;
PATHNAME sub role;

IS_PRIMITIVE sub relationship
	relates PRIMITIVE;
PRIMITIVE sub role;

IS_STATEMENT sub relationship
	relates STATEMENT;
STATEMENT sub role;

IS_ADD sub relationship
	relates ADD;
ADD sub role;

IS_ARGS_LIST sub relationship
	relates ARGS_LIST;
ARGS_LIST sub role;

IS_FOR sub relationship
	relates FOR;
FOR sub role;

IS_LIST sub relationship
	relates LIST;
LIST sub role;

IS_BINARY sub relationship
	relates BINARY;
BINARY sub role;

IS_ASSIGNMENT sub relationship
	relates ASSIGNMENT;
ASSIGNMENT sub role;

IS_IDENTIFIER sub relationship
	relates IDENTIFIER;
IDENTIFIER sub role;

IS_ASSERT sub relationship
	relates ASSERT;
ASSERT sub role;

IS_EQUAL sub relationship
	relates EQUAL;
EQUAL sub role;

IS_DEFAULT sub relationship
	relates DEFAULT;
DEFAULT sub role;

IS_ELSE sub relationship
	relates ELSE;
ELSE sub role;

IS_IF sub relationship
	relates IF;
IF sub role;

IS_LITERAL sub relationship
	relates LITERAL;
LITERAL sub role;

IS_LESS_THAN sub relationship
	relates LESS_THAN;
LESS_THAN sub role;

IS_MAP sub relationship
	relates MAP;
MAP sub role;

IS_COMMENT sub relationship
	relates COMMENT;
COMMENT sub role;

IS_ITERATOR sub relationship
	relates ITERATOR;
ITERATOR sub role;

IS_BYTE_STRING sub relationship
	relates BYTE_STRING;
BYTE_STRING sub role;

IS_CATCH sub relationship
	relates CATCH;
CATCH sub role;

IS_ARGUMENT sub relationship
	relates ARGUMENT;
ARGUMENT sub role;

IS_RIGHT sub relationship
	relates RIGHT;
RIGHT sub role;

IS_UPDATE sub relationship
	relates UPDATE;
UPDATE sub role;

IS_FILE sub relationship
	relates FILE;
FILE sub role;

IS_ANONYMOUS sub relationship
	relates ANONYMOUS;
ANONYMOUS sub role;

IS_CALLEE sub relationship
	relates CALLEE;
CALLEE sub role;

IS_ALIAS sub relationship
	relates ALIAS;
ALIAS sub role;

IS_VALUE sub relationship
	relates VALUE;
VALUE sub role;

IS_TRY sub relationship
	relates TRY;
TRY sub role;

IS_LESS_THAN_OR_EQUAL sub relationship
	relates LESS_THAN_OR_EQUAL;
LESS_THAN_OR_EQUAL sub role;

IS_NULL sub relationship
	relates NULL;
NULL sub role;

IS_MODULE sub relationship
	relates MODULE;
MODULE sub role;

IS_AND sub relationship
	relates AND;
AND sub role;

IS_NEGATIVE sub relationship
	relates NEGATIVE;
NEGATIVE sub role;

IS_BODY sub relationship
	relates BODY;
BODY sub role;

IS_UNARY sub relationship
	relates UNARY;
UNARY sub role;

IS_RELATIONAL sub relationship
	relates RELATIONAL;
RELATIONAL sub role;

IS_OR sub relationship
	relates OR;
OR sub role;

IS_INCOMPLETE sub relationship
	relates INCOMPLETE;
INCOMPLETE sub role;

IS_UNANNOTATED sub relationship
	relates UNANNOTATED;
UNANNOTATED sub role;

IS_THROW sub relationship
	relates THROW;
THROW sub role;

IS_ARITHMETIC sub relationship
	relates ARITHMETIC;
ARITHMETIC sub role;

IS_DECLARATION sub relationship
	relates DECLARATION;
DECLARATION sub role;

IS_CONDITION sub relationship
	relates CONDITION;
CONDITION sub role;

IS_THEN sub relationship
	relates THEN;
THEN sub role;

IS_KEY sub relationship
	relates KEY;
KEY sub role;

IS_CALL sub relationship
	relates CALL;
CALL sub role;

IS_STRING sub relationship
	relates STRING;
STRING sub role;

IS_RIGHT_SHIFT sub relationship
	relates RIGHT_SHIFT;
RIGHT_SHIFT sub role;

IS_SCOPE sub relationship
	relates SCOPE;
SCOPE sub role;

IS_FINALLY sub relationship
	relates FINALLY;
FINALLY sub role;

IS_NUMBER sub relationship
	relates NUMBER;
NUMBER sub role;

IS_BOOLEAN sub relationship
	relates BOOLEAN;
BOOLEAN sub role;

IS_NAME sub relationship
	relates NAME;
NAME sub role;

IS_NOT sub relationship
	relates NOT;
NOT sub role;

IS_POSITIVE sub relationship
	relates POSITIVE;
POSITIVE sub role;

IS_CONTAINS sub relationship
	relates CONTAINS;
CONTAINS sub role;

IS_BASE sub relationship
	relates BASE;
BASE sub role;

IS_RETURN sub relationship
	relates RETURN;
RETURN sub role;

IS_ANNOTATION sub relationship
	relates ANNOTATION;
ANNOTATION sub role;

IS_GREATER_THAN sub relationship
	relates GREATER_THAN;
GREATER_THAN sub role;

IS_BREAK sub relationship
	relates BREAK;
BREAK sub role;

IS_TYPE sub relationship
	relates TYPE;
TYPE sub role;

IS_FUNCTION sub relationship
	relates FUNCTION;
FUNCTION sub role;

IS_NOOP sub relationship
	relates NOOP;
NOOP sub role;

IS_IMPORT sub relationship
	relates IMPORT;
IMPORT sub role;

IS_SUBSTRACT sub relationship
	relates SUBSTRACT;
SUBSTRACT sub role;

IS_TUPLE sub relationship
	relates TUPLE;
TUPLE sub role;

IS_EXPRESSION sub relationship
	relates EXPRESSION;
EXPRESSION sub role;

IS_WORLD sub relationship
	relates WORLD;
WORLD sub role;

IS_BITWISE sub relationship
	relates BITWISE;
BITWISE sub role;

IS_BLOCK sub relationship
	relates BLOCK;
BLOCK sub role;

IS_IDENTICAL sub relationship
	relates IDENTICAL;
IDENTICAL sub role;

IS_VISIBILITY sub relationship
	relates VISIBILITY;
VISIBILITY sub role;

IS_MULTIPLY sub relationship
	relates MULTIPLY;
MULTIPLY sub role;

IS_QUALIFIED sub relationship
	relates QUALIFIED;
QUALIFIED sub role;

IS_WHILE sub relationship
	relates WHILE;
WHILE sub role;
