define

##########---------- Entities ----------##########

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

AddArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ADD,
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_OPERATOR;

AliasArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER,
	plays IS_IMPORT,
	plays IS_PATHNAME;

AliasAsnameArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ALIAS,
	plays IS_IDENTIFIER,
	plays IS_IMPORT,
	plays IS_PATHNAME;

AndArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_AND,
	plays IS_BOOLEAN,
	plays IS_OPERATOR;

AnnAssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_OPERATOR;

ArgArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_NAME;

ArgumentsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE;

AssertArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSERT,
	plays IS_STATEMENT;

AssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_EXPRESSION;

AsyncForArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FOR,
	plays IS_INCOMPLETE,
	plays IS_ITERATOR,
	plays IS_STATEMENT;

AsyncFunctionDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_INCOMPLETE,
	plays IS_NAME;

AsyncWithArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_SCOPE,
	plays IS_STATEMENT;

AttributeArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_IDENTIFIER;

AugAssignArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ASSIGNMENT,
	plays IS_BINARY,
	plays IS_EXPRESSION,
	plays IS_OPERATOR;

AwaitArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_UPDATE,
	plays IS_VALUE;

BinOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

BitAndArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_AND,
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_OPERATOR;

BitOrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_OPERATOR,
	plays IS_OR;

BitXorArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_OPERATOR,
	plays IS_XOR;

BoolLiteralArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE,
	plays IS_WHILE;

BoolOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

BreakArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BREAK,
	plays IS_STATEMENT;

BytesArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BYTE_STRING,
	plays IS_CALL,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE;

CallArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

ClassDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_IDENTIFIER,
	plays IS_STATEMENT,
	plays IS_TYPE;

ClassDefBasesArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BASE,
	plays IS_DECLARATION,
	plays IS_TYPE;

ClassDefBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_TYPE;

ClassDefDecoratorListArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CALL,
	plays IS_DECLARATION,
	plays IS_INCOMPLETE,
	plays IS_TYPE;

CompareArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE,
	plays IS_WHILE;

CompareComparatorsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_RIGHT;

CompareOpsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION;

ComprehensionArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_INCOMPLETE,
	plays IS_ITERATOR;

ContinueArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CONTINUE,
	plays IS_STATEMENT;

DeleteArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_STATEMENT;

DictArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

DictCompArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

DivArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_DIVIDE,
	plays IS_OPERATOR;

EllipsisArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DEFAULT,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN;

EqArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EQUAL,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

ExceptHandlerArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CATCH,
	plays IS_IDENTIFIER,
	plays IS_TRY;

ExecArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_UNANNOTATED;

ExprArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION;

ExtSliceArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE;

FloorDivArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_DIVIDE,
	plays IS_INCOMPLETE,
	plays IS_OPERATOR;

ForArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FOR,
	plays IS_ITERATOR,
	plays IS_STATEMENT;

ForBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_FOR,
	plays IS_WHILE;

FormattedValueArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE;

ForOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_FOR,
	plays IS_WHILE;

FunctionDefArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_NAME;

FunctionDefBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_DECLARATION,
	plays IS_FUNCTION;

FunctionDefDecoratorsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE;

GeneratorExpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UNANNOTATED,
	plays IS_UPDATE,
	plays IS_VALUE;

GlobalArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_STATEMENT,
	plays IS_VISIBILITY,
	plays IS_WORLD;

GtArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_GREATER_THAN,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

GtEArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_GREATER_THAN_OR_EQUAL,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

IfArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_IF;

IfBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_IF,
	plays IS_THEN;

IfExpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

IfOrelseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_ELSE,
	plays IS_IF;

ImportArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_IMPORT,
	plays IS_STATEMENT;

ImportFromArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_DECLARATION,
	plays IS_IMPORT,
	plays IS_STATEMENT;

ImportFromLevelArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IMPORT,
	plays IS_INCOMPLETE;

ImportFromModuleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER,
	plays IS_IMPORT,
	plays IS_PATHNAME;

ImportFromNamesArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTIFIER,
	plays IS_IMPORT,
	plays IS_INCOMPLETE,
	plays IS_PATHNAME;

InArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CONTAINS,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

IndexArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE;

InvertArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BITWISE,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_UNARY;

IsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTICAL,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

IsNotArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_IDENTICAL,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

JoinedStrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_STRING,
	plays IS_THEN,
	plays IS_VALUE;

KeywordArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_NAME;

KwargArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_MAP,
	plays IS_NAME;

KwonlyArgArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_NAME;

LambdaArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANONYMOUS,
	plays IS_ARGUMENT,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_DECLARATION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

ListArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LIST,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE;

ListCompArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LIST,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE;

LShiftArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_LEFT_SHIFT,
	plays IS_OPERATOR;

LtArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_LESS_THAN,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

LtEArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_LESS_THAN_OR_EQUAL,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

MatMultArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_INCOMPLETE,
	plays IS_MULTIPLY,
	plays IS_OPERATOR;

ModArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_MODULE,
	plays IS_OPERATOR;

ModuleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FILE,
	plays IS_MODULE;

MultArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_MULTIPLY,
	plays IS_OPERATOR;

NameArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

NoneLiteralArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_NULL,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE;

NonlocalArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_INCOMPLETE,
	plays IS_MODULE,
	plays IS_STATEMENT,
	plays IS_VISIBILITY;

NoopLineArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_NOOP;

NoopSameLineArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_COMMENT,
	plays IS_NOOP;

NotArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BOOLEAN,
	plays IS_NOT,
	plays IS_OPERATOR;

NotEqArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EQUAL,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

NotInArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CONTAINS,
	plays IS_NOT,
	plays IS_OPERATOR,
	plays IS_RELATIONAL;

NumArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_NUMBER,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_VALUE,
	plays IS_WHILE;

OrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BOOLEAN,
	plays IS_OPERATOR,
	plays IS_OR;

PassArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_NOOP,
	plays IS_STATEMENT;

PowArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_INCOMPLETE,
	plays IS_OPERATOR;

PreviousNoopsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_NOOP;

PrintArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER;

QualifiedIdentifierArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_POSITIONAL,
	plays IS_QUALIFIED,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

RaiseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_STATEMENT,
	plays IS_THROW;

RemainderNoopsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_NOOP;

ReturnArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_RETURN,
	plays IS_STATEMENT;

RShiftArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BINARY,
	plays IS_BITWISE,
	plays IS_OPERATOR,
	plays IS_RIGHT_SHIFT;

SameLineNoopsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_COMMENT;

SetArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_SET,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE;

SetCompArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_SET,
	plays IS_THEN,
	plays IS_VALUE;

SliceArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_INCOMPLETE;

StarredArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_FUNCTION,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_UNANNOTATED;

StrArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_STRING,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE;

SubArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARITHMETIC,
	plays IS_BINARY,
	plays IS_OPERATOR,
	plays IS_SUBSTRACT;

SubscriptArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ANNOTATION,
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_CALLEE,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_NOOP,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_UPDATE,
	plays IS_VALUE,
	plays IS_WHILE;

TryArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_STATEMENT,
	plays IS_TRY;

TryBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BODY,
	plays IS_TRY;

TryElseArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ELSE,
	plays IS_TRY;

TryExceptArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CATCH,
	plays IS_STATEMENT,
	plays IS_TRY;

TryFinalbodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FINALLY,
	plays IS_TRY;

TryFinallyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FINALLY,
	plays IS_STATEMENT,
	plays IS_TRY;

TryHandlersArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_CATCH,
	plays IS_TRY;

TupleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_CALL,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_LITERAL,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_PRIMITIVE,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_THEN,
	plays IS_TUPLE,
	plays IS_UPDATE,
	plays IS_VALUE;

UAddArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BITWISE,
	plays IS_OPERATOR,
	plays IS_POSITIVE,
	plays IS_UNARY;

UnaryOpArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_BINARY,
	plays IS_BODY,
	plays IS_BOOLEAN,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_DEFAULT,
	plays IS_ELSE,
	plays IS_EXPRESSION,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_KEY,
	plays IS_LEFT,
	plays IS_MAP,
	plays IS_NAME,
	plays IS_OPERATOR,
	plays IS_POSITIONAL,
	plays IS_RIGHT,
	plays IS_THEN,
	plays IS_UNARY,
	plays IS_VALUE,
	plays IS_WHILE;

USubArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BITWISE,
	plays IS_NEGATIVE,
	plays IS_OPERATOR,
	plays IS_UNARY;

VarargArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGS_LIST,
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_LIST,
	plays IS_NAME;

WhileArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_STATEMENT,
	plays IS_WHILE;

WithArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_SCOPE,
	plays IS_STATEMENT,
	plays IS_UNANNOTATED;

WithBodyArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_BODY,
	plays IS_INCOMPLETE,
	plays IS_SCOPE;

WithitemArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_EXPRESSION,
	plays IS_IDENTIFIER,
	plays IS_INCOMPLETE;

WithItemsArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_BLOCK,
	plays IS_INCOMPLETE,
	plays IS_SCOPE;

YieldArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_FUNCTION,
	plays IS_INCOMPLETE,
	plays IS_LEFT,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RETURN,
	plays IS_RIGHT,
	plays IS_STATEMENT;

YieldFromArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_ARGUMENT,
	plays IS_CALL,
	plays IS_CONDITION,
	plays IS_FOR,
	plays IS_FUNCTION,
	plays IS_IF,
	plays IS_INCOMPLETE,
	plays IS_NAME,
	plays IS_POSITIONAL,
	plays IS_RETURN,
	plays IS_RIGHT,
	plays IS_STATEMENT,
	plays IS_UPDATE;

##########---------- Semantic Roles ----------##########
ADD sub relation,
	relates IS_ADD;

ALIAS sub relation,
	relates IS_ALIAS;

AND sub relation,
	relates IS_AND;

ANNOTATION sub relation,
	relates IS_ANNOTATION;

ANONYMOUS sub relation,
	relates IS_ANONYMOUS;

ARGS_LIST sub relation,
	relates IS_ARGS_LIST;

ARGUMENT sub relation,
	relates IS_ARGUMENT;

ARITHMETIC sub relation,
	relates IS_ARITHMETIC;

ASSERT sub relation,
	relates IS_ASSERT;

ASSIGNMENT sub relation,
	relates IS_ASSIGNMENT;

BASE sub relation,
	relates IS_BASE;

BINARY sub relation,
	relates IS_BINARY;

BITWISE sub relation,
	relates IS_BITWISE;

BLOCK sub relation,
	relates IS_BLOCK;

BODY sub relation,
	relates IS_BODY;

BOOLEAN sub relation,
	relates IS_BOOLEAN;

BREAK sub relation,
	relates IS_BREAK;

BYTE_STRING sub relation,
	relates IS_BYTE_STRING;

CALL sub relation,
	relates IS_CALL;

CALLEE sub relation,
	relates IS_CALLEE;

CATCH sub relation,
	relates IS_CATCH;

COMMENT sub relation,
	relates IS_COMMENT;

CONDITION sub relation,
	relates IS_CONDITION;

CONTAINS sub relation,
	relates IS_CONTAINS;

CONTINUE sub relation,
	relates IS_CONTINUE;

DECLARATION sub relation,
	relates IS_DECLARATION;

DEFAULT sub relation,
	relates IS_DEFAULT;

DIVIDE sub relation,
	relates IS_DIVIDE;

ELSE sub relation,
	relates IS_ELSE;

EQUAL sub relation,
	relates IS_EQUAL;

EXPRESSION sub relation,
	relates IS_EXPRESSION;

FILE sub relation,
	relates IS_FILE;

FINALLY sub relation,
	relates IS_FINALLY;

FOR sub relation,
	relates IS_FOR;

FUNCTION sub relation,
	relates IS_FUNCTION;

GREATER_THAN sub relation,
	relates IS_GREATER_THAN;

GREATER_THAN_OR_EQUAL sub relation,
	relates IS_GREATER_THAN_OR_EQUAL;

IDENTICAL sub relation,
	relates IS_IDENTICAL;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

IF sub relation,
	relates IS_IF;

IMPORT sub relation,
	relates IS_IMPORT;

INCOMPLETE sub relation,
	relates IS_INCOMPLETE;

ITERATOR sub relation,
	relates IS_ITERATOR;

KEY sub relation,
	relates IS_KEY;

LEFT sub relation,
	relates IS_LEFT;

LEFT_SHIFT sub relation,
	relates IS_LEFT_SHIFT;

LESS_THAN sub relation,
	relates IS_LESS_THAN;

LESS_THAN_OR_EQUAL sub relation,
	relates IS_LESS_THAN_OR_EQUAL;

LIST sub relation,
	relates IS_LIST;

LITERAL sub relation,
	relates IS_LITERAL;

MAP sub relation,
	relates IS_MAP;

MODULE sub relation,
	relates IS_MODULE;

MULTIPLY sub relation,
	relates IS_MULTIPLY;

NAME sub relation,
	relates IS_NAME;

NEGATIVE sub relation,
	relates IS_NEGATIVE;

NOOP sub relation,
	relates IS_NOOP;

NOT sub relation,
	relates IS_NOT;

NULL sub relation,
	relates IS_NULL;

NUMBER sub relation,
	relates IS_NUMBER;

OPERATOR sub relation,
	relates IS_OPERATOR;

OR sub relation,
	relates IS_OR;

PATHNAME sub relation,
	relates IS_PATHNAME;

POSITIONAL sub relation,
	relates IS_POSITIONAL;

POSITIVE sub relation,
	relates IS_POSITIVE;

PRIMITIVE sub relation,
	relates IS_PRIMITIVE;

QUALIFIED sub relation,
	relates IS_QUALIFIED;

RELATIONAL sub relation,
	relates IS_RELATIONAL;

RETURN sub relation,
	relates IS_RETURN;

RIGHT sub relation,
	relates IS_RIGHT;

RIGHT_SHIFT sub relation,
	relates IS_RIGHT_SHIFT;

SCOPE sub relation,
	relates IS_SCOPE;

SET sub relation,
	relates IS_SET;

STATEMENT sub relation,
	relates IS_STATEMENT;

STRING sub relation,
	relates IS_STRING;

SUBSTRACT sub relation,
	relates IS_SUBSTRACT;

THEN sub relation,
	relates IS_THEN;

THROW sub relation,
	relates IS_THROW;

TRY sub relation,
	relates IS_TRY;

TUPLE sub relation,
	relates IS_TUPLE;

TYPE sub relation,
	relates IS_TYPE;

UNANNOTATED sub relation,
	relates IS_UNANNOTATED;

UNARY sub relation,
	relates IS_UNARY;

UPDATE sub relation,
	relates IS_UPDATE;

VALUE sub relation,
	relates IS_VALUE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WHILE sub relation,
	relates IS_WHILE;

WORLD sub relation,
	relates IS_WORLD;

XOR sub relation,
	relates IS_XOR;
