define

##########---------- Attributes ----------##########
booleanValue sub attribute, datatype boolean;
doubleValue sub attribute, datatype double;
name sub attribute, datatype string;
numberValue sub attribute, datatype long;
stringValue sub attribute, datatype string;
token sub attribute, datatype string;

#####----- Java -----#####
javaConstructorAttribute sub attribute, datatype string;

#####----- Javascript -----#####
javascriptAsyncAttribute sub attribute, datatype string;
javascriptGeneratorAttribute sub attribute, datatype string;

#####----- Php -----#####
phpByRefAttribute sub attribute, datatype string;

#####----- Csharp -----#####
csharpArityAttribute sub attribute, datatype string;
csharpIsMissingAttribute sub attribute, datatype string;
csharpIsStructuredTriviaAttribute sub attribute, datatype string;

#####----- Cplusplus -----#####
cplusplusIsDefaultedAttribute sub attribute, datatype string;
cplusplusIsDeletedAttribute sub attribute, datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	has token,
	plays is_child,
	plays is_parent;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoFileArtifact sub GoSourceArtifact,
	# Structural
	plays has_go_decls_role,
	# Semantic
	plays IS_FILE;

GoFuncDeclArtifact sub GoSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_go_decls_role,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaCompilationUnitArtifact sub JavaSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_parent,
	# Semantic
	plays IS_FILE;

JavaMethodDeclarationArtifact sub JavaSourceArtifact,
	# Attributes
	has javaConstructorAttribute,
	has name,
	# Structural
	plays is_child,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_VISIBILITY,
	plays IS_WORLD;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptFileArtifact sub JavascriptSourceArtifact,
	# Structural
	plays is_parent,
	# Semantic
	plays IS_FILE;

JavascriptFunctionDeclarationArtifact sub JavascriptSourceArtifact,
	# Attributes
	has javascriptAsyncAttribute,
	has javascriptGeneratorAttribute,
	has name,
	# Structural
	plays is_child,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_STATEMENT;

#####----- Php -----#####
PhpSourceArtifact sub SourceArtifact;

PhpModuleArtifact sub PhpSourceArtifact,
	# Structural
	plays has_php_children_role,
	# Semantic
	plays IS_MODULE;

PhpStmtFunctionArtifact sub PhpSourceArtifact,
	# Attributes
	has phpByRefAttribute,
	has name,
	# Structural
	plays is_php_children_role,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonFunctionDefArtifact sub PythonSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_python_body_role,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_NAME;

PythonModuleArtifact sub PythonSourceArtifact,
	# Structural
	plays has_python_body_role,
	# Semantic
	plays IS_FILE,
	plays IS_MODULE;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

RubyDefArtifact sub RubySourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_ruby_file_role,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_IDENTIFIER,
	plays IS_STATEMENT;

RubyModuleArtifact sub RubySourceArtifact,
	# Structural
	plays has_ruby_file_role,
	# Semantic
	plays IS_IDENTIFIER,
	plays IS_MODULE,
	plays IS_STATEMENT;

#####----- Csharp -----#####
CsharpSourceArtifact sub SourceArtifact;

CsharpCompilationUnitArtifact sub CsharpSourceArtifact,
	# Attributes
	has csharpIsMissingAttribute,
	has csharpIsStructuredTriviaAttribute,
	# Structural
	plays is_parent,
	# Semantic
	plays IS_FILE,
	plays IS_MODULE;

CsharpMethodDeclarationArtifact sub CsharpSourceArtifact,
	# Attributes
	has csharpArityAttribute,
	has csharpIsMissingAttribute,
	has csharpIsStructuredTriviaAttribute,
	has name,
	# Structural
	plays is_child,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_TYPE;

#####----- Bash -----#####
BashSourceArtifact sub SourceArtifact;

BashFILEArtifact sub BashSourceArtifact,
	# Semantic
	plays IS_FILE;

#####----- Cplusplus -----#####
CplusplusSourceArtifact sub SourceArtifact;

CplusplusCPPASTFunctionDefinitionArtifact sub CplusplusSourceArtifact,
	# Attributes
	has cplusplusIsDefaultedAttribute,
	has cplusplusIsDeletedAttribute,
	has name,
	# Structural
	plays is_cplusplus_prop__declarations_role,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION;

CplusplusCPPASTTranslationUnitArtifact sub CplusplusSourceArtifact,
	# Structural
	plays has_cplusplus_prop__declarations_role,
	# Semantic
	plays IS_FILE,
	plays IS_MODULE;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Go -----#####
go_decls_relation sub parent_child_relation,
	relates is_go_decls_role as is_child, relates has_go_decls_role as is_parent;

#####----- Php -----#####
php_children_relation sub parent_child_relation,
	relates is_php_children_role as is_child, relates has_php_children_role as is_parent;

#####----- Python -----#####
python_body_relation sub parent_child_relation,
	relates is_python_body_role as is_child, relates has_python_body_role as is_parent;

#####----- Ruby -----#####
ruby_file_relation sub parent_child_relation,
	relates is_ruby_file_role as is_child, relates has_ruby_file_role as is_parent;

#####----- Cplusplus -----#####
cplusplus_prop__declarations_relation sub parent_child_relation,
	relates is_cplusplus_prop__declarations_role as is_child, relates has_cplusplus_prop__declarations_role as is_parent;

##########---------- Semantic Roles ----------##########
DECLARATION sub relation,
	relates IS_DECLARATION;

FILE sub relation,
	relates IS_FILE;

FUNCTION sub relation,
	relates IS_FUNCTION;

IDENTIFIER sub relation,
	relates IS_IDENTIFIER;

MODULE sub relation,
	relates IS_MODULE;

NAME sub relation,
	relates IS_NAME;

STATEMENT sub relation,
	relates IS_STATEMENT;

TYPE sub relation,
	relates IS_TYPE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WORLD sub relation,
	relates IS_WORLD;
