define

##########---------- Attributes ----------##########
booleanValue sub attribute, datatype boolean;
doubleValue sub attribute, datatype double;
name sub attribute, datatype string;
numberValue sub attribute, datatype long;
token sub attribute, datatype string;

#####----- Java -----#####
javaConstructorAttribute sub attribute, datatype string;

#####----- Php -----#####
phpByRefAttribute sub attribute, datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	has token,
	plays is_child,
	plays is_parent;

#####----- Omnilingual -----#####
OmnilingualSourceArtifact sub SourceArtifact;

FileArtifact sub OmnilingualSourceArtifact,
	# Semantic
	plays IS_FILE;

#####----- Go -----#####
GoSourceArtifact sub SourceArtifact;

GoFileArtifact sub FileArtifact,
	# Structural
	plays has_go_decls_role;

GoFuncDeclArtifact sub GoSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_go_decls_role,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION;

#####----- Java -----#####
JavaSourceArtifact sub SourceArtifact;

JavaCompilationUnitArtifact sub JavaSourceArtifact,
	# Attributes
	has name,
	# Structural
	plays is_parent,
	# Semantic
	plays IS_FILE;

JavaMethodDeclarationArtifact sub JavaSourceArtifact,
	# Attributes
	has javaConstructorAttribute,
	has name,
	# Structural
	plays is_child,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION,
	plays IS_VISIBILITY,
	plays IS_WORLD;

#####----- Javascript -----#####
JavascriptSourceArtifact sub SourceArtifact;

JavascriptFileArtifact sub FileArtifact;

#####----- Php -----#####
PhpSourceArtifact sub SourceArtifact;

PhpStmtFunctionArtifact sub PhpSourceArtifact,
	# Attributes
	has phpByRefAttribute,
	# Semantic
	plays IS_DECLARATION,
	plays IS_FUNCTION;

#####----- Python -----#####
PythonSourceArtifact sub SourceArtifact;

PythonModuleArtifact sub PythonSourceArtifact,
	# Semantic
	plays IS_FILE,
	plays IS_MODULE;

#####----- Ruby -----#####
RubySourceArtifact sub SourceArtifact;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Go -----#####
go_decls_relation sub parent_child_relation,
	relates is_go_decls_role as is_child, relates has_go_decls_role as is_parent;

##########---------- Semantic Roles ----------##########
DECLARATION sub relation,
	relates IS_DECLARATION;

FILE sub relation,
	relates IS_FILE;

FUNCTION sub relation,
	relates IS_FUNCTION;

MODULE sub relation,
	relates IS_MODULE;

VISIBILITY sub relation,
	relates IS_VISIBILITY;

WORLD sub relation,
	relates IS_WORLD;
