define

##########---------- Attributes ----------##########
booleanValue sub attribute, datatype boolean;
doubleValue sub attribute, datatype double;
name sub attribute, datatype string;
numberValue sub attribute, datatype long;
token sub attribute, datatype string;

#####----- Php -----#####
aliasAttribute sub attribute, datatype string;
byRefAttribute sub attribute, datatype string;
flagsAttribute sub attribute, datatype string;
methodAttribute sub attribute, datatype string;
newModifierAttribute sub attribute, datatype string;
remainingAttribute sub attribute, datatype string;
returnTypeAttribute sub attribute, datatype string;
staticAttribute sub attribute, datatype string;
typeAttribute sub attribute, datatype string;
unpackAttribute sub attribute, datatype string;
varAttribute sub attribute, datatype string;
variadicAttribute sub attribute, datatype string;

##########---------- Entities ----------##########
SourceArtifact sub entity,
	has token,
	plays is_child,
	plays is_parent;

#####----- Php -----#####
PhpSourceArtifact sub SourceArtifact;

ArgArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	has unpackAttribute,
	# Structural
	plays is_args_role,
	plays has_comments_role,
	plays has_value_role;

CommentArtifact sub PhpSourceArtifact,
	# Structural
	plays is_comments_role;

CommentDocArtifact sub PhpSourceArtifact,
	# Structural
	plays is_comments_role;

ConstArtifact sub PhpSourceArtifact,
	# Structural
	plays is_consts_role,
	plays has_name_role,
	plays has_value_role;

DeclareStmtsArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role;

ExprArrayArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_value_role,
	plays is_value_var_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_items_role;

ExprArrayDimFetchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_parts_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays is_vars_role,
	plays has_comments_role,
	plays has_dim_role,
	plays has_var_role;

ExprArrayItemArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	# Structural
	plays is_items_role,
	plays has_comments_role,
	plays has_key_role,
	plays has_value_role;

ExprAssignArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_init_role,
	plays is_key_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpBitwiseAndArtifact sub PhpSourceArtifact,
	# Structural
	plays is_right_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpBitwiseOrArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpBitwiseXorArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpConcatArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpDivArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpMinusArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_expr_role,
	plays is_loop_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpModArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_right_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpMulArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpPlusArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_expr_role,
	plays is_init_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpPowArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpShiftLeftArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignOpShiftRightArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprAssignRefArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_init_role,
	plays is_loop_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_var_role;

ExprBinaryOpBitwiseAndArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpBitwiseOrArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpBitwiseXorArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpBooleanAndArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpBooleanOrArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpCoalesceArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpConcatArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpDivArtifact sub PhpSourceArtifact,
	# Structural
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpEqualArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpGreaterArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpGreaterOrEqualArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpIdenticalArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpLogicalAndArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_cond_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpLogicalOrArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpLogicalXorArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_expr_role,
	plays is_right_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpMinusArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpModArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpMulArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpNotEqualArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpNotIdenticalArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpPlusArtifact sub PhpSourceArtifact,
	# Structural
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpPowArtifact sub PhpSourceArtifact,
	# Structural
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpShiftLeftArtifact sub PhpSourceArtifact,
	# Structural
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpShiftRightArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpSmallerArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpSmallerOrEqualArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_left_role,
	plays has_right_role;

ExprBinaryOpSpaceshipArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_expr_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_left_role,
	plays has_right_role;

ExprBitwiseNotArtifact sub PhpSourceArtifact,
	# Structural
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_expr_role;

ExprBooleanNotArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprCastArrayArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays is_var_role,
	plays has_expr_role;

ExprCastBoolArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_expr_role;

ExprCastDoubleArtifact sub PhpSourceArtifact,
	# Structural
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprCastIntArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprCastObjectArtifact sub PhpSourceArtifact,
	# Structural
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_expr_role;

ExprCastStringArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprCastUnsetArtifact sub PhpSourceArtifact,
	# Structural
	plays is_expr_role,
	plays has_expr_role;

ExprClassConstFetchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_class_role,
	plays has_comments_role,
	plays has_name_role;

ExprCloneArtifact sub PhpSourceArtifact,
	# Structural
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_expr_role;

ExprClosureArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	has returnTypeAttribute,
	has staticAttribute,
	# Structural
	plays is_children_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_params_role,
	plays has_return_type_role,
	plays has_stmts_role,
	plays has_uses_role;

ExprClosureUseArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	has varAttribute,
	# Structural
	plays is_uses_role;

ExprConstFetchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_name_role;

ExprEmptyArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_cond_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprErrorSuppressArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprEvalArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprExitArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_if_role,
	plays is_right_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role;

ExprFuncCallArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_init_role,
	plays is_key_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_args_role,
	plays has_comments_role,
	plays has_name_role;

ExprIncludeArtifact sub PhpSourceArtifact,
	# Attributes
	has typeAttribute,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprInstanceofArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_class_role,
	plays has_expr_role;

ExprIssetArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_cond_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_vars_role;

ExprListArtifact sub PhpSourceArtifact,
	# Structural
	plays is_value_role,
	plays is_value_var_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_items_role;

ExprMethodCallArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_init_role,
	plays is_key_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_name_role,
	plays is_parts_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_args_role,
	plays has_comments_role,
	plays has_name_role,
	plays has_var_role;

ExprNewArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_args_role,
	plays has_class_role,
	plays has_comments_role;

ExprPostDecArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_init_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_var_role;

ExprPostIncArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_init_role,
	plays is_key_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_var_role;

ExprPreDecArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_dim_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_init_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_var_role;

ExprPreIncArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_init_role,
	plays is_left_role,
	plays is_loop_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_var_role;

ExprPrintArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role;

ExprPropertyFetchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_key_var_role,
	plays is_left_role,
	plays is_name_role,
	plays is_parts_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_value_var_role,
	plays is_var_role,
	plays is_vars_role,
	plays has_comments_role,
	plays has_name_role,
	plays has_var_role;

ExprShellExecArtifact sub PhpSourceArtifact,
	# Structural
	plays is_expr_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_parts_role;

ExprStaticCallArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_args_role,
	plays has_class_role,
	plays has_comments_role,
	plays has_name_role;

ExprStaticPropertyFetchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays is_vars_role,
	plays has_class_role,
	plays has_comments_role,
	plays has_name_role;

ExprTernaryArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_init_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_var_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_else_role,
	plays has_if_role;

ExprUnaryMinusArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_expr_role;

ExprUnaryPlusArtifact sub PhpSourceArtifact,
	# Structural
	plays is_else_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_expr_role;

ExprVariableArtifact sub PhpSourceArtifact,
	# Structural
	plays is_class_role,
	plays is_cond_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_init_role,
	plays is_key_role,
	plays is_key_var_role,
	plays is_left_role,
	plays is_name_role,
	plays is_parts_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays is_value_var_role,
	plays is_var_role,
	plays is_vars_role,
	plays has_comments_role,
	plays has_name_role;

ExprYieldArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_expr_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_key_role,
	plays has_value_role;

ExprYieldFromArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_stmts_role,
	plays has_expr_role;

FunctionBodyArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_body_role;

FunctionReturnTypeArtifact sub PhpSourceArtifact,
	# Structural
	plays is_return_type_role;

ModuleArtifact sub PhpSourceArtifact,
	# Structural
	plays has_children_role;

NameArtifact sub PhpSourceArtifact,
	# Structural
	plays is_class_role,
	plays is_extends_role,
	plays is_implements_role,
	plays is_insteadof_role,
	plays is_name_role,
	plays is_prefix_role,
	plays is_return_type_role,
	plays is_trait_role,
	plays is_traits_role,
	plays is_type_role,
	plays is_types_role,
	plays has_comments_role;

NameFullyQualifiedArtifact sub PhpSourceArtifact,
	# Structural
	plays is_class_role,
	plays is_extends_role,
	plays is_implements_role,
	plays is_insteadof_role,
	plays is_name_role,
	plays is_return_type_role,
	plays is_trait_role,
	plays is_traits_role,
	plays is_type_role,
	plays is_types_role,
	plays has_comments_role;

NullableTypeArtifact sub PhpSourceArtifact,
	# Attributes
	has typeAttribute,
	# Structural
	plays is_return_type_role,
	plays is_type_role,
	plays has_type_role;

ParamArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	has typeAttribute,
	has variadicAttribute,
	# Structural
	plays is_params_role,
	plays has_comments_role,
	plays has_default_role,
	plays has_name_role,
	plays has_type_role;

ScalarDNumberArtifact sub PhpSourceArtifact,
	# Structural
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_comments_role;

ScalarEncapsedArtifact sub PhpSourceArtifact,
	# Structural
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role,
	plays has_parts_role;

ScalarEncapsedStringPartArtifact sub PhpSourceArtifact,
	# Structural
	plays is_parts_role;

ScalarLNumberArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_num_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role;

ScalarMagicConstClassArtifact sub PhpSourceArtifact,
	# Structural
	plays is_default_role,
	plays is_dim_role,
	plays is_expr_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_value_role;

ScalarMagicConstDirArtifact sub PhpSourceArtifact,
	# Structural
	plays is_expr_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role,
	plays has_comments_role;

ScalarMagicConstFileArtifact sub PhpSourceArtifact,
	# Structural
	plays is_default_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role;

ScalarMagicConstFunctionArtifact sub PhpSourceArtifact,
	# Structural
	plays is_dim_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_value_role;

ScalarMagicConstLineArtifact sub PhpSourceArtifact,
	# Structural
	plays is_default_role,
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role;

ScalarMagicConstMethodArtifact sub PhpSourceArtifact,
	# Structural
	plays is_dim_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role;

ScalarMagicConstNamespaceArtifact sub PhpSourceArtifact,
	# Structural
	plays is_expr_role,
	plays is_left_role,
	plays is_right_role,
	plays is_value_role;

ScalarMagicConstTraitArtifact sub PhpSourceArtifact,
	# Structural
	plays is_left_role;

ScalarStringArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cond_role,
	plays is_default_role,
	plays is_dim_role,
	plays is_else_role,
	plays is_expr_role,
	plays is_exprs_role,
	plays is_if_role,
	plays is_key_role,
	plays is_left_role,
	plays is_name_role,
	plays is_right_role,
	plays is_stmts_role,
	plays is_value_role,
	plays has_comments_role;

StmtBreakArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_num_role;

StmtCaseArtifact sub PhpSourceArtifact,
	# Structural
	plays is_cases_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_stmts_role;

StmtCatchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_catches_role,
	plays has_comments_role,
	plays has_stmts_role,
	plays has_types_role;

StmtClassArtifact sub PhpSourceArtifact,
	# Attributes
	has flagsAttribute,
	has typeAttribute,
	# Structural
	plays is_children_role,
	plays is_class_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_extends_role,
	plays has_implements_role,
	plays has_name_role,
	plays has_stmts_role;

StmtClassConstArtifact sub PhpSourceArtifact,
	# Attributes
	has flagsAttribute,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_consts_role;

StmtClassMethodArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	has flagsAttribute,
	has returnTypeAttribute,
	has typeAttribute,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_name_role,
	plays has_params_role,
	plays has_return_type_role,
	plays has_stmts_role;

StmtConstArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_consts_role;

StmtContinueArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_num_role;

StmtDeclareArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_declares_role,
	plays has_stmts_role;

StmtDeclareDeclareArtifact sub PhpSourceArtifact,
	# Structural
	plays is_declares_role,
	plays has_value_role;

StmtDoArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_stmts_role;

StmtEchoArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_exprs_role;

StmtElseArtifact sub PhpSourceArtifact,
	# Structural
	plays is_else_role,
	plays has_comments_role,
	plays has_stmts_role;

StmtElseIfArtifact sub PhpSourceArtifact,
	# Structural
	plays is_elseifs_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_stmts_role;

StmtFinallyArtifact sub PhpSourceArtifact,
	# Structural
	plays is_finally_role,
	plays has_stmts_role;

StmtForArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_init_role,
	plays has_loop_role,
	plays has_stmts_role;

StmtForeachArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role,
	plays has_key_var_role,
	plays has_stmts_role,
	plays has_value_var_role;

StmtFunctionArtifact sub PhpSourceArtifact,
	# Attributes
	has byRefAttribute,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_name_role,
	plays has_params_role,
	plays has_return_type_role,
	plays has_stmts_role;

StmtGlobalArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_vars_role;

StmtGotoArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_name_role;

StmtGroupUseArtifact sub PhpSourceArtifact,
	# Attributes
	has typeAttribute,
	# Structural
	plays is_stmts_role,
	plays has_prefix_role,
	plays has_uses_role;

StmtHaltCompilerArtifact sub PhpSourceArtifact,
	# Attributes
	has remainingAttribute,
	# Structural
	plays is_children_role;

StmtIfArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_else_role,
	plays has_elseifs_role,
	plays has_stmts_role;

StmtInlineHTMLArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role;

StmtInterfaceArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_extends_role,
	plays has_name_role,
	plays has_stmts_role;

StmtLabelArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_name_role;

StmtNamespaceArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays has_comments_role,
	plays has_name_role,
	plays has_stmts_role;

StmtNopArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role;

StmtPropertyArtifact sub PhpSourceArtifact,
	# Attributes
	has flagsAttribute,
	has typeAttribute,
	# Structural
	plays is_stmts_role,
	plays has_comments_role,
	plays has_props_role;

StmtPropertyPropertyArtifact sub PhpSourceArtifact,
	# Structural
	plays is_props_role,
	plays has_default_role,
	plays has_name_role;

StmtReturnArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role;

StmtStaticArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_vars_role;

StmtStaticVarArtifact sub PhpSourceArtifact,
	# Structural
	plays is_vars_role,
	plays has_default_role,
	plays has_name_role;

StmtSwitchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_cases_role,
	plays has_comments_role,
	plays has_cond_role;

StmtThrowArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_expr_role;

StmtTraitArtifact sub PhpSourceArtifact,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_name_role,
	plays has_stmts_role;

StmtTraitUseAdaptationAliasArtifact sub PhpSourceArtifact,
	# Attributes
	has methodAttribute,
	has newModifierAttribute,
	# Structural
	plays is_adaptations_role,
	plays has_trait_role;

StmtTraitUseAdaptationPrecedenceArtifact sub PhpSourceArtifact,
	# Attributes
	has methodAttribute,
	# Structural
	plays is_adaptations_role,
	plays has_insteadof_role,
	plays has_trait_role;

StmtTraitUseArtifact sub PhpSourceArtifact,
	# Structural
	plays is_stmts_role,
	plays has_adaptations_role,
	plays has_comments_role,
	plays has_traits_role;

StmtTryCatchArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_catches_role,
	plays has_comments_role,
	plays has_finally_role,
	plays has_stmts_role;

StmtUnsetArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_vars_role;

StmtUseArtifact sub PhpSourceArtifact,
	# Attributes
	has typeAttribute,
	# Structural
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_uses_role;

StmtUseUseArtifact sub PhpSourceArtifact,
	# Attributes
	has aliasAttribute,
	has typeAttribute,
	# Structural
	plays is_uses_role,
	plays has_name_role;

StmtWhileArtifact sub PhpSourceArtifact,
	# Structural
	plays is_body_role,
	plays is_children_role,
	plays is_stmts_role,
	plays has_comments_role,
	plays has_cond_role,
	plays has_stmts_role;

##########---------- Structural Relationships ----------##########
parent_child_relation sub relation,
	relates is_parent, relates is_child;

#####----- Php -----#####
adaptations_relation sub parent_child_relation,
	relates is_adaptations_role as is_child, relates has_adaptations_role as is_parent;

args_relation sub parent_child_relation,
	relates is_args_role as is_child, relates has_args_role as is_parent;

body_relation sub parent_child_relation,
	relates is_body_role as is_child, relates has_body_role as is_parent;

cases_relation sub parent_child_relation,
	relates is_cases_role as is_child, relates has_cases_role as is_parent;

catches_relation sub parent_child_relation,
	relates is_catches_role as is_child, relates has_catches_role as is_parent;

children_relation sub parent_child_relation,
	relates is_children_role as is_child, relates has_children_role as is_parent;

class_relation sub parent_child_relation,
	relates is_class_role as is_child, relates has_class_role as is_parent;

comments_relation sub parent_child_relation,
	relates is_comments_role as is_child, relates has_comments_role as is_parent;

cond_relation sub parent_child_relation,
	relates is_cond_role as is_child, relates has_cond_role as is_parent;

consts_relation sub parent_child_relation,
	relates is_consts_role as is_child, relates has_consts_role as is_parent;

declares_relation sub parent_child_relation,
	relates is_declares_role as is_child, relates has_declares_role as is_parent;

default_relation sub parent_child_relation,
	relates is_default_role as is_child, relates has_default_role as is_parent;

dim_relation sub parent_child_relation,
	relates is_dim_role as is_child, relates has_dim_role as is_parent;

else_relation sub parent_child_relation,
	relates is_else_role as is_child, relates has_else_role as is_parent;

elseifs_relation sub parent_child_relation,
	relates is_elseifs_role as is_child, relates has_elseifs_role as is_parent;

expr_relation sub parent_child_relation,
	relates is_expr_role as is_child, relates has_expr_role as is_parent;

exprs_relation sub parent_child_relation,
	relates is_exprs_role as is_child, relates has_exprs_role as is_parent;

extends_relation sub parent_child_relation,
	relates is_extends_role as is_child, relates has_extends_role as is_parent;

finally_relation sub parent_child_relation,
	relates is_finally_role as is_child, relates has_finally_role as is_parent;

if_relation sub parent_child_relation,
	relates is_if_role as is_child, relates has_if_role as is_parent;

implements_relation sub parent_child_relation,
	relates is_implements_role as is_child, relates has_implements_role as is_parent;

init_relation sub parent_child_relation,
	relates is_init_role as is_child, relates has_init_role as is_parent;

insteadof_relation sub parent_child_relation,
	relates is_insteadof_role as is_child, relates has_insteadof_role as is_parent;

items_relation sub parent_child_relation,
	relates is_items_role as is_child, relates has_items_role as is_parent;

key_relation sub parent_child_relation,
	relates is_key_role as is_child, relates has_key_role as is_parent;

key_var_relation sub parent_child_relation,
	relates is_key_var_role as is_child, relates has_key_var_role as is_parent;

left_relation sub parent_child_relation,
	relates is_left_role as is_child, relates has_left_role as is_parent;

loop_relation sub parent_child_relation,
	relates is_loop_role as is_child, relates has_loop_role as is_parent;

name_relation sub parent_child_relation,
	relates is_name_role as is_child, relates has_name_role as is_parent;

num_relation sub parent_child_relation,
	relates is_num_role as is_child, relates has_num_role as is_parent;

params_relation sub parent_child_relation,
	relates is_params_role as is_child, relates has_params_role as is_parent;

parts_relation sub parent_child_relation,
	relates is_parts_role as is_child, relates has_parts_role as is_parent;

prefix_relation sub parent_child_relation,
	relates is_prefix_role as is_child, relates has_prefix_role as is_parent;

props_relation sub parent_child_relation,
	relates is_props_role as is_child, relates has_props_role as is_parent;

return_type_relation sub parent_child_relation,
	relates is_return_type_role as is_child, relates has_return_type_role as is_parent;

right_relation sub parent_child_relation,
	relates is_right_role as is_child, relates has_right_role as is_parent;

stmts_relation sub parent_child_relation,
	relates is_stmts_role as is_child, relates has_stmts_role as is_parent;

trait_relation sub parent_child_relation,
	relates is_trait_role as is_child, relates has_trait_role as is_parent;

traits_relation sub parent_child_relation,
	relates is_traits_role as is_child, relates has_traits_role as is_parent;

type_relation sub parent_child_relation,
	relates is_type_role as is_child, relates has_type_role as is_parent;

types_relation sub parent_child_relation,
	relates is_types_role as is_child, relates has_types_role as is_parent;

uses_relation sub parent_child_relation,
	relates is_uses_role as is_child, relates has_uses_role as is_parent;

value_relation sub parent_child_relation,
	relates is_value_role as is_child, relates has_value_role as is_parent;

value_var_relation sub parent_child_relation,
	relates is_value_var_role as is_child, relates has_value_var_role as is_parent;

var_relation sub parent_child_relation,
	relates is_var_role as is_child, relates has_var_role as is_parent;

vars_relation sub parent_child_relation,
	relates is_vars_role as is_child, relates has_vars_role as is_parent;
